"use client";

import { ChangeEvent, DragEvent, useEffect, useMemo, useState } from "react";
import { BookOpen, Brain, Check, FileText, GitBranch, Lightbulb, MessageCircleQuestion, Search, Target, Trash2, Upload } from "lucide-react";
import { deleteLibraryFile, listLibraryFiles, saveLibraryFile, type StoredLibraryFile } from "@/lib/libraryStorage";

type Mode = "inicio" | "mapa" | "socratico" | "feynman" | "cazador" | "caso" | "perfil";
type Concept = { term: string; frequency: number; context: string };

type DetectiveState = { xp: number; feynman: number; socratic: number; hunter: number; case: number; answers: Record<string, string>; foundErrors: number };
const STATE_KEY = "datam-detective-v1";
const STOPWORDS = new Set("de la el en y a los las un una que por con para es del se al como su sus más pero o este esta entre sin sobre también hasta desde nos les ni lo le ya muy todo todos toda ser son fue fueron está están hay había eran sea sido tiene tienen hacer hace puede pueden debe deben solo según tras durante mediante así donde cuando porque aunque cual cuales quien quienes esto aquello algo alguien nadie nada siempre nunca tampoco además entonces luego después antes mientras".split(" "));

function words(text: string) { return text.toLowerCase().match(/[a-záéíóúñü]{4,}/g) ?? []; }
function conceptsFrom(text: string): Concept[] { const frequency: Record<string, number> = {}; words(text).forEach((word) => { if (!STOPWORDS.has(word)) frequency[word] = (frequency[word] ?? 0) + 1; }); return Object.entries(frequency).sort((a, b) => b[1] - a[1]).slice(0, 12).map(([term, frequency]) => ({ term, frequency, context: text.split(/(?<=[.!?])\s+/).find((sentence) => sentence.toLowerCase().includes(term))?.slice(0, 220) ?? "Concepto detectado en el material." })); }
function readState(): DetectiveState { try { return { xp: 0, feynman: 0, socratic: 0, hunter: 0, case: 0, answers: {}, foundErrors: 0, ...JSON.parse(window.localStorage.getItem(STATE_KEY) ?? "{}") }; } catch { return { xp: 0, feynman: 0, socratic: 0, hunter: 0, case: 0, answers: {}, foundErrors: 0 }; } }

export default function DetectiveWorkspace() {
  const [files, setFiles] = useState<StoredLibraryFile[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [mode, setMode] = useState<Mode>("inicio");
  const [state, setState] = useState<DetectiveState>(readState);
  const [message, setMessage] = useState("");
  const [query, setQuery] = useState("");
  const [dragging, setDragging] = useState(false);
  const [socraticIndex, setSocraticIndex] = useState(0);
  const [feynmanText, setFeynmanText] = useState("");
  const [hunterIndex, setHunterIndex] = useState(0);
  const [hunterDone, setHunterDone] = useState(false);
  const [caseAnswers, setCaseAnswers] = useState<string[]>(["", "", ""]);

  useEffect(() => { void listLibraryFiles().then(setFiles); }, []);
  useEffect(() => { window.localStorage.setItem(STATE_KEY, JSON.stringify(state)); }, [state]);

  const selected = files.find((file) => file.id === selectedId) ?? files[0];
  const concepts = useMemo(() => selected ? conceptsFrom(selected.text) : [], [selected]);
  const sentences = useMemo(() => selected?.text.split(/(?<=[.!?])\s+/).map((line) => line.trim()).filter((line) => line.length > 45).slice(0, 30) ?? [], [selected]);
  const filteredFiles = files.filter((file) => file.name.toLowerCase().includes(query.toLowerCase()));
  const currentConcept = concepts[socraticIndex % Math.max(1, concepts.length)];
  const hunterSentence = sentences[hunterIndex % Math.max(1, sentences.length)] ?? "Sube un material con texto para iniciar la investigación.";

  function award(amount: number, key: keyof Pick<DetectiveState, "feynman" | "socratic" | "hunter" | "case">) { setState((current) => ({ ...current, xp: current.xp + amount, [key]: current[key] + amount })); }
  async function processFiles(input: FileList | File[]) { const next: StoredLibraryFile[] = []; for (const file of Array.from(input)) { if (file.size > 50 * 1024 * 1024) { setMessage(`${file.name}: supera 50 MB.`); continue; } const type = file.name.split(".").pop()?.toLowerCase() ?? "archivo"; let text = ""; if (type === "pdf") { const script = document.createElement("script"); script.src = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js"; await new Promise<void>((resolve, reject) => { script.onload = () => resolve(); script.onerror = () => reject(new Error("No se pudo leer el PDF.")); document.head.appendChild(script); }); const pdfjs = (window as unknown as { pdfjsLib: { GlobalWorkerOptions: { workerSrc: string }; getDocument: (options: { data: ArrayBuffer; disableWorker: boolean }) => { promise: Promise<{ numPages: number; getPage: (n: number) => Promise<{ getTextContent: () => Promise<{ items: Array<{ str?: string }> }> }> }> } } }).pdfjsLib; pdfjs.GlobalWorkerOptions.workerSrc = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js"; const pdf = await pdfjs.getDocument({ data: await file.arrayBuffer(), disableWorker: true }).promise; const pages: string[] = []; for (let page = 1; page <= pdf.numPages; page += 1) { const content = await (await pdf.getPage(page)).getTextContent(); pages.push(content.items.map((item) => item.str ?? "").join(" ")); } text = pages.join("\n\n"); } else if (file.type.startsWith("text/") || ["txt", "md", "csv", "json", "sql", "py", "js", "ts", "html", "css", "ipynb"].includes(type)) text = await file.text(); const item: StoredLibraryFile = { id: `${Date.now()}-${Math.random().toString(36).slice(2)}`, name: file.name, type, mimeType: file.type || "application/octet-stream", size: file.size, text, summary: text ? `Material investigable con ${words(text).length.toLocaleString("es-PE")} palabras.` : "Archivo guardado sin texto extraíble.", concepts: conceptsFrom(text).map((concept) => concept.term), missions: [], flashcards: conceptsFrom(text).slice(0, 8).map((concept) => ({ term: concept.term, definition: "Explícalo con un ejemplo del material." })), createdAt: new Date().toISOString(), blob: file }; await saveLibraryFile(item); next.push(item); } if (next.length) { setFiles((current) => [...next, ...current]); setSelectedId(next[0].id); setMode("inicio"); setMessage(`${next.length} material${next.length === 1 ? "" : "es"} listo${next.length === 1 ? "" : "s"} para investigar.`); } }
  function handleInput(event: ChangeEvent<HTMLInputElement>) { if (event.target.files) void processFiles(event.target.files); event.target.value = ""; }
  function handleDrop(event: DragEvent<HTMLLabelElement>) { event.preventDefault(); setDragging(false); void processFiles(event.dataTransfer.files); }
  async function removeFile(id: string) { await deleteLibraryFile(id); setFiles((current) => current.filter((file) => file.id !== id)); if (selectedId === id) setSelectedId(null); }
  function submitSocratic(answer: string) { if (answer.trim().length < 15) return; award(25, "socratic"); setSocraticIndex((index) => index + 1); }
  function evaluateFeynman() { const count = feynmanText.trim().split(/\s+/).filter(Boolean).length; if (count < 20) return; award(Math.min(80, 20 + count), "feynman"); setFeynmanText(""); }
  function answerHunter(isFalse: boolean) { setHunterDone(true); if (isFalse) { award(40, "hunter"); setState((current) => ({ ...current, foundErrors: current.foundErrors + 1 })); } else award(5, "hunter"); }
  function completeCase() { if (caseAnswers.every((answer) => answer.trim().length >= 20)) award(80, "case"); }

  const modes: Array<{ id: Mode; label: string; icon: typeof Search; description: string }> = [{ id: "inicio", label: "Inicio", icon: Search, description: "Material y siguiente investigación" }, { id: "mapa", label: "Mapa cognitivo", icon: GitBranch, description: "Conexiones entre conceptos" }, { id: "socratico", label: "Interrogatorio socrático", icon: MessageCircleQuestion, description: "Preguntas que revelan comprensión" }, { id: "feynman", label: "Enseña a Dax", icon: Brain, description: "Explica con tus propias palabras" }, { id: "cazador", label: "Cazador de errores", icon: Target, description: "Entrena pensamiento crítico" }, { id: "caso", label: "Caso real", icon: Lightbulb, description: "Transfiere a una situación laboral" }, { id: "perfil", label: "Habilidades", icon: Check, description: "Tu dominio cognitivo" }];

  return <div className="detective-space">
    <section className="detective-hero"><p className="data-cell-header detective-kicker">Método Detective Cognitivo</p><h1 className="mt-2 font-display text-3xl font-bold text-white sm:text-4xl">No solo leas tu material. <em>Investígalo.</em></h1><p className="mt-3 max-w-3xl text-sm leading-6 text-blue-100">Convierte tus materiales en preguntas, explicaciones, errores por detectar y casos reales. Cada acción entrena una habilidad profesional.</p><div className="mt-5 flex flex-wrap gap-5 text-sm text-blue-100"><span><b className="text-white">{state.xp}</b> XP</span><span><b className="text-white">{state.socratic}</b> interrogación</span><span><b className="text-white">{state.feynman}</b> explicación</span><span><b className="text-white">{state.case}</b> transferencia</span></div></section>
    <label htmlFor="detective-input" onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={handleDrop} className={`detective-dropzone ${dragging ? "active" : ""}`}><Upload className="mx-auto h-8 w-8 text-accent2" /><b className="mt-3 block text-lg text-white">Sube el material que quieres investigar</b><span className="mt-2 block text-sm text-blue-100">PDF, documentos, datos, código o texto. Los formatos con texto se analizan localmente.</span><span className="mt-4 inline-flex rounded-cell bg-accent px-4 py-2 text-sm font-bold text-white">Seleccionar material</span><input id="detective-input" type="file" onChange={handleInput} className="sr-only" /></label>
    {message && <p role="status" className="mt-3 text-sm text-blue-800">{message}</p>}
    <div className="mt-6 grid gap-5 lg:grid-cols-[240px_minmax(0,1fr)]"><aside className="detective-nav"><p className="data-cell-header">Investigación</p><div className="mt-3 space-y-1">{modes.map(({ id, label, icon: Icon, description }) => <button key={id} type="button" onClick={() => setMode(id)} className={`detective-nav-item ${mode === id ? "active" : ""}`}><Icon className="h-4 w-4 shrink-0" /><span><b>{label}</b><small>{description}</small></span></button>)}</div><p className="mt-6 data-cell-header">Materiales</p><div className="mt-3 space-y-1">{filteredFiles.length === 0 ? <p className="px-3 text-xs text-muted">Aún no hay materiales.</p> : filteredFiles.map((file) => <button key={file.id} type="button" onClick={() => { setSelectedId(file.id); setMode("inicio"); }} className={`detective-file ${selected?.id === file.id ? "active" : ""}`}><FileText className="h-4 w-4" /><span className="truncate">{file.name}</span><Trash2 onClick={(event) => { event.stopPropagation(); void removeFile(file.id); }} className="ml-auto h-3.5 w-3.5 shrink-0" /></button>)}</div><div className="mt-3"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar material" className="w-full rounded-cell border border-line bg-white px-3 py-2 text-xs" /></div></aside>
      <main className="detective-panel">{!selected ? <div className="detective-empty"><BookOpen className="mx-auto h-10 w-10 text-blue-300" /><h2 className="mt-3 font-display text-xl font-bold text-white">Tu caso aún no existe</h2><p className="mt-2 text-sm text-blue-100">Sube un material para iniciar tu investigación cognitiva.</p></div> : <><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="data-cell-header">Caso activo</p><h2 className="mt-1 break-all font-display text-xl font-bold text-white">{selected.name}</h2><p className="mt-1 text-sm text-blue-100">{selected.text ? `${words(selected.text).length.toLocaleString("es-PE")} palabras · ${concepts.length} conceptos detectados` : "Sin texto extraíble"}</p></div><span className="rounded-cell bg-green-100 px-2 py-1 text-xs font-bold text-green-800">Investigación activa</span></div><DetectiveMode mode={mode} selected={selected} concepts={concepts} sentences={sentences} currentConcept={currentConcept} hunterSentence={hunterSentence} hunterDone={hunterDone} socraticIndex={socraticIndex} feynmanText={feynmanText} setFeynmanText={setFeynmanText} caseAnswers={caseAnswers} setCaseAnswers={setCaseAnswers} onSocratic={submitSocratic} onFeynman={evaluateFeynman} onHunter={answerHunter} onNextHunter={() => { setHunterIndex((index) => index + 1); setHunterDone(false); }} onCase={completeCase} state={state} /></>}</main>
    </div>
  </div>;
}

function DetectiveMode({ mode, selected, concepts, sentences, currentConcept, hunterSentence, hunterDone, socraticIndex, feynmanText, setFeynmanText, caseAnswers, setCaseAnswers, onSocratic, onFeynman, onHunter, onNextHunter, onCase, state }: { mode: Mode; selected: StoredLibraryFile; concepts: Concept[]; sentences: string[]; currentConcept?: Concept; hunterSentence: string; hunterDone: boolean; socraticIndex: number; feynmanText: string; setFeynmanText: (value: string) => void; caseAnswers: string[]; setCaseAnswers: (value: string[]) => void; onSocratic: (value: string) => void; onFeynman: () => void; onHunter: (isFalse: boolean) => void; onNextHunter: () => void; onCase: () => void; state: DetectiveState }) {
  if (mode === "mapa") return <section className="detective-content"><h3>Mapa cognitivo</h3><p>Los conceptos más frecuentes del material aparecen como un mapa de conexiones. Selecciona un concepto para revisar su contexto.</p><div className="concept-map">{concepts.map((concept, index) => <div key={concept.term} className={`concept-node ring-${index % 3}`}><b>{concept.term}</b><small>{concept.frequency} apariciones</small></div>)}</div><div className="mt-4 grid gap-2">{concepts.slice(0, 6).map((concept) => <details key={concept.term} className="detective-card"><summary>{concept.term}</summary><p>{concept.context}</p></details>)}</div></section>;
  if (mode === "socratico") return <section className="detective-content"><p className="data-cell-header">Interrogación elaborativa · Pregunta {Math.min(socraticIndex + 1, concepts.length || 1)}</p><h3>¿Qué significa <em>{currentConcept?.term ?? "este material"}</em> con tus propias palabras?</h3><p>Evita copiar. Explica qué es, por qué importa y da un ejemplo nuevo.</p><textarea className="detective-textarea" placeholder="Escribe una respuesta de al menos 15 caracteres..." onKeyDown={(event) => { if (event.key === "Enter" && event.ctrlKey) onSocratic(event.currentTarget.value); }} /><button type="button" onClick={(event) => { const textarea = event.currentTarget.previousElementSibling as HTMLTextAreaElement; onSocratic(textarea.value); textarea.value = ""; }} className="mt-3 rounded-cell bg-accent px-4 py-2 text-sm font-bold text-white">Responder y continuar</button></section>;
  if (mode === "feynman") return <section className="detective-content"><p className="data-cell-header">Autoexplicación Feynman</p><h3>Enséñale <em>{concepts[0]?.term ?? "el concepto"}</em> a Dax</h3><p>Usa lenguaje simple, una analogía, un ejemplo y explica por qué importa.</p><textarea value={feynmanText} onChange={(event) => setFeynmanText(event.target.value)} className="detective-textarea" placeholder="Mira Dax, imagina que..." /><div className="mt-2 flex justify-between text-xs text-muted"><span>{feynmanText.trim().split(/\s+/).filter(Boolean).length} palabras</span><span>Mínimo recomendado: 20</span></div><button type="button" onClick={onFeynman} className="mt-3 rounded-cell bg-accent px-4 py-2 text-sm font-bold text-white">Evaluar mi explicación</button></section>;
  if (mode === "cazador") return <section className="detective-content"><p className="data-cell-header">Detección de errores</p><h3>¿Esta afirmación es fiel al material?</h3><div className="detective-quote">{hunterSentence}</div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => onHunter(false)} className="rounded-cell border border-line px-4 py-2 text-sm text-ink">Es correcta</button><button type="button" onClick={() => onHunter(true)} className="rounded-cell border border-red-300 px-4 py-2 text-sm text-red-700">Es falsa</button></div>{hunterDone && <div className="mt-4 rounded-cell bg-green-50 p-4 text-sm text-green-800">Respuesta registrada. Contrasta siempre la afirmación con el contexto original antes de concluir.</div>}<button type="button" onClick={onNextHunter} className="mt-3 rounded-cell bg-ink px-4 py-2 text-sm font-bold text-white">Nueva afirmación</button></section>;
  if (mode === "caso") return <section className="detective-content"><p className="data-cell-header">Transferencia profesional</p><h3>Aplica lo aprendido a una situación nueva</h3><p>Un equipo necesita usar el material para resolver un problema real. Responde con acciones concretas y medibles.</p>{["Diagnóstico: ¿qué problema resolverías y con qué concepto?", "Aplicación: ¿qué harías primero, segundo y tercero?", "Medición: ¿cómo demostrarías que la solución funcionó?"] .map((question, index) => <label key={question} className="mt-4 block text-sm font-bold text-white">{question}<textarea value={caseAnswers[index]} onChange={(event) => { const next = [...caseAnswers]; next[index] = event.target.value; setCaseAnswers(next); }} className="detective-textarea mt-2" /></label>)}<button type="button" onClick={onCase} className="mt-4 rounded-cell bg-accent px-4 py-2 text-sm font-bold text-white">Evaluar caso</button></section>;
  if (mode === "perfil") return <section className="detective-content"><p className="data-cell-header">Habilidades cognitivas</p><h3>Tu dominio se construye con evidencia</h3><div className="skill-grid">{[["Recuperación socrática", state.socratic], ["Explicación Feynman", state.feynman], ["Detección de errores", state.hunter], ["Transferencia profesional", state.case]].map(([label, value]) => <div key={label as string} className="skill-card"><b>{value as number} XP</b><span>{label as string}</span></div>)}</div></section>;
  return <section className="detective-content"><p className="data-cell-header">Inicio de investigación</p><h3>Elige una técnica para dominar este material</h3><div className="detective-method-grid"><div><Search className="text-accent" /><b>Mapa cognitivo</b><span>Organiza conceptos y contexto.</span></div><div><MessageCircleQuestion className="text-accent" /><b>Interrogatorio socrático</b><span>Recupera lo que realmente comprendes.</span></div><div><Brain className="text-accent" /><b>Enseña a Dax</b><span>Explica sin copiar.</span></div><div><Target className="text-accent" /><b>Cazador de errores</b><span>Fortalece tu criterio.</span></div></div><div className="mt-5 rounded-cell border-l-4 border-cyan-400 bg-cyan-950/30 p-4 text-sm text-blue-100">La biblioteca complementa los cursos oficiales. El aprendizaje y el certificado siguen dependiendo de las actividades y evaluaciones del curso.</div></section>;
}
