export type Course = {
	slug: string;
	code: string;
	title: string;
	level: string;
	duration: string;
	description: string;
	image: string;
	summary: string;
	professionalUse: string;
	modules: { title: string; lessons: { title: string; topics: string[]; videoUrl?: string }[] }[];
};

const images = {
	excel: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=900&q=80",
	powerBi: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80",
	python: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80",
	sql: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=900&q=80",
	query: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80",
	ai: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=80",
	research: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=900&q=80",
	web: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80",
	finance: "https://images.unsplash.com/photo-1559526324-593bc073d938?auto=format&fit=crop&w=900&q=80",
};

const lesson = (title: string, topics: string[], videoUrl?: string) => ({ title, topics, videoUrl });
const module = (title: string, lessons: ReturnType<typeof lesson>[]) => ({ title, lessons });

export const courses: Course[] = [
	{ slug: "excel-avanzado", code: "B1", title: "Excel Avanzado", level: "Intermedio", duration: "6 semanas", description: "Tablas dinámicas, fórmulas avanzadas y automatización.", image: images.excel, summary: "Aprenderás a organizar, analizar y automatizar información en Excel mediante fórmulas avanzadas, tablas dinámicas y reportes claros, desarrollando una habilidad práctica para estudios, emprendimientos y trabajos administrativos o financieros.", professionalUse: "Te ayudará a crear reportes, controlar presupuestos, analizar ventas y presentar información para tomar decisiones.", modules: [module("Fundamentos para trabajar con datos", [lesson("Estructura de una base de datos", ["Tablas y registros", "Tipos de datos", "Orden y filtros"]), lesson("Fórmulas esenciales", ["Referencias absolutas y relativas", "Funciones lógicas", "Funciones de texto y fecha"])]), module("Análisis y visualización", [lesson("Tablas dinámicas", ["Campos y segmentaciones", "Agrupación de información", "Indicadores de resumen"]), lesson("Dashboards en Excel", ["Gráficos adecuados", "Diseño de reportes", "Presentación de hallazgos"])]), module("Automatización aplicada", [lesson("Procesos eficientes", ["Validación de datos", "Plantillas reutilizables", "Introducción a macros"])]) ] },
	{ slug: "power-bi-desde-cero", code: "B2", title: "Power BI desde Cero", level: "Principiante", duration: "5 semanas", description: "Dashboards reales conectando y modelando datos.", image: images.powerBi, summary: "Construirás dashboards interactivos desde cero, conectando fuentes, limpiando datos y creando visualizaciones que convierten números en historias comprensibles.", professionalUse: "Podrás apoyar decisiones comerciales y operativas con indicadores y paneles de resultados.", modules: [module("Primeros pasos con Power BI", [lesson("Entorno y fuentes", ["Interfaz", "Importación de Excel y CSV", "Tipos de visualización"])]), module("Preparación y modelo de datos", [lesson("Datos listos para analizar", ["Limpieza básica", "Relaciones entre tablas", "Modelo estrella"])]), module("Dashboard final", [lesson("Indicadores para decisiones", ["Medidas básicas", "Filtros y segmentadores", "Publicación de un informe"], "/videos/power-bi-desde-cero/modulo-03-dashboard-final/clase-01-indicadores/AQMv6X025x31BrL_5X8E6vOwYy__mKHKxAgtJWgX0h2JnPbEHYGAmKIChT0TlEPDAtMy7NUZMruaB4Om1i3gYR7cye6vWltXvbs.mp4")]) ] },
	{ slug: "python-para-datos", code: "B3", title: "Python para Datos", level: "Intermedio", duration: "8 semanas", description: "Pandas, visualización y automatización de reportes.", image: images.python, summary: "Aprenderás a usar Python para cargar, limpiar, explorar y visualizar datos, creando análisis reproducibles y automatizaciones confiables.", professionalUse: "Te permitirá automatizar reportes y analizar grandes volúmenes de información.", modules: [module("Python y pensamiento lógico", [lesson("Bases del lenguaje", ["Variables", "Condicionales y ciclos", "Funciones"])]), module("Análisis con Pandas", [lesson("Trabajar con datos", ["DataFrames", "Limpieza", "Agrupaciones y métricas"])]), module("Proyecto de análisis", [lesson("Reporte automatizado", ["Gráficos", "Conclusiones", "Exportación de resultados"])]) ] },
	{ slug: "sql-para-analisis", code: "B4", title: "SQL para Análisis", level: "Principiante", duration: "4 semanas", description: "Consultas, filtros y relaciones entre tablas.", image: images.sql, summary: "Aprenderás a consultar bases de datos con SQL, seleccionar información relevante, unir tablas y responder preguntas de negocio.", professionalUse: "Es una competencia clave para analistas y equipos que extraen información de sistemas empresariales.", modules: [module("Consultas básicas", [lesson("Leer información", ["SELECT", "WHERE", "ORDER BY y LIMIT"])]), module("Cruce y resumen de datos", [lesson("Relaciones", ["JOIN", "GROUP BY", "Funciones de agregación"])]), module("Consultas para decisiones", [lesson("Análisis práctico", ["Subconsultas", "Indicadores", "Caso de negocio"])]) ] },
	{ slug: "power-query", code: "B5", title: "Power Query", level: "Intermedio", duration: "3 semanas", description: "Limpieza y transformación de datos paso a paso.", image: images.query, summary: "Dominarás un flujo ordenado para importar, limpiar y transformar datos de distintas fuentes, reduciendo errores.", professionalUse: "Te ayudará a estandarizar bases de datos y ahorrar tiempo en reportes recurrentes.", modules: [module("Conectar fuentes", [lesson("Importación organizada", ["Excel y CSV", "Tipos de origen", "Actualización de consultas"])]), module("Limpiar y transformar", [lesson("Preparar datos", ["Valores nulos", "Dividir y combinar columnas", "Unir consultas"])]) ] },
	{ slug: "introduccion-a-la-ia", code: "B6", title: "Introducción a la IA", level: "Principiante", duration: "5 semanas", description: "Fundamentos prácticos de inteligencia artificial aplicada.", image: images.ai, summary: "Conocerás conceptos esenciales de inteligencia artificial y utilizarás herramientas de forma responsable para investigar, crear y automatizar.", professionalUse: "Te permitirá identificar oportunidades de automatización y adaptarte a nuevas herramientas.", modules: [module("Comprender la IA", [lesson("Conceptos esenciales", ["IA, datos y modelos", "Usos cotidianos", "Limitaciones y sesgos"])]), module("IA para aprender y trabajar", [lesson("Herramientas responsables", ["Prompts claros", "Verificación de resultados", "Privacidad y ética"])]), module("Proyecto aplicado", [lesson("Solución con IA", ["Definir un problema", "Prototipo", "Presentar resultados"])]) ] },
	{ slug: "investigacion-aplicada", code: "B7", title: "Investigación Aplicada", level: "Principiante", duration: "6 semanas", description: "Diseña investigaciones claras con datos, fuentes confiables y resultados útiles.", image: images.research, summary: "Aprenderás a transformar una idea en una investigación ordenada, formulando problemas, objetivos y preguntas, seleccionando fuentes confiables y analizando información.", professionalUse: "Te ayudará a elaborar proyectos, diagnósticos, informes y propuestas con evidencia.", modules: [module("Bases de la investigación", [lesson("Del problema a la pregunta", ["Identificación del problema", "Justificación", "Preguntas de investigación"]), lesson("Objetivos y variables", ["Objetivo general y específicos", "Variables e indicadores", "Alcance del estudio"])]), module("Fuentes y metodología", [lesson("Buscar información confiable", ["Fuentes académicas", "Antecedentes", "Citas y referencias"]), lesson("Diseño metodológico", ["Enfoques de investigación", "Población y muestra", "Instrumentos"])]), module("Análisis y presentación", [lesson("Resultados y conclusiones", ["Organización de datos", "Interpretación", "Informe final"])]) ] },
	{ slug: "programacion-desarrollo-web", code: "B8", title: "Programación y Desarrollo Web", level: "Principiante", duration: "8 semanas", description: "Crea páginas web modernas desde la estructura hasta la publicación.", image: images.web, summary: "Construirás una página web funcional aprendiendo HTML, CSS y JavaScript, con buenas prácticas para crear experiencias adaptables.", professionalUse: "Te permitirá crear portafolios, sitios para emprendimientos y prototipos digitales.", modules: [module("Fundamentos de la web", [lesson("Cómo funciona una página", ["Navegador y servidor", "HTML semántico", "Estructura de un documento"]), lesson("Primer proyecto", ["Textos e imágenes", "Enlaces y formularios", "Organización de carpetas"])]), module("Diseño y estilos", [lesson("CSS desde cero", ["Selectores", "Colores y tipografía", "Modelo de caja"]), lesson("Diseño responsive", ["Flexbox y Grid", "Adaptación a celulares", "Accesibilidad"])]), module("Interactividad y publicación", [lesson("JavaScript básico", ["Variables y funciones", "Eventos", "Validación"]), lesson("Publicar un sitio", ["Git", "Hosting", "Proyecto final"])]) ] },
	{ slug: "finanzas-para-emprendedores", code: "B9", title: "Finanzas para Emprendedores", level: "Principiante", duration: "5 semanas", description: "Organiza tus finanzas y toma mejores decisiones para tu negocio.", image: images.finance, summary: "Aprenderás a ordenar ingresos y gastos, elaborar presupuestos, calcular costos y leer indicadores financieros básicos para cuidar el dinero.", professionalUse: "Te ayudará a controlar el flujo de caja, definir precios, evaluar inversiones y presentar información financiera.", modules: [module("Orden financiero", [lesson("Ingresos y gastos", ["Clasificación", "Registro financiero", "Separar finanzas personales"]), lesson("Presupuesto", ["Metas", "Presupuesto mensual", "Escenarios"])]), module("Costos y precios", [lesson("Conocer los costos", ["Costos fijos y variables", "Punto de equilibrio", "Margen"]), lesson("Definir precios", ["Costos", "Valor para el cliente", "Competencia"])]), module("Decisiones y crecimiento", [lesson("Flujo de caja", ["Entradas y salidas", "Liquidez", "Proyección"]), lesson("Indicadores básicos", ["Rentabilidad", "Endeudamiento", "Plan financiero"])]) ] },
];

export function getCourse(slug: string) { return courses.find((course) => course.slug === slug); }
