export type AssessmentQuestion = {
  prompt: string;
  options: string[];
  correctOption: number;
};

export type CourseAssessment = {
  projectTitle: string;
  projectInstructions: string;
  acceptedFormats: string;
  questions: AssessmentQuestion[];
};

const sharedQuestions: AssessmentQuestion[] = [
  {
    prompt: "¿Cuál es la mejor forma de consolidar una habilidad nueva?",
    options: ["Memorizar definiciones", "Aplicarla en una práctica con datos reales", "Ver el video varias veces", "Saltar a la siguiente clase"],
    correctOption: 1,
  },
  {
    prompt: "Antes de presentar un resultado, ¿qué debes comprobar?",
    options: ["Que tenga muchos colores", "Que responda al objetivo planteado", "Que use una herramienta avanzada", "Que sea lo más largo posible"],
    correctOption: 1,
  },
  {
    prompt: "¿Qué actitud ayuda más a superar un error durante la práctica?",
    options: ["Revisar el error y corregirlo", "Ignorarlo y continuar", "Borrar todo el trabajo", "Culpar a la herramienta"],
    correctOption: 0,
  },
  {
    prompt: "¿Por qué es importante seguir el orden de los módulos de un curso?",
    options: ["Porque cada tema se construye sobre el anterior", "Porque es un requisito sin razón", "Para tardar más tiempo", "No es importante"],
    correctOption: 0,
  },
  {
    prompt: "¿Qué debes hacer si un concepto no queda claro?",
    options: ["Repasar el material y practicar de nuevo", "Avanzar sin entenderlo", "Adivinar en el examen", "Copiar la respuesta de otra persona"],
    correctOption: 0,
  },
  {
    prompt: "¿Cuál es un buen hábito antes de enviar un proyecto final?",
    options: ["Revisar que cumple con todos los requisitos pedidos", "Enviarlo sin revisar", "Cambiar el formato al azar", "Omitir las instrucciones"],
    correctOption: 0,
  },
  {
    prompt: "¿Qué papel cumple la práctica constante en el aprendizaje de una herramienta?",
    options: ["Refuerza la habilidad y la memoria a largo plazo", "No tiene ningún efecto", "Solo sirve para pasar el tiempo", "Reemplaza la teoría por completo"],
    correctOption: 0,
  },
  {
    prompt: "¿Qué se recomienda hacer con la retroalimentación de un revisor?",
    options: ["Aplicarla para mejorar el proyecto", "Ignorarla completamente", "Discutir sin analizarla", "Borrar el proyecto"],
    correctOption: 0,
  },
];

const assessments: Record<string, CourseAssessment> = {
  "excel-basico": {
    projectTitle: "Control de ventas y gastos personales",
    projectInstructions: "Crea una hoja de control de ventas y gastos personales aplicando tipos de datos correctos, formato de tabla, formato condicional y las funciones SUMA, PROMEDIO, MAX, MIN y CONTAR.",
    acceptedFormats: "Comparte un enlace de OneDrive, Google Drive o GitHub con tu archivo .xlsx.",
    questions: [
      { prompt: "¿Qué función suma valores que cumplen una condición?", options: ["SUMAR.SI", "PROMEDIO", "CONTAR", "BUSCARV"], correctOption: 0 },
      { prompt: "¿Qué referencia cambia al copiar una fórmula hacia otra celda?", options: ["Relativa", "Absoluta", "Mixta con $ en fila y columna", "Ninguna"], correctOption: 0 },
      { prompt: "¿Qué elemento de Excel agrupa los comandos por fichas como Inicio, Insertar y Datos?", options: ["La Cinta de opciones", "La barra de estado", "El panel de notas", "El explorador de archivos"], correctOption: 0 },
      { prompt: "¿Qué función calcula el valor más alto de un rango?", options: ["MAX", "MIN", "CONTAR", "PROMEDIO"], correctOption: 0 },
      { prompt: "¿Qué función calcula el valor más bajo de un rango?", options: ["MIN", "MAX", "SUMA", "SI"], correctOption: 0 },
      { prompt: "¿Qué permite convertir una lista en una tabla con filtros automáticos?", options: ["Formato como tabla", "Combinar celdas", "Validación de datos", "Buscar objetivo"], correctOption: 0 },
      { prompt: "¿Qué hace el formato condicional?", options: ["Resalta valores automáticamente según una regla", "Cuenta celdas vacías", "Elimina duplicados", "Cambia el idioma de la hoja"], correctOption: 0 },
      { prompt: "¿Qué tipo de dato representa una fecha en Excel?", options: ["Fecha", "Macro", "Hipervínculo", "Etiqueta"], correctOption: 0 },
      { prompt: "¿Para qué sirve 'Ajustar texto'?", options: ["Para mostrar contenido largo en varias líneas", "Para traducir el texto", "Para contar palabras", "Para cambiar el tipo de dato"], correctOption: 0 },
      { prompt: "¿Qué combinación de teclas guarda un archivo?", options: ["Ctrl+S", "Ctrl+P", "Ctrl+Z", "Ctrl+N"], correctOption: 0 },
      { prompt: "¿Qué mide la función CONTAR?", options: ["Cuántas celdas de un rango tienen números", "El valor más alto de un rango", "El promedio de un rango", "El nombre de una hoja"], correctOption: 0 },
      { prompt: "¿Qué logra aplicar un estilo de tabla predefinido?", options: ["Un diseño profesional en un clic", "Eliminar todas las fórmulas", "Cambiar el nombre del archivo", "Ocultar los datos"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "excel-intermedio": {
    projectTitle: "Dashboard de ventas con tablas dinámicas",
    projectInstructions: "Construye un dashboard de ventas con tablas dinámicas y gráficos interactivos, aplicando funciones SI.CONJUNTO, BUSCARX y filtros avanzados sobre una base de datos real.",
    acceptedFormats: "Comparte un enlace de OneDrive, Google Drive o GitHub con tu archivo .xlsx.",
    questions: [
      { prompt: "¿Qué herramienta resume información por categorías en Excel?", options: ["Tabla dinámica", "Formato condicional", "Buscar y reemplazar", "Validación de datos"], correctOption: 0 },
      { prompt: "¿Qué referencia no cambia al copiar una fórmula?", options: ["Relativa", "Absoluta", "Mixta", "Circular"], correctOption: 1 },
      { prompt: "¿Qué función evalúa varias condiciones en orden sin anidar varios SI?", options: ["SI.CONJUNTO", "CONTAR.SI", "BUSCARV", "Y"], correctOption: 0 },
      { prompt: "¿Qué función de búsqueda puede buscar en cualquier dirección?", options: ["BUSCARX", "BUSCARV", "BUSCARH", "SUMAR.SI"], correctOption: 0 },
      { prompt: "¿Qué devuelve la función COINCIDIR?", options: ["La posición de un valor dentro de un rango", "El valor máximo de un rango", "El promedio de un rango", "El nombre de una hoja"], correctOption: 0 },
      { prompt: "¿Qué permite hacer un segmentador de datos en una tabla dinámica?", options: ["Filtrar visualmente con un clic", "Sumar valores", "Ordenar alfabéticamente", "Proteger el archivo"], correctOption: 0 },
      { prompt: "¿Qué acción elimina registros repetidos en una base de datos?", options: ["Eliminar duplicados", "Combinar celdas", "Ajustar texto", "Formato condicional"], correctOption: 0 },
      { prompt: "¿Qué gráfico es ideal para comparar valores entre categorías?", options: ["Gráfico de barras", "Gráfico circular", "Gráfico combinado", "Ninguno"], correctOption: 0 },
      { prompt: "¿Qué gráfico muestra la proporción de cada categoría respecto a un total?", options: ["Gráfico circular", "Gráfico de barras", "Gráfico de líneas", "Ninguno"], correctOption: 0 },
      { prompt: "¿Qué permite restringir lo que se escribe en una celda?", options: ["Validación de datos", "Formato condicional", "Combinar celdas", "Segmentación"], correctOption: 0 },
      { prompt: "¿Qué función devuelve VERDADERO solo si todas las condiciones se cumplen?", options: ["Y", "O", "SI.ERROR", "CONTAR.SI"], correctOption: 0 },
      { prompt: "¿Qué logra agrupar fechas en una tabla dinámica?", options: ["Resumir por mes o año", "Eliminar columnas", "Cambiar el color de la hoja", "Ordenar alfabéticamente"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "excel-avanzado": {
    projectTitle: "Sistema de análisis empresarial con Power Query y VBA",
    projectInstructions: "Desarrolla un sistema completo de análisis empresarial combinando Power Query para preparar los datos, un dashboard ejecutivo con KPIs y al menos una macro de VBA que automatice una tarea repetitiva.",
    acceptedFormats: "Comparte un enlace de OneDrive, Google Drive o GitHub con tu archivo .xlsx habilitado para macros.",
    questions: [
      { prompt: "¿Qué herramienta se usa para importar y transformar datos antes de analizarlos?", options: ["Power Query", "Formato condicional", "Buscar y reemplazar", "Validación de datos"], correctOption: 0 },
      { prompt: "¿Qué permite automatizar tareas repetitivas en Excel?", options: ["Una macro", "Un filtro", "Un comentario", "Un hipervínculo"], correctOption: 0 },
      { prompt: "¿Qué función suma valores que cumplen múltiples criterios a la vez?", options: ["SUMAR.SI.CONJUNTO", "SUMAR.SI", "CONTAR.SI", "PROMEDIO.SI"], correctOption: 0 },
      { prompt: "¿Qué función cuenta celdas que cumplen un único criterio?", options: ["CONTAR.SI", "SUMAR.SI.CONJUNTO", "PROMEDIO.SI", "BUSCARX"], correctOption: 0 },
      { prompt: "¿Qué función calcula el promedio de un rango que cumple una condición?", options: ["PROMEDIO.SI", "SUMAR.SI", "CONTAR.SI", "MAX"], correctOption: 0 },
      { prompt: "¿Qué herramienta encuentra el valor de entrada necesario para lograr un resultado deseado?", options: ["Buscar objetivo", "Solver", "Escenarios", "Power Query"], correctOption: 0 },
      { prompt: "¿Qué herramienta resuelve problemas de optimización con restricciones?", options: ["Solver", "Buscar objetivo", "Segmentación", "Validación de datos"], correctOption: 0 },
      { prompt: "¿Qué herramienta permite comparar distintos conjuntos de valores de entrada?", options: ["Escenarios", "Macros", "Power Query", "CONTAR.SI"], correctOption: 0 },
      { prompt: "¿Qué hace Power Query?", options: ["Importar, limpiar y transformar datos", "Crear gráficos automáticamente", "Proteger archivos", "Traducir contenido"], correctOption: 0 },
      { prompt: "¿Qué lenguaje de programación se usa para automatizar tareas en Excel?", options: ["VBA", "Python", "SQL", "HTML"], correctOption: 0 },
      { prompt: "¿Qué registra una macro grabada?", options: ["Los pasos realizados para repetirlos automáticamente", "Solo el nombre del archivo", "El color de las celdas", "El idioma del sistema"], correctOption: 0 },
      { prompt: "¿Qué mide un KPI?", options: ["Si un objetivo de negocio se cumple o no", "El color de una celda", "El número de hojas del libro", "El idioma del archivo"], correctOption: 0 },
      { prompt: "¿Qué muestra un dashboard financiero?", options: ["Ingresos, gastos y utilidad", "Solo el logotipo de la empresa", "Solo gráficos circulares", "Solo texto"], correctOption: 0 },
      { prompt: "¿En qué se enfoca un dashboard comercial?", options: ["Ventas y desempeño por vendedor o región", "Solo gastos administrativos", "Solo el organigrama", "Solo el clima laboral"], correctOption: 0 },
      { prompt: "¿Qué organiza el modelado de datos?", options: ["Tablas relacionadas entre sí", "El color de fondo de las hojas", "El idioma del archivo", "El número de columnas visibles"], correctOption: 0 },
      { prompt: "¿Qué herramienta de Excel se puede conectar directamente con Power BI?", options: ["Power Pivot", "Solver", "Buscar objetivo", "Validación de datos"], correctOption: 0 },
      { prompt: "¿Qué reduce la toma de decisiones basada en datos?", options: ["El riesgo de decidir solo por intuición", "La cantidad de datos disponibles", "La necesidad de reportes", "El uso de Excel en general"], correctOption: 0 },
      { prompt: "¿Qué debe priorizar un buen dashboard?", options: ["Pocos indicadores clave y claridad visual", "La mayor cantidad de datos posible", "Muchos colores llamativos", "Textos largos y detallados"], correctOption: 0 },
      { prompt: "¿Qué análisis evalúa cómo cambia un resultado al variar una variable?", options: ["Análisis de sensibilidad", "Análisis de texto", "Análisis de formato", "Análisis de color"], correctOption: 0 },
      { prompt: "¿Qué permite un formulario en Excel?", options: ["Que un usuario interactúe con el archivo sin ver fórmulas", "Cambiar el idioma del sistema", "Eliminar columnas automáticamente", "Proteger la hoja con contraseña"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "power-bi-basico": {
    projectTitle: "Dashboard comercial en Power BI",
    projectInstructions: "Construye un dashboard con ventas, fecha, producto y región. Incluye al menos tres indicadores, segmentadores y una conclusión de negocio.",
    acceptedFormats: "Comparte un enlace de OneDrive, Google Drive o Power BI Service con tu archivo .pbix o informe publicado.",
    questions: [
      { prompt: "¿Qué elemento permite filtrar varias visualizaciones en Power BI?", options: ["Segmentador", "Marcador", "Tema", "Tooltip"], correctOption: 0 },
      { prompt: "¿Qué modelo organiza hechos y dimensiones para análisis?", options: ["Modelo estrella", "Modelo circular", "Modelo lineal", "Modelo de texto"], correctOption: 0 },
      { prompt: "¿Cuáles son las tres vistas principales de Power BI Desktop?", options: ["Informe, Datos y Modelo", "Inicio, Insertar y Vista", "Archivo, Editar y Ver", "Tabla, Gráfico y Texto"], correctOption: 0 },
      { prompt: "¿Qué extensión tiene un archivo de Power BI Desktop?", options: [".pbix", ".xlsx", ".csv", ".docx"], correctOption: 0 },
      { prompt: "¿Qué gráfico es más adecuado para mostrar una tendencia en el tiempo?", options: ["Gráfico de líneas", "Gráfico circular", "Tarjeta", "Mapa"], correctOption: 0 },
      { prompt: "¿Qué conecta una relación entre dos tablas?", options: ["Una columna en común", "El color de las celdas", "El nombre del archivo", "El tamaño de la tabla"], correctOption: 0 },
      { prompt: "¿Qué cardinalidad es la más común en un modelo de datos?", options: ["Uno a varios", "Varios a varios", "Cero a uno", "Ninguna"], correctOption: 0 },
      { prompt: "¿Qué es una medida en Power BI?", options: ["Un cálculo creado con DAX usado en visualizaciones", "Una imagen insertada en el informe", "Un tipo de relación entre tablas", "Un archivo CSV"], correctOption: 0 },
      { prompt: "¿Qué es un segmentador?", options: ["Un control visual para filtrar interactivamente", "Una medida DAX", "Un tipo de gráfico circular", "Una tabla de hechos"], correctOption: 0 },
      { prompt: "¿Qué permite hacer publicar un informe en Power BI Service?", options: ["Compartirlo de forma segura con otras personas", "Eliminar el archivo original", "Cambiar el modelo de datos", "Ocultar las visualizaciones"], correctOption: 0 },
      { prompt: "¿Qué lenguaje se usa para crear medidas en Power BI?", options: ["DAX", "SQL", "Python", "VBA"], correctOption: 0 },
      { prompt: "¿Por qué es importante limpiar los datos antes de analizarlos?", options: ["Para evitar errores y resultados incorrectos en el análisis", "Para cambiar el idioma del programa", "Para que el archivo sea más pesado", "Para eliminar los gráficos"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "power-bi-intermedio": {
    projectTitle: "Modelo de datos con medidas DAX",
    projectInstructions: "Diseña un modelo con una tabla calendario y relaciones correctas, y crea al menos tres medidas DAX que comparen periodos.",
    acceptedFormats: "Comparte un enlace de OneDrive, Google Drive o Power BI Service con tu archivo .pbix.",
    questions: [
      { prompt: "¿Qué función se usa para modificar el contexto de filtro en DAX?", options: ["CALCULATE", "SUM", "IF", "COUNT"], correctOption: 0 },
      { prompt: "¿Para qué sirve una tabla calendario?", options: ["Calcular indicadores de tiempo", "Guardar imágenes", "Ordenar columnas de texto", "Crear segmentadores visuales"], correctOption: 0 },
      { prompt: "¿Qué diferencia a una relación activa de una inactiva?", options: ["La activa se usa automáticamente; la inactiva requiere USERELATIONSHIP", "La inactiva es más rápida", "La activa no permite filtros", "No existe diferencia real"], correctOption: 0 },
      { prompt: "¿Qué contienen las tablas de hechos?", options: ["Datos transaccionales como ventas o pedidos", "Solo nombres de productos", "Solo fechas", "Solo colores"], correctOption: 0 },
      { prompt: "¿Qué función de DAX genera un rango de fechas?", options: ["CALENDAR", "SUM", "FILTER", "RELATED"], correctOption: 0 },
      { prompt: "¿Qué hace la función ALL?", options: ["Elimina todos los filtros de una tabla o columna", "Aplica todos los filtros posibles", "Crea una nueva relación", "Cambia el tipo de dato"], correctOption: 0 },
      { prompt: "¿Qué diferencia a ALLSELECTED de ALL?", options: ["ALLSELECTED respeta los filtros del reporte, pero ignora los del usuario", "ALLSELECTED es más lenta", "ALLSELECTED no existe en DAX", "No hay ninguna diferencia"], correctOption: 0 },
      { prompt: "¿Qué compara un indicador año contra año (YoY)?", options: ["Un periodo actual con el mismo periodo del año anterior", "Dos productos distintos", "Dos regiones distintas", "Dos vendedores distintos"], correctOption: 0 },
      { prompt: "¿Qué calcula un acumulado o 'year to date'?", options: ["La suma desde el inicio del año hasta la fecha del filtro", "El promedio de todo el histórico", "El valor máximo de un solo día", "El total de un solo mes"], correctOption: 0 },
      { prompt: "¿Qué función DAX compara con el mismo periodo del año anterior?", options: ["SAMEPERIODLASTYEAR", "DATESYTD", "ALL", "FILTER"], correctOption: 0 },
      { prompt: "¿Qué es el contexto de fila?", options: ["La fila actual que se está evaluando", "Los filtros del reporte", "El nombre de la tabla", "El color de la visualización"], correctOption: 0 },
      { prompt: "¿Qué se necesita para que las medidas de tiempo funcionen correctamente?", options: ["Una tabla calendario correctamente relacionada", "Un archivo CSV adicional", "Un segmentador de color", "Una relación varios a varios"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "power-bi-avanzado": {
    projectTitle: "Informe seguro y publicado en Power BI Service",
    projectInstructions: "Aplica seguridad a nivel de fila (RLS) a un modelo, prueba al menos dos roles y publica el informe con actualización programada.",
    acceptedFormats: "Comparte un enlace de Power BI Service con el informe publicado y la configuración de roles documentada.",
    questions: [
      { prompt: "¿Qué mecanismo restringe los datos que ve cada usuario en Power BI?", options: ["Seguridad a nivel de fila (RLS)", "Un marcador", "Un tema visual", "Un tooltip"], correctOption: 0 },
      { prompt: "¿Dónde se publican y comparten los informes de Power BI?", options: ["Power BI Service", "Un correo electrónico", "Una hoja de Excel", "Un documento PDF"], correctOption: 0 },
      { prompt: "¿Qué caracteriza a un rol estático?", options: ["Filtra datos con un valor fijo", "Cambia según el usuario que inicia sesión", "No aplica ningún filtro", "Solo funciona con fechas"], correctOption: 0 },
      { prompt: "¿Qué caracteriza a un rol dinámico?", options: ["Filtra datos según el usuario que inició sesión", "Filtra siempre el mismo valor fijo", "No requiere ninguna fórmula", "Solo se aplica a administradores"], correctOption: 0 },
      { prompt: "¿Cómo se prueban los roles antes de publicar?", options: ["Con la opción 'Ver como roles'", "Publicando directamente sin revisar", "Cambiando el idioma del informe", "Eliminando las relaciones del modelo"], correctOption: 0 },
      { prompt: "¿Qué es un workspace en Power BI Service?", options: ["Un espacio donde se organizan informes, dashboards y conjuntos de datos", "Un tipo de gráfico", "Una función DAX", "Un archivo CSV"], correctOption: 0 },
      { prompt: "¿Qué permite la actualización programada?", options: ["Que los datos se refresquen automáticamente sin intervención manual", "Que el informe cambie de idioma", "Que se eliminen visualizaciones antiguas", "Que se genere un nuevo modelo de datos"], correctOption: 0 },
      { prompt: "¿Qué determinan los permisos en un workspace?", options: ["Quién puede ver, editar o administrar un informe", "El color de las visualizaciones", "El tipo de gráfico disponible", "El idioma del sistema"], correctOption: 0 },
      { prompt: "¿Qué logra reducir columnas innecesarias en el modelo?", options: ["Disminuir el tamaño del archivo y mejorar la velocidad", "Aumentar el número de relaciones", "Cambiar el idioma del informe", "Eliminar todas las medidas"], correctOption: 0 },
      { prompt: "¿Qué evita el uso de variables (VAR) en DAX?", options: ["Recalcular la misma expresión varias veces", "Crear relaciones entre tablas", "Usar funciones de tiempo", "Aplicar seguridad a nivel de fila"], correctOption: 0 },
      { prompt: "¿Qué identifica el Analizador de rendimiento?", options: ["Qué visualización o consulta tarda más en cargar", "El color de los gráficos", "El idioma del informe", "El número de usuarios conectados"], correctOption: 0 },
      { prompt: "¿Qué hacen las funciones iteradoras como SUMX?", options: ["Recorren fila por fila una tabla para calcular un resultado", "Eliminan relaciones del modelo", "Cambian el idioma del informe", "Solo funcionan con texto"], correctOption: 0 },
      { prompt: "¿Qué es una tabla virtual en DAX?", options: ["Una tabla temporal creada dentro de una fórmula que no existe físicamente", "Una tabla importada desde Excel", "Una tabla de seguridad", "Una tabla calendario"], correctOption: 0 },
      { prompt: "¿Qué función se usa para crear una tabla virtual agrupada?", options: ["SUMMARIZE", "SUM", "RELATED", "ALLSELECTED"], correctOption: 0 },
      { prompt: "¿Qué patrón de análisis identifica a los mejores clientes o productos?", options: ["Top N (como Top 5 clientes)", "Comparativo año contra año", "Seguridad a nivel de fila", "Actualización programada"], correctOption: 0 },
      { prompt: "¿Qué función se usa comúnmente en roles dinámicos?", options: ["USERPRINCIPALNAME()", "SUM()", "CALENDAR()", "ALLSELECTED()"], correctOption: 0 },
      { prompt: "¿Cómo se puede distribuir un informe de Power BI?", options: ["Mediante apps, enlaces directos o incrustación", "Solo imprimiéndolo en papel", "Solo enviándolo por correo como imagen", "No se puede distribuir"], correctOption: 0 },
      { prompt: "¿Qué evita una buena gobernanza de workspaces?", options: ["Informes duplicados y desactualizados", "El uso de medidas DAX", "La creación de relaciones", "El uso de segmentadores"], correctOption: 0 },
      { prompt: "¿Qué se recomienda evitar en favor de las medidas?", options: ["Columnas calculadas innecesarias", "Las tablas de dimensión", "Las relaciones activas", "Los segmentadores"], correctOption: 0 },
      { prompt: "¿Qué requiere dominar el DAX avanzado?", options: ["Entender bien el contexto de fila y de filtro", "Solo conocer Excel básico", "Solo saber crear gráficos", "Solo conocer Power Query"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "sql-basico": {
    projectTitle: "Consulta de indicadores con SQL",
    projectInstructions: "Diseña consultas que filtren información, unan dos tablas y calculen un indicador de negocio usando una base de práctica.",
    acceptedFormats: "Comparte un enlace de GitHub, Google Drive o un archivo .sql.",
    questions: [
      { prompt: "¿Qué cláusula se usa para combinar registros de dos tablas relacionadas?", options: ["JOIN", "ORDER BY", "LIMIT", "DELETE"], correctOption: 0 },
      { prompt: "¿Qué instrucción agrupa resultados para calcular totales?", options: ["GROUP BY", "WHERE", "SELECT", "VALUES"], correctOption: 0 },
      { prompt: "¿Qué hace SELECT?", options: ["Recupera columnas específicas de una tabla", "Elimina filas", "Crea una tabla", "Cambia un tipo de dato"], correctOption: 0 },
      { prompt: "¿Qué hace WHERE?", options: ["Filtra las filas que cumplen una condición", "Ordena los resultados", "Limita las filas", "Une dos tablas"], correctOption: 0 },
      { prompt: "¿Qué hace ORDER BY?", options: ["Ordena los resultados ascendente o descendentemente", "Filtra filas", "Cuenta registros", "Elimina duplicados"], correctOption: 0 },
      { prompt: "¿Qué hace LIMIT?", options: ["Restringe el número de filas devueltas", "Ordena resultados", "Filtra por condición", "Cambia el nombre de una columna"], correctOption: 0 },
      { prompt: "¿Qué devuelve INNER JOIN?", options: ["Solo las filas que coinciden en ambas tablas", "Todas las filas de ambas tablas", "Solo filas sin coincidencia", "Ninguna fila"], correctOption: 0 },
      { prompt: "¿Qué función calcula un promedio?", options: ["AVG", "SUM", "COUNT", "MAX"], correctOption: 0 },
      { prompt: "¿Qué es una subconsulta?", options: ["Una consulta dentro de otra consulta", "Una tabla física", "Un tipo de índice", "Un procedimiento almacenado"], correctOption: 0 },
      { prompt: "¿Por qué es mejor especificar columnas en lugar de usar SELECT *?", options: ["Porque mejora el rendimiento y la claridad de la consulta", "Porque es obligatorio en SQL", "Porque elimina errores de sintaxis", "Porque cambia el nombre de la tabla"], correctOption: 0 },
      { prompt: "¿Qué diferencia a HAVING de WHERE?", options: ["HAVING filtra después de agrupar, WHERE filtra antes", "Son idénticos", "WHERE solo funciona con JOIN", "HAVING no permite condiciones"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "sql-intermedio": {
    projectTitle: "Reporte con múltiples tablas y subconsultas",
    projectInstructions: "Escribe consultas que combinen al menos tres tablas, incluyan una subconsulta y una vista o CTE reutilizable.",
    acceptedFormats: "Comparte un enlace de GitHub, Google Drive o un archivo .sql.",
    questions: [
      { prompt: "¿Qué permite reutilizar una consulta compleja dentro de otra?", options: ["Una CTE", "Un ORDER BY", "Un LIMIT", "Un DELETE"], correctOption: 0 },
      { prompt: "¿Qué función asigna un número de fila dentro de una partición?", options: ["ROW_NUMBER", "SUM", "AVG", "COUNT"], correctOption: 0 },
      { prompt: "¿Qué devuelve LEFT JOIN?", options: ["Todas las filas de la tabla izquierda, con NULL si no hay coincidencia", "Solo coincidencias", "Solo filas de la derecha", "Ninguna fila"], correctOption: 0 },
      { prompt: "¿Para qué sirven los alias en SQL?", options: ["Para acortar nombres y hacer las consultas más legibles", "Para eliminar columnas", "Para crear índices", "Para cambiar el tipo de dato"], correctOption: 0 },
      { prompt: "¿Qué caracteriza a una subconsulta correlacionada?", options: ["Depende de la fila actual de la consulta externa", "Se ejecuta una sola vez siempre", "No puede usarse en WHERE", "Solo funciona con JOIN"], correctOption: 0 },
      { prompt: "¿Cómo se trata una subconsulta en el FROM?", options: ["Como una tabla temporal", "Como una columna nueva", "Como un índice", "Como un procedimiento almacenado"], correctOption: 0 },
      { prompt: "¿Qué hace RANK()?", options: ["Asigna una posición de ranking, dejando huecos si hay empates", "Cuenta filas", "Ordena alfabéticamente", "Filtra por condición"], correctOption: 0 },
      { prompt: "¿Qué hace PARTITION BY?", options: ["Divide los datos en grupos para aplicar la función por separado", "Elimina una tabla", "Crea un índice", "Cambia el nombre de una columna"], correctOption: 0 },
      { prompt: "¿Cómo se define una CTE?", options: ["Con WITH nombre AS (consulta)", "Con CREATE TABLE", "Con INSERT INTO", "Con DELETE FROM"], correctOption: 0 },
      { prompt: "¿Qué es una vista (VIEW) en SQL?", options: ["Una consulta guardada como tabla virtual reutilizable", "Un tipo de índice", "Un procedimiento almacenado", "Una función de ventana"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "sql-avanzado": {
    projectTitle: "Optimización y procedimiento almacenado",
    projectInstructions: "Optimiza una consulta lenta usando índices, y crea un procedimiento almacenado que reciba parámetros y controle errores.",
    acceptedFormats: "Comparte un enlace de GitHub, Google Drive o un archivo .sql.",
    questions: [
      { prompt: "¿Qué estructura mejora el rendimiento de búsquedas frecuentes?", options: ["Un índice", "Un comentario", "Un alias", "Un LIMIT"], correctOption: 0 },
      { prompt: "¿Qué instrucción confirma los cambios de una transacción?", options: ["COMMIT", "SELECT", "JOIN", "WHERE"], correctOption: 0 },
      { prompt: "¿Qué hace LAG()?", options: ["Obtiene el valor de una fila anterior dentro de la partición", "Obtiene el valor de una fila siguiente", "Suma todos los valores", "Elimina una fila"], correctOption: 0 },
      { prompt: "¿Qué hace LEAD()?", options: ["Obtiene el valor de una fila siguiente dentro de la partición", "Obtiene el valor de una fila anterior", "Cuenta las filas", "Ordena los resultados"], correctOption: 0 },
      { prompt: "¿Qué calcula un acumulado (running total)?", options: ["La suma progresiva de los valores anteriores", "El promedio de toda la tabla", "El valor máximo", "El número total de filas"], correctOption: 0 },
      { prompt: "¿Qué hace un índice en una base de datos?", options: ["Acelera la búsqueda de datos en una columna", "Elimina filas duplicadas", "Cambia el tipo de dato", "Crea una nueva tabla"], correctOption: 0 },
      { prompt: "¿Qué muestra un plan de ejecución?", options: ["Cómo la base de datos procesará una consulta", "El historial de usuarios", "El color de las tablas", "El idioma del motor"], correctOption: 0 },
      { prompt: "¿Qué es un procedimiento almacenado?", options: ["Un bloque de código SQL guardado en la base de datos, ejecutable con una instrucción", "Un tipo de índice", "Una vista temporal", "Una función de ventana"], correctOption: 0 },
      { prompt: "¿Para qué sirven los parámetros en un procedimiento?", options: ["Para recibir valores distintos en cada ejecución", "Para eliminar tablas", "Para crear índices automáticamente", "Para cambiar el idioma del sistema"], correctOption: 0 },
      { prompt: "¿Qué previene el control de errores en un procedimiento?", options: ["Que falle silenciosamente sin explicación", "Que se ejecute más rápido", "Que reciba parámetros", "Que se guarde en la base de datos"], correctOption: 0 },
      { prompt: "¿Qué agrupa una transacción?", options: ["Varias operaciones SQL para que se ejecuten todas juntas o ninguna", "Solo una operación de lectura", "Solo consultas SELECT", "Solo la creación de tablas"], correctOption: 0 },
      { prompt: "¿Qué hace ROLLBACK?", options: ["Deshace todos los cambios de una transacción si algo falla", "Confirma los cambios de forma permanente", "Crea una vista nueva", "Elimina un procedimiento almacenado"], correctOption: 0 },
      { prompt: "¿Qué controlan los niveles de aislamiento?", options: ["Cómo las transacciones concurrentes se afectan entre sí", "El color de las tablas", "El tipo de dato de una columna", "El idioma del motor"], correctOption: 0 },
      { prompt: "¿Qué instrucciones se usan para gestionar permisos de acceso?", options: ["GRANT y REVOKE", "COMMIT y ROLLBACK", "SELECT e INSERT", "CREATE y DROP"], correctOption: 0 },
      { prompt: "¿Qué puede impedir el uso de un índice existente?", options: ["Aplicar una función sobre la columna filtrada", "Usar WHERE en la consulta", "Usar un alias en la tabla", "Ordenar los resultados"], correctOption: 0 },
      { prompt: "¿Qué logra un promedio móvil?", options: ["Suavizar variaciones temporales en los datos", "Eliminar valores duplicados", "Cambiar el tipo de dato", "Crear un nuevo índice"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "python-basico": {
    projectTitle: "Programa básico en Python",
    projectInstructions: "Escribe un programa que use variables, condicionales, un ciclo y al menos una función propia para resolver un problema simple.",
    acceptedFormats: "Comparte un enlace de GitHub, Google Drive o Colab con tu archivo .py.",
    questions: [
      { prompt: "¿Qué estructura repite instrucciones mientras se cumple una condición?", options: ["Ciclo while", "Diccionario", "Función", "Comentario"], correctOption: 0 },
      { prompt: "¿Qué permite reutilizar un bloque de código con distintos valores?", options: ["Una función", "Una variable global", "Un comentario", "Un print"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "python-intermedio": {
    projectTitle: "Reporte automatizado con Python",
    projectInstructions: "Analiza un archivo CSV con Pandas, limpia datos relevantes, calcula al menos dos métricas y genera un gráfico con una conclusión.",
    acceptedFormats: "Comparte un enlace de GitHub, Google Drive o Colab con tu archivo .ipynb o .py.",
    questions: [
      { prompt: "¿Qué estructura usa Pandas para trabajar con datos tabulares?", options: ["DataFrame", "Variable global", "Lista CSS", "Tabla dinámica"], correctOption: 0 },
      { prompt: "¿Qué acción es clave antes de analizar una base?", options: ["Limpiar y revisar datos", "Cambiar todos los nombres", "Eliminar columnas al azar", "Exportar sin revisar"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "python-avanzado": {
    projectTitle: "Script orientado a objetos con consumo de API",
    projectInstructions: "Crea al menos una clase con métodos propios y un script que consuma una API pública, maneje errores y guarde el resultado en un archivo.",
    acceptedFormats: "Comparte un enlace de GitHub con tu repositorio y archivo .py.",
    questions: [
      { prompt: "¿Qué palabra clave define una clase en Python?", options: ["class", "def", "import", "return"], correctOption: 0 },
      { prompt: "¿Qué formato usan comúnmente las respuestas de una API?", options: ["JSON", "XLSX", "DOCX", "PPTX"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "ingles-basico": {
    projectTitle: "Presentación personal en inglés",
    projectInstructions: "Graba o escribe una presentación breve sobre ti usando presente simple, incluyendo tu rutina diaria y datos personales básicos.",
    acceptedFormats: "Comparte un enlace de Google Drive con un audio, video o documento de texto.",
    questions: [
      { prompt: "¿Qué verbo se usa para describir estados y características (soy, estoy)?", options: ["To be", "To do", "To have", "To go"], correctOption: 0 },
      { prompt: "¿Qué tiempo verbal se usa para describir rutinas diarias?", options: ["Presente simple", "Pasado simple", "Futuro", "Presente perfecto"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "ingles-intermedio": {
    projectTitle: "Correo profesional en inglés",
    projectInstructions: "Redacta un correo formal en inglés solicitando información o proponiendo una reunión, usando pasado o futuro según corresponda.",
    acceptedFormats: "Comparte un enlace de Google Drive o un archivo PDF/Word con tu correo.",
    questions: [
      { prompt: "¿Qué tono se recomienda usar en un correo de trabajo?", options: ["Formal", "Muy informal", "Con abreviaciones", "Sin saludo"], correctOption: 0 },
      { prompt: "¿Qué tiempo verbal se usa para narrar experiencias pasadas?", options: ["Pasado simple", "Presente simple", "Futuro", "Imperativo"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "ingles-avanzado": {
    projectTitle: "Presentación de negociación en inglés",
    projectInstructions: "Prepara una presentación o simulación de negociación en inglés, incluyendo una propuesta, argumentos y respuesta a posibles objeciones.",
    acceptedFormats: "Comparte un enlace de Google Drive con un video, audio o documento de la presentación.",
    questions: [
      { prompt: "¿Qué elemento es clave en una negociación efectiva?", options: ["Argumentar una postura con claridad", "Hablar sin escuchar", "Evitar llegar a acuerdos", "Usar solo vocabulario informal"], correctOption: 0 },
      { prompt: "¿Qué característica debe tener un reporte profesional en inglés?", options: ["Cohesión y registro formal", "Errores intencionales", "Lenguaje coloquial", "Frases inconexas"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "programacion-desarrollo-web": {
    projectTitle: "Sitio web funcional",
    projectInstructions: "Crea una página web responsive con estructura semántica, estilos propios y una interacción básica en JavaScript.",
    acceptedFormats: "Comparte el enlace publicado y el repositorio de GitHub.",
    questions: [
      { prompt: "¿Qué lenguaje aporta estructura semántica a una página web?", options: ["HTML", "CSS", "SQL", "Power BI"], correctOption: 0 },
      { prompt: "¿Qué técnica ayuda a adaptar un sitio a celulares?", options: ["Diseño responsive", "Texto fijo", "Imágenes sin tamaño", "Solo escritorio"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "introduccion-a-la-ia": {
    projectTitle: "Propuesta de IA responsable",
    projectInstructions: "Define un problema cotidiano, plantea una solución apoyada por IA, redacta prompts de prueba e identifica riesgos y validaciones necesarias.",
    acceptedFormats: "Comparte un enlace de Google Drive, Notion o un archivo PDF.",
    questions: [
      { prompt: "¿Qué debes hacer con una respuesta generada por IA antes de usarla?", options: ["Verificarla", "Publicarla sin revisar", "Copiarla siempre", "Ocultar su origen"], correctOption: 0 },
      { prompt: "¿Qué información no debes incluir en un prompt público?", options: ["Datos personales sensibles", "Objetivo de la tarea", "Formato deseado", "Contexto permitido"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "investigacion-aplicada": {
    projectTitle: "Mini proyecto de investigación",
    projectInstructions: "Formula un problema, objetivos, preguntas, metodología y una conclusión basada en fuentes confiables.",
    acceptedFormats: "Comparte un enlace de Google Drive o un archivo .docx o PDF.",
    questions: [
      { prompt: "¿Qué debe responder un objetivo de investigación?", options: ["Qué se busca lograr", "El color del informe", "La opinión personal", "El nombre del archivo"], correctOption: 0 },
      { prompt: "¿Por qué se citan las fuentes?", options: ["Para respaldar y atribuir información", "Para llenar páginas", "Para evitar analizar", "Para usar más texto"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
  "finanzas-para-emprendedores": {
    projectTitle: "Plan financiero de un emprendimiento",
    projectInstructions: "Elabora un presupuesto con ingresos, gastos, costos, precios y una proyección de flujo de caja para un negocio simple.",
    acceptedFormats: "Comparte un enlace de OneDrive, Google Drive o un archivo .xlsx.",
    questions: [
      { prompt: "¿Qué muestra el flujo de caja?", options: ["Entradas y salidas de dinero", "Solo las ventas", "El logo del negocio", "Las horas de trabajo"], correctOption: 0 },
      { prompt: "¿Qué costo se mantiene aunque no se venda?", options: ["Costo fijo", "Costo variable", "Descuento", "Ingreso"], correctOption: 0 },
      ...sharedQuestions,
    ],
  },
};

export function getCourseAssessment(courseSlug: string) {
  return assessments[courseSlug];
}
