export type EnglishLevel = "principiante" | "intermedio" | "avanzado";
export type EnglishLessonType = "vocab" | "listen" | "pron" | "reading" | "quiz";
export type EnglishVocabCard = { emoji: string; en: string; ipa: string; es: string };
export type EnglishExercise = { audio: string; options: [string, string, string]; correct: number };
export type EnglishPhrase = { en: string; es: string };
export type EnglishQuestion = { q: string; options: [string, string, string, string]; correct: number; explain: string };
export type EnglishContext = { type: EnglishLessonType; listened: Set<string>; completed: number; answered: Set<number>; practiced: number; marked: Set<number> };
export type EnglishCheck = { desc: string; test: (ctx: EnglishContext) => boolean };
export type EnglishLesson = {
  id: string; type: EnglishLessonType; icon: string; xp: number; minutes: number; title: string; desc: string; level: EnglishLevel;
  objectives: [string, string, string]; dax: { hint: string; explain: string; example: string };
  intro?: string; vocab?: EnglishVocabCard[]; exercises?: EnglishExercise[]; phrases?: EnglishPhrase[];
  content?: string; keyPoints?: [string, string, string]; questions?: EnglishQuestion[]; checks?: [EnglishCheck];
};
export type EnglishModule = { id: string; title: string; minutes: number; goal: string; level: EnglishLevel; photo: string; photoAlt: string; lessons: EnglishLesson[] };

type VocabSpec = { title: string; desc: string; cards: EnglishVocabCard[]; hint: string; analogy: string; example: string; threshold: number; intro?: string };
type ListenSpec = { title: string; desc: string; exercises: EnglishExercise[]; hint: string; analogy: string; example: string; intro?: string };
type PronSpec = { title: string; desc: string; phrases: EnglishPhrase[]; hint: string; analogy: string; example: string; threshold: number; intro?: string };
type ReadingSpec = { title: string; desc: string; explanation: string; pattern: string; points: [string, string, string]; note: string; tip: string; hint: string; analogy: string; example: string };
type ModuleSpec = { title: string; level: EnglishLevel; goal: string; photo: string; photoAlt: string; vocab: VocabSpec[]; listen: ListenSpec[]; pron: PronSpec[]; reading: ReadingSpec[]; quiz: EnglishQuestion[] };

const photos = {
  hello: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1100&q=85",
  family: "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=1100&q=85",
  cafe: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1100&q=85",
  routine: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1100&q=85",
  journey: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1100&q=85",
  conversation: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1100&q=85",
  travel: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1100&q=85",
  work: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1100&q=85",
  city: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1100&q=85",
  compare: "https://images.unsplash.com/photo-1490730141103-6cac27aaab94?auto=format&fit=crop&w=1100&q=85",
  journal: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1100&q=85",
  ideas: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1100&q=85",
  culture: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=1100&q=85",
  books: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=1100&q=85",
  stage: "https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1100&q=85",
};

const specs: ModuleSpec[] = [
  {
    title: "Hello! First Steps", level: "principiante", photo: photos.hello, photoAlt: "Dos personas adultas conversan en una cafetería", goal: "Saludar, presentarte e intercambiar información personal y números básicos.",
    vocab: [
      { title: "Greetings & Introductions", desc: "Saluda y comparte tu nombre con naturalidad.", cards: [
        { emoji: "👋", en: "Hello", ipa: "/həˈloʊ/", es: "Hola" }, { emoji: "🌤️", en: "Hi", ipa: "/haɪ/", es: "Hola informal" }, { emoji: "🌅", en: "Good morning", ipa: "/ɡʊd ˈmɔːrnɪŋ/", es: "Buenos días" }, { emoji: "☀️", en: "Good afternoon", ipa: "/ɡʊd ˌæftərˈnuːn/", es: "Buenas tardes" }, { emoji: "🌆", en: "Good evening", ipa: "/ɡʊd ˈiːvnɪŋ/", es: "Buenas noches al saludar" }, { emoji: "👤", en: "My name is", ipa: "/maɪ ˈneɪm ɪz/", es: "Me llamo" }, { emoji: "🤝", en: "Nice to meet you", ipa: "/naɪs tə ˈmiːt juː/", es: "Mucho gusto" }, { emoji: "❓", en: "How are you?", ipa: "/haʊ ɑːr juː/", es: "¿Cómo estás?" }, { emoji: "😊", en: "I'm fine", ipa: "/aɪm faɪn/", es: "Estoy bien" }, { emoji: "🙏", en: "Thank you", ipa: "/θæŋk juː/", es: "Gracias" },
      ], hint: "Escucha la sílaba acentuada y repite la expresión completa, no palabra por palabra.", analogy: "Un saludo es como abrir una puerta: una frase corta inicia el intercambio.", example: "Hi, I'm Ana. Nice to meet you. (Hola, soy Ana. Mucho gusto.)", threshold: 6 },
      { title: "Numbers 1–20", desc: "Escucha números para decir tu edad o un teléfono.", cards: [
        { emoji: "1️⃣", en: "One", ipa: "/wʌn/", es: "Uno" }, { emoji: "2️⃣", en: "Two", ipa: "/tuː/", es: "Dos" }, { emoji: "3️⃣", en: "Three", ipa: "/θriː/", es: "Tres" }, { emoji: "4️⃣", en: "Four", ipa: "/fɔːr/", es: "Cuatro" }, { emoji: "5️⃣", en: "Five, six", ipa: "/faɪv sɪks/", es: "Cinco y seis" }, { emoji: "7️⃣", en: "Seven, eight", ipa: "/ˈsevən eɪt/", es: "Siete y ocho" }, { emoji: "9️⃣", en: "Nine, ten", ipa: "/naɪn ten/", es: "Nueve y diez" }, { emoji: "🔢", en: "Eleven, twelve", ipa: "/ɪˈlevən twelv/", es: "Once y doce" }, { emoji: "🎂", en: "Thirteen, fourteen", ipa: "/ˌθɜːrˈtiːn ˌfɔːrˈtiːn/", es: "Trece y catorce" }, { emoji: "🔟", en: "Fifteen, sixteen", ipa: "/ˌfɪfˈtiːn ˌsɪkˈstiːn/", es: "Quince y dieciséis" }, { emoji: "🔟", en: "Seventeen, eighteen", ipa: "/ˌsevənˈtiːn ˌeɪˈtiːn/", es: "Diecisiete y dieciocho" }, { emoji: "🔟", en: "Nineteen, twenty", ipa: "/ˌnaɪnˈtiːn ˈtwenti/", es: "Diecinueve y veinte" },
      ], hint: "En thirteen suele destacarse -teen; escucha y repite esa terminación con claridad.", analogy: "Los números funcionan como claves: hay que reconocerlos aunque cambie la voz.", example: "I'm twenty years old. (Tengo veinte años.)", threshold: 7 },
    ],
    listen: [{ title: "Greeting Sounds", desc: "Distingue saludos de sonido parecido.", exercises: [
      { audio: "Hello", options: ["Hello", "Yellow", "Hollow"], correct: 0 }, { audio: "Good morning", options: ["Good morning", "Good evening", "Good afternoon"], correct: 0 }, { audio: "Thank you", options: ["Think you", "Thank you", "Tank you"], correct: 1 }, { audio: "Nice to meet you", options: ["Nice to meet you", "Nice to see you", "Nine to meet you"], correct: 0 }, { audio: "How are you?", options: ["How are you?", "Who are you?", "How old are you?"], correct: 0 },
    ], hint: "Compara el inicio y la vocal tónica antes de elegir.", analogy: "Como distinguir melodías cercanas, primero reconoce el ritmo y luego los sonidos clave.", example: "How are you? (¿Cómo estás?)" }],
    pron: [{ title: "Meet Someone", desc: "Ensaya una presentación breve y amable.", phrases: [
      { en: "Hello, my name is Ana.", es: "Hola, me llamo Ana." }, { en: "Nice to meet you. How are you?", es: "Mucho gusto. ¿Cómo estás?" }, { en: "I'm fine, thank you. And you?", es: "Estoy bien, gracias. ¿Y tú?" }, { en: "I live in Lima, Peru.", es: "Vivo en Lima, Perú." },
    ], hint: "Une I'm como una sola sílaba y mantén suave to en Nice to meet you.", analogy: "Practicar la presentación es como ensayar una entrada: primero despacio y luego natural.", example: "Nice to meet you. (Mucho gusto.)", threshold: 3 }], reading: [],
    quiz: [
      { q: "¿Cómo se dice «buenos días»?", options: ["Good night", "Good morning", "Good evening", "Good bye"], correct: 1, explain: "Good morning se usa durante la mañana." }, { q: "¿Qué significa «Nice to meet you»?", options: ["Hasta luego", "Mucho gusto", "Buenas noches", "¿Cuántos años tienes?"], correct: 1, explain: "Es una frase habitual al conocer a alguien." }, { q: "¿Qué sonido inicial representa /θ/ en «three»?", options: ["La t de tea", "El sonido th de three", "La f de fine", "La s de see"], correct: 1, explain: "/θ/ se produce colocando suavemente la lengua entre los dientes." }, { q: "¿Cuál responde naturalmente a «How are you?»?", options: ["I am fine, thank you.", "Good night.", "Nice to meet you.", "The check, please."], correct: 0, explain: "I am fine, thank you responde cómo te encuentras." },
    ],
  },
  {
    title: "Family & Colors", level: "principiante", photo: photos.family, photoAlt: "Familia adulta paseando en un parque", goal: "Nombrar familiares y colores, y describir personas u objetos sencillos.",
    vocab: [
      { title: "Family Members", desc: "Reconoce y pronuncia relaciones familiares.", cards: [
        { emoji: "👨", en: "Father", ipa: "/ˈfɑːðər/", es: "Padre" }, { emoji: "👩", en: "Mother", ipa: "/ˈmʌðər/", es: "Madre" }, { emoji: "👦", en: "Brother", ipa: "/ˈbrʌðər/", es: "Hermano" }, { emoji: "👧", en: "Sister", ipa: "/ˈsɪstər/", es: "Hermana" }, { emoji: "👴", en: "Grandfather", ipa: "/ˈɡrændˌfɑːðər/", es: "Abuelo" }, { emoji: "👵", en: "Grandmother", ipa: "/ˈɡrændˌmʌðər/", es: "Abuela" }, { emoji: "👶", en: "Baby", ipa: "/ˈbeɪbi/", es: "Bebé" }, { emoji: "🧑", en: "Cousin", ipa: "/ˈkʌzən/", es: "Primo o prima" },
      ], hint: "Father y mother comparten /ð/; escucha el sonido inicial que cambia en brother.", analogy: "Las palabras de familia son etiquetas en un árbol: aprenderlas en pares facilita recordarlas.", example: "My sister lives with my mother. (Mi hermana vive con mi madre.)", threshold: 5 },
      { title: "Colors & Descriptions", desc: "Asocia colores con objetos y practica adjetivos básicos.", cards: [
        { emoji: "🔴", en: "Red", ipa: "/red/", es: "Rojo" }, { emoji: "🔵", en: "Blue", ipa: "/bluː/", es: "Azul" }, { emoji: "🟢", en: "Green", ipa: "/ɡriːn/", es: "Verde" }, { emoji: "🟡", en: "Yellow", ipa: "/ˈjeloʊ/", es: "Amarillo" }, { emoji: "🟠", en: "Orange", ipa: "/ˈɔːrɪndʒ/", es: "Naranja" }, { emoji: "🟣", en: "Purple", ipa: "/ˈpɜːrpəl/", es: "Morado" }, { emoji: "⚫", en: "Black", ipa: "/blæk/", es: "Negro" }, { emoji: "⚪", en: "White", ipa: "/waɪt/", es: "Blanco" }, { emoji: "🟤", en: "Brown", ipa: "/braʊn/", es: "Marrón" }, { emoji: "🩷", en: "Pink", ipa: "/pɪŋk/", es: "Rosa" },
      ], hint: "Escucha el inicio de green y la primera sílaba de yellow.", analogy: "El color etiqueta el objeto; en inglés se coloca delante: a blue bag.", example: "The red jacket is new. (La chaqueta roja es nueva.)", threshold: 6 },
    ], listen: [{ title: "Family & Color Listening", desc: "Distingue sonidos cercanos de familia y colores.", exercises: [
      { audio: "Mother", options: ["Mother", "Brother", "Other"], correct: 0 }, { audio: "Yellow", options: ["Yellow", "Hello", "Mellow"], correct: 0 }, { audio: "Sister", options: ["Mister", "Sister", "System"], correct: 1 }, { audio: "Green", options: ["Grin", "Green", "Grain"], correct: 1 }, { audio: "Grandfather", options: ["Grandmother", "Grandfather", "Granddaughter"], correct: 1 },
    ], hint: "En mother y brother, escucha la vocal de la primera sílaba.", analogy: "Compara sonidos como al reconocer voces familiares: busca un detalle distintivo.", example: "My brother likes green. (A mi hermano le gusta el verde.)" }], pron: [], reading: [],
    quiz: [
      { q: "¿Cómo se dice «hermana»?", options: ["Brother", "Mother", "Sister", "Father"], correct: 2, explain: "Sister significa hermana; brother significa hermano." }, { q: "¿Qué color es «blue»?", options: ["Rojo", "Azul", "Verde", "Amarillo"], correct: 1, explain: "Blue se traduce como azul." }, { q: "¿Qué palabra significa «abuelo»?", options: ["Grandfather", "Grandmother", "Father", "Brother"], correct: 0, explain: "Grandfather es abuelo y grandmother es abuela." }, { q: "¿Dónde va el color en «a ___ car»?", options: ["Después de car", "Antes de car", "Al final de la frase", "No acompaña sustantivos"], correct: 1, explain: "Los adjetivos descriptivos suelen ir antes del sustantivo: a red car." },
    ],
  },
  {
    title: "Everyday Vocabulary", level: "principiante", photo: photos.cafe, photoAlt: "Café con comida y bebidas sobre una mesa", goal: "Pedir comida, describir ropa y reconocer lugares habituales con frases útiles.",
    vocab: [
      { title: "Food & Drinks", desc: "Reconoce alimentos y bebidas de una cafetería.", cards: [
        { emoji: "🍎", en: "Apple", ipa: "/ˈæpəl/", es: "Manzana" }, { emoji: "🍞", en: "Bread", ipa: "/bred/", es: "Pan" }, { emoji: "🥛", en: "Milk", ipa: "/mɪlk/", es: "Leche" }, { emoji: "💧", en: "Water", ipa: "/ˈwɔːtər/", es: "Agua" }, { emoji: "☕", en: "Coffee", ipa: "/ˈkɔːfi/", es: "Café" }, { emoji: "🍵", en: "Tea", ipa: "/tiː/", es: "Té" }, { emoji: "🍚", en: "Rice", ipa: "/raɪs/", es: "Arroz" }, { emoji: "🥗", en: "Salad", ipa: "/ˈsæləd/", es: "Ensalada" }, { emoji: "🍗", en: "Chicken", ipa: "/ˈtʃɪkɪn/", es: "Pollo" }, { emoji: "🐟", en: "Fish", ipa: "/fɪʃ/", es: "Pescado" },
      ], hint: "Coffee tiene dos sílabas: escucha el acento al principio y la vocal final /i/.", analogy: "Aprender un menú por grupos, como bebidas y platos, ayuda a pedir con rapidez.", example: "I'd like a coffee and some bread. (Quisiera un café y algo de pan.)", threshold: 6 },
      { title: "Clothes & Places", desc: "Nombra ropa y lugares comunes para describir tu entorno.", cards: [
        { emoji: "👕", en: "Shirt", ipa: "/ʃɜːrt/", es: "Camisa" }, { emoji: "👖", en: "Pants", ipa: "/pænts/", es: "Pantalones" }, { emoji: "👟", en: "Shoes", ipa: "/ʃuːz/", es: "Zapatos" }, { emoji: "🧥", en: "Jacket", ipa: "/ˈdʒækɪt/", es: "Chaqueta" }, { emoji: "🧦", en: "Socks", ipa: "/sɑːks/", es: "Medias" }, { emoji: "🏪", en: "Store", ipa: "/stɔːr/", es: "Tienda" }, { emoji: "🏥", en: "Hospital", ipa: "/ˈhɑːspɪtəl/", es: "Hospital" }, { emoji: "🏦", en: "Bank", ipa: "/bæŋk/", es: "Banco" },
      ], hint: "Pants suele usarse en plural para hablar de esta prenda.", analogy: "Ropa y lugares son un mapa personal de lo que llevas y adónde vas.", example: "The store is near the bank. (La tienda está cerca del banco.)", threshold: 5 },
    ], listen: [{ title: "Everyday Listening", desc: "Distingue vocabulario cotidiano con sonidos parecidos.", exercises: [
      { audio: "Water", options: ["Water", "Waiter", "Walter"], correct: 0 }, { audio: "Coffee", options: ["Copy", "Coffee", "Coffin"], correct: 1 }, { audio: "Shoes", options: ["Choose", "Shoes", "Snooze"], correct: 1 }, { audio: "Apple", options: ["April", "Apple", "Able"], correct: 1 }, { audio: "Chicken", options: ["Kitchen", "Chicken", "Check in"], correct: 1 },
    ], hint: "Chicken y kitchen comparten sonidos; escucha el inicio /tʃ/ y la vocal siguiente.", analogy: "Una vocal breve puede cambiar la palabra, como una pieza pequeña cambia una frase.", example: "Chicken, please. (Pollo, por favor.)" }], pron: [{ title: "At the Restaurant", desc: "Practica pedidos corteses en un restaurante.", phrases: [
      { en: "A table for two, please.", es: "Una mesa para dos, por favor." }, { en: "Can I see the menu, please?", es: "¿Puedo ver el menú, por favor?" }, { en: "I'd like a coffee, please.", es: "Quisiera un café, por favor." }, { en: "Could I have some water?", es: "¿Podría tomar un poco de agua?" },
    ], hint: "Une I'd like y cierra la petición con please en un tono cordial.", analogy: "Please funciona como un tono amable al cerrar una petición.", example: "Could I have some water? (¿Podría tomar un poco de agua?)", threshold: 3 }], reading: [],
    quiz: [
      { q: "¿Cómo se dice «agua»?", options: ["Milk", "Water", "Juice", "Tea"], correct: 1, explain: "Water significa agua." }, { q: "¿Qué significa «shoes»?", options: ["Camisa", "Zapatos", "Gorra", "Medias"], correct: 1, explain: "Shoes es el plural de shoe: zapatos." }, { q: "¿Qué frase pide una bebida con cortesía?", options: ["I'd like a coffee, please.", "I coffee now.", "Coffee you are.", "I am coffee."], correct: 0, explain: "I'd like es una forma educada de pedir algo." }, { q: "¿Qué sonido rima más con el final de «coffee»?", options: ["La vocal /i/ de copy", "La /t/ de water", "La /d/ de bread", "La /ʃ/ de fish"], correct: 0, explain: "Coffee y copy comparten una terminación sonora cercana." },
    ],
  },
  {
    title: "Present Simple", level: "principiante", photo: photos.routine, photoAlt: "Persona organiza su rutina diaria en una agenda", goal: "Describir rutinas y hábitos con presente simple, do y does.",
    vocab: [{ title: "Daily Routines", desc: "Escucha verbos para contar tu día habitual.", cards: [
      { emoji: "🛏️", en: "Wake up", ipa: "/weɪk ʌp/", es: "Despertarse" }, { emoji: "🚿", en: "Take a shower", ipa: "/teɪk ə ˈʃaʊər/", es: "Ducharse" }, { emoji: "🍳", en: "Have breakfast", ipa: "/hæv ˈbrekfəst/", es: "Desayunar" }, { emoji: "🚌", en: "Go to work", ipa: "/ɡoʊ tə wɜːrk/", es: "Ir al trabajo" }, { emoji: "💼", en: "Work", ipa: "/wɜːrk/", es: "Trabajar" }, { emoji: "🍽️", en: "Have lunch", ipa: "/hæv lʌntʃ/", es: "Almorzar" }, { emoji: "📚", en: "Study", ipa: "/ˈstʌdi/", es: "Estudiar" }, { emoji: "😴", en: "Go to bed", ipa: "/ɡoʊ tə bed/", es: "Acostarse" },
    ], hint: "Escucha la terminación -s de works y studies cuando el sujeto es he o she.", analogy: "El presente simple es una foto de una rutina que se repite.", example: "She studies after work. (Ella estudia después del trabajo.)", threshold: 5 }], listen: [{ title: "Daily Routine Listening", desc: "Reconoce acciones habituales y preguntas sobre rutinas.", exercises: [
      { audio: "I wake up early.", options: ["I wake up early.", "I walk up early.", "I wake up lately."], correct: 0 }, { audio: "She goes to work by bus.", options: ["She goes to work by bus.", "She goes to work by car.", "She gets to work by bus."], correct: 0 }, { audio: "He doesn't like coffee.", options: ["He doesn't like coffee.", "He likes coffee.", "He doesn't drink coffee."], correct: 0 }, { audio: "Do you study every day?", options: ["Do you study every day?", "Do you play every day?", "Did you study every day?"], correct: 0 }, { audio: "They have lunch at noon.", options: ["They have lunch at noon.", "They have lunch at night.", "They had lunch at noon."], correct: 0 },
    ], hint: "Do suele abrir preguntas; doesn't marca una negativa para he, she o it.", analogy: "Una señal gramatical como do o -s ayuda a reconstruir la frase escuchada.", example: "Does he work on Fridays? (¿Él trabaja los viernes?)" }], reading: [{ title: "Present Simple: Habits", desc: "Construye afirmaciones, negativas y preguntas sobre hábitos.", explanation: "El presente simple describe hábitos, rutinas y hechos generales. En afirmativa, he, she e it suelen llevar -s en el verbo.", pattern: "I work. She works.\nI don't work. Does she work?", points: ["Usa verbo base con I, you, we y they.", "Añade -s en afirmativas con he, she e it.", "Do y does llevan la marca de pregunta o negación."], note: "Error frecuente: decir Does she works?; con does, el verbo principal vuelve a su forma base.", tip: "Practica un par: She works. Does she work?", hint: "Escucha quién realiza la acción y decide si el verbo necesita -s.", analogy: "El presente simple es como el calendario habitual de una persona.", example: "She works every weekday. (Ella trabaja todos los días laborables.)" }], pron: [],
    quiz: [
      { q: "¿Qué significa «She works at a hotel»?", options: ["Ella trabaja en un hotel", "Ella trabajó en un hotel", "¿Ella trabaja en un hotel?", "Ella está trabajando en casa"], correct: 0, explain: "Works describe una rutina o hecho y lleva -s con she." }, { q: "¿Cómo se dice «¿Estudias cada día?»?", options: ["Do you study every day?", "Does you study every day?", "Are you study every day?", "Did you studies every day?"], correct: 0, explain: "Con you se usa Do + sujeto + verbo base." }, { q: "¿Qué error hay en «Does he likes tea?»?", options: ["El verbo debe ir en forma base: Does he like tea?", "Falta el pasado liked", "Does solo se usa con I", "Likes debe convertirse en liking"], correct: 0, explain: "Does ya marca tercera persona; no se agrega -s al verbo principal." }, { q: "¿Qué auxiliar forma la negativa de «I work»?", options: ["don't", "doesn't", "isn't", "wasn't"], correct: 0, explain: "Con I, you, we y they se usa do not o don't." },
    ],
  },
  {
    title: "Past & Future", level: "principiante", photo: photos.journey, photoAlt: "Viaje por carretera hacia un paisaje montañoso", goal: "Contar acciones terminadas y expresar planes o predicciones futuras.", vocab: [], listen: [{ title: "Past or Future?", desc: "Distingue acciones pasadas y planes futuros al escuchar.", exercises: [
      { audio: "I went to the cinema yesterday.", options: ["I went to the cinema yesterday.", "I go to the cinema today.", "I will go to the cinema tomorrow."], correct: 0 }, { audio: "She is going to study tonight.", options: ["She studied last night.", "She is going to study tonight.", "She studies every night."], correct: 1 }, { audio: "They didn't eat breakfast.", options: ["They didn't eat breakfast.", "They don't eat breakfast.", "They won't eat breakfast."], correct: 0 }, { audio: "We will see you tomorrow.", options: ["We saw you yesterday.", "We see you today.", "We will see you tomorrow."], correct: 2 }, { audio: "He made a cake last weekend.", options: ["He makes cakes every week.", "He made a cake last weekend.", "He will make a cake."], correct: 1 },
    ], hint: "Yesterday y last sitúan el relato atrás; tomorrow señala una referencia futura.", analogy: "Las palabras de tiempo son señales en una línea que ubican la acción.", example: "We will travel tomorrow. (Viajaremos mañana.)" }], pron: [{ title: "Tell a Short Story", desc: "Repite un relato breve que conecta pasado y futuro.", phrases: [
      { en: "Yesterday I went to a coffee shop.", es: "Ayer fui a una cafetería." }, { en: "I had a lovely time with my friends.", es: "Lo pasé muy bien con mis amistades." }, { en: "Tomorrow I'm going to study English.", es: "Mañana voy a estudiar inglés." }, { en: "I will call you when I get home.", es: "Te llamaré cuando llegue a casa." },
    ], hint: "Marca yesterday y tomorrow; luego escucha cómo cambia went frente a will call.", analogy: "Contar una historia es tender un puente entre lo que pasó y lo que planeas hacer.", example: "Yesterday I went out. (Ayer salí.)", threshold: 3 }], reading: [
      { title: "Past Simple: Finished Events", desc: "Habla de acciones terminadas en un momento pasado.", explanation: "Usa past simple con acciones que terminaron. Los verbos regulares suelen añadir -ed; los irregulares cambian de forma.", pattern: "I worked yesterday.\nShe went home.\nDid you work? I didn't work.", points: ["Los regulares suelen añadir -ed.", "Los irregulares tienen formas como go → went.", "Con did o didn't, el verbo principal va en forma base."], note: "Error frecuente: Did you went? Después de did se dice Did you go?", tip: "Aprende verbos irregulares dentro de frases y con audio.", hint: "Busca did o la forma irregular para ubicar la acción pasada.", analogy: "El pasado simple es una caja cerrada: la acción ya terminó.", example: "I called my sister yesterday. (Llamé a mi hermana ayer.)" },
      { title: "Plans and Predictions", desc: "Elige going to para planes y will para predicciones o decisiones.", explanation: "Going to suele expresar una intención previa; will se usa para predicciones, promesas o decisiones tomadas al hablar.", pattern: "I'm going to visit my aunt.\nI think it will rain.", points: ["Going to presenta un plan o intención.", "Will expresa predicción, promesa o decisión espontánea.", "Ambas formas van seguidas de verbo base."], note: "No conjugues el segundo verbo: se dice She will travel, no She will travels.", tip: "Pregunta si el plan existía antes de hablar para elegir la forma.", hint: "Escucha el contexto: plan ya decidido o respuesta espontánea.", analogy: "Going to es una cita anotada; will puede ser una decisión del momento.", example: "I'll help you with your bag. (Te ayudaré con tu bolso.)" },
    ], quiz: [
      { q: "¿Qué significa «I went home yesterday»?", options: ["Fui a casa ayer", "Voy a casa cada día", "Iré a casa mañana", "Estoy yendo a casa"], correct: 0, explain: "Went es el pasado irregular de go y yesterday marca pasado." }, { q: "¿Cómo se dice «No comí»?", options: ["I didn't eat", "I don't ate", "I not ate", "I wasn't eat"], correct: 0, explain: "En negativa del pasado se usa didn't + verbo base." }, { q: "¿Cuál frase expresa un plan decidido?", options: ["I'm going to visit my aunt.", "I visited my aunt yesterday.", "I visit my aunt every week.", "I am visit my aunt."], correct: 0, explain: "Going to expresa una intención o plan previo." }, { q: "¿Qué error hay en «Did she called?»?", options: ["Después de did va call, sin -ed", "Falta will", "Did solo se usa en negativas", "Called debe ser calling"], correct: 0, explain: "El auxiliar did ya expresa pasado; el verbo principal vuelve a base." }, { q: "¿Qué significa «I will help you»?", options: ["Te ayudaré", "Te ayudé", "Te ayudo cada día", "No te ayudaré"], correct: 0, explain: "Will seguido del verbo base expresa futuro." },
    ],
  },
  {
    title: "Real Conversations", level: "intermedio", photo: photos.conversation, photoAlt: "Colegas conversan alrededor de una mesa", goal: "Sostener small talk y comprender contracciones comunes en conversaciones cotidianas.", vocab: [], reading: [], pron: [{ title: "Small Talk Exchange", desc: "Ensaya turnos breves para iniciar y mantener una conversación casual.", phrases: [
      { en: "Hi, how are you doing today?", es: "Hola, ¿cómo estás hoy?" }, { en: "I'm doing well, thanks. How about you?", es: "Estoy bien, gracias. ¿Y tú?" }, { en: "What have you been up to lately?", es: "¿Qué has estado haciendo últimamente?" }, { en: "I've been learning English after work.", es: "He estado aprendiendo inglés después del trabajo." }, { en: "That sounds interesting. How is it going?", es: "Suena interesante. ¿Cómo va?" }, { en: "Pretty well. I practice a little every day.", es: "Bastante bien. Practico un poco cada día." },
    ], hint: "Une I'm e I've con la palabra siguiente; evita separar las contracciones en sílabas rígidas.", analogy: "Small talk es como pasarse una pelota: cada respuesta devuelve una idea y una pregunta.", example: "How about you? (¿Y tú?)", threshold: 4 }], listen: [{ title: "Conversation Details", desc: "Identifica ideas y contracciones dentro de un diálogo breve.", exercises: [
      { audio: "How are you doing today?", options: ["How are you doing today?", "How old are you today?", "Who are you today?"], correct: 0 }, { audio: "I've been learning English.", options: ["I've been learning English.", "I've been teaching English.", "I began learning English."], correct: 0 }, { audio: "I practice every day.", options: ["I practice every day.", "I play every day.", "I prayed every day."], correct: 0 }, { audio: "That sounds interesting.", options: ["That sounds interesting.", "That sounds amazing.", "That sounds difficult."], correct: 0 }, { audio: "It's going pretty well.", options: ["It's going pretty well.", "It's going away.", "It went very well."], correct: 0 },
    ], hint: "En I've, escucha el sonido /v/ unido a been y detecta el verbo siguiente.", analogy: "Reconocer una contracción es entender la frase como bloque, no traducir sílaba por sílaba.", example: "I've been learning. (He estado aprendiendo.)" }],
    quiz: [
      { q: "¿Qué significa «What have you been up to lately?»?", options: ["¿Qué has estado haciendo últimamente?", "¿A dónde vas ahora?", "¿Qué edad tienes?", "¿Qué hiciste ayer a las ocho?"], correct: 0, explain: "Es una pregunta informal sobre actividades recientes." }, { q: "¿Cómo responderías naturalmente a «How are you doing?»?", options: ["I'm doing well, thanks. How about you?", "A table for two.", "I went tomorrow.", "The blue one is taller."], correct: 0, explain: "La respuesta devuelve el saludo y mantiene la conversación." }, { q: "¿Qué contracción representa I am?", options: ["I'm", "I'am", "Im'", "I amn't"], correct: 0, explain: "I'm combina I y am en una forma común e informal." }, { q: "¿Por qué conviene practicar contracciones con audio?", options: ["Aparecen a menudo y enlazan palabras en el habla natural", "Reemplazan todos los verbos", "Siempre son más formales", "Evitan escuchar el contexto"], correct: 0, explain: "Reconocer contracciones mejora la comprensión del habla cotidiana." },
    ],
  },
  {
    title: "Travel & Directions", level: "intermedio", photo: photos.travel, photoAlt: "Avión de pasajeros preparado para un viaje", goal: "Pedir ayuda, orientarte y resolver intercambios sencillos durante un viaje.",
    vocab: [
      { title: "Airport & Hotel", desc: "Reconoce términos prácticos de aeropuerto y alojamiento.", cards: [
        { emoji: "✈️", en: "Airport", ipa: "/ˈerpɔːrt/", es: "Aeropuerto" }, { emoji: "🎫", en: "Boarding pass", ipa: "/ˈbɔːrdɪŋ pæs/", es: "Pase de abordar" }, { emoji: "🧳", en: "Luggage", ipa: "/ˈlʌɡɪdʒ/", es: "Equipaje" }, { emoji: "🛂", en: "Passport", ipa: "/ˈpæspɔːrt/", es: "Pasaporte" }, { emoji: "🏨", en: "Hotel", ipa: "/hoʊˈtel/", es: "Hotel" }, { emoji: "🛎️", en: "Reservation", ipa: "/ˌrezərˈveɪʃən/", es: "Reserva" }, { emoji: "🚪", en: "Room key", ipa: "/ruːm kiː/", es: "Llave de habitación" }, { emoji: "🧾", en: "Check-in", ipa: "/ˈtʃek ɪn/", es: "Registro de entrada" },
      ], hint: "Boarding empieza con /bɔːr/; escucha la palabra completa boarding pass.", analogy: "El vocabulario de viaje es un mapa de documentos, equipaje y alojamiento.", example: "Where is the check-in desk? (¿Dónde está el mostrador de registro?)", threshold: 5 },
      { title: "Directions & Transport", desc: "Sigue indicaciones y reconoce medios de transporte.", cards: [
        { emoji: "⬅️", en: "Turn left", ipa: "/tɜːrn left/", es: "Gira a la izquierda" }, { emoji: "➡️", en: "Turn right", ipa: "/tɜːrn raɪt/", es: "Gira a la derecha" }, { emoji: "⬆️", en: "Go straight", ipa: "/ɡoʊ streɪt/", es: "Sigue derecho" }, { emoji: "🚇", en: "Subway", ipa: "/ˈsʌbweɪ/", es: "Metro" }, { emoji: "🚕", en: "Taxi", ipa: "/ˈtæksi/", es: "Taxi" }, { emoji: "🚌", en: "Bus stop", ipa: "/ˈbʌs stɑːp/", es: "Parada de autobús" }, { emoji: "📍", en: "Next to", ipa: "/nekst tuː/", es: "Al lado de" }, { emoji: "🛣️", en: "Across from", ipa: "/əˈkrɔːs frəm/", es: "Enfrente de" },
      ], hint: "Left y right acaban con consonantes distintas; acompaña el sonido con un gesto de orientación.", analogy: "Las indicaciones forman un mapa hablado: primero escucha el movimiento y luego la dirección.", example: "The station is across from the hotel. (La estación está enfrente del hotel.)", threshold: 5 },
    ], listen: [{ title: "Travel Listening", desc: "Comprende instrucciones cortas en aeropuerto y ciudad.", exercises: [
      { audio: "Where is the airport?", options: ["Where is the airport?", "Where is the hotel?", "When is the airport?"], correct: 0 }, { audio: "Turn left at the station.", options: ["Turn right at the station.", "Turn left at the station.", "Go straight past the station."], correct: 1 }, { audio: "I have one suitcase.", options: ["I have one suitcase.", "I have one ticket.", "I have two suitcases."], correct: 0 }, { audio: "The hotel is next to the bank.", options: ["The hotel is next to the bank.", "The hotel is behind the bank.", "The hotel is across from the bank."], correct: 0 }, { audio: "Could you call a taxi, please?", options: ["Could you call a taxi, please?", "Could you find a bus, please?", "Could you call a doctor, please?"], correct: 0 },
    ], hint: "Si confundes left y right, escucha la consonante final y repite la frase despacio.", analogy: "En un viaje, captar una palabra clave puede ser como reconocer el nombre de tu parada.", example: "Go straight for two blocks. (Sigue derecho por dos cuadras.)" }], pron: [{ title: "At the Airport", desc: "Ensaya preguntas útiles para pedir orientación al viajar.", phrases: [
      { en: "Where can I check in for my flight?", es: "¿Dónde puedo registrarme para mi vuelo?" }, { en: "Could you help me find gate twelve?", es: "¿Podría ayudarme a encontrar la puerta doce?" }, { en: "I have one suitcase to check.", es: "Tengo una maleta para documentar." }, { en: "How long does the journey take?", es: "¿Cuánto tarda el viaje?" },
    ], hint: "En Could you, enlaza la d suavemente con you.", analogy: "Una pregunta amable es una llave: abre el intercambio sin exigir una respuesta.", example: "Could you help me? (¿Podría ayudarme?)", threshold: 3 }], reading: [],
    quiz: [
      { q: "¿Qué significa «boarding pass»?", options: ["Pase de abordar", "Llave de hotel", "Maleta grande", "Parada de autobús"], correct: 0, explain: "Boarding pass es el documento necesario para abordar el vuelo." }, { q: "¿Cómo pedirías ayuda de forma cortés?", options: ["Could you help me, please?", "You help me now.", "Where help?", "I helping you."], correct: 0, explain: "Could you…? expresa una petición educada." }, { q: "¿Qué frase indica girar a la derecha?", options: ["Turn right", "Turn left", "Go straight", "Across from"], correct: 0, explain: "Right significa derecha." }, { q: "¿Qué suele venir después de «Where is…»?", options: ["El lugar que quieres encontrar", "Un verbo en pasado obligatoriamente", "Una respuesta sin sustantivo", "Un adjetivo superlativo"], correct: 0, explain: "Where is the station? pregunta por la ubicación de un sitio." },
    ],
  },
  {
    title: "Work & Professions", level: "intermedio", photo: photos.work, photoAlt: "Espacio de trabajo moderno con mesa de reuniones", goal: "Describir empleos y participar en intercambios básicos de oficina y entrevistas.",
    vocab: [
      { title: "Jobs & Skills", desc: "Nombra profesiones y capacidades del trabajo.", cards: [
        { emoji: "👩‍⚕️", en: "Nurse", ipa: "/nɜːrs/", es: "Enfermera o enfermero" }, { emoji: "👨‍🏫", en: "Teacher", ipa: "/ˈtiːtʃər/", es: "Docente" }, { emoji: "💻", en: "Designer", ipa: "/dɪˈzaɪnər/", es: "Diseñador o diseñadora" }, { emoji: "📊", en: "Accountant", ipa: "/əˈkaʊntənt/", es: "Contador o contadora" }, { emoji: "🧑‍🍳", en: "Chef", ipa: "/ʃef/", es: "Chef" }, { emoji: "🛠️", en: "Engineer", ipa: "/ˌendʒɪˈnɪr/", es: "Ingeniero o ingeniera" }, { emoji: "🤝", en: "Teamwork", ipa: "/ˈtiːmwɜːrk/", es: "Trabajo en equipo" }, { emoji: "🧩", en: "Problem-solving", ipa: "/ˈprɑːbləm ˌsɑːlvɪŋ/", es: "Resolución de problemas" },
      ], hint: "En accountant, escucha el acento en -count.", analogy: "Una profesión etiqueta el trabajo; una habilidad explica cómo lo realizas.", example: "She is an engineer with strong teamwork skills. (Es ingeniera y tiene buenas habilidades de equipo.)", threshold: 5 },
      { title: "Office & Interviews", desc: "Practica palabras para reuniones, correo y entrevistas.", cards: [
        { emoji: "📅", en: "Meeting", ipa: "/ˈmiːtɪŋ/", es: "Reunión" }, { emoji: "✉️", en: "Email", ipa: "/ˈiːmeɪl/", es: "Correo electrónico" }, { emoji: "📄", en: "Resume", ipa: "/ˈrezəmeɪ/", es: "Currículum" }, { emoji: "🎤", en: "Interview", ipa: "/ˈɪntərvjuː/", es: "Entrevista" }, { emoji: "📌", en: "Deadline", ipa: "/ˈdedlaɪn/", es: "Fecha límite" }, { emoji: "🗂️", en: "Project", ipa: "/ˈprɑːdʒekt/", es: "Proyecto" }, { emoji: "🪪", en: "Experience", ipa: "/ɪkˈspɪriəns/", es: "Experiencia" }, { emoji: "🗣️", en: "Colleague", ipa: "/ˈkɑːliːɡ/", es: "Colega" },
      ], hint: "Interview tiene acento inicial; escucha el ritmo antes de repetir la palabra completa.", analogy: "El vocabulario de oficina es una caja de herramientas: cada palabra sirve en una situación distinta.", example: "I have an interview on Monday. (Tengo una entrevista el lunes.)", threshold: 5 },
    ], listen: [{ title: "Workplace Listening", desc: "Reconoce profesiones y detalles de una entrevista.", exercises: [
      { audio: "My sister is an engineer.", options: ["My sister is an engineer.", "My sister is a teacher.", "My sister is an editor."], correct: 0 }, { audio: "The meeting starts at nine.", options: ["The meeting starts at five.", "The meeting starts at nine.", "The interview starts at nine."], correct: 1 }, { audio: "Please send me your resume.", options: ["Please send me your resume.", "Please show me your result.", "Please send me your email."], correct: 0 }, { audio: "We work well as a team.", options: ["We work well as a team.", "We work late every week.", "We walk to the team."], correct: 0 }, { audio: "The deadline is next Friday.", options: ["The deadline is this Friday.", "The deadline is next Friday.", "The meeting is next Friday."], correct: 1 },
    ], hint: "Reconoce deadline o meeting primero y después escucha el detalle temporal.", analogy: "En una reunión, una palabra clave ayuda a reconstruir el mensaje entero.", example: "Could you send the report today? (¿Podrías enviar el informe hoy?)" }], pron: [], reading: [],
    quiz: [
      { q: "¿Qué significa «deadline»?", options: ["Fecha límite", "Entrevista", "Colega", "Habilidad"], correct: 0, explain: "Deadline es la fecha o plazo límite para una tarea." }, { q: "¿Cómo dirías «Soy diseñadora»?", options: ["I am a designer.", "I designer am.", "I do designer.", "I am design."], correct: 0, explain: "Usa be + a/an + profesión: I am a designer." }, { q: "¿Qué frase pide el currículum?", options: ["Please send me your resume.", "Please send me your deadline.", "Please interview my email.", "Please colleague my resume."], correct: 0, explain: "Resume es el documento que resume la experiencia profesional." }, { q: "¿Dónde está el acento en «teacher»?", options: ["En la primera sílaba", "Solo al final", "No tiene acento", "En la tercera sílaba"], correct: 0, explain: "Teacher lleva el acento principal al inicio: /ˈtiːtʃər/." },
    ],
  },
  {
    title: "Present Continuous", level: "intermedio", photo: photos.city, photoAlt: "Personas caminando por una calle de la ciudad", goal: "Describir acciones en progreso y distinguirlas de hábitos con presente simple.", vocab: [], pron: [], reading: [
      { title: "Actions Happening Now", desc: "Forma presente continuo con be y verbo terminado en -ing.", explanation: "Usa present continuous para acciones que ocurren ahora o alrededor del momento actual: sujeto + am/is/are + verbo-ing.", pattern: "I am working now.\nShe is reading a message.\nThey are waiting outside.", points: ["Usa am con I, is con he/she/it y are con you/we/they.", "El verbo principal añade -ing.", "Now y at the moment suelen señalar una acción en progreso."], note: "Error frecuente: omitir be y decir I working; la forma necesita I am working.", tip: "Escucha primero el auxiliar be y después identifica el verbo con -ing.", hint: "Comprueba quién es el sujeto antes de elegir am, is o are.", analogy: "El presente continuo es como una transmisión en vivo: la acción sucede ahora.", example: "I am studying now. (Estoy estudiando ahora.)" },
      { title: "Habits or Actions Now?", desc: "Contrasta rutinas permanentes con acciones temporales en progreso.", explanation: "Present simple describe hábitos; present continuous describe lo que sucede ahora o temporalmente. La diferencia cambia el significado del mismo verbo.", pattern: "I work every weekday.\nI'm working from home this week.", points: ["Every day suele acompañar rutinas en presente simple.", "Now y this week pueden marcar una acción actual o temporal.", "Algunos verbos de estado normalmente no se usan en continuo en este nivel."], note: "No confundas una rutina (She works) con una actividad actual (She is working).", tip: "Busca expresiones de frecuencia o de tiempo actual antes de escoger el tiempo verbal.", hint: "Decide si la frase describe algo habitual o algo que está ocurriendo en este periodo.", analogy: "El presente simple es un calendario; el continuo es una foto del momento.", example: "She's working from home this week. (Está trabajando desde casa esta semana.)" },
    ], listen: [{ title: "Now or Usually?", desc: "Distingue hábitos de acciones que ocurren en este momento.", exercises: [
      { audio: "She is talking on the phone.", options: ["She is talking on the phone.", "She talks on the phone.", "She is walking on the phone."], correct: 0 }, { audio: "I usually take the train.", options: ["I usually take the train.", "I'm taking the train now.", "I used to take the train."], correct: 0 }, { audio: "They are waiting outside.", options: ["They were waiting outside.", "They are waiting outside.", "They wait outside every day."], correct: 1 }, { audio: "He works every Saturday.", options: ["He is working right now.", "He worked last Saturday.", "He works every Saturday."], correct: 2 }, { audio: "We are having lunch at the moment.", options: ["We have lunch at noon.", "We are having lunch at the moment.", "We had lunch a moment ago."], correct: 1 },
    ], hint: "Usually y every Saturday indican hábito; at the moment apunta a una acción en curso.", analogy: "Be + -ing es una señal visual de una cámara encendida durante la acción.", example: "They're waiting right now. (Están esperando ahora mismo.)" }],
    quiz: [
      { q: "¿Qué expresa «They are waiting outside»?", options: ["Están esperando afuera ahora", "Esperan afuera todos los días", "Esperaron afuera ayer", "Esperarán afuera mañana"], correct: 0, explain: "Are waiting combina be con -ing para una acción actual." }, { q: "¿Cómo se dice «Ella está leyendo»?", options: ["She is reading.", "She reading.", "She does reading.", "She read now."], correct: 0, explain: "Con she se usa is + verbo-ing." }, { q: "¿Qué error aparece en «I working now»?", options: ["Falta el auxiliar am", "Sobra now", "Working debe ir en pasado", "I solo usa does"], correct: 0, explain: "Present continuous necesita am/is/are antes del verbo con -ing." }, { q: "¿Qué tiempo escogerías con «every morning» para una rutina?", options: ["Present simple", "Present continuous obligatoriamente", "Past continuous", "Present perfect"], correct: 0, explain: "Every morning señala una acción habitual." },
    ],
  },
  {
    title: "Comparatives & Superlatives", level: "intermedio", photo: photos.compare, photoAlt: "Dos paisajes diferentes para comparar", goal: "Comparar personas y lugares usando comparativos y superlativos frecuentes.",
    vocab: [{ title: "Comparing Things", desc: "Escucha adjetivos y expresiones de comparación.", cards: [
      { emoji: "📏", en: "Taller", ipa: "/ˈtɔːlər/", es: "Más alto" }, { emoji: "⚡", en: "Faster", ipa: "/ˈfæstər/", es: "Más rápido" }, { emoji: "💰", en: "More expensive", ipa: "/mɔːr ɪkˈspensɪv/", es: "Más caro" }, { emoji: "🌱", en: "Cheaper", ipa: "/ˈtʃiːpər/", es: "Más barato" }, { emoji: "🏆", en: "The best", ipa: "/ðə best/", es: "El mejor" }, { emoji: "🌟", en: "The most interesting", ipa: "/ðə moʊst ˈɪntrəstɪŋ/", es: "El más interesante" }, { emoji: "🧊", en: "Colder", ipa: "/ˈkoʊldər/", es: "Más frío" }, { emoji: "🧭", en: "The nearest", ipa: "/ðə ˈnɪrɪst/", es: "El más cercano" },
    ], hint: "Escucha the antes del superlativo y compara el sonido -er con more.", analogy: "Comparative enfrenta dos opciones; superlative elige una dentro del grupo.", example: "This route is shorter. (Esta ruta es más corta.)", threshold: 5 }], listen: [{ title: "Comparison Listening", desc: "Distingue comparaciones y superlativos en frases cortas.", exercises: [
      { audio: "This bag is lighter than mine.", options: ["This bag is lighter than mine.", "This bag is larger than mine.", "This bag is the lightest of all."], correct: 0 }, { audio: "The blue car is faster.", options: ["The blue car is faster.", "The blue car is farther.", "The blue car is the fastest."], correct: 0 }, { audio: "This is the most comfortable chair.", options: ["This is a comfortable chair.", "This is the most comfortable chair.", "This chair is more colorful."], correct: 1 }, { audio: "The train is cheaper than a taxi.", options: ["The train is cheaper than a taxi.", "The train is slower than a taxi.", "The train is the cheapest taxi."], correct: 0 }, { audio: "That was the best meal.", options: ["That was the best meal.", "That was a better deal.", "That was the biggest meal."], correct: 0 },
    ], hint: "Than suele introducir el segundo elemento de una comparación.", analogy: "Than es el puente verbal que conecta las dos opciones comparadas.", example: "This hotel is cheaper than that one. (Este hotel es más barato que aquel.)" }], reading: [{ title: "Comparatives and Superlatives", desc: "Compara dos elementos o destaca uno dentro de un conjunto.", explanation: "Los comparativos contrastan dos elementos. Los superlativos señalan el grado máximo dentro de un grupo.", pattern: "small → smaller → the smallest\ninteresting → more interesting → the most interesting", points: ["Adjetivos cortos suelen añadir -er y -est.", "Adjetivos largos suelen usar more y the most.", "Good y bad tienen formas irregulares: better/best y worse/worst."], note: "No combines more con una terminación -er; evita decir more faster.", tip: "Menciona el grupo de referencia al usar un superlativo.", hint: "Observa si comparas dos elementos o eliges uno entre varios.", analogy: "El comparativo es una carrera entre dos; el superlativo sube al podio del grupo.", example: "This room is quieter than the lobby. (Esta habitación es más silenciosa que el vestíbulo.)" }], pron: [],
    quiz: [
      { q: "¿Qué significa «This route is shorter than mine»?", options: ["Esta ruta es más corta que la mía", "Esta ruta es la más larga", "Mi ruta es nueva", "Esta ruta es tan corta como la mía"], correct: 0, explain: "Shorter than compara dos rutas: esta tiene menor longitud." }, { q: "¿Cómo se dice «el más interesante»?", options: ["The most interesting", "The interestinger", "More interestingest", "The more interesting"], correct: 0, explain: "Con este adjetivo largo se utiliza the most." }, { q: "¿Qué error hay en «more faster»?", options: ["Se mezclan dos formas comparativas; basta faster", "Falta el artículo the", "Than siempre va antes del adjetivo", "Fast no admite comparación"], correct: 0, explain: "No combines more con -er en el mismo comparativo." }, { q: "¿Qué forma es el superlativo irregular de good?", options: ["The best", "The goodest", "More good", "The better"], correct: 0, explain: "Good cambia a better en comparativo y best en superlativo." },
    ],
  },
  {
    title: "Present Perfect", level: "avanzado", photo: photos.journal, photoAlt: "Persona escribe experiencias en una libreta", goal: "Hablar de experiencias y acciones recientes conectadas con el presente.", vocab: [], pron: [], reading: [
      { title: "Experiences with Present Perfect", desc: "Forma have/has más participio para experiencias sin fecha concreta.", explanation: "El present perfect conecta una experiencia pasada con el presente. Su forma es have/has + participio, especialmente al hablar de lo que alguien ha vivido.", pattern: "I have visited Cusco.\nShe has tried ceviche.\nHave you ever traveled alone?", points: ["Usa have con I/you/we/they y has con he/she/it.", "El participio puede ser regular o irregular.", "Ever pregunta por experiencias en cualquier momento."], note: "Si mencionas un momento terminado concreto como yesterday, normalmente se usa past simple.", tip: "Pregunta si importa la fecha exacta o la experiencia hasta ahora.", hint: "Escucha have/has y el participio; nota si la fecha está especificada.", analogy: "El present perfect es un puente: el hecho ocurrió antes, pero importa ahora.", example: "Have you ever visited Arequipa? (¿Has visitado Arequipa alguna vez?)" },
      { title: "Just, Already, Yet and Never", desc: "Ubica adverbios frecuentes para hablar de acciones recientes o pendientes.", explanation: "Just indica algo recién ocurrido; already, algo que ya ocurrió; yet pregunta o niega si pasó hasta ahora; never comunica que no ha ocurrido en ninguna ocasión.", pattern: "I've just arrived.\nShe's already eaten.\nHave you called yet?\nWe've never flown abroad.", points: ["Just y already suelen aparecer entre have/has y el participio.", "Yet suele aparecer al final de preguntas y negativas.", "Never comunica ausencia de experiencia."], note: "Evita usar yet en una afirmación con el orden de una pregunta: su función y posición dependen de la frase.", tip: "Escucha el auxiliar primero y el adverbio después para interpretar el momento.", hint: "Identifica si la frase afirma algo reciente, algo ya ocurrido o algo pendiente.", analogy: "Estos adverbios son marcadores en una línea de tiempo que llega hasta ahora.", example: "I've just arrived. (Acabo de llegar.)" },
    ], listen: [{ title: "Life Experiences Listening", desc: "Reconoce experiencias y acciones recientes.", exercises: [
      { audio: "I've visited Mexico twice.", options: ["I've visited Mexico twice.", "I visited Mexico last week.", "I've missed Mexico twice."], correct: 0 }, { audio: "She has never tried sushi.", options: ["She has never tried sushi.", "She has tried sushi before.", "She is trying sushi now."], correct: 0 }, { audio: "Have you finished your report yet?", options: ["Have you finished your report yet?", "Did you finish your report yesterday?", "Have you started your report yet?"], correct: 0 }, { audio: "We have just arrived.", options: ["We have just arrived.", "We have already left.", "We are just arriving."], correct: 0 }, { audio: "They've already booked the hotel.", options: ["They've already booked the hotel.", "They haven't booked the hotel yet.", "They booked another hotel."], correct: 0 },
    ], hint: "Escucha have/has y el participio para reconocer la conexión con el presente.", analogy: "El auxiliar conecta una experiencia anterior con lo que importa ahora.", example: "We've already booked the room. (Ya reservamos la habitación.)" }],
    quiz: [
      { q: "¿Qué significa «She has never tried sushi»?", options: ["Nunca ha probado sushi", "Lo probó ayer", "Está probando sushi ahora", "Lo probará mañana"], correct: 0, explain: "Has never + participio describe ausencia de esa experiencia hasta ahora." }, { q: "¿Cómo preguntas «¿Has terminado ya?»?", options: ["Have you finished yet?", "Did you finished already?", "Are you finish yet?", "Have you finish yesterday?"], correct: 0, explain: "Present perfect se forma con have + participio; yet puede cerrar la pregunta." }, { q: "¿Qué error hay en «He have seen it»?", options: ["Con he se usa has", "Seen debe ser seeing", "Present perfect no usa auxiliar", "Falta did"], correct: 0, explain: "He, she e it usan has." }, { q: "¿Qué tiempo suele usarse con «yesterday» y una acción terminada?", options: ["Past simple", "Present perfect", "Present continuous", "Second conditional"], correct: 0, explain: "Yesterday indica un momento pasado y terminado." },
    ],
  },
  {
    title: "Conditionals", level: "avanzado", photo: photos.ideas, photoAlt: "Equipo conversa mientras organiza ideas en una mesa", goal: "Expresar verdades generales, consecuencias probables e hipótesis con condicionales.", vocab: [], pron: [], reading: [
      { title: "Zero and First Conditional", desc: "Distingue reglas generales de resultados futuros probables.", explanation: "Zero conditional expresa resultados habituales o hechos generales. First conditional presenta una condición posible y su consecuencia futura.", pattern: "If you heat ice, it melts.\nIf it rains tomorrow, we'll stay home.", points: ["Zero: if + present, present.", "First: if + present, will + verbo base.", "La cláusula con if puede aparecer al inicio o al final."], note: "En la cláusula con if del first conditional se suele usar presente, no will.", tip: "Decide si describes una regla general o una posibilidad futura concreta.", hint: "Escucha si la consecuencia ocurre siempre o solo podría suceder en el futuro.", analogy: "Zero conditional es una regla de manual; first conditional, un plan según lo que pase.", example: "If the train is late, I'll call you. (Si el tren se retrasa, te llamaré.)" },
      { title: "Second Conditional", desc: "Imagina situaciones hipotéticas y plantea sus posibles resultados.", explanation: "Second conditional habla de situaciones imaginarias o poco probables. Usa if + past simple y would + verbo base.", pattern: "If I had more time, I would learn another language.\nIf she lived nearby, she'd visit us.", points: ["La condición lleva past simple.", "La consecuencia usa would + verbo base.", "Were puede usarse en hipótesis formales con distintas personas."], note: "No uses would dentro de la cláusula con if en el patrón básico.", tip: "Escucha la secuencia if + pasado y luego would para reconocer la hipótesis.", hint: "Pregúntate si la situación es real/probable o imaginaria/poco probable.", analogy: "Second conditional dibuja una posibilidad alternativa, como imaginar otro camino.", example: "If I lived near the sea, I'd swim every day. (Si viviera cerca del mar, nadaría cada día.)" },
    ], listen: [{ title: "If and Consequences", desc: "Distingue reglas, planes probables e hipótesis.", exercises: [
      { audio: "If you heat ice, it melts.", options: ["If you heat ice, it melts.", "If you heat rice, it melts.", "If you heated ice, it would melt."], correct: 0 }, { audio: "If it rains, we'll stay home.", options: ["If it rains, we'll stay home.", "If it rained, we'd stay home.", "If it rains, we stay home every day."], correct: 0 }, { audio: "If I had more time, I'd travel.", options: ["If I had more time, I'd travel.", "If I have more time, I travel.", "If I had more time, I'll travel."], correct: 0 }, { audio: "If she calls, I'll tell her.", options: ["If she calls, I'll tell her.", "If she called, I'd tell her.", "If she calls, I told her."], correct: 0 }, { audio: "If we lived closer, we'd walk.", options: ["If we lived closer, we'd walk.", "If we live closer, we walk.", "If we lived closer, we'll walk."], correct: 0 },
    ], hint: "Distingue will de would: el primero suele apuntar a una posibilidad real; el segundo, a una hipótesis.", analogy: "Las condicionales son bifurcaciones: una condición abre un resultado posible.", example: "If I have time, I'll join you. (Si tengo tiempo, me uniré a ti.)" }],
    quiz: [
      { q: "¿Qué expresa «If you heat ice, it melts»?", options: ["Una regla general", "Un plan para mañana", "Una hipótesis imposible", "Una experiencia pasada"], correct: 0, explain: "Zero conditional expresa una relación general entre condición y resultado." }, { q: "Completa: If it rains tomorrow, we ___ home.", options: ["will stay", "would stayed", "stays", "stayed"], correct: 0, explain: "First conditional usa presente en if y will + verbo base en el resultado." }, { q: "¿Qué error hay en «If it will rain, we'll stay home»?", options: ["En el patrón básico, la cláusula con if usa presente: If it rains", "Will nunca expresa futuro", "La frase necesita pasado", "Stay siempre lleva -s"], correct: 0, explain: "La consecuencia lleva will; la condición usa presente simple." }, { q: "¿Qué forma introduce una situación hipotética poco probable?", options: ["If I had..., I would...", "If I have..., I will... siempre", "When I had yesterday...", "Have I would..."], correct: 0, explain: "Second conditional combina pasado simple y would + verbo base." },
    ],
  },
  {
    title: "Phrasal Verbs & Idioms", level: "avanzado", photo: photos.books, photoAlt: "Persona hojea libros y notas de estudio", goal: "Comprender y usar phrasal verbs e idioms frecuentes en conversaciones reales.",
    vocab: [
      { title: "Everyday Phrasal Verbs", desc: "Aprende verbos compuestos comunes en conversaciones cotidianas.", cards: [
        { emoji: "⏰", en: "Wake up", ipa: "/weɪk ʌp/", es: "Despertarse" }, { emoji: "🚪", en: "Come in", ipa: "/kʌm ɪn/", es: "Entrar" }, { emoji: "🔍", en: "Find out", ipa: "/faɪnd aʊt/", es: "Averiguar" }, { emoji: "📞", en: "Call back", ipa: "/kɔːl bæk/", es: "Devolver una llamada" }, { emoji: "📝", en: "Write down", ipa: "/raɪt daʊn/", es: "Anotar" }, { emoji: "🧹", en: "Clean up", ipa: "/kliːn ʌp/", es: "Limpiar y ordenar" }, { emoji: "🚶", en: "Head out", ipa: "/hed aʊt/", es: "Salir" }, { emoji: "📦", en: "Pick up", ipa: "/pɪk ʌp/", es: "Recoger" },
      ], hint: "Escucha la partícula final: puede cambiar el sentido del verbo.", analogy: "Un phrasal verb es como una herramienta compuesta: las piezas juntas crean un sentido nuevo.", example: "I'll call you back after the meeting. (Te devolveré la llamada después de la reunión.)", threshold: 5 },
      { title: "Useful Everyday Idioms", desc: "Interpreta expresiones idiomáticas sin traducirlas palabra por palabra.", cards: [
        { emoji: "🧊", en: "Break the ice", ipa: "/breɪk ði aɪs/", es: "Romper el hielo" }, { emoji: "💸", en: "A piece of cake", ipa: "/ə piːs əv keɪk/", es: "Pan comido" }, { emoji: "🌧️", en: "Under the weather", ipa: "/ˈʌndər ðə ˈweðər/", es: "Sentirse indispuesto" }, { emoji: "📍", en: "On the same page", ipa: "/ɑːn ðə seɪm peɪdʒ/", es: "Estar de acuerdo" }, { emoji: "⏳", en: "In the long run", ipa: "/ɪn ðə lɔːŋ rʌn/", es: "A largo plazo" }, { emoji: "🤝", en: "Give it a shot", ipa: "/ɡɪv ɪt ə ʃɑːt/", es: "Intentarlo" }, { emoji: "👀", en: "Keep an eye on", ipa: "/kiːp ən aɪ ɑːn/", es: "Vigilar" }, { emoji: "🌟", en: "So far, so good", ipa: "/soʊ fɑːr soʊ ɡʊd/", es: "Hasta ahora, todo bien" },
      ], hint: "Recuerda la situación donde se dice la expresión, no una traducción literal de cada palabra.", analogy: "Un idiom es como una señal cultural: su sentido se entiende dentro del contexto.", example: "Let's break the ice with a simple question. (Rompamos el hielo con una pregunta sencilla.)", threshold: 5 },
    ], listen: [{ title: "Phrasal Verb Context", desc: "Reconoce verbos compuestos y su sentido en una situación.", exercises: [
      { audio: "Please write down the address.", options: ["Please write down the address.", "Please turn down the address.", "Please write about the address."], correct: 0 }, { audio: "I'll call you back later.", options: ["I'll call you back later.", "I'll call you later tonight.", "I'll call back the letter."], correct: 0 }, { audio: "We need to find out the time.", options: ["We need to find out the time.", "We need to find the time out.", "We need to find it on time."], correct: 0 }, { audio: "Could you pick up the parcel?", options: ["Could you pick up the parcel?", "Could you pack up the parcel?", "Could you put down the parcel?"], correct: 0 }, { audio: "Let's break the ice.", options: ["Let's break the ice.", "Let's break a glass.", "Let's make the ice."], correct: 0 },
    ], hint: "La partícula cambia el sentido; escucha su posición con relación al objeto.", analogy: "El contexto es una pista que revela el sentido figurado de una expresión.", example: "We found out the train was late. (Averiguamos que el tren se retrasó.)" }], pron: [], reading: [],
    quiz: [
      { q: "¿Qué significa «find out» en «I need to find out the answer»?", options: ["Averiguar", "Salir", "Despertarse", "Limpiar"], correct: 0, explain: "Find out significa descubrir o averiguar información." }, { q: "¿Cómo dirías «Anota el número»?", options: ["Write down the number.", "Wake up the number.", "Head out the number.", "Call back the number."], correct: 0, explain: "Write down significa anotar por escrito." }, { q: "¿Qué significa break the ice en una charla?", options: ["Iniciar conversación y reducir la tensión", "Romper una ventana", "Salir de una reunión", "Cambiar de asiento"], correct: 0, explain: "En contexto social, break the ice significa facilitar el inicio de la conversación." }, { q: "¿Qué estrategia ayuda a aprender un idiom?", options: ["Recordar una situación donde se usa", "Traducir cada palabra por separado", "Cambiarlo al pasado", "Memorizar solo el artículo"], correct: 0, explain: "El contexto y la situación de uso fijan mejor su significado." },
    ],
  },
  {
    title: "Movies, Music & Culture", level: "avanzado", photo: photos.culture, photoAlt: "Público en un concierto con luces de escenario", goal: "Expresar opiniones y comprender conversaciones sobre películas, música y cultura.",
    vocab: [
      { title: "Movies & Stories", desc: "Describe géneros, personajes y opiniones sobre películas.", cards: [
        { emoji: "🎬", en: "Movie", ipa: "/ˈmuːvi/", es: "Película" }, { emoji: "😂", en: "Comedy", ipa: "/ˈkɑːmədi/", es: "Comedia" }, { emoji: "🕵️", en: "Mystery", ipa: "/ˈmɪstəri/", es: "Misterio" }, { emoji: "🚀", en: "Science fiction", ipa: "/ˌsaɪəns ˈfɪkʃən/", es: "Ciencia ficción" }, { emoji: "🎭", en: "Character", ipa: "/ˈkærəktər/", es: "Personaje" }, { emoji: "📖", en: "Plot", ipa: "/plɑːt/", es: "Trama" }, { emoji: "⭐", en: "Performance", ipa: "/pərˈfɔːrməns/", es: "Interpretación" }, { emoji: "🍿", en: "Soundtrack", ipa: "/ˈsaʊndtræk/", es: "Banda sonora" },
      ], hint: "Mystery lleva el acento al principio; performance destaca la segunda parte.", analogy: "Un género es como una etiqueta en una biblioteca: anticipa el tipo de historia.", example: "The soundtrack made the movie unforgettable. (La banda sonora hizo inolvidable la película.)", threshold: 5 },
      { title: "Music & Opinions", desc: "Habla de géneros musicales y justifica tus preferencias.", cards: [
        { emoji: "🎸", en: "Rock music", ipa: "/rɑːk ˈmjuːzɪk/", es: "Música rock" }, { emoji: "🎹", en: "Jazz", ipa: "/dʒæz/", es: "Jazz" }, { emoji: "🎤", en: "Live show", ipa: "/laɪv ʃoʊ/", es: "Espectáculo en vivo" }, { emoji: "🎧", en: "Lyrics", ipa: "/ˈlɪrɪks/", es: "Letra de una canción" }, { emoji: "❤️", en: "Moving", ipa: "/ˈmuːvɪŋ/", es: "Conmovedor" }, { emoji: "✨", en: "Creative", ipa: "/kriˈeɪtɪv/", es: "Creativo" }, { emoji: "👍", en: "I agree", ipa: "/aɪ əˈɡriː/", es: "Estoy de acuerdo" }, { emoji: "💭", en: "In my opinion", ipa: "/ɪn maɪ əˈpɪnjən/", es: "En mi opinión" },
      ], hint: "En opinion el acento principal suele oírse en -pin; escucha la palabra completa.", analogy: "Dar una opinión con una razón es como presentar una recomendación con evidencia.", example: "In my opinion, the lyrics are moving. (En mi opinión, la letra es conmovedora.)", threshold: 5 },
    ], listen: [{ title: "Culture Listening", desc: "Comprende preferencias y opiniones culturales.", exercises: [
      { audio: "I prefer comedies to horror movies.", options: ["I prefer comedies to horror movies.", "I prepare comedies for movie night.", "I prefer horror movies to comedies."], correct: 0 }, { audio: "The soundtrack was moving.", options: ["The soundtrack was moving.", "The story was confusing.", "The soundtrack was missing."], correct: 0 }, { audio: "In my opinion, jazz is relaxing.", options: ["In my opinion, jazz is relaxing.", "In my opinion, rock is relaxing.", "In my experience, jazz is exciting."], correct: 0 }, { audio: "The main character changes a lot.", options: ["The main character changes a lot.", "The movie starts very late.", "The music changes a lot."], correct: 0 }, { audio: "I agree because the story feels real.", options: ["I agree because the story feels real.", "I disagree because the story feels real.", "I agree because the music feels loud."], correct: 0 },
    ], hint: "Escucha marcadores de opinión como prefer, in my opinion, agree y because.", analogy: "Una opinión se entiende mejor junto con la razón que la acompaña.", example: "I liked the story because it felt real. (Me gustó la historia porque parecía real.)" }], pron: [{ title: "Share Your Opinion", desc: "Practica opiniones naturales sobre una película o canción.", phrases: [
      { en: "I really enjoyed the story and its characters.", es: "Disfruté mucho la historia y sus personajes." }, { en: "In my opinion, the music is beautiful.", es: "En mi opinión, la música es hermosa." }, { en: "I prefer comedies because they make me laugh.", es: "Prefiero las comedias porque me hacen reír." }, { en: "The ending was surprising but satisfying.", es: "El final fue sorprendente, pero satisfactorio." },
    ], hint: "En because, enlaza el final con la razón sin insertar una vocal.", analogy: "Compartir una opinión es recomendar una experiencia y explicar qué la hizo especial.", example: "I enjoyed it because it was funny. (Lo disfruté porque fue divertido.)", threshold: 3 }], reading: [],
    quiz: [
      { q: "¿Qué significa «The soundtrack was moving»?", options: ["La banda sonora fue conmovedora", "La película fue corta", "La historia fue confusa", "El concierto fue gratuito"], correct: 0, explain: "Moving describe algo que emociona o conmueve." }, { q: "¿Cómo dices «Prefiero el jazz»?", options: ["I prefer jazz.", "I pretend jazz.", "I preferring jazz.", "I preference jazz."], correct: 0, explain: "Prefer es el verbo para expresar una preferencia." }, { q: "¿Qué palabra introduce una razón en «I liked it because…»?", options: ["because", "although", "unless", "while"], correct: 0, explain: "Because introduce la causa o razón." }, { q: "¿Cómo empieza «character»?", options: ["Con /k/", "Con /tʃ/ como chair", "Con /ʃ/ como she", "Con /h/"], correct: 0, explain: "Character comienza con /k/, no con /tʃ/." },
    ],
  },
  {
    title: "Real Conversations Advanced", level: "avanzado", photo: photos.stage, photoAlt: "Artistas en un escenario iluminado frente al público", goal: "Sostener una conversación A2-B1 integrando experiencias, planes, opiniones y escucha activa.",
    vocab: [], reading: [], pron: [{ title: "Conversation: Plans & Experiences", desc: "Ensaya una conversación larga para compartir experiencias, planes y opiniones.", phrases: [
      { en: "Have you ever traveled somewhere on your own?", es: "¿Has viajado alguna vez a algún lugar por tu cuenta?" }, { en: "Yes, I have, and I learned a lot.", es: "Sí, y aprendí muchísimo." }, { en: "What are you planning to do next year?", es: "¿Qué planeas hacer el próximo año?" }, { en: "If I have enough time, I'll visit my friends.", es: "Si tengo tiempo suficiente, visitaré a mis amistades." }, { en: "That sounds exciting. What do you enjoy most?", es: "Suena emocionante. ¿Qué es lo que más disfrutas?" }, { en: "I enjoy meeting people and learning about new cultures.", es: "Disfruto conocer personas y aprender sobre culturas nuevas." },
    ], hint: "Escucha la pregunta completa, identifica su tiempo verbal y responde retomando una palabra clave.", analogy: "Una conversación fluida es un puente de ida y vuelta: escuchas, conectas una idea y devuelves una pregunta.", example: "Have you ever tried it? (¿Lo has probado alguna vez?)", threshold: 4 }], listen: [{ title: "Real Conversation Listening", desc: "Comprende una conversación que combina experiencias y planes.", exercises: [
      { audio: "Have you ever traveled alone?", options: ["Have you ever traveled alone?", "Did you travel alone yesterday?", "Are you traveling alone now?"], correct: 0 }, { audio: "I went to Cusco last year.", options: ["I went to Cusco last year.", "I've gone to Cusco many times.", "I'm going to Cusco next year."], correct: 0 }, { audio: "What are you planning to do next year?", options: ["What are you planning to do next year?", "What did you plan last year?", "What do you do every year?"], correct: 0 }, { audio: "If I have time, I'll visit my friends.", options: ["If I have time, I'll visit my friends.", "If I had time, I'd visit my friends.", "I have time when I visit my friends."], correct: 0 }, { audio: "I enjoy meeting people from other cultures.", options: ["I enjoy meeting people from other cultures.", "I avoid meeting people from other cultures.", "I enjoy reading about other cultures."], correct: 0 }, { audio: "That sounds exciting. Tell me more.", options: ["That sounds exciting. Tell me more.", "That sounds exhausting. Tell me later.", "That seems exciting. Tell me now."], correct: 0 },
    ], hint: "Usa la forma verbal para distinguir experiencia, evento fechado y plan futuro.", analogy: "Responder a una idea previa demuestra escucha tanto como pronunciar con claridad.", example: "If I have time, I'll join you. (Si tengo tiempo, me uniré a ti.)" }],
    quiz: [
      { q: "¿Qué pregunta por experiencias sin fecha específica?", options: ["Have you ever traveled alone?", "Did you travel yesterday?", "Are you traveling now?", "Do you travel every Monday?"], correct: 0, explain: "Ever con present perfect pregunta por experiencias hasta el presente." }, { q: "¿Cómo se dice «Si tengo tiempo, visitaré a mis amigos»?", options: ["If I have time, I'll visit my friends.", "If I will have time, I visit my friends.", "If I had time, I visited them.", "If I have time, I visited them."], correct: 0, explain: "First conditional usa presente en if y will en la consecuencia futura." }, { q: "¿Qué problema hay si respondes «Yes» a «What do you enjoy most?»?", options: ["No indicas qué actividad disfrutas", "Yes está en pasado", "La pregunta exige un número", "Enjoy solo se usa en futuro"], correct: 0, explain: "La pregunta solicita una actividad o preferencia, no un sí o no." }, { q: "¿Qué ayuda a mantener una conversación fluida?", options: ["Escuchar, responder a la idea y hacer una pregunta relacionada", "Cambiar de tema en cada turno", "Hablar más rápido que la otra persona", "Esperar sin mostrar atención"], correct: 0, explain: "La escucha activa y las preguntas de seguimiento sostienen el intercambio." }, { q: "¿Cómo se produce el sonido /θ/ de think?", options: ["Con la lengua entre los dientes", "Como la t de tea", "Como la s de see", "Como la f de fine"], correct: 0, explain: "/θ/ es un sonido sordo que se articula con la lengua entre los dientes." },
    ],
  },
];

export const ENGLISH_MODULE_ICONS = ["👋", "👨‍👩‍👧", "🍎", "🌅", "⏳", "💬", "🌍", "💼", "🎬", "📰", "🧠", "💭", "🎭", "📚", "🏆"];

function b1Reading(title: string, desc: string, explanation: string, pattern: string, points: [string, string, string], example: string): ReadingSpec {
  return { title, desc, explanation, pattern, points, example, note: "Elige la estructura por el significado y el contexto, no solo por una palabra aislada.", tip: "Lee el ejemplo en voz alta y explica qué pista temporal o contextual te ayudó a elegir.", hint: "Identifica primero el significado que quieres comunicar; después reconoce el patrón.", analogy: "La gramática es un mapa: el contexto indica qué camino expresa mejor tu idea." };
}

const b1SupplementalReadings: Record<number, ReadingSpec[]> = {
  10: [b1Reading("Past or Present Connection?", "Contrasta una experiencia abierta con un evento pasado fechado.", "Past simple sitúa un hecho en un momento terminado; present perfect conecta una experiencia anterior con el presente sin indicar cuándo ocurrió.", "I visited Cusco last year.\nI've visited Cusco twice.", ["Usa past simple con momentos terminados y concretos.", "Usa have/has + participio para experiencias hasta ahora.", "Ever y never suelen acompañar preguntas o experiencias sin fecha."], "I've never traveled alone. (Nunca he viajado por mi cuenta.)")],
  11: [b1Reading("Choose the Conditional", "Selecciona una forma condicional según la posibilidad y el propósito.", "Las condicionales conectan una situación con su resultado. La forma verbal muestra si describes una regla, un plan probable o una hipótesis poco probable.", "If water reaches 100°C, it boils.\nIf I have time, I'll call.\nIf I had time, I'd travel.", ["Zero: if + present, present para hechos generales.", "First: if + present, will + verbo base para posibilidades futuras.", "Second: if + past, would + verbo base para hipótesis."], "If I had a free week, I'd visit my family. (Si tuviera una semana libre, visitaría a mi familia.)")],
  12: [
    b1Reading("Phrasal Verbs in Context", "Interpreta verbos compuestos mediante la situación y sus partículas.", "Un phrasal verb combina un verbo y una partícula. El significado puede cambiar respecto al verbo por separado, así que conviene aprenderlo dentro de una frase.", "find out = discover\nPlease find out the train time.", ["Escucha la partícula junto al verbo.", "Observa el objeto y la situación para deducir el sentido.", "Guarda un ejemplo completo, no solo una traducción."], "I found out the meeting was canceled. (Me enteré de que cancelaron la reunión.)"),
    b1Reading("Phrasal Verb Word Order", "Reconoce dónde colocar el objeto con verbos separables.", "Algunos phrasal verbs admiten el objeto entre el verbo y la partícula. Si el objeto es un pronombre, normalmente debe ir en medio.", "write down the address\nwrite it down\ncall your friend back", ["Con sustantivos, el objeto puede ir antes o después de la partícula en algunos verbos.", "Con pronombres, usa verbo + pronombre + partícula.", "Comprueba el orden con una frase completa y su audio."], "Please write it down. (Por favor, anótalo.)"),
    b1Reading("Idioms and Meaning", "Deduce expresiones idiomáticas usando el contexto conversacional.", "Un idiom tiene un significado convencional que no siempre se deduce palabra por palabra. El contexto y la intención del hablante ayudan a interpretarlo.", "Let's break the ice.\nThat test was a piece of cake.", ["Identifica la situación social o el tema.", "Busca el sentido global antes de traducir palabras sueltas.", "Practica la expresión dentro de una respuesta natural."], "The first question helped break the ice. (La primera pregunta ayudó a romper el hielo.)"),
  ],
  13: [
    b1Reading("Describe a Story", "Organiza vocabulario de cine en una opinión comprensible.", "Para comentar una película, presenta el género o la trama, describe un personaje y conecta la opinión con una razón.", "The story was moving because the characters felt real.", ["Usa adjetivos para describir la experiencia.", "Incluye because para explicar una razón.", "Conecta la opinión con un detalle de la historia."], "I enjoyed the comedy because it made me laugh. (Disfruté la comedia porque me hizo reír.)"),
    b1Reading("Compare Music and Films", "Compara preferencias culturales con comparativos y superlativos.", "Los comparativos permiten contrastar dos obras o estilos. Los superlativos destacan una opción dentro de un grupo.", "This soundtrack is more relaxing than the last one.\nIt's the best song on the album.", ["Usa than para introducir una comparación.", "Usa the con muchos superlativos.", "Good y bad tienen formas irregulares: better/best y worse/worst."], "The second film was better than the first. (La segunda película fue mejor que la primera.)"),
    b1Reading("Agree and Disagree", "Expresa una opinión y responde a la idea de otra persona.", "Una conversación cultural fluida combina una postura, una razón y una respuesta conectada con el turno anterior.", "I agree because the music is original.\nI see your point, but the ending felt rushed.", ["Usa marcadores como I agree o In my opinion.", "Sostén la opinión con because o un detalle concreto.", "Al discrepar, reconoce primero la idea de la otra persona."], "I see your point, but I prefer the original version. (Entiendo tu punto, pero prefiero la versión original.)"),
  ],
};

function vocabLesson(spec: VocabSpec, module: ModuleSpec, moduleIndex: number, lessonIndex: number): EnglishLesson {
  const threshold = Math.ceil(spec.cards.length * 0.6);
  return { id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "vocab", icon: "👋", xp: 30, minutes: 10, title: spec.title, desc: spec.desc, level: module.level, objectives: ["Escuchar y reconocer palabras del tema.", "Repetir sonidos y acento con claridad.", "Relacionar expresiones con situaciones cotidianas."], dax: { hint: spec.hint, explain: spec.analogy, example: spec.example }, intro: spec.intro ?? `<p>${spec.desc} Escucha cada tarjeta, observa su pronunciación IPA y repite la expresión en voz alta.</p>`, vocab: spec.cards, checks: [{ desc: `Escucha al menos ${threshold} palabras`, test: (ctx) => ctx.type === "vocab" && ctx.listened.size >= threshold }] };
}

function listenLesson(spec: ListenSpec, module: ModuleSpec, moduleIndex: number, lessonIndex: number): EnglishLesson {
  return { id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "listen", icon: "🎧", xp: moduleIndex === 14 ? 100 : 40, minutes: 11, title: spec.title, desc: spec.desc, level: module.level, objectives: ["Escuchar el audio antes de responder.", "Distinguir palabras fonéticamente cercanas.", "Comprobar la comprensión de una frase oral."], dax: { hint: spec.hint, explain: spec.analogy, example: spec.example }, intro: spec.intro ?? `<p>${spec.desc} Escucha cada frase completa, detecta sus sonidos clave y elige la opción que coincide.</p>`, exercises: spec.exercises, checks: [{ desc: `Completa los ${spec.exercises.length} ejercicios`, test: (ctx) => ctx.type === "listen" && ctx.completed >= spec.exercises.length }] };
}

function pronLesson(spec: PronSpec, module: ModuleSpec, moduleIndex: number, lessonIndex: number): EnglishLesson {
  return { id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "pron", icon: "🗣️", xp: 50, minutes: 13, title: spec.title, desc: spec.desc, level: module.level, objectives: ["Escuchar frases útiles en inglés.", "Repetir ritmo y entonación con voz clara.", "Practicar frases en un contexto cotidiano."], dax: { hint: spec.hint, explain: spec.analogy, example: spec.example }, intro: spec.intro ?? `<p>${spec.desc} Escucha la frase a velocidad normal y lenta, repítela en voz alta y márcala como practicada.</p>`, phrases: spec.phrases, checks: [{ desc: `Practica al menos ${spec.threshold} frases`, test: (ctx) => ctx.type === "pron" && ctx.practiced >= spec.threshold }] };
}

function readingLesson(spec: ReadingSpec, module: ModuleSpec, moduleIndex: number, lessonIndex: number): EnglishLesson {
  const content = `<p>${spec.explanation}</p><h3>Escucha y observa</h3><pre style="background:#0b1220;color:#fca5a5;padding:14px 18px;border-radius:10px;font-family:ui-monospace;font-size:14px;overflow:auto">${spec.pattern}</pre><h3>Una analogía</h3><p>${spec.analogy}</p><ul>${spec.points.map((point) => `<li>${point}</li>`).join("")}</ul><div class="note"><strong>Error frecuente:</strong> ${spec.note}</div><div class="tip"><strong>Buena práctica:</strong> ${spec.tip}</div>`;
  return { id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "reading", icon: "📖", xp: 30, minutes: 12, title: spec.title, desc: spec.desc, level: module.level, objectives: ["Reconocer la estructura en un ejemplo.", "Comparar su forma con una idea en español.", "Aplicar el patrón en una frase propia."], dax: { hint: spec.hint, explain: spec.analogy, example: spec.example }, content, keyPoints: [...spec.points] };
}

function quizLesson(sourceQuestions: EnglishQuestion[], module: ModuleSpec, moduleIndex: number, lessonIndex: number): EnglishLesson {
  const finalQuiz = moduleIndex === 14;
  const longerQuiz = moduleIndex === 4 || moduleIndex === 9;
  const questions: EnglishQuestion[] = moduleIndex === 9 ? [...sourceQuestions, { q: "¿Qué estructura compara dos opciones?", options: ["Adjetivo comparativo + than", "The + adjetivo base", "More + verbo", "As + sustantivo"] as [string, string, string, string], correct: 0, explain: "El comparativo suele ir seguido de than para introducir el segundo elemento." }] : sourceQuestions;
  return { id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "quiz", icon: "📝", xp: finalQuiz ? 120 : longerQuiz ? 60 : 50, minutes: finalQuiz ? 15 : longerQuiz ? 10 : 9, title: finalQuiz ? "Final Conversation Quiz" : "Review & Respond", desc: "Comprueba vocabulario, comprensión, gramática y pronunciación.", level: module.level, objectives: ["Interpretar una frase escuchada.", "Elegir la estructura adecuada al contexto.", "Reconocer un sonido clave del vocabulario."], dax: { hint: "Lee el contexto y escucha mentalmente el ritmo de las opciones.", explain: "Resolver una pregunta es como reconstruir una conversación con pistas de sonido y significado.", example: "What have you tried? (¿Qué has probado?)" }, questions };
}

export const ENGLISH_CURRICULUM: EnglishModule[] = specs.map((module, moduleIndex) => {
  const lessons: EnglishLesson[] = [];
  const b1Readings = b1SupplementalReadings[moduleIndex] ?? [];
  [...module.reading, ...b1Readings].forEach((spec) => lessons.push(readingLesson(spec, module, moduleIndex, lessons.length)));
  if (moduleIndex !== 12 && moduleIndex !== 13) module.vocab.forEach((spec) => lessons.push(vocabLesson(spec, module, moduleIndex, lessons.length)));
  module.listen.forEach((spec) => lessons.push(listenLesson(spec, module, moduleIndex, lessons.length)));
  if (moduleIndex !== 12 && moduleIndex !== 13) module.pron.forEach((spec) => lessons.push(pronLesson(spec, module, moduleIndex, lessons.length)));
  lessons.push(quizLesson(module.quiz, module, moduleIndex, lessons.length));
  return { id: `m${moduleIndex + 1}`, title: module.title, minutes: lessons.reduce((sum, lesson) => sum + lesson.minutes, 0), goal: module.goal, level: module.level, photo: module.photo, photoAlt: module.photoAlt, lessons };
});

export function validateEnglishCurriculum() {
  const lessonCounts = [5, 4, 5, 4, 5, 3, 5, 4, 4, 4, 5, 5, 5, 5, 3];
  const audioCounts = [4, 3, 4, 2, 2, 2, 4, 3, 1, 2, 1, 1, 1, 1, 2];
  if (ENGLISH_CURRICULUM.length !== 15 || ENGLISH_MODULE_ICONS.length !== 15) throw new Error("El curso de inglés requiere 15 módulos e iconos.");
  ENGLISH_CURRICULUM.forEach((module, moduleIndex) => {
    const level: EnglishLevel = moduleIndex < 5 ? "principiante" : moduleIndex < 10 ? "intermedio" : "avanzado";
    if (module.id !== `m${moduleIndex + 1}` || module.level !== level || module.lessons.length !== lessonCounts[moduleIndex] || module.minutes !== module.lessons.reduce((sum, lesson) => sum + lesson.minutes, 0) || !/^https:\/\/images\.unsplash\.com\//.test(module.photo)) throw new Error(`Estructura inválida en ${module.id}.`);
    let audioActivities = 0;
    const lessonTypeCounts = module.lessons.reduce<Record<EnglishLessonType, number>>((counts, lesson) => ({ ...counts, [lesson.type]: counts[lesson.type] + 1 }), { vocab: 0, listen: 0, pron: 0, reading: 0, quiz: 0 });
    module.lessons.forEach((lesson, lessonIndex) => {
      if (lesson.id !== `m${moduleIndex + 1}l${lessonIndex + 1}` || lesson.level !== level || lesson.title.split(/\s+/).length > 5 || lesson.minutes < 8 || lesson.minutes > 20 || lesson.objectives.length !== 3 || !lesson.dax.hint || !lesson.dax.explain || !lesson.dax.example) throw new Error(`Actividad incompleta: ${lesson.id}.`);
      if (lesson.type === "vocab") { audioActivities += 1; if (!lesson.intro || lesson.vocab!.length < 8 || lesson.vocab!.length > 12 || lesson.vocab!.some((card) => !card.emoji || !card.en || !card.ipa || !card.es) || lesson.checks?.length !== 1 || lesson.checks[0].test({ type: "vocab", listened: new Set(), completed: 0, answered: new Set(), practiced: 0, marked: new Set() })) throw new Error(`Vocabulario inválido: ${lesson.id}.`); }
      if (lesson.type === "listen") { audioActivities += 1; if (!lesson.intro || lesson.exercises!.length < 5 || lesson.exercises!.length > 6 || lesson.exercises!.some((item) => item.options.length !== 3 || item.correct < 0 || item.correct > 2) || lesson.checks?.length !== 1 || lesson.checks[0].test({ type: "listen", listened: new Set(), completed: 0, answered: new Set(), practiced: 0, marked: new Set() })) throw new Error(`Escucha inválida: ${lesson.id}.`); }
      if (lesson.type === "pron") { audioActivities += 1; if (!lesson.intro || lesson.phrases!.length < 4 || lesson.phrases!.length > 6 || lesson.phrases!.some((phrase) => phrase.en.split(/\s+/).length < 4 || phrase.en.split(/\s+/).length > 10 || !phrase.es) || lesson.checks?.length !== 1 || lesson.checks[0].test({ type: "pron", listened: new Set(), completed: 0, answered: new Set(), practiced: 0, marked: new Set() })) throw new Error(`Pronunciación inválida: ${lesson.id}.`); }
      if (lesson.type === "reading" && (!lesson.content?.includes("<pre") || !lesson.content.includes("class=\"note\"") || !lesson.content.includes("class=\"tip\"") || lesson.keyPoints?.length !== 3)) throw new Error(`Lectura incompleta: ${lesson.id}.`);
      if (lesson.type === "quiz" && (!lesson.questions || lesson.questions.length !== ([4, 9, 14].includes(moduleIndex) ? 5 : 4) || lesson.questions.some((question) => question.options.length !== 4 || question.correct < 0 || question.correct > 3))) throw new Error(`Quiz inválido: ${lesson.id}.`);
    });
    if (audioActivities !== audioCounts[moduleIndex]) throw new Error(`Cantidad de actividades auditivas inválida en ${module.id}.`);
    if (moduleIndex < 5) {
      const expectedTypes: Record<number, Partial<Record<EnglishLessonType, number>>> = {
        0: { vocab: 2, listen: 1, pron: 1 }, 1: { vocab: 2, listen: 1 }, 2: { vocab: 2, listen: 1, pron: 1 },
        3: { reading: 1, vocab: 1, listen: 1 }, 4: { reading: 2, listen: 1, pron: 1 },
      };
      if (Object.entries(expectedTypes[moduleIndex]).some(([type, count]) => lessonTypeCounts[type as EnglishLessonType] !== count) || lessonTypeCounts.quiz !== 1) throw new Error(`Secuencia A1 inválida en ${module.id}.`);
    }
    if (moduleIndex >= 10 && moduleIndex <= 13 && (lessonTypeCounts.reading !== 3 || lessonTypeCounts.listen !== 1 || lessonTypeCounts.quiz !== 1)) throw new Error(`Secuencia B1 inválida en ${module.id}.`);
    if (moduleIndex === 14 && (lessonTypeCounts.pron !== 1 || lessonTypeCounts.listen !== 1 || lessonTypeCounts.quiz !== 1 || module.lessons.find((lesson) => lesson.type === "listen")?.xp !== 100 || module.lessons.find((lesson) => lesson.type === "quiz")?.xp !== 120 || module.lessons.find((lesson) => lesson.type === "quiz")?.minutes !== 15)) throw new Error("La evaluación final de inglés debe incluir listening y quiz con sus XP y duración requeridos.");
    if ([0, 2, 4, 5].includes(moduleIndex) && !module.lessons.some((lesson) => lesson.type === "pron")) throw new Error(`Falta pronunciación en ${module.id}.`);
  });
}

validateEnglishCurriculum();
