import { calculateExcelSheet } from "@/lib/excelFormulaEngine";

export type ExcelLevel = "principiante" | "intermedio" | "avanzado";
export type ExcelLessonType = "reading" | "sheet" | "quiz";
export type ExcelCellMap = Record<string, string>;
export type ExcelValueMap = Record<string, string | number | boolean | null>;
export type ExcelCheck = { desc: string; test: (cells: ExcelCellMap, values: ExcelValueMap) => boolean };
export type ExcelQuestion = { q: string; options: string[]; correct: number; explain: string };
export type ExcelLesson = {
  id: string; type: ExcelLessonType; icon: string; xp: number; minutes: number; title: string; desc: string;
  level: ExcelLevel; objectives: string[]; dax: { hint: string; explain: string; example: string };
  content?: string; keyPoints?: string[]; prompt?: string; initCells?: ExcelCellMap;
  checks?: ExcelCheck[]; solution?: ExcelCellMap; questions?: ExcelQuestion[];
};
export type ExcelModule = { id: string; title: string; minutes: number; goal: string; level: ExcelLevel; lessons: ExcelLesson[] };

type ReadingSpec = { title: string; desc: string; formula: string; keyPoints: [string, string, string]; note: string; tip: string; analogy: string };
type SheetSpec = { title: string; desc: string; prompt: string; cells: ExcelCellMap; formulas: string[]; solution: ExcelCellMap; results: Array<[string, number | string]>; functionName?: string; formulaPattern?: string; objectives: [string, string, string] };
type ModuleSpec = { title: string; goal: string; level: ExcelLevel; readings: ReadingSpec[]; sheets: SheetSpec[]; quiz: ExcelQuestion[] };

const specs: ModuleSpec[] = [
  { title: "Fundamentos y navegación en Excel", level: "principiante", goal: "Organizar datos en una hoja y construir cálculos sencillos con referencias claras.", readings: [
    { title: "Interfaz, celdas y rangos", desc: "Ubica celdas y rangos para construir una hoja comprensible.", formula: "=A1:C5", keyPoints: ["La celda combina letra de columna y número de fila.", "Los dos puntos describen un rango continuo.", "Los encabezados hacen comprensible cada columna."], note: "Evita filas vacías dentro de una tabla: dificultan filtros, fórmulas y análisis.", tip: "Usa Ctrl+Inicio para volver rápidamente a A1.", analogy: "Una hoja se parece a una ciudad: cada celda tiene una dirección formada por calle y número." },
    { title: "Tipos de datos y formatos", desc: "Distingue texto, números, fechas y fórmulas antes de analizarlos.", formula: "=250*4", keyPoints: ["El valor almacenado y su formato visual son cosas distintas.", "Una fórmula empieza con igual.", "Las fechas también se almacenan como valores numéricos."], note: "Un número guardado como texto puede impedir cálculos y ordenamientos correctos.", tip: "Aplica formato de moneda o fecha sin alterar el valor subyacente.", analogy: "Es como ordenar productos por categoría antes de llevar el inventario." },
    { title: "Operadores y primeros cálculos", desc: "Combina operadores respetando la jerarquía matemática.", formula: "=12+8*3", keyPoints: ["La multiplicación se evalúa antes que la suma.", "Los paréntesis hacen explícita la intención.", "& concatena textos; no suma palabras."], note: "No uses el guion de un texto como si fuera una resta sin verificar el tipo de dato.", tip: "Agrega paréntesis cuando faciliten la revisión de una fórmula.", analogy: "La precedencia funciona como una receta que indica qué paso debe ejecutarse primero." },
  ], sheets: [{ title: "Primera hoja de ventas", desc: "Calcula el total de un pedido usando referencias de celdas.", prompt: "En A1 escribe `Precio`, B1 `Cantidad`, C1 `Total`; en A2 coloca 250 y B2 4. Escribe en C2 una fórmula que use A2 y B2. El resultado esperado es 1000.", cells: { A1: "Precio", B1: "Cantidad", C1: "Total", A2: "250", B2: "4" }, formulas: ["C2"], solution: { C2: "=A2*B2" }, results: [["C2", 1000]], objectives: ["Ingresar encabezados y datos con tipos correctos.", "Calcular el total con referencias de celdas.", "Comprobar que el resultado se actualiza al cambiar una entrada."] }], quiz: [
    { q: "¿Qué devuelve `=4+3*2`?", options: ["14", "10", "20", "9"], correct: 1, explain: "La multiplicación se calcula antes: 4 + 6 = 10." },
    { q: "¿Qué error puede causar guardar 250 como texto?", options: ["No se puede usar nunca como encabezado", "Puede impedir que funciones numéricas lo calculen", "Excel lo transforma siempre en fecha", "La celda se elimina"], correct: 1, explain: "El tipo almacenado importa para los cálculos; el formato visual no siempre corrige un valor textual." },
    { q: "¿Cuándo conviene separar una tabla en encabezados y filas de datos?", options: ["Cuando se quiere filtrar y analizar registros", "Solo para cambiar el color", "Para impedir el uso de fórmulas", "Cuando todas las celdas son imágenes"], correct: 0, explain: "Una estructura tabular consistente permite ordenar, filtrar y resumir registros." },
    { q: "¿Qué representa `B2:D4`?", options: ["Una fórmula", "Un rango rectangular de celdas", "Una hoja llamada B2", "Una función de fecha"], correct: 1, explain: "Los dos puntos incluyen el bloque desde B2 hasta D4." },
  ] },
  { title: "Fórmulas y referencias", level: "principiante", goal: "Construir fórmulas que se copian de forma correcta con referencias relativas y absolutas.", readings: [
    { title: "Referencias al copiar", desc: "Predice cómo cambian las referencias al copiar una fórmula.", formula: "=B2*C2", keyPoints: ["Las referencias relativas se ajustan al copiar.", "Copiar hacia abajo cambia normalmente la fila.", "Copiar a la derecha cambia normalmente la columna."], note: "Revisa la primera fórmula copiada antes de rellenar cientos de filas.", tip: "Usa el controlador de relleno y confirma los resultados de varias filas.", analogy: "Una referencia relativa es una dirección que se desplaza con quien la lee." },
    { title: "Referencias absolutas y entre hojas", desc: "Fija constantes con `$` y comprende referencias entre pestañas.", formula: "=B2*(1+$B$1)", keyPoints: ["`$B$1` fija columna y fila.", "`B$1` fija solo la fila; `$B1` fija solo la columna.", "Hoja2!A1 identifica una celda en otra hoja."], note: "Si copias una tasa sin fijarla, la fórmula puede apuntar a una celda equivocada.", tip: "F4 alterna los tipos de referencia durante la edición.", analogy: "El signo dólar es un ancla para mantener una parte de la dirección en su sitio." },
  ], sheets: [{ title: "Precios con IVA fijo", desc: "Aplica el mismo IVA a varios productos sin desplazar la tasa.", prompt: "Escribe IVA en A1 y 0.19 en B1. Pon precios 1000, 50 y 80 en B3:B5. En C3:C5 calcula el precio con IVA usando la referencia absoluta `$B$1`. Resultados: 1190, 59.5 y 95.2.", cells: { A1: "IVA", B1: "0.19", A2: "Producto", B2: "Precio", C2: "Con IVA", A3: "Laptop", B3: "1000", A4: "Mouse", B4: "50", A5: "Teclado", B5: "80" }, formulas: ["C3", "C4", "C5"], solution: { C3: "=B3*(1+$B$1)", C4: "=B4*(1+$B$1)", C5: "=B5*(1+$B$1)" }, results: [["C3", 1190], ["C4", 59.5], ["C5", 95.2]], objectives: ["Fijar una tasa compartida con referencia absoluta.", "Calcular importes para varias filas.", "Verificar que la referencia permanece anclada."] }], quiz: [
    { q: "Al copiar `=A1*$B$1` una fila abajo, ¿qué sucede?", options: ["Cambia A1 a A2 y conserva $B$1", "Cambia ambas referencias", "Conserva A1 y cambia B1", "La fórmula se convierte en texto"], correct: 0, explain: "A1 es relativa; `$B$1` fija tanto columna como fila." },
    { q: "¿Qué referencia fija la columna A, pero permite cambiar de fila?", options: ["A$1", "$A1", "$A$1", "A1"], correct: 1, explain: "El dólar antes de la letra fija la columna; la fila queda relativa." },
    { q: "¿Cuándo usarías `Hoja2!A1`?", options: ["Para referirte a otra pestaña del libro", "Para crear un nombre definido", "Para sumar una columna", "Para fijar una fila"], correct: 0, explain: "El signo de exclamación separa el nombre de la hoja de la celda." },
    { q: "¿Por qué fijar una tasa de impuesto al copiar una fórmula?", options: ["Para usar la misma tasa en cada fila", "Para impedir que cambien los precios", "Para evitar que Excel calcule", "Para convertir el rango en tabla"], correct: 0, explain: "La tasa es un dato constante del cálculo y debe apuntar a la misma celda." },
  ] },
  { title: "Funciones esenciales y precisión", level: "principiante", goal: "Resumir datos numéricos con agregaciones y redondeos adecuados.", readings: [
    { title: "Sumar, promediar y contar", desc: "Selecciona una función según la pregunta que responde el reporte.", formula: "=PROMEDIO(B2:B8)", keyPoints: ["SUMA totaliza valores numéricos.", "PROMEDIO calcula la media aritmética.", "CONTAR considera números; CONTARA considera celdas no vacías."], note: "CONTAR y CONTARA responden preguntas distintas cuando la columna mezcla texto y números.", tip: "Comprueba el tamaño del rango para no excluir la última fila.", analogy: "SUMA reúne todas las monedas; PROMEDIO calcula una porción equitativa." },
    { title: "Máximos, mínimos y ABS", desc: "Encuentra extremos y mide diferencias sin signo.", formula: "=ABS(B2-C2)", keyPoints: ["MAX identifica el valor mayor.", "MIN identifica el valor menor.", "ABS devuelve una distancia no negativa."], note: "Un mínimo puede ser cero si el rango contiene ceros reales; interpreta el dato antes de concluir.", tip: "Usa MAX y MIN junto al promedio para contextualizar la variabilidad.", analogy: "MAX y MIN ubican primero y último; ABS mide cuánto separa a dos resultados." },
    { title: "Redondeo para reportes", desc: "Controla la precisión numérica sin confundirla con el formato visual.", formula: "=REDONDEAR(18.756;2)", keyPoints: ["REDONDEAR recibe valor y cantidad de decimales.", "El formato visual no necesariamente modifica el valor almacenado.", "La precisión debe responder a la unidad del negocio."], note: "Redondear cada línea antes de sumar puede dar un total distinto a redondear solo el resultado final.", tip: "Mantén precisión suficiente durante el cálculo y formatea la presentación después.", analogy: "Es como medir con una regla fina y mostrar luego el resultado con menos decimales." },
  ], sheets: [
    { title: "Resumen de notas", desc: "Calcula promedio y extremos de un grupo de estudiantes.", prompt: "Coloca las notas 6.5, 4, 7, 3.5 y 5.5 en B2:B6. En B8 usa PROMEDIO, B9 MAX y B10 MIN. Resultados: promedio 5.3, máximo 7 y mínimo 3.5.", cells: { A1: "Estudiante", B1: "Nota", A2: "Ana", B2: "6.5", A3: "Luis", B3: "4", A4: "Sofía", B4: "7", A5: "Marco", B5: "3.5", A6: "Elena", B6: "5.5", A8: "Promedio", A9: "Máxima", A10: "Mínima" }, formulas: ["B8", "B9", "B10"], solution: { B8: "=PROMEDIO(B2:B6)", B9: "=MAX(B2:B6)", B10: "=MIN(B2:B6)" }, results: [["B8", 5.3], ["B9", 7], ["B10", 3.5]], objectives: ["Calcular el promedio del grupo.", "Encontrar los valores extremos.", "Usar funciones en lugar de sumar celdas manualmente."] },
    { title: "Control de conteo y redondeo", desc: "Cuenta celdas con valores y redondea un promedio de gastos.", prompt: "Escribe importes en A2:A5: 18.35, 20.1, 15 y 21.45. En B2 calcula CONTAR(A2:A5), B3 CONTARA(A1:A5), B4 REDONDEAR(PROMEDIO(A2:A5);1) y B5 ABS(-12). Resultados: 4, 5, 18.7 y 12.", cells: { A1: "Gastos", A2: "18.35", A3: "20.1", A4: "15", A5: "21.45" }, formulas: ["B2", "B3", "B4", "B5"], solution: { B2: "=CONTAR(A2:A5)", B3: "=CONTARA(A1:A5)", B4: "=REDONDEAR(PROMEDIO(A2:A5);1)", B5: "=ABS(-12)" }, results: [["B2", 4], ["B3", 5], ["B4", 18.7], ["B5", 12]], objectives: ["Diferenciar CONTAR de CONTARA.", "Redondear el promedio al decimal solicitado.", "Calcular valor absoluto con una función."] },
  ], quiz: [
    { q: "¿Qué devuelve `=CONTARA(A1:A4)` si hay tres textos y una celda vacía?", options: ["4", "3", "1", "0"], correct: 1, explain: "CONTARA cuenta las tres celdas no vacías, sin importar si son texto o números." },
    { q: "¿Qué hace `=REDONDEAR(12.346;2)`?", options: ["12.34", "12.35", "12.3", "1234.6"], correct: 1, explain: "Redondea a dos decimales; el tercer decimal hace subir la centésima." },
    { q: "¿Qué función es más adecuada para conocer cuántas respuestas numéricas hay?", options: ["CONTARA", "CONTAR", "MAX", "ABS"], correct: 1, explain: "CONTAR incluye celdas numéricas y excluye textos." },
    { q: "¿Por qué puede diferir el total si redondeas cada fila?", options: ["Cada redondeo introduce una pequeña variación acumulable", "REDONDEAR borra las filas", "Excel cambia el tipo de gráfico", "El promedio deja de existir"], correct: 0, explain: "Redondear componentes antes de agregarlos puede acumular diferencias." },
  ] },
  { title: "Lógica condicional para decisiones", level: "principiante", goal: "Clasificar datos mediante condiciones sencillas y combinadas.", readings: [
    { title: "SI y comparadores", desc: "Devuelve etiquetas diferentes según una regla verificable.", formula: "=SI(B2>=11;\"Aprobado\";\"Reforzar\")", keyPoints: ["SI recibe condición, valor verdadero y valor falso.", "<> significa distinto.", "El texto dentro de la fórmula va entre comillas."], note: "Comprueba el límite exacto para evitar aprobar un valor que queda por debajo del criterio.", tip: "Prueba un dato igual al mínimo y otro justo debajo.", analogy: "SI es una bifurcación que dirige cada registro según una pregunta." },
    { title: "Combinar condiciones con Y y O", desc: "Representa reglas que necesitan todos o alguno de sus criterios.", formula: "=SI(Y(B2>=11;C2=\"Sí\");\"Aprobado\";\"Revisar\")", keyPoints: ["Y es verdadero cuando todas sus condiciones son verdaderas.", "O es verdadero cuando al menos una condición lo es.", "Los comparadores evalúan valores, no colores."], note: "Usar Y cuando bastaba una condición puede excluir casos válidos; traduce la regla empresarial con cuidado.", tip: "Escribe primero la regla en lenguaje natural y luego conviértela en condiciones.", analogy: "Y se parece a una puerta con dos cerraduras; O, a dos caminos alternativos." },
    { title: "SI anidado y categorías", desc: "Ordena umbrales para clasificar registros en más de dos grupos.", formula: "=SI(B2>=18;\"Alto\";SI(B2>=12;\"Medio\";\"Bajo\"))", keyPoints: ["Evalúa umbrales de mayor a menor.", "La primera condición verdadera determina el resultado.", "Demasiados niveles anidados dificultan el mantenimiento."], note: "Si un umbral amplio aparece primero, puede impedir que se alcancen las categorías específicas.", tip: "Documenta los límites junto al reporte para que otras personas entiendan la regla.", analogy: "Es como clasificar paquetes por tamaño: primero se identifica el más grande." },
  ], sheets: [
    { title: "Clasifica resultados", desc: "Aprueba notas a partir del criterio académico del curso.", prompt: "Escribe notas 14 y 8 en B2 y B3. Usa SI en C2 y C3 para mostrar Aprobado cuando la nota sea al menos 11; de lo contrario Reforzar. Resultados: `Aprobado`, `Reforzar`.", cells: { A1: "Estudiante", B1: "Nota", C1: "Estado", A2: "Ana", B2: "14", A3: "Luis", B3: "8" }, formulas: ["C2", "C3"], solution: { C2: "=SI(B2>=11;\"Aprobado\";\"Reforzar\")", C3: "=SI(B3>=11;\"Aprobado\";\"Reforzar\")" }, results: [["C2", "Aprobado"], ["C3", "Reforzar"]], functionName: "SI", objectives: ["Escribir una condición con el umbral de aprobación.", "Devolver etiquetas de texto mediante SI.", "Comprobar ambos caminos de la regla."] },
    { title: "Bono por desempeño", desc: "Asigna una categoría usando dos condiciones de negocio.", prompt: "En B2 escribe ventas 1200 y C2 `Sí`; en B3 800 y C3 `Sí`. En D2:D3 usa SI con Y: bono si ventas >=1000 y cliente frecuente = Sí; en otro caso Sin bono. Resultados: Bono y Sin bono.", cells: { A1: "Asesor", B1: "Ventas", C1: "Frecuente", D1: "Bono", A2: "Iris", B2: "1200", C2: "Sí", A3: "Noa", B3: "800", C3: "Sí" }, formulas: ["D2", "D3"], solution: { D2: "=SI(Y(B2>=1000;C2=\"Sí\");\"Bono\";\"Sin bono\")", D3: "=SI(Y(B3>=1000;C3=\"Sí\");\"Bono\";\"Sin bono\")" }, results: [["D2", "Bono"], ["D3", "Sin bono"]], functionName: "Y", objectives: ["Combinar condiciones con Y.", "Aplicar dos criterios para una decisión.", "Validar resultados positivos y negativos."] },
  ], quiz: [
    { q: "¿Qué devuelve `=SI(Y(A1>5;B1=\"Sí\");1;0)` cuando A1=7 y B1=\"No\"?", options: ["1", "0", "Sí", "FALSO"], correct: 1, explain: "Y requiere que ambas condiciones sean verdaderas; la segunda no se cumple." },
    { q: "¿Qué error produce usar `=` para asignar cuando se quería comparar?", options: ["La fórmula puede no representar la condición deseada", "Convierte SI en SUMA", "Siempre devuelve VERDADERO", "Cambia el formato de la celda"], correct: 0, explain: "El comparador de igualdad es `=` en Excel, pero debe usarse dentro de una condición bien formada, no como si fuera una asignación separada." },
    { q: "¿Cuándo usarías O en una regla de acceso?", options: ["Si basta con cumplir una de varias condiciones", "Si todas las condiciones deben cumplirse", "Para sumar texto", "Para fijar una referencia"], correct: 0, explain: "O representa alternativas suficientes para que la regla se cumpla." },
    { q: "¿Por qué ordenar de mayor a menor los umbrales de un SI anidado?", options: ["Para evaluar primero la categoría más específica", "Para ordenar los registros físicamente", "Para cambiar el tipo de dato", "Para hacer absoluta la referencia"], correct: 0, explain: "Una condición amplia al inicio puede capturar casos antes de que se revisen categorías más altas." },
  ] },
  { title: "Funciones condicionales avanzadas", level: "principiante", goal: "Contar y sumar registros según criterios de texto y comparación.", readings: [
    { title: "CONTAR.SI con criterios", desc: "Cuenta registros que coinciden con texto o comparaciones.", formula: "=CONTAR.SI(B2:B8;\">100\")", keyPoints: ["CONTAR.SI recibe rango y criterio.", "Los operadores se incluyen entre comillas dentro del criterio.", "Los comodines permiten patrones de texto."], note: "El criterio `>100` debe expresarse como texto entre comillas para que Excel lo interprete correctamente.", tip: "Comprueba que el rango del criterio incluya todos los registros.", analogy: "Es un filtro que cuenta cuántos productos cumplen una condición." },
    { title: "SUMAR.SI y rangos paralelos", desc: "Suma importes solo cuando un rango cumple el criterio.", formula: "=SUMAR.SI(A2:A8;\"Lima\";B2:B8)", keyPoints: ["El primer rango se evalúa.", "El tercer argumento contiene los valores que se suman.", "Los dos rangos deben corresponder fila por fila."], note: "Rangos desalineados pueden sumar ventas de una zona equivocada.", tip: "Mantén la misma altura para rango de criterio y rango de suma.", analogy: "Primero seleccionas las filas con una etiqueta; luego sumas sus importes." },
    { title: "Comodines y criterios", desc: "Busca patrones de texto y umbrales sin alterar los datos.", formula: "=CONTAR.SI(A2:A8;\"A*\")", keyPoints: ["El asterisco representa varios caracteres.", "`?` representa un carácter en ciertos criterios de Excel.", "Los criterios numéricos pueden combinar operadores y valores."], note: "Un comodín demasiado amplio puede contar códigos que no pertenecen al grupo esperado.", tip: "Prueba el criterio con una lista pequeña antes de usarlo en el reporte.", analogy: "El comodín se parece a una plantilla de búsqueda que deja algunas letras abiertas." },
  ], sheets: [
    { title: "Ventas por ciudad", desc: "Resume ingresos y cantidad de pedidos por zona.", prompt: "Ingresa Lima 120, Lima 340, Lima 90, Santiago 500, Santiago 210 y Bogotá 300 en A2:B7. En B10 usa SUMAR.SI para Lima; B11 CONTAR.SI para Santiago; B12 SUMAR.SI para Santiago. Resultados: 550, 2 y 710.", cells: { A1: "Ciudad", B1: "Ventas", A2: "Lima", B2: "120", A3: "Lima", B3: "340", A4: "Lima", B4: "90", A5: "Santiago", B5: "500", A6: "Santiago", B6: "210", A7: "Bogotá", B7: "300", A10: "Total Lima", A11: "Pedidos Santiago", A12: "Ventas Santiago" }, formulas: ["B10", "B11", "B12"], solution: { B10: "=SUMAR.SI(A2:A7;\"Lima\";B2:B7)", B11: "=CONTAR.SI(A2:A7;\"Santiago\")", B12: "=SUMAR.SI(A2:A7;\"Santiago\";B2:B7)" }, results: [["B10", 550], ["B11", 2], ["B12", 710]], functionName: "SUMAR.SI", objectives: ["Sumar importes por ciudad.", "Contar registros que coinciden con un texto.", "Verificar que criterios y rangos estén alineados."] },
    { title: "Filtra pedidos por umbral", desc: "Suma pedidos mayores al mínimo de campaña.", prompt: "Coloca importes 80, 150, 230, 95 en B2:B5. En B7 cuenta valores mayores que 100 con CONTAR.SI; en B8 suma esos valores con SUMAR.SI. Criterios `>100` entre comillas. Resultados: 2 y 380.", cells: { A1: "Pedido", B1: "Importe", A2: "P-1", B2: "80", A3: "P-2", B3: "150", A4: "P-3", B4: "230", A5: "P-4", B5: "95", A7: "Sobre 100", A8: "Total sobre 100" }, formulas: ["B7", "B8"], solution: { B7: "=CONTAR.SI(B2:B5;\">100\")", B8: "=SUMAR.SI(B2:B5;\">100\";B2:B5)" }, results: [["B7", 2], ["B8", 380]], functionName: "CONTAR.SI", objectives: ["Expresar criterios numéricos como texto.", "Contar y sumar con el mismo umbral.", "Comparar el resultado con las filas seleccionadas."] },
  ], quiz: [
    { q: "¿Qué devuelve `=CONTAR.SI(A1:A5;\"Lima\")`?", options: ["La suma de ventas", "La cantidad de celdas que coinciden con Lima", "La primera fila de Lima", "El promedio de la ciudad"], correct: 1, explain: "CONTAR.SI cuenta coincidencias dentro del rango." },
    { q: "¿Qué error hay en escribir el criterio `>100` sin comillas en CONTAR.SI?", options: ["Puede no interpretarse como el criterio textual esperado", "Convierte el rango a fecha", "Ordena los datos", "Fija la columna"], correct: 0, explain: "Los criterios con operadores se pasan como texto; por ejemplo, un criterio de mayor que 100 se escribe entre comillas." },
    { q: "¿Cuándo es más apropiado SUMAR.SI que SUMA?", options: ["Cuando solo se deben agregar filas que cumplen un criterio", "Cuando se cuentan etiquetas", "Cuando se cambia el formato", "Cuando se buscan datos horizontalmente"], correct: 0, explain: "SUMAR.SI permite agregar importes filtrados por una condición." },
    { q: "¿Qué significa `A*` en un criterio de texto?", options: ["Texto que empieza con A", "Solo la letra A al final", "Un valor numérico negativo", "Una referencia absoluta"], correct: 0, explain: "El asterisco representa una secuencia de caracteres posteriores." },
  ] },
  { title: "Funciones para limpiar texto", level: "intermedio", goal: "Normalizar identificadores y presentar texto concatenado de forma consistente.", readings: [
    { title: "Unir textos con CONCATENAR", desc: "Construye etiquetas con piezas de información separadas.", formula: "=CONCATENAR(A2;\" - \";B2)", keyPoints: ["CONCATENAR une piezas de texto.", "El operador `&` también concatena.", "Incluye separadores explícitos para facilitar lectura."], note: "Unir códigos sin separador puede producir identificadores ambiguos.", tip: "Usa & para unir dos piezas y CONCATENAR cuando quieras enumerar varios argumentos.", analogy: "Es como unir nombre y apellido con un espacio entre ambos." },
    { title: "Extraer y medir cadenas", desc: "Extrae partes de códigos mediante posiciones conocidas.", formula: "=IZQUIERDA(A2;3)", keyPoints: ["IZQUIERDA y DERECHA extraen extremos.", "MEDIO extrae desde una posición indicada.", "LARGO cuenta caracteres, incluidos espacios."], note: "Una posición inicial equivocada puede cortar el prefijo que identifica el producto.", tip: "Cuenta primero los caracteres del patrón y prueba con un código corto.", analogy: "Es como cortar una etiqueta por una marca exacta." },
    { title: "Buscar y dar formato al texto", desc: "Localiza fragmentos y normaliza mayúsculas o presentaciones.", formula: "=HALLAR(\"-\";A2)", keyPoints: ["HALLAR devuelve una posición del texto buscado.", "MAYUSC y MINUSC normalizan capitalización.", "TEXTO controla cómo se muestra un número en una cadena."], note: "Las funciones de texto pueden devolver errores cuando el fragmento no existe.", tip: "Mantén el valor original en otra columna si necesitas auditar la transformación.", analogy: "Es como buscar una palabra dentro de una dirección impresa." },
  ], sheets: [{ title: "Identificadores de pedidos", desc: "Combina prefijos y números para crear códigos legibles.", prompt: "Escribe tienda `LIM` en A2, número 28 en B2 y crea en C2 un identificador con CONCATENAR. Resultado `LIM-28`. La función debe unir datos de celdas.", cells: { A1: "Tienda", B1: "Pedido", C1: "Código", A2: "LIM", B2: "28" }, formulas: ["C2"], solution: { C2: "=CONCATENAR(A2;\"-\";B2)" }, results: [["C2", "LIM-28"]], functionName: "CONCATENAR", objectives: ["Combinar valores de celdas sin fijar el resultado.", "Agregar un separador legible.", "Comprobar el texto final del identificador."] }], quiz: [
    { q: "¿Qué devuelve `=DERECHA(\"LIM-28\";2)`?", options: ["LIM", "28", "-2", "6"], correct: 1, explain: "DERECHA devuelve los dos caracteres del extremo derecho." },
    { q: "¿Qué problema puede causar un espacio invisible al inicio de un código?", options: ["Puede impedir coincidencias exactas", "Cambia la hoja de cálculo", "Fija las referencias", "Convierte el dato a moneda"], correct: 0, explain: "Los espacios alteran las comparaciones textuales y pueden ocultar duplicados aparentes." },
    { q: "¿Qué función conviene para extraer desde una posición intermedia?", options: ["MEDIO", "MAX", "CONTAR.SI", "ABS"], correct: 0, explain: "MEDIO extrae una cantidad de caracteres desde la posición indicada." },
    { q: "¿Cuándo usarías TEXTO?", options: ["Al incorporar un número con formato deseado en una etiqueta", "Para sumar un rango", "Para cambiar una referencia relativa", "Para crear una tabla dinámica"], correct: 0, explain: "TEXTO transforma la presentación de un valor cuando se integra en texto." },
  ] },
  { title: "Fechas para seguimiento operativo", level: "intermedio", goal: "Desglosar y calcular fechas para planificar vencimientos y periodos.", readings: [
    { title: "Fechas como valores", desc: "Comprende el almacenamiento y formato de las fechas.", formula: "=FECHA(2026;9;26)", keyPoints: ["Excel representa fechas mediante valores seriales.", "El formato cambia cómo se muestran.", "FECHA construye una fecha con año, mes y día."], note: "Una fecha importada como texto puede no responder a filtros cronológicos.", tip: "Valida el formato regional al importar fechas de otros sistemas.", analogy: "La fecha visible es una etiqueta sobre un número que Excel puede ordenar." },
    { title: "Extraer componentes de fecha", desc: "Obtén año, mes y día para agrupar eventos.", formula: "=MES(A2)", keyPoints: ["AÑO, MES y DIA extraen partes de una fecha.", "HOY y AHORA cambian con el reloj del sistema.", "DIAS permite medir la separación entre fechas."], note: "Un cálculo con HOY cambia mañana; no lo uses como valor histórico fijo.", tip: "Guarda la fecha de corte del reporte si debe poder reproducirse.", analogy: "Separar año, mes y día es como dividir una dirección postal en campos." },
    { title: "Periodos y antigüedad", desc: "Interpreta intervalos de tiempo con funciones apropiadas.", formula: "=DIAS(B2;A2)", keyPoints: ["DIAS calcula días entre fechas.", "SIFECHA se usa conceptualmente para años o meses completos.", "La unidad de periodo debe coincidir con la pregunta."], note: "Revisa cuál fecha es inicio y cuál es final para evitar intervalos negativos inesperados.", tip: "Prueba vencimientos al inicio y al final del mes.", analogy: "Un calendario de pared permite contar el tramo entre dos marcas." },
  ], sheets: [{ title: "Antigüedad de pedidos", desc: "Calcula días transcurridos desde la fecha de registro.", prompt: "Escribe la fecha serial inicial 46000 en A2 y final 46012 en B2. En C2 calcula la diferencia con resta simple (la resta de fechas está soportada). Resultado: 12 días.", cells: { A1: "Registro", B1: "Cierre", C1: "Días", A2: "46000", B2: "46012" }, formulas: ["C2"], solution: { C2: "=B2-A2" }, results: [["C2", 12]], formulaPattern: "B2\\s*-\\s*A2", objectives: ["Reconocer que fechas almacenadas como seriales se pueden restar.", "Calcular una duración en días con operadores básicos.", "Verificar el sentido del intervalo."] }], quiz: [
    { q: "¿Qué devuelve `=MES(A2)` si A2 contiene una fecha válida?", options: ["El número del mes", "El día de la semana", "El año completo", "El total de días del mes"], correct: 0, explain: "MES extrae el componente mensual de la fecha." },
    { q: "¿Qué riesgo hay al importar fechas como texto?", options: ["El orden cronológico y cálculos pueden fallar", "Excel las vuelve fórmulas absolutas", "Las fechas se borran al filtrar", "Solo se afectan los colores"], correct: 0, explain: "Excel puede no reconocer una fecha textual como valor temporal." },
    { q: "¿Qué función elegirías para calcular días entre dos fechas?", options: ["DIAS", "CONTARA", "IZQUIERDA", "SUMAR.SI"], correct: 0, explain: "DIAS calcula el intervalo de días entre dos fechas." },
    { q: "¿Por qué HOY no es adecuado para fijar una fecha histórica de corte?", options: ["Su resultado cambia con el calendario", "No puede devolver fechas", "Solo funciona en tablas", "Reemplaza los datos de entrada"], correct: 0, explain: "HOY se actualiza y hace que un reporte pasado pueda cambiar al abrirse después." },
  ] },
  { title: "Búsqueda vertical con BUSCARV", level: "intermedio", goal: "Cruzar catálogos mediante coincidencias exactas y rangos bien definidos.", readings: [
    { title: "Sintaxis de BUSCARV", desc: "Busca una clave en la primera columna y devuelve un campo relacionado.", formula: "=BUSCARV(A2;A5:C20;3;FALSO)", keyPoints: ["La clave se busca en la primera columna del rango.", "El índice de columna comienza en uno.", "FALSO solicita coincidencia exacta."], note: "Una tabla cuyo código no está en la primera columna no es adecuada para BUSCARV.", tip: "Fija el rango de búsqueda con `$` antes de copiar la fórmula.", analogy: "Es como buscar un código en el índice y leer un dato de la misma fila." },
    { title: "Errores frecuentes en búsquedas", desc: "Diagnostica columnas desplazadas y coincidencias aproximadas.", formula: "=BUSCARV(E2;$A$2:$C$20;2;FALSO)", keyPoints: ["El índice de columna debe corresponder al rango seleccionado.", "Los códigos deben tener tipos consistentes.", "Una coincidencia aproximada requiere datos ordenados."], note: "Omitir el argumento final puede generar resultados aproximados inesperados.", tip: "Para códigos e identificadores, prefiere coincidencia exacta.", analogy: "Una guía con índice mal ordenado puede llevarte a una fila vecina." },
    { title: "Verifica cruces de catálogo", desc: "Audita las claves y los valores devueltos antes de usar el reporte.", formula: "=BUSCARV(E2;$A$2:$C$20;3;FALSO)", keyPoints: ["Busca claves duplicadas antes de confiar en el primer resultado.", "Comprueba faltantes y errores de coincidencia.", "Separa catálogo y transacciones."], note: "BUSCARV devuelve la primera coincidencia y puede ocultar duplicados.", tip: "Incluye un control de códigos no encontrados en el flujo de revisión.", analogy: "Es comparar cada etiqueta de un pedido con el catálogo maestro." },
  ], sheets: [], quiz: [
    { q: "En `BUSCARV(E2;A2:C20;3;FALSO)`, ¿qué dato se devuelve?", options: ["La tercera columna de la fila coincidente", "La tercera fila del rango", "La suma de la columna C", "La coincidencia más cercana"], correct: 0, explain: "El tercer argumento indica el índice de columna que se devuelve dentro del rango." },
    { q: "¿Qué error provoca un índice de columna mayor que el ancho de la tabla?", options: ["Puede producir un error de índice", "Ordena el catálogo", "Devuelve la primera columna", "Fija la referencia"], correct: 0, explain: "El índice debe caber dentro del rango de búsqueda." },
    { q: "¿Cuándo conviene FALSO en una búsqueda de código de producto?", options: ["Cuando se requiere coincidencia exacta", "Cuando los códigos están ordenados y se acepta aproximación", "Cuando se desea sumar", "Cuando se quiere contar vacíos"], correct: 0, explain: "Los identificadores deben coincidir exactamente para evitar asignar otro producto." },
    { q: "¿Qué limitación tiene BUSCARV?", options: ["La clave debe estar en la primera columna del rango", "No devuelve texto", "Solo trabaja con fechas", "No admite rangos"], correct: 0, explain: "BUSCARV busca en la primera columna y devuelve datos hacia la derecha." },
  ] },
  { title: "Búsquedas horizontales y flexibles", level: "intermedio", goal: "Combinar índices y posiciones para búsquedas menos frágiles.", readings: [
    { title: "Búsqueda horizontal con BUSCARH", desc: "Busca en la primera fila de una tabla horizontal.", formula: "=BUSCARH(B1;B1:F3;3;FALSO)", keyPoints: ["BUSCARH busca horizontalmente en la primera fila.", "El índice identifica la fila de retorno.", "FALSO conserva coincidencia exacta."], note: "BUSCARH comparte las limitaciones de posición de BUSCARV, pero opera por filas.", tip: "Si puedes, organiza datos en columnas para facilitar análisis y filtros.", analogy: "Es recorrer un estante de izquierda a derecha y recuperar un dato de otra fila." },
    { title: "INDICE y COINCIDIR", desc: "Encuentra la posición y devuelve el dato correspondiente.", formula: "=INDICE(C2:C20;COINCIDIR(E2;A2:A20;0))", keyPoints: ["COINCIDIR devuelve una posición.", "INDICE usa esa posición para extraer un dato.", "La combinación puede buscar en cualquier dirección."], note: "Los rangos de búsqueda y retorno deben tener tamaños alineados.", tip: "Explica por separado qué encuentra COINCIDIR y qué devuelve INDICE.", analogy: "COINCIDIR encuentra el número de asiento; INDICE entrega el contenido de ese asiento." },
    { title: "Elegir una estrategia de búsqueda", desc: "Compara flexibilidad, legibilidad y mantenimiento de cada patrón.", formula: "=INDICE(B2:B10;COINCIDIR(E2;C2:C10;0))", keyPoints: ["BUSCARV es rápido de leer en tablas simples.", "INDICE+COINCIDIR admite búsquedas hacia la izquierda.", "Un rango acotado ayuda a revisar y mantener la fórmula."], note: "No uses columnas completas sin motivo en libros muy grandes.", tip: "Documenta qué columna contiene la clave y cuál el dato de salida.", analogy: "Es elegir entre un mapa simple y un índice separado que permite cambiar rutas." },
  ], sheets: [], quiz: [
    { q: "¿En qué dirección busca BUSCARH?", options: ["En la primera fila", "En la primera columna", "En diagonal", "Solo en otra hoja"], correct: 0, explain: "BUSCARH encuentra el valor en la fila superior del rango." },
    { q: "¿Qué devuelve COINCIDIR?", options: ["La posición relativa de una coincidencia", "El valor asociado directamente", "El total de la columna", "Una referencia absoluta"], correct: 0, explain: "COINCIDIR localiza la posición; INDICE puede devolver el valor correspondiente." },
    { q: "¿Por qué INDICE+COINCIDIR es más flexible que BUSCARV en algunos casos?", options: ["Puede devolver valores a la izquierda de la columna buscada", "Siempre es más rápida", "No requiere rangos", "Elimina duplicados automáticamente"], correct: 0, explain: "La posición de los rangos de búsqueda y retorno es independiente." },
    { q: "¿Qué argumento de COINCIDIR pide coincidencia exacta?", options: ["0", "1", "-1", "FALSO como índice de columna"], correct: 0, explain: "El tercer argumento 0 busca una coincidencia exacta." },
  ] },
  { title: "Errores y validación de datos", level: "intermedio", goal: "Prevenir entradas inválidas y presentar errores de búsqueda de forma controlada.", readings: [
    { title: "SI.ERROR y ESERROR", desc: "Detecta errores y ofrece resultados comprensibles al usuario.", formula: "=SI.ERROR(BUSCARV(A2;D2:E20;2;FALSO);\"No encontrado\")", keyPoints: ["SI.ERROR devuelve una alternativa cuando una fórmula falla.", "ESERROR permite evaluar si hay un error.", "No ocultes errores antes de comprender su causa."], note: "Una etiqueta amable no debe encubrir una columna equivocada o un dato ausente.", tip: "Usa una columna de control para distinguir faltantes esperados de fallos inesperados.", analogy: "Es una señal de desvío que explica qué hacer cuando no se encuentra el destino." },
    { title: "Validación y listas", desc: "Restringe entradas para mantener criterios uniformes.", formula: "=SI(B2=\"Lima\";1;0)", keyPoints: ["Las listas desplegables reducen errores de escritura.", "Los límites numéricos controlan rangos permitidos.", "La validación guía, pero también se deben revisar datos importados."], note: "Pegar datos puede saltarse controles de validación; audita los valores recibidos.", tip: "Mantén las opciones de lista en un catálogo documentado.", analogy: "Es un formulario con opciones aprobadas en vez de una caja de texto libre." },
    { title: "Diseñar controles de calidad", desc: "Define reglas para revisar consistencia antes de reportar.", formula: "=CONTAR.SI(B2:B20;\"\")", keyPoints: ["Los controles deben corresponder al riesgo del dato.", "Los valores fuera de rango requieren revisión.", "La validación no reemplaza la limpieza de datos."], note: "Un dato válido en formato puede ser incorrecto desde el punto de vista del negocio.", tip: "Incluye conteos de vacíos, duplicados y valores fuera de rango.", analogy: "Es una lista de inspección antes de enviar un pedido." },
  ], sheets: [{ title: "Resumen con función SI", desc: "Calcula un resultado de cumplimiento con control condicional.", prompt: "Ingresa metas 100, 140 y 80 en B2:B4; resultados 120, 110 y 80 en C2:C4. En D2:D4 usa SI para mostrar Cumple si resultado >= meta y Revisar en caso contrario. Resultados: Cumple, Revisar, Cumple.", cells: { A1: "Asesor", B1: "Meta", C1: "Resultado", D1: "Estado", A2: "Ana", B2: "100", C2: "120", A3: "Luis", B3: "140", C3: "110", A4: "Sol", B4: "80", C4: "80" }, formulas: ["D2", "D3", "D4"], solution: { D2: "=SI(C2>=B2;\"Cumple\";\"Revisar\")", D3: "=SI(C3>=B3;\"Cumple\";\"Revisar\")", D4: "=SI(C4>=B4;\"Cumple\";\"Revisar\")" }, results: [["D2", "Cumple"], ["D3", "Revisar"], ["D4", "Cumple"]], functionName: "SI", objectives: ["Comparar valor real contra meta.", "Mostrar un estado legible para cada fila.", "Probar límites iguales y valores por debajo."] }], quiz: [
    { q: "¿Qué devuelve SI.ERROR si su primer argumento no falla?", options: ["El resultado original", "Siempre el segundo argumento", "FALSO", "Una celda vacía"], correct: 0, explain: "SI.ERROR solo usa la alternativa cuando el primer argumento produce error." },
    { q: "¿Qué limitación tiene la validación de datos?", options: ["Pegar datos puede evadir algunas restricciones", "Impide crear listas", "Solo acepta fórmulas", "Corrige datos históricos automáticamente"], correct: 0, explain: "La validación ayuda al ingreso, pero no sustituye una auditoría de datos." },
    { q: "¿Cuándo conviene una lista desplegable?", options: ["Cuando una columna debe usar categorías consistentes", "Cuando se necesitan comentarios libres extensos", "Para reemplazar todas las fórmulas", "Para ocultar errores"], correct: 0, explain: "Una lista reduce variantes de escritura en campos categóricos." },
    { q: "¿Por qué se debe investigar un error antes de envolverlo con SI.ERROR?", options: ["Para no esconder defectos de fórmula o datos", "Porque SI.ERROR borra el libro", "Porque el error vuelve absoluta la referencia", "Para impedir la validación"], correct: 0, explain: "Controlar la presentación no corrige la causa del problema." },
  ] },
  { title: "Tablas y ordenamiento profesional", level: "avanzado", goal: "Preparar bases tabulares consistentes para análisis y reportes repetibles.", readings: [
    { title: "Convertir rangos en tablas", desc: "Crea tablas estructuradas que se amplían con nuevos registros.", formula: "=SUMA(B2:B100)", keyPoints: ["Cada columna debe tener un encabezado único.", "Ctrl+T crea una tabla con filtros.", "Las tablas se expanden cuando se agregan filas contiguas."], note: "Evita celdas combinadas y subtotales dentro del bloque de datos fuente.", tip: "Separa la base transaccional del resumen ejecutivo.", analogy: "Una tabla es un archivador que mantiene etiquetas y filtros al crecer." },
    { title: "Orden, filtros y segmentación", desc: "Explora registros sin borrar ni alterar la base fuente.", formula: "=CONTAR.SI(B2:B100;\"Lima\")", keyPoints: ["Ordenar cambia la secuencia de las filas.", "Filtrar oculta temporalmente registros que no cumplen.", "Los segmentadores ofrecen controles visuales en tablas compatibles."], note: "Ordena toda la tabla, no una sola columna aislada, para mantener cada registro íntegro.", tip: "Agrega campos de fecha y categoría consistentes para filtrar con precisión.", analogy: "Ordenar acomoda expedientes; filtrar deja a la vista solo los que cumplen." },
  ], sheets: [], quiz: [
    { q: "¿Qué ventaja aporta convertir una base en Tabla con Ctrl+T?", options: ["Filtros y expansión de rangos al añadir datos", "Elimina automáticamente los duplicados", "Crea una macro", "Sustituye las columnas por gráficos"], correct: 0, explain: "Las tablas amplían el rango y mantienen encabezados y filtros." },
    { q: "¿Qué error se comete al ordenar solo una columna de una base?", options: ["Se separan valores de sus registros", "Se borran las fórmulas", "Se crea una tabla dinámica", "Se activa validación"], correct: 0, explain: "Hay que ordenar toda la tabla para conservar juntas las columnas de cada registro." },
    { q: "¿Qué hace un filtro aplicado a una tabla?", options: ["Oculta temporalmente filas que no cumplen", "Elimina registros", "Cambia los valores almacenados", "Calcula el promedio"], correct: 0, explain: "Filtrar afecta la visualización, no borra los registros." },
    { q: "¿Por qué se evitan celdas combinadas en los datos fuente?", options: ["Dificultan ordenar, filtrar y resumir", "Impiden cambiar colores", "Aumentan la cantidad de filas", "Hacen que las fórmulas sean absolutas"], correct: 0, explain: "La estructura rectangular y consistente facilita el análisis." },
  ] },
  { title: "Formato condicional para alertas", level: "avanzado", goal: "Diseñar señales visuales que destaquen riesgos y oportunidades sin ocultar el dato.", readings: [
    { title: "Reglas y escalas de color", desc: "Aplica reglas y gradientes para priorizar valores que requieren atención.", formula: "=SI(B2<100;\"Bajo\";\"OK\")", keyPoints: ["Las reglas resaltan umbrales definidos.", "Las escalas comparan valores en un rango.", "Una regla visual no cambia el valor real."], note: "El color por sí solo no debe ser la única forma de comunicar una alerta.", tip: "Acompaña los colores con etiquetas o iconos accesibles.", analogy: "Un semáforo dirige la mirada hacia los valores que necesitan acción." },
    { title: "Barras e iconos de desempeño", desc: "Compara magnitudes con señales visuales consistentes.", formula: "=MAX(B2:B20)", keyPoints: ["Las barras muestran magnitudes relativas.", "Los conjuntos de iconos categorizan umbrales.", "Una leyenda debe explicar qué significa cada señal."], note: "Umbrales mal elegidos pueden exagerar diferencias pequeñas.", tip: "Usa escalas y colores consistentes entre reportes del mismo equipo.", analogy: "Las barras son como marcas de nivel en recipientes transparentes." },
  ], sheets: [], quiz: [
    { q: "¿Qué modifica el formato condicional?", options: ["La apariencia según una regla", "El valor de la fórmula", "El tipo de dato siempre", "El orden de los registros"], correct: 0, explain: "El formato condicional modifica la apariencia, no el contenido calculado." },
    { q: "¿Para qué sirve una escala de color?", options: ["Comparar niveles graduales en un rango", "Validar fórmulas", "Unir celdas", "Buscar texto"], correct: 0, explain: "Una escala comunica posiciones relativas entre valores." },
    { q: "¿Por qué no usar solo color para indicar riesgo?", options: ["Algunas personas no distinguen ciertos colores y el significado puede perderse", "Excel no permite colores", "Las reglas no funcionan con números", "El color cambia las fórmulas"], correct: 0, explain: "Etiquetas, iconos y contraste ayudan a comunicar la alerta con más claridad." },
    { q: "¿Cuándo convienen barras de datos?", options: ["Para comparar magnitudes en contexto", "Para reemplazar los valores numéricos", "Para hacer búsquedas verticales", "Para validar fechas"], correct: 0, explain: "Las barras ayudan a comparar visualmente sin ocultar el dato." },
  ] },
  { title: "Tablas dinámicas para análisis", level: "avanzado", goal: "Resumir bases de datos multidimensionales mediante campos y filtros.", readings: [
    { title: "Diseño de una tabla dinámica", desc: "Organiza dimensiones y métricas para responder preguntas de negocio.", formula: "=SUMAR.SI(B2:B100;\"Lima\";C2:C100)", keyPoints: ["Filas y columnas definen dimensiones.", "Valores resumen medidas como suma o conteo.", "Los encabezados únicos y los tipos consistentes evitan problemas."], note: "Una tabla dinámica resume lo que hay; no corrige registros fuente mal formados.", tip: "Actualiza la tabla después de cambiar la base.", analogy: "Es una mesa de clasificación que agrupa fichas y suma sus importes." },
    { title: "Agrupar y segmentar fechas", desc: "Resume periodos y filtra dimensiones de manera interactiva.", formula: "=SUMA(C2:C50)", keyPoints: ["Las fechas válidas pueden agruparse por mes o año.", "Los segmentadores filtran campos seleccionados.", "Los gráficos dinámicos siguen el resumen."], note: "Fechas almacenadas como texto pueden impedir una agrupación temporal correcta.", tip: "Limpia tipos y vacíos antes de insertar la tabla dinámica.", analogy: "Agrupar fechas es archivar facturas por carpetas de mes." },
    { title: "Campos calculados y gráficos", desc: "Amplía el análisis con métricas derivadas y visualizaciones conectadas.", formula: "=SI(B2=0;0;C2/B2)", keyPoints: ["Un campo calculado deriva métricas de campos existentes.", "Los gráficos dinámicos reflejan filtros y estructura.", "Verifica las definiciones de agregación."], note: "Una suma de porcentajes puede ser engañosa si la métrica requiere un promedio ponderado.", tip: "Valida un subtotal manual antes de presentar el resultado.", analogy: "Un campo calculado es una receta aplicada a cada grupo de datos." },
  ], sheets: [], quiz: [
    { q: "¿Qué área de una tabla dinámica suele contener métricas agregadas?", options: ["Valores", "Filtros de página únicamente", "Título", "Barra de estado"], correct: 0, explain: "El área Valores agrega campos con suma, conteo u otra operación." },
    { q: "¿Qué puede impedir agrupar fechas por mes?", options: ["Fechas guardadas como texto o celdas no válidas", "Un encabezado corto", "Un filtro de color", "Una fórmula SUMA"], correct: 0, explain: "La agrupación requiere datos de fecha consistentes." },
    { q: "¿Por qué revisar una agregación de porcentaje?", options: ["Una suma simple puede no representar la métrica correcta", "Los porcentajes no se permiten en Excel", "La tabla dinámica borra la base", "Los segmentadores redondean los datos"], correct: 0, explain: "La forma de agregar debe corresponder a la definición del indicador." },
    { q: "¿Qué beneficio ofrece un segmentador?", options: ["Filtrar visualmente un análisis con controles claros", "Corregir datos duplicados", "Crear fórmulas en la base", "Cambiar los valores fuente"], correct: 0, explain: "El segmentador permite explorar subconjuntos de forma interactiva." },
  ] },
  { title: "Dashboards y storytelling", level: "avanzado", goal: "Comunicar indicadores con visualizaciones claras, relevantes y orientadas a decisiones.", readings: [
    { title: "Elegir gráficos según la pregunta", desc: "Selecciona gráficos según comparación, tendencia o composición.", formula: "=MAX(B2:B12)", keyPoints: ["Barras comparan categorías.", "Líneas muestran evolución temporal.", "La visualización debe responder una pregunta concreta."], note: "Evita gráficos 3D que distorsionan comparaciones simples.", tip: "Escribe la pregunta de negocio antes de insertar un gráfico.", analogy: "Cada gráfico es una herramienta distinta, como una llave para una tuerca específica." },
    { title: "KPIs y jerarquía visual", desc: "Resume metas y resultados para acelerar la lectura ejecutiva.", formula: "=SI(B2>=C2;\"Meta lograda\";\"Pendiente\")", keyPoints: ["Un KPI necesita definición, unidad y periodo.", "La jerarquía visual guía el recorrido de lectura.", "El contexto permite interpretar un número."], note: "Un indicador sin denominador, meta o periodo puede inducir a conclusiones erróneas.", tip: "Limita cada vista a las decisiones que su audiencia debe tomar.", analogy: "Un tablero de vehículo muestra primero la información necesaria para actuar." },
    { title: "Storytelling con datos", desc: "Conecta contexto, evidencia e implicación sin exagerar causalidad.", formula: "=SI(B2>A2;\"Sube\";\"Revisar\")", keyPoints: ["El relato debe separar observación e interpretación.", "Las comparaciones requieren periodos equivalentes.", "Una recomendación debe poder rastrearse a evidencia."], note: "Una correlación en el dashboard no prueba por sí sola que una variable cause otra.", tip: "Titula los gráficos con una conclusión verificable, no solo el nombre de la métrica.", analogy: "Contar la historia es guiar a la audiencia por el mapa y señalar qué decisión importa." },
  ], sheets: [], quiz: [
    { q: "¿Qué gráfico suele comunicar mejor una tendencia mensual?", options: ["Líneas", "Circular", "Anillo 3D", "Dispersión sin ejes"], correct: 0, explain: "Las líneas muestran continuidad temporal y dirección del cambio." },
    { q: "¿Qué información mínima debe acompañar un KPI?", options: ["Definición, unidad y periodo", "Solo un color", "El nombre del archivo", "Una animación"], correct: 0, explain: "Sin definición y contexto temporal, el indicador puede interpretarse mal." },
    { q: "¿Qué hace más confiable una recomendación en un dashboard?", options: ["Trazarla a evidencia y reconocer límites", "Usar más colores", "Ocultar periodos desfavorables", "Convertir correlación en causalidad"], correct: 0, explain: "La recomendación debe poder verificarse con los datos y sus limitaciones." },
    { q: "¿Por qué conviene reducir elementos decorativos?", options: ["Para destacar la información que apoya decisiones", "Para que el archivo tenga más hojas", "Para evitar crear KPIs", "Para reemplazar la fuente de datos"], correct: 0, explain: "La claridad visual ayuda a encontrar rápidamente señales relevantes." },
  ] },
  { title: "Power Query y proyecto integrador", level: "avanzado", goal: "Diseñar un reporte profesional que integra fórmulas, limpieza, automatización y comunicación.", readings: [
    { title: "Introducción a Power Query", desc: "Importa, limpia y actualiza datos con pasos repetibles.", formula: "=SUMAR.SI(B2:B20;\"Lima\";C2:C20)", keyPoints: ["Power Query registra transformaciones reproducibles.", "La limpieza se separa de la visualización.", "La actualización reejecuta pasos sobre nuevos datos."], note: "Conserva una copia de la fuente y documenta transformaciones que cambian registros.", tip: "Nombra pasos con intención para facilitar auditoría y mantenimiento.", analogy: "Es una línea de preparación que limpia ingredientes igual cada vez." },
    { title: "Macros y proyecto analítico", desc: "Comprende macros grabadas y define un entregable reproducible.", formula: "=SI(B2>=C2;\"Cumple\";\"Revisar\")", keyPoints: ["Una macro grabada reproduce acciones repetitivas.", "Revisa seguridad y alcance antes de habilitar macros.", "Un proyecto necesita objetivo, fuente, controles y conclusión."], note: "No habilites macros de archivos desconocidos; el código puede realizar acciones no deseadas.", tip: "Deja instrucciones de actualización y valida cifras antes de compartir el reporte.", analogy: "Una macro es como una lista de pasos guardada para repetir una tarea con revisión." },
  ], sheets: [{ title: "Reporte integrador de ventas", desc: "Construye un resumen dinámico con criterios y decisiones de negocio.", prompt: "Ingresa zona y venta: Lima 120, Bogotá 90, Lima 340, Santiago 500, Lima 90. En E2 calcula el total Lima con SUMAR.SI; E3 clasifica ese total con SI como Meta lograda si >=500; E4 calcula CONTAR.SI para Lima. Resultados: 550, Meta lograda y 3. Debes usar fórmulas, no escribir resultados fijos.", cells: { A1: "Zona", B1: "Venta", A2: "Lima", B2: "120", A3: "Bogotá", B3: "90", A4: "Lima", B4: "340", A5: "Santiago", B5: "500", A6: "Lima", B6: "90", D1: "Indicador", D2: "Total Lima", D3: "Estado", D4: "Pedidos Lima" }, formulas: ["E2", "E3", "E4"], solution: { E2: "=SUMAR.SI(A2:A6;\"Lima\";B2:B6)", E3: "=SI(E2>=500;\"Meta lograda\";\"Revisar\")", E4: "=CONTAR.SI(A2:A6;\"Lima\")" }, results: [["E2", 550], ["E3", "Meta lograda"], ["E4", 3]], functionName: "SUMAR.SI", objectives: ["Resumir ventas por criterio con SUMAR.SI.", "Clasificar el indicador mediante SI.", "Contar registros de una categoría con CONTAR.SI."] }], quiz: [
    { q: "¿Qué hace Power Query en un flujo de análisis?", options: ["Registra pasos para importar y transformar datos", "Solo dibuja gráficos", "Reemplaza todas las fórmulas", "Activa macros automáticamente"], correct: 0, explain: "Power Query automatiza pasos de conexión y preparación de datos." },
    { q: "¿Qué control es importante antes de habilitar una macro?", options: ["Verificar origen y acciones del archivo", "Cambiar el color de las celdas", "Ordenar los gráficos", "Ocultar el nombre de archivo"], correct: 0, explain: "Las macros pueden ejecutar acciones, así que el origen y contenido deben ser confiables." },
    { q: "¿Qué integra mejor un proyecto de análisis profesional?", options: ["Fuente documentada, controles, indicadores y conclusión", "Solo una captura de pantalla", "Fórmulas sin etiquetas", "Gráficos sin periodo"], correct: 0, explain: "Un entregable reproducible explica de dónde vienen los datos y cómo se validan." },
    { q: "¿Por qué usar una referencia absoluta en un cálculo de impuesto?", options: ["Para conservar fija la celda de tasa al copiar", "Para cambiar la tasa cada fila", "Para impedir calcular el precio", "Para volver el dato texto"], correct: 0, explain: "La tasa común debe permanecer anclada mientras cambian las filas de productos." },
  ] },
];

export const EXCEL_MODULE_ICONS = ["📊", "🎯", "🔢", "🔍", "🧮", "📈", "🗂️", "⚡", "🧠", "🔎", "📉", "⚙️", "📋", "🤖", "🚀"];

function makeReading(spec: ReadingSpec, module: ModuleSpec, moduleIndex: number, lessonIndex: number): ExcelLesson {
  const content = `<p>${spec.desc} ${module.goal}</p><h3>Una analogía cotidiana</h3><p>${spec.analogy}</p><h3>Observa la fórmula</h3><pre>${spec.formula}</pre><ul>${spec.keyPoints.map((point) => `<li>${point}</li>`).join("")}</ul><div class="note"><b>Atención:</b> ${spec.note}</div><div class="tip"><b>Buena práctica:</b> ${spec.tip}</div>`;
  return { id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "reading", icon: "📖", xp: 20, minutes: 10, title: spec.title, desc: spec.desc, level: module.level, objectives: ["Explicar el concepto con tus palabras.", "Interpretar la fórmula de ejemplo.", "Relacionar la técnica con una decisión real."], dax: { hint: `Antes de escribir la fórmula de ${spec.title.toLowerCase()}, identifica los datos de entrada y el resultado esperado.`, explain: spec.analogy, example: "=SUMA(12;18)" }, content, keyPoints: [...spec.keyPoints] };
}

function makeSheet(spec: SheetSpec, module: ModuleSpec, moduleIndex: number, lessonIndex: number): ExcelLesson {
  const checks: ExcelCheck[] = [
    ...spec.formulas.map((ref) => ({ desc: `${ref} contiene una fórmula, no un resultado fijo.`, test: (cells: ExcelCellMap) => typeof cells[ref] === "string" && cells[ref].startsWith("=") })),
    { desc: "Los datos iniciales y etiquetas están completos.", test: (cells: ExcelCellMap) => Object.entries(spec.cells).every(([ref, value]) => String(cells[ref] ?? "").trim().toLowerCase() === value.trim().toLowerCase()) },
    ...spec.results.map(([ref, expected]) => ({ desc: `${ref} calcula ${expected}.`, test: (_cells: ExcelCellMap, values: ExcelValueMap) => typeof expected === "number" ? typeof values[ref] === "number" && Math.abs(Number(values[ref]) - expected) < 0.01 : String(values[ref] ?? "") === expected })),
    ...(spec.functionName ? [{ desc: `La fórmula usa ${spec.functionName}.`, test: (cells: ExcelCellMap) => spec.formulas.some((ref) => (cells[ref] ?? "").toLocaleUpperCase().includes(spec.functionName!.toLocaleUpperCase())) }] : []),
    ...(spec.formulaPattern ? [{ desc: "La fórmula usa la resta entre las celdas de fecha indicadas.", test: (cells: ExcelCellMap) => spec.formulas.some((ref) => new RegExp(spec.formulaPattern!, "i").test(cells[ref] ?? "")) }] : []),
  ];
  const lastModule = moduleIndex === 14;
  return { id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "sheet", icon: lastModule ? "🚀" : "💻", xp: lastModule ? 150 : module.level === "principiante" ? 50 : 60, minutes: lastModule ? 35 : module.level === "principiante" ? 18 : 20, title: spec.title, desc: spec.desc, level: module.level, objectives: [...spec.objectives], dax: { hint: "Empieza por completar las entradas; después escribe la fórmula usando referencias y revisa el valor calculado.", explain: "La hoja se comporta como un tablero de control: al cambiar una entrada, las fórmulas deben actualizar el resultado.", example: "=MAX(12;18)" }, prompt: `<p>${spec.prompt}</p><p><strong>Criterio:</strong> los resultados deben salir de fórmulas; escribirlos manualmente no supera la práctica.</p>`, initCells: {}, checks, solution: { ...spec.cells, ...spec.solution } };
}

function makeQuiz(questions: ExcelQuestion[], module: ModuleSpec, moduleIndex: number, lessonIndex: number): ExcelLesson {
  return { id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "quiz", icon: "📝", xp: moduleIndex === 14 ? 100 : 60, minutes: moduleIndex === 14 ? 15 : 10, title: moduleIndex === 14 ? "Evaluación final del curso" : `Desafío: ${module.title}`, desc: "Analiza resultados y elige un método adecuado para el caso.", level: module.level, objectives: ["Interpretar una fórmula o resultado.", "Detectar un error frecuente.", "Elegir una estrategia adecuada al caso."], dax: { hint: "Lee todos los argumentos y determina qué conjunto de datos modifica cada uno.", explain: "Como una receta, el orden y la función de cada ingrediente determinan el resultado.", example: "=REDONDEAR(12.345;1)" }, questions };
}

export const EXCEL_CURRICULUM: ExcelModule[] = specs.map((module, moduleIndex) => {
  const lessons: ExcelLesson[] = [];
  module.readings.forEach((reading) => lessons.push(makeReading(reading, module, moduleIndex, lessons.length)));
  module.sheets.forEach((sheet) => lessons.push(makeSheet(sheet, module, moduleIndex, lessons.length)));
  lessons.push(makeQuiz(module.quiz, module, moduleIndex, lessons.length));
  return { id: `m${moduleIndex + 1}`, title: module.title, level: module.level, goal: module.goal, minutes: lessons.reduce((sum, lesson) => sum + lesson.minutes, 0), lessons };
});

export function validateExcelCurriculum() {
  const readings = [3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 3, 3, 2];
  const sheets = [1, 1, 2, 2, 2, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1];
  if (EXCEL_CURRICULUM.length !== 15 || EXCEL_MODULE_ICONS.length !== 15) throw new Error("El curso Excel debe tener 15 módulos e iconos.");
  EXCEL_CURRICULUM.forEach((module, index) => {
    const expectedLevel = index < 5 ? "principiante" : index < 10 ? "intermedio" : "avanzado";
    const moduleWords = module.title.trim().split(/\s+/).length;
    if (module.id !== `m${index + 1}` || moduleWords < 3 || moduleWords > 7 || module.level !== expectedLevel || module.lessons.filter((lesson) => lesson.type === "reading").length !== readings[index] || module.lessons.filter((lesson) => lesson.type === "sheet").length !== sheets[index] || module.lessons.filter((lesson) => lesson.type === "quiz").length !== 1) throw new Error(`El módulo ${module.id} de Excel incumple el esquema solicitado.`);
    if (index >= 10 && index < 14 && module.lessons.some((lesson) => lesson.type === "sheet")) throw new Error("Los módulos 11 a 14 no deben contener laboratorios de hoja.");
    module.lessons.forEach((lesson, lessonIndex) => {
      if (lesson.id !== `m${index + 1}l${lessonIndex + 1}` || lesson.title.trim().split(/\s+/).length > 6 || lesson.level !== module.level || !lesson.dax.hint || !lesson.dax.explain || !lesson.dax.example || lesson.objectives.length < 3) throw new Error(`La actividad ${lesson.id} está incompleta.`);
      if (lesson.type === "reading" && (lesson.xp !== 20 || lesson.minutes < 8 || lesson.minutes > 12)) throw new Error(`La lectura ${lesson.id} incumple el XP o duración acordados.`);
      if (lesson.type === "sheet" && (!lesson.checks?.length || !lesson.solution || Object.keys(lesson.initCells ?? {}).length || !lesson.checks.some((check) => check.desc.toLowerCase().includes("fórmula")))) throw new Error(`El laboratorio ${lesson.id} debe iniciar vacío y comprobar una fórmula real.`);
      if (lesson.type === "sheet" && (index === 14 ? lesson.xp !== 150 || lesson.minutes !== 35 : module.level === "principiante" ? lesson.xp !== 50 || lesson.minutes < 15 || lesson.minutes > 20 : lesson.xp !== 60 || lesson.minutes < 18 || lesson.minutes > 22)) throw new Error(`El laboratorio ${lesson.id} incumple el XP o duración acordados.`);
      if (lesson.type === "sheet") {
        const values = calculateExcelSheet(lesson.solution ?? {});
        const failedChecks = lesson.checks?.filter((check) => !check.test(lesson.solution ?? {}, values)).map((check) => check.desc) ?? [];
        if (failedChecks.length) throw new Error(`La solución del laboratorio ${lesson.id} no supera: ${failedChecks.join("; ")}. Valores calculados: ${JSON.stringify(values)}.`);
      }
      if (lesson.type === "quiz" && (lesson.xp !== (index === 14 ? 100 : 60) || lesson.minutes !== (index === 14 ? 15 : 10) || lesson.questions?.some((question) => question.options.length !== 4 || question.correct < 0 || question.correct >= question.options.length))) throw new Error(`El quiz ${lesson.id} tiene opciones, XP o duración inválidos.`);
    });
  });
}

