import { evaluateDax, POWER_BI_SAMPLE_MODEL, type DaxScalar } from "@/lib/powerBiDaxEngine";

export type PowerBiLevel = "principiante" | "intermedio" | "avanzado";
export type PowerBiLessonType = "reading" | "dax" | "quiz";
export type DaxCheck = { desc: string; test: (code: string, result: DaxScalar) => boolean };
export type PowerBiQuestion = { q: string; options: string[]; correct: number; explain: string };
export type PowerBiLesson = {
  id: string; type: PowerBiLessonType; icon: string; xp: number; minutes: number; title: string; desc: string;
  level: PowerBiLevel; objectives: string[]; dax: { hint: string; explain: string; example: string };
  content?: string; keyPoints?: string[]; prompt?: string; starter?: string; checks?: DaxCheck[]; solution?: string; questions?: PowerBiQuestion[];
};
export type PowerBiModule = { id: string; title: string; minutes: number; goal: string; level: PowerBiLevel; lessons: PowerBiLesson[] };

type ReadingSpec = { title: string; desc: string; analogy: string; example: string; note: string; tip: string; points: [string, string, string] };
type LabSpec = { title: string; desc: string; prompt: string; solution: string; expected: number; functions: string[]; pattern?: RegExp; hint: string };
type ModuleSpec = { title: string; goal: string; level: PowerBiLevel; readings: ReadingSpec[]; labs: LabSpec[]; quiz: PowerBiQuestion[] };

const specs: ModuleSpec[] = [
  { title: "Fundamentos de Power BI", level: "principiante", goal: "Explicar el flujo de trabajo de BI y reconocer los componentes principales de Power BI.", readings: [
    { title: "Plataforma y flujo de BI", desc: "Conecta fuentes y convierte datos en decisiones compartibles.", analogy: "Una fábrica que recibe materias primas, las prepara y entrega productos listos para decidir.", example: "Excel de ventas → Power Query → modelo → medida Total = SUM(Ventas[Ventas]) → reporte", note: "Power BI complementa Excel para modelos consistentes y reportes compartidos; no reemplaza toda exploración local.", tip: "Antes de abrir la herramienta, define quién tomará una decisión y qué dato necesita.", points: ["Desktop construye el modelo y el informe.", "Service publica, comparte y administra actualizaciones.", "Mobile facilita consultar reportes desde dispositivos móviles."] },
    { title: "Vistas y objetos del modelo", desc: "Distingue tablas, columnas, medidas y visualizaciones.", analogy: "Como un taller: las tablas son materiales, las medidas son cálculos y los visuales son el tablero de control.", example: "Total por vendedor = SUM(Ventas[Ventas])", note: "Una columna calculada se materializa por fila; una medida responde al contexto del visual.", tip: "Usa medidas para agregaciones que deben responder a filtros.", points: ["Informe organiza visuales en páginas.", "Datos muestra filas y columnas cargadas.", "Modelo permite revisar tablas y relaciones."] },
    { title: "Primer reporte con propósito", desc: "Relaciona una pregunta de negocio con una visualización apropiada.", analogy: "Elegir un gráfico se parece a escoger el mapa correcto para el viaje.", example: "Ventas por ciudad → barras; evolución por fecha → líneas", note: "Un visual atractivo no compensa una pregunta de negocio mal definida.", tip: "Escribe la pregunta y la unidad antes de diseñar el gráfico.", points: ["Tarjetas destacan indicadores clave.", "Barras comparan categorías.", "Un .pbix guarda modelo y páginas del informe."] },
  ], labs: [], quiz: [
    { q: "¿Qué devuelve `SUM(Ventas[Ventas])` en el modelo de práctica?", options: ["4930", "6", "19", "821.67"], correct: 0, explain: "SUM agrega los seis importes de la columna Ventas." },
    { q: "¿Qué error conceptual hay al llamar medida a cada fila calculada por separado?", options: ["Confundir una agregación dinámica con una columna materializada", "Usar el nombre correcto", "Publicar el informe", "Filtrar por ciudad"], correct: 0, explain: "Las columnas se calculan por fila; las medidas se evalúan en el contexto activo." },
    { q: "¿Cuándo usarías un gráfico de líneas?", options: ["Para explicar una tendencia temporal", "Para mostrar permisos", "Para reemplazar el modelo", "Para enumerar columnas"], correct: 0, explain: "La continuidad visual de una línea ayuda a leer cambios a través del tiempo." },
    { q: "¿Qué componente se usa principalmente para compartir el informe publicado?", options: ["Power BI Service", "Bloc de notas", "Vista Modelo", "Editor DAX"], correct: 0, explain: "Service hospeda y distribuye informes y modelos publicados." },
  ] },
  { title: "Conectar y transformar datos", level: "principiante", goal: "Importar fuentes comunes y preparar datos repetiblemente con Power Query.", readings: [
    { title: "Fuentes y modos de conexión", desc: "Elige una estrategia de conexión según actualización, tamaño y latencia.", analogy: "Importar es llevar una copia al taller; DirectQuery es consultar el almacén cada vez.", example: "Excel/CSV → importar; fuente compatible con baja latencia → evaluar DirectQuery", note: "No todas las fuentes ni funciones se comportan igual en cada modo de conexión.", tip: "Documenta la fuente, credenciales y periodicidad de actualización.", points: ["Obtener datos inicia la conexión.", "Importar carga datos al modelo.", "DirectQuery consulta el origen para responder consultas."] },
    { title: "Pasos aplicados de Query", desc: "Registra limpieza y transformación como una receta actualizable.", analogy: "Una receta de cocina que se repite cuando llega una nueva caja de ingredientes.", example: "Origen → promover encabezados → cambiar tipo → quitar filas vacías → cargar", note: "Los pasos se vuelven a ejecutar; un paso que depende de una posición frágil puede fallar al refrescar.", tip: "Renombra pasos y columnas con términos que otra persona pueda mantener.", points: ["Promover encabezados da nombre a los campos.", "Cambiar tipos permite cálculos coherentes.", "Pasos aplicados conserva la secuencia de transformaciones."] },
    { title: "Calidad y forma de datos", desc: "Prepara tablas rectangulares y resuelve nulos, errores y duplicados.", analogy: "Antes de contar piezas, etiquetas cada caja y separas las dañadas.", example: "Una fila por venta; columnas: fecha, producto, ciudad, importe", note: "Quitar duplicados sin una clave clara puede borrar transacciones legítimas.", tip: "Separa hechos transaccionales de atributos descriptivos antes del modelo.", points: ["Una columna debe representar un atributo.", "Cada fila representa un registro del mismo nivel.", "Los tipos se validan antes de cargar."] },
  ], labs: [], quiz: [
    { q: "¿Qué hace Power Query en el proceso?", options: ["Conecta y transforma datos mediante pasos", "Crea permisos de RLS", "Dibuja todos los visuales", "Sustituye la tabla de hechos"], correct: 0, explain: "Power Query permite preparar datos y guardar las transformaciones." },
    { q: "¿Qué riesgo tiene borrar duplicados sin revisar la clave?", options: ["Eliminar transacciones válidas que coinciden en algunos campos", "Aumentar cardinalidad útil", "Crear medidas", "Mejorar automáticamente el modelo"], correct: 0, explain: "Dos operaciones pueden compartir atributos y ser transacciones diferentes." },
    { q: "¿Cuándo conviene Importar?", options: ["Cuando se acepta cargar una copia al modelo para analizarla", "Solo cuando se desea RLS", "Para evitar elegir tipos de datos", "Cuando no existen datos"], correct: 0, explain: "Importar suele ofrecer análisis rápido sobre datos cargados en el modelo." },
    { q: "¿Por qué asignar tipos antes de modelar?", options: ["Para que fechas y medidas se interpreten correctamente", "Para cambiar la licencia", "Para ocultar registros", "Para generar una app"], correct: 0, explain: "Los tipos correctos reducen errores en relaciones, filtros y cálculos." },
  ] },
  { title: "Modelado de datos", level: "principiante", goal: "Diseñar relaciones y dimensiones en un esquema estrella confiable.", readings: [
    { title: "Hechos y dimensiones", desc: "Separa transacciones de atributos que las describen.", analogy: "Las ventas son recibos; productos, clientes y fechas son los índices para encontrarlos.", example: "DimProducto[Id] (1) → Ventas[ProductoId] (*)", note: "Evita relacionar tablas de hechos directamente si una dimensión compartida resuelve el diseño.", tip: "Define primero el grano: qué representa exactamente una fila de hechos.", points: ["Hechos guardan eventos y métricas.", "Dimensiones describen producto, ciudad o fecha.", "El esquema estrella mejora comprensión y filtrado."] },
    { title: "Cardinalidad y dirección", desc: "Configura relaciones uno a muchos con claves consistentes.", analogy: "Un catálogo contiene cada producto una vez; muchas ventas pueden apuntar a ese producto.", example: "Productos[IdProducto] (1) → Ventas[IdProducto] (*)", note: "Relaciones muchos a muchos y filtros bidireccionales requieren justificación y pruebas.", tip: "Usa dimensiones con claves únicas y valida filas sin correspondencia.", points: ["El lado uno tiene valores únicos.", "La dimensión suele filtrar a la tabla de hechos.", "La columna relacionada debe tener tipos compatibles."] },
    { title: "Calendario y gobierno del modelo", desc: "Prepara una dimensión de fechas completa y documenta relaciones.", analogy: "Un calendario común permite comparar todos los departamentos usando las mismas fechas.", example: "Calendario[Fecha] (1) → Ventas[Fecha] (*)", note: "Fechas como texto o con vacíos impiden una inteligencia temporal confiable.", tip: "Marca la tabla calendario y oculta claves técnicas a quien construye informes.", points: ["Una tabla calendario contiene una fila por fecha.", "Se relaciona con la fecha del hecho.", "Nombres y descripciones reducen errores de uso."] },
  ], labs: [], quiz: [
    { q: "¿Qué cardinalidad suele conectar dimensión de producto con ventas?", options: ["Uno a muchos", "Muchos a uno en ambos sentidos siempre", "Cero a cero", "Sin relación"], correct: 0, explain: "Un producto puede aparecer en muchas transacciones." },
    { q: "¿Qué contiene una tabla de hechos?", options: ["Eventos como ventas y sus claves", "Solo nombres únicos de productos", "Permisos de usuarios", "Definiciones de visuales"], correct: 0, explain: "La tabla de hechos representa eventos medibles del negocio." },
    { q: "¿Por qué evitar relaciones bidireccionales innecesarias?", options: ["Pueden crear rutas de filtro ambiguas", "Impiden cualquier medida", "Cambian el idioma del modelo", "Borran dimensiones"], correct: 0, explain: "La propagación de filtros compleja dificulta predecir resultados." },
    { q: "¿Qué condición necesita la clave del lado uno?", options: ["Valores únicos", "Todos los valores vacíos", "Tipo distinto al lado muchos", "Orden descendente obligatorio"], correct: 0, explain: "La unicidad permite identificar cada fila de dimensión." },
  ] },
  { title: "DAX esencial para medidas", level: "principiante", goal: "Escribir medidas básicas de agregación y división segura sobre el modelo.", readings: [
    { title: "Sintaxis y agregaciones base", desc: "Crea medidas escalares que responden a los filtros del informe.", analogy: "Una medida es una calculadora que recibe como contexto las filas visibles.", example: "Total Cantidad = SUM(Ventas[Cantidad])", note: "Una columna suelta puede comportarse de forma distinta a una medida agregada.", tip: "Nombra la medida según la pregunta de negocio que responde.", points: ["Sintaxis: Nombre = expresión.", "Tabla[Columna] identifica un campo.", "SUM, AVERAGE, MIN y MAX agregan una columna."] },
    { title: "Conteos y valores distintos", desc: "Elige cómo contar registros, datos no vacíos o categorías únicas.", analogy: "Contar filas es contar recibos; contar ciudades distintas es contar destinos únicos.", example: "Ciudades = DISTINCTCOUNT(Ventas[Ciudad])", note: "COUNT cuenta números; COUNTA incluye valores no vacíos; COUNTROWS cuenta filas.", tip: "Formula primero la pregunta: registros, números, celdas con datos o categorías únicas.", points: ["COUNT cuenta valores numéricos.", "COUNTROWS cuenta filas de una tabla.", "DISTINCTCOUNT cuenta categorías únicas."] },
  ], labs: [{ title: "Total de ventas", desc: "Construye la medida base del reporte comercial.", prompt: "Escribe una expresión que sume `Ventas[Ventas]`. Resultado exacto esperado: 4930. La expresión debe usar SUM; no escribas el resultado literal.", solution: "SUM(Ventas[Ventas])", expected: 4930, functions: ["SUM"], pattern: /Ventas\s*\[\s*Ventas\s*\]/i, hint: "Usa la sintaxis Tabla[Columna] y piensa qué agregación responde a ‘total’." }], quiz: [
    { q: "¿Qué devuelve `SUM(Ventas[Ventas])`?", options: ["4930", "19", "6", "3"], correct: 0, explain: "SUM suma los seis importes de ventas." },
    { q: "¿Qué diferencia COUNTROWS de DISTINCTCOUNT?", options: ["Filas totales frente a valores únicos de una columna", "Son idénticas", "COUNTROWS suma; DISTINCTCOUNT promedia", "Solo cambian colores"], correct: 0, explain: "Cada función cuenta una unidad distinta: filas o valores distintos." },
    { q: "¿Qué error puede causar dividir directamente por una cantidad que puede ser cero?", options: ["Resultado o error no controlado", "Relación muchos a muchos", "Filtro de fecha", "Cambio de contexto"], correct: 0, explain: "DIVIDE permite definir una alternativa cuando el denominador es cero." },
    { q: "¿Cuándo elegirías DISTINCTCOUNT?", options: ["Para contar ciudades únicas", "Para sumar ingresos", "Para contar solo filas visibles sin columna", "Para encontrar el importe mínimo"], correct: 0, explain: "DISTINCTCOUNT cuenta valores únicos de una columna." },
  ] },
  { title: "Iteradores y contexto de fila", level: "principiante", goal: "Distinguir agregaciones directas de cálculos evaluados fila por fila.", readings: [
    { title: "SUMX frente a SUM", desc: "Decide si una medida necesita recorrer cada fila antes de agregar.", analogy: "SUM agrega precios ya calculados; SUMX calcula cada línea del recibo y luego las reúne.", example: "Unidades = SUM(Ventas[Cantidad])", note: "SUMX no es automáticamente mejor: úsalo cuando la expresión por fila sea necesaria.", tip: "Explica la unidad de cada columna antes de multiplicarlas.", points: ["SUM opera sobre una columna existente.", "SUMX recibe tabla y expresión por fila.", "La fila actual define valores de las columnas iteradas."] },
    { title: "AVERAGEX y cálculos por fila", desc: "Promedia resultados derivados de cada registro.", analogy: "Primero calcula el costo por pedido; luego calcula el promedio de esos costos.", example: "Promedio Unidades = AVERAGE(Ventas[Cantidad])", note: "AVERAGE y AVERAGEX no siempre son equivalentes si la expresión transforma cada fila.", tip: "Comprueba el resultado con pocos registros calculados a mano.", points: ["AVERAGEX evalúa una expresión por fila.", "Después promedia los resultados.", "Contexto de fila aparece durante la iteración."] },
  ], labs: [
    { title: "Facturación iterada", desc: "Calcula el valor total de unidades por venta.", prompt: "Usa SUMX sobre Ventas para sumar Cantidad multiplicada por Ventas en cada fila. Resultado exacto esperado: 12970.", solution: "SUMX(Ventas, Ventas[Cantidad] * Ventas[Ventas])", expected: 12970, functions: ["SUMX"], pattern: /Cantidad\s*\]\s*\*\s*Ventas\s*\[\s*Ventas\s*\]/i, hint: "El total facturado por línea necesita multiplicar ambos campos dentro del recorrido." },
    { title: "Promedio de unidades", desc: "Promedia unidades vendidas por fila del modelo.", prompt: "Calcula el promedio de la columna Cantidad usando AVERAGE. Resultado esperado: 19/6, aproximadamente 3.1667.", solution: "AVERAGE(Ventas[Cantidad])", expected: 19 / 6, functions: ["AVERAGE"], pattern: /Ventas\s*\[\s*Cantidad\s*\]/i, hint: "Se pide el promedio del campo existente, no una expresión derivada por fila." },
  ], quiz: [
    { q: "¿Qué devuelve `SUMX(Ventas, Ventas[Cantidad] * Ventas[Ventas])`?", options: ["12970", "4930", "19", "821.67"], correct: 0, explain: "SUMX multiplica Cantidad por Ventas en cada fila y suma los seis productos." },
    { q: "¿Qué error sería usar SUM para calcular cantidad por precio por fila?", options: ["SUM no recibe una expresión multiplicada por fila", "SUM siempre cuenta texto", "SUM crea una relación", "SUM cambia el contexto de filtro"], correct: 0, explain: "Para evaluar una expresión fila por fila se usa un iterador como SUMX." },
    { q: "¿Cuándo basta SUM en vez de SUMX?", options: ["Cuando se agrega una columna ya calculada", "Cuando se necesita multiplicar campos por fila", "Cuando se agrupa una fecha", "Cuando se crea RLS"], correct: 0, explain: "SUM es claro y eficiente cuando el valor a agregar ya existe en una columna." },
    { q: "¿Qué describe el contexto de fila?", options: ["La fila evaluada actualmente por un iterador", "Los usuarios con permiso", "Las páginas del reporte", "El orden de las relaciones"], correct: 0, explain: "Durante SUMX, cada iteración evalúa la expresión para una fila." },
  ] },
  { title: "CALCULATE y contexto de filtro", level: "intermedio", goal: "Modificar filtros de una medida y razonar sobre contexto de fila y filtro.", readings: [
    { title: "CALCULATE modifica filtros", desc: "Evalúa una expresión bajo condiciones de filtro explícitas.", analogy: "Es la misma balanza, pero seleccionas únicamente los recibos de una ciudad.", example: "CALCULATE(SUM(Ventas[Cantidad]), Ventas[Ciudad] = \"Lima\")", note: "Un filtro directo puede reemplazar el filtro previo de esa columna; comprueba la intención.", tip: "Escribe primero la medida base y añade un filtro cada vez.", points: ["CALCULATE toma expresión y filtros.", "Los filtros modifican el contexto de evaluación.", "El mismo total puede variar según visual y segmentadores."] },
    { title: "Fila y filtro en medidas", desc: "Separa la fila que itera de las restricciones visibles del informe.", analogy: "Una fila es el recibo en la mano; el filtro es el conjunto de recibos que llegaron a la mesa.", example: "CALCULATE(SUM(Ventas[Ventas]), Ventas[Ciudad] = \"Bogotá\")", note: "No confundas el contexto que aporta un visual con el contexto creado por CALCULATE.", tip: "Prueba una ciudad y compara con el total general del modelo.", points: ["Contexto de fila evalúa registros individuales.", "Contexto de filtro define filas visibles.", "CALCULATE puede modificar el contexto de filtro."] },
  ], labs: [
    { title: "Ventas filtradas por Lima", desc: "Calcula ventas de una ciudad sin modificar el modelo.", prompt: "Usa CALCULATE con SUM para sumar Ventas[Ventas] filtrando Ventas[Ciudad] = `Lima`. Resultado exacto: 1250.", solution: "CALCULATE(SUM(Ventas[Ventas]), Ventas[Ciudad] = \"Lima\")", expected: 1250, functions: ["CALCULATE", "SUM"], pattern: /Ciudad\s*=\s*"Lima"/i, hint: "Envuelve la medida base con un filtro directo de ciudad." },
    { title: "Ingresos por Santiago", desc: "Aplica dos filtros de ciudad a una misma expresión base.", prompt: "Calcula el total de la ciudad Santiago con CALCULATE y SUM. Resultado: 1580.", solution: "CALCULATE(SUM(Ventas[Ventas]), Ventas[Ciudad] = \"Santiago\")", expected: 1580, functions: ["CALCULATE", "SUM"], pattern: /Ciudad\s*=\s*"Santiago"/i, hint: "Mantén la expresión agregada separada del filtro de ciudad." },
  ], quiz: [
    { q: "¿Qué devuelve `CALCULATE(SUM(Ventas[Ventas]), Ventas[Ciudad]=\"Lima\")`?", options: ["1250", "4930", "1580", "2100"], correct: 0, explain: "CALCULATE filtra la suma a las dos filas de Lima." },
    { q: "¿Qué ocurre si CALCULATE fija Ciudad=Lima aunque el visual muestre Santiago?", options: ["La expresión usa el filtro de Lima para esa medida", "Se suman todas las ciudades", "Se elimina la tabla", "La medida se convierte en columna"], correct: 0, explain: "El filtro explícito de CALCULATE modifica el contexto para esa expresión." },
    { q: "¿Qué error común causa confundir contexto de fila y filtro?", options: ["Esperar que cada fila visual cree automáticamente una iteración", "Cambiar el formato del visual", "Crear una tabla fecha", "Importar un CSV"], correct: 0, explain: "Una medida no itera filas por sí sola; un iterador crea contexto de fila." },
    { q: "¿Cuándo usarías CALCULATE?", options: ["Cuando una expresión debe evaluarse bajo filtros modificados", "Para renombrar columnas", "Para importar archivos", "Para dibujar segmentadores"], correct: 0, explain: "CALCULATE permite alterar el contexto de filtro de una expresión." },
  ] },
  { title: "Lógica condicional DAX", level: "intermedio", goal: "Construir medidas y categorías condicionales con operadores lógicos.", readings: [
    { title: "IF, AND y OR", desc: "Expresa decisiones de negocio con una o varias condiciones.", analogy: "Una regla de acceso que deja pasar si todas o alguna de las credenciales son válidas.", example: "IF(SUM(Ventas[Ventas]) > 5000, \"Meta\", \"Seguimiento\")", note: "AND y OR tienen reglas diferentes; traduce exactamente el criterio del negocio.", tip: "Prueba límites, casos verdaderos y falsos antes de publicar una categoría.", points: ["IF elige entre resultado verdadero y falso.", "AND exige todas las condiciones.", "OR acepta al menos una condición."] },
    { title: "SWITCH y condiciones mantenibles", desc: "Organiza categorías múltiples sin encadenar demasiadas condiciones.", analogy: "Un selector de rutas que asigna una salida según la opción observada.", example: "SWITCH(Ventas[Ciudad], \"Lima\", 1, \"Santiago\", 2, 0)", note: "En medidas, el valor que compara SWITCH debe ser escalar; no pases una columna completa sin agregación.", tip: "Documenta categorías y resultado predeterminado.", points: ["SWITCH compara una expresión con alternativas.", "NOT invierte una condición.", "Un valor por defecto cubre casos no previstos."] },
  ], labs: [{ title: "Clasifica el total comercial", desc: "Asigna una prioridad usando una condición de umbral.", prompt: "Usa IF para clasificar el total de ventas: si SUM(Ventas[Ventas]) supera 4000, devuelve 1; si no, 0. Resultado esperado: 1.", solution: "IF(SUM(Ventas[Ventas]) > 4000, 1, 0)", expected: 1, functions: ["IF", "SUM"], pattern: />\s*4000/, hint: "Construye primero el total y luego decide cómo clasificarlo." }], quiz: [
    { q: "¿Qué devuelve `IF(SUM(Ventas[Ventas])>5000,1,0)`?", options: ["0", "1", "4930", "TRUE"], correct: 0, explain: "El total es 4930, no supera 5000, por eso devuelve cero." },
    { q: "¿Qué error de lógica hay en usar AND cuando bastaría cumplir una condición?", options: ["La regla puede ser demasiado restrictiva", "AND suma los valores", "AND ignora filtros", "AND elimina filas"], correct: 0, explain: "AND solo devuelve verdadero cuando todas las condiciones son verdaderas." },
    { q: "¿Cuándo preferir SWITCH?", options: ["Al asignar resultados a varias categorías discretas", "Al contar filas", "Al cambiar tipos en Power Query", "Al crear relaciones"], correct: 0, explain: "SWITCH hace más legible una selección de varios casos." },
    { q: "¿Qué hace NOT en una expresión lógica?", options: ["Invierte verdadero y falso", "Suma dos medidas", "Cuenta valores distintos", "Cambia el contexto"], correct: 0, explain: "NOT devuelve la negación lógica de su argumento." },
  ] },
  { title: "Funciones relacionales DAX", level: "intermedio", goal: "Comprender cómo las relaciones permiten recuperar atributos de dimensiones.", readings: [
    { title: "RELATED y RELATEDTABLE", desc: "Recupera atributos relacionados desde el lado adecuado de una relación.", analogy: "RELATED consulta la ficha del producto desde una venta; RELATEDTABLE reúne las ventas asociadas a un producto.", example: "RELATED(Producto[Categoria])", note: "RELATED requiere una relación válida y contexto de fila apropiado.", tip: "Prefiere un modelo estrella claro antes de añadir funciones de búsqueda.", points: ["RELATED navega hacia un valor relacionado.", "RELATEDTABLE devuelve filas relacionadas.", "La dirección depende de la relación y del contexto."] },
    { title: "LOOKUPVALUE y claves", desc: "Localiza valores con criterios explícitos y claves consistentes.", analogy: "Buscar una ficha usando un código exacto y único.", example: "LOOKUPVALUE(Productos[Nombre], Productos[Id], Ventas[IdProducto])", note: "Si más de una fila coincide con valores incompatibles, la búsqueda puede ser ambigua.", tip: "Resuelve cruces habituales con relaciones en vez de búsquedas repetidas cuando sea posible.", points: ["LOOKUPVALUE recibe columna de salida y pares de búsqueda.", "Las claves deben ser consistentes.", "USERELATIONSHIP activa una relación inactiva en una medida (conceptual)."] },
    { title: "Elegir navegación relacional", desc: "Compara relaciones, búsqueda explícita y activación de rutas inactivas.", analogy: "Una relación es un puente permanente; USERELATIONSHIP elige temporalmente otro puente ya construido.", example: "Medida por fecha de entrega: CALCULATE([Ventas], USERELATIONSHIP(...))", note: "La función no sustituye una relación ausente o una clave mal preparada.", tip: "Documenta qué fecha de negocio usa cada medida.", points: ["Las relaciones son preferibles para propagación regular.", "LOOKUPVALUE es útil en búsquedas concretas.", "USERELATIONSHIP permite usar una relación inactiva (conceptual)."] },
  ], labs: [], quiz: [
    { q: "¿Qué necesita RELATED para recuperar un atributo?", options: ["Una relación válida y contexto apropiado", "Una tabla sin claves", "Una visualización de líneas", "Una columna de fecha siempre"], correct: 0, explain: "RELATED navega una relación existente para obtener un valor relacionado." },
    { q: "¿Qué riesgo tiene LOOKUPVALUE con claves duplicadas ambiguas?", options: ["No hay una salida única confiable", "Siempre devuelve la suma", "Convierte relaciones a bidireccionales", "Elimina la tabla de hechos"], correct: 0, explain: "Una búsqueda ambigua no define con claridad un único valor de salida." },
    { q: "¿Qué modelado suele ser preferible para análisis repetidos por producto?", options: ["Relación entre dimensión Producto y hechos Ventas", "LOOKUPVALUE repetido en cada medida", "Duplicar la tabla completa", "Unir nombres en una sola columna"], correct: 0, explain: "Una relación bien definida es más mantenible para filtrar y analizar repetidamente." },
    { q: "¿Para qué sirve USERELATIONSHIP?", options: ["Activar una relación inactiva en el cálculo (conceptual)", "Crear una nueva tabla física", "Importar datos desde SQL", "Calcular un promedio"], correct: 0, explain: "Permite especificar cuál relación inactiva se usa durante una medida." },
  ] },
  { title: "Inteligencia de tiempo esencial", level: "intermedio", goal: "Diseñar medidas temporales conceptualmente correctas con una dimensión calendario.", readings: [
    { title: "Calendario marcado y completo", desc: "Prepara una dimensión de fechas continua para análisis temporal.", analogy: "Una agenda completa evita perder días sin ventas al comparar periodos.", example: "CALENDARIO[Fecha] relacionada con Ventas[Fecha]", note: "La tabla debe cubrir todo el periodo necesario y tener fechas únicas.", tip: "Marca el calendario como tabla de fechas y revisa su relación activa.", points: ["Una fila por fecha sin interrupciones.", "Atributos de año, mes y trimestre.", "Relación con el campo de fecha de hechos."] },
    { title: "Acumulados YTD", desc: "Interpreta acumulados desde el comienzo del año hasta el periodo actual.", analogy: "Un contador de kilómetros que suma el recorrido desde enero.", example: "TOTALYTD([Ventas Totales], Calendario[Fecha])", note: "La medida depende del contexto de fecha y de una tabla calendario correcta.", tip: "Compara el acumulado con los periodos visibles en una tabla antes de publicarlo.", points: ["TOTALYTD calcula año a la fecha.", "DATESYTD define fechas desde el inicio anual.", "La fecha debe estar relacionada con los hechos."] },
    { title: "Comparar año contra año", desc: "Compara periodos equivalentes y comunica variaciones con contexto.", analogy: "Comparar la misma temporada evita confundir estacionalidad con crecimiento.", example: "CALCULATE([Ventas Totales], SAMEPERIODLASTYEAR(Calendario[Fecha]))", note: "Comparar periodos incompletos contra un año completo produce conclusiones sesgadas.", tip: "Muestra periodo actual y periodo comparable junto al cambio porcentual.", points: ["SAMEPERIODLASTYEAR desplaza al mismo periodo anterior.", "Las fechas equivalentes mejoran comparación.", "La variación necesita base y periodo explícitos."] },
  ], labs: [], quiz: [
    { q: "¿Qué debe tener una tabla calendario para inteligencia de tiempo fiable?", options: ["Fechas únicas, continuas y relacionadas", "Solo meses con ventas", "Productos únicos", "Filas duplicadas por ciudad"], correct: 0, explain: "La continuidad permite comparar periodos aunque un día no tenga transacciones." },
    { q: "¿Qué significa YTD?", options: ["Acumulado desde inicio del año hasta el contexto actual", "Promedio del año anterior", "Total de un único día", "Conteo de clientes"], correct: 0, explain: "Year-to-date acumula desde el inicio anual hasta la fecha del contexto." },
    { q: "¿Qué error causa comparar un mes parcial contra un año completo?", options: ["La comparación mezcla periodos no equivalentes", "La tabla se vuelve estrella", "Se eliminan filtros", "Las fechas se convierten en texto"], correct: 0, explain: "Los periodos deben ser comparables para interpretar variaciones." },
    { q: "¿Qué función se relaciona con mismo periodo del año anterior?", options: ["SAMEPERIODLASTYEAR", "DISTINCTCOUNT", "RELATED", "SUMX"], correct: 0, explain: "SAMEPERIODLASTYEAR desplaza el conjunto de fechas al año anterior." },
  ] },
  { title: "Comparativos de tiempo avanzados", level: "intermedio", goal: "Planificar comparaciones temporales y crecimiento mensual o anual correctamente.", readings: [
    { title: "Desplazar periodos", desc: "Selecciona periodos previos para comparaciones temporales.", analogy: "Mover una ventana de calendario para comparar la misma duración en otro periodo.", example: "DATEADD(Calendario[Fecha], -1, MONTH)", note: "Desplazamientos requieren calendario continuo y contexto temporal bien definido.", tip: "Valida inicio y fin del periodo al cambiar entre granularidades.", points: ["DATEADD desplaza fechas por una unidad.", "PARALLELPERIOD devuelve periodos paralelos.", "MoM compara contra el mes inmediatamente anterior."] },
    { title: "YoY, MoM y porcentajes", desc: "Diseña medidas comparables para crecimiento y variación.", analogy: "Un velocímetro tiene sentido al compararlo con la misma unidad y tramo.", example: "DIVIDE([Ventas]-[Ventas previas], [Ventas previas], 0)", note: "Si el periodo base es cero, define una política de negocio para presentar la variación.", tip: "Presenta importe absoluto y porcentaje para que el usuario entienda la magnitud.", points: ["YoY compara con año previo.", "MoM compara con mes previo.", "El porcentaje divide cambio entre base comparable."] },
    { title: "Validar medidas temporales", desc: "Comprueba periodos, estacionalidad y filtros antes de concluir.", analogy: "Verificar que comparas temporadas equivalentes antes de juzgar un resultado.", example: "Mes actual vs mismo mes del año previo", note: "Cambios en calendario fiscal pueden requerir reglas distintas al calendario natural.", tip: "Anota supuestos fiscales y zonas horarias en el reporte.", points: ["Revisa periodos parciales.", "Comprueba filtros de calendario.", "Explica denominadores y datos ausentes."] },
  ], labs: [], quiz: [
    { q: "¿Qué comparación representa MoM?", options: ["Mes actual frente al mes previo", "Año actual frente a toda la historia", "Ventas frente a cantidad", "Ciudad frente a vendedor"], correct: 0, explain: "Month-over-month compara un periodo mensual con el inmediato anterior." },
    { q: "¿Qué riesgo existe si el denominador de una variación es cero?", options: ["El porcentaje no está definido sin una regla alternativa", "Se convierte en tabla calendario", "El filtro desaparece", "La medida devuelve siempre 100%"], correct: 0, explain: "La organización debe definir cómo comunicar crecimiento cuando no había base." },
    { q: "¿Qué hace conceptualmente DATEADD en inteligencia de tiempo?", options: ["Desplaza el conjunto de fechas por un intervalo", "Crea relaciones", "Cuenta filas", "Ordena productos"], correct: 0, explain: "DATEADD permite desplazar fechas para comparar otros periodos." },
    { q: "¿Por qué mostrar importe y porcentaje de crecimiento juntos?", options: ["El porcentaje da proporción y el importe muestra magnitud", "Para duplicar el KPI", "Para eliminar la estacionalidad", "Porque Power BI lo exige"], correct: 0, explain: "Un porcentaje alto sobre una base pequeña puede representar poco importe." },
  ] },
  { title: "Variables y tablas calculadas", level: "avanzado", goal: "Leer expresiones DAX con variables y diferenciar tablas calculadas de medidas.", readings: [
    { title: "VAR y RETURN", desc: "Nombra resultados intermedios para mejorar claridad y evitar repetición.", analogy: "Anotar subtotales antes de llegar al resultado final de una cuenta.", example: "VAR Base = SUM(Ventas[Ventas]) RETURN Base", note: "El alcance de una variable es la expresión donde se declara; no es una columna global.", tip: "Nombra variables por significado y mantén expresiones cortas.", points: ["VAR asigna nombres a valores intermedios.", "RETURN entrega el resultado final.", "Variables pueden mejorar legibilidad y evaluación repetida."] },
    { title: "Tablas calculadas y medidas", desc: "Distingue una tabla materializada de un cálculo escalar dinámico.", analogy: "Una tabla calculada es una hoja preparada al actualizar; una medida es una cuenta hecha según la pregunta actual.", example: "Tabla calculada: SUMMARIZE(Ventas, Ventas[Ciudad])", note: "Las tablas calculadas ocupan memoria y se actualizan con el modelo, no con cada clic del visual.", tip: "Prefiere medidas para resultados que deben responder dinámicamente a filtros.", points: ["Una tabla calculada devuelve estructura tabular.", "Una medida devuelve un escalar.", "SUMMARIZE/ADDCOLUMNS se enseñan aquí conceptualmente."] },
    { title: "Tablas virtuales y selección", desc: "Interpreta patrones con tablas temporales en una expresión.", analogy: "Una hoja de cálculo temporal que existe solo mientras se resuelve una pregunta.", example: "SUMMARIZE(Ventas, Ventas[Ciudad])", note: "Las tablas virtuales avanzadas requieren controlar contexto y cardinalidad.", tip: "Dibuja la estructura esperada de la tabla antes de escribir el patrón.", points: ["ADDCOLUMNS agrega expresiones a una tabla.", "SELECTCOLUMNS proyecta campos seleccionados.", "SUMMARIZE agrupa por columnas."] },
  ], labs: [], quiz: [
    { q: "¿Qué beneficio aporta VAR/RETURN?", options: ["Nombrar cálculos intermedios y devolver una expresión final", "Crear permisos", "Importar CSV", "Cambiar relaciones"], correct: 0, explain: "Las variables hacen la medida más legible y permiten reutilizar resultados." },
    { q: "¿Qué diferencia una tabla calculada de una medida?", options: ["La tabla materializa filas; la medida calcula un escalar según contexto", "No hay diferencias", "La tabla siempre es más rápida", "La medida crea relaciones"], correct: 0, explain: "Sus resultados tienen naturaleza y actualización diferentes." },
    { q: "¿Qué error de rendimiento puede causar una tabla calculada innecesaria?", options: ["Más memoria y materialización de datos", "Menos columnas", "Eliminación de contexto", "Cambio automático de licencia"], correct: 0, explain: "Las tablas calculadas ocupan espacio en el modelo." },
    { q: "¿Cuándo preferirías una medida?", options: ["Cuando el resultado debe responder a filtros del informe", "Cuando se necesita guardar filas físicas", "Para cambiar tipos en Query", "Para publicar un workspace"], correct: 0, explain: "Las medidas se evalúan dinámicamente en el contexto del visual." },
  ] },
  { title: "Optimización y rendimiento", level: "avanzado", goal: "Diagnosticar cuellos de botella y simplificar modelos DAX para usuarios reales.", readings: [
    { title: "Cardinalidad y tamaño", desc: "Reduce columnas y valores únicos innecesarios en el modelo.", analogy: "Un equipaje ligero permite que el viaje y las búsquedas sean más rápidos.", example: "Eliminar identificadores temporales que no participan en análisis", note: "No elimines campos necesarios para auditoría o relaciones sin validar dependencias.", tip: "Revisa cardinalidad y uso de cada columna antes de quitarla.", points: ["Columnas de alta cardinalidad cuestan memoria.", "Tipos correctos reducen almacenamiento.", "Oculta claves técnicas que no deben usarse en visuales."] },
    { title: "Analizar medidas y visuales", desc: "Mide la duración de consultas antes y después de un cambio.", analogy: "Un cronómetro localiza qué estación de una línea retrasa la producción.", example: "Performance Analyzer identifica visuales y consultas lentas", note: "Optimizar sin medir puede desplazar el problema en lugar de resolverlo.", tip: "Registra el escenario, filtros y tiempo antes de comparar versiones.", points: ["Performance Analyzer separa tiempos de visuales.", "Inspecciona consultas caras.", "Prueba filtros representativos del uso real."] },
    { title: "Diseñar DAX mantenible", desc: "Prioriza medidas simples y modelos claros sobre parches complejos.", analogy: "Una ruta directa suele ser mejor que añadir desvíos a una carretera mal diseñada.", example: "Preferir medida reutilizable sobre columnas calculadas redundantes", note: "Una fórmula más corta no siempre es más rápida; mide con datos representativos.", tip: "Optimiza primero relaciones y modelo, después expresiones concretas.", points: ["Evita cálculos fila a fila si existe una agregación directa.", "Reduce columnas innecesarias.", "Documenta supuestos y resultados de rendimiento."] },
  ], labs: [], quiz: [
    { q: "¿Qué mide Performance Analyzer?", options: ["Duración de visuales y consultas", "Calidad de colores", "Permisos RLS", "Número de páginas PDF"], correct: 0, explain: "Permite identificar qué elementos tardan más en responder." },
    { q: "¿Por qué puede ser costosa una columna de alta cardinalidad?", options: ["Puede aumentar memoria del modelo", "Siempre elimina filtros", "No se puede relacionar", "Cambia el idioma"], correct: 0, explain: "Muchos valores distintos suelen requerir más almacenamiento." },
    { q: "¿Qué enfoque es mejor para optimizar?", options: ["Medir, cambiar una cosa y comparar en el mismo escenario", "Reescribir todo sin medir", "Agregar columnas por si acaso", "Ocultar todos los filtros"], correct: 0, explain: "La medición controlada confirma si el cambio mejoró el rendimiento." },
    { q: "¿Por qué preferir modelo simple antes de microoptimizar una fórmula?", options: ["Relaciones y estructura afectan muchas consultas", "El DAX no importa", "Las dimensiones reducen exactitud", "Los visuales no consultan datos"], correct: 0, explain: "Un modelo eficiente beneficia múltiples medidas y visualizaciones." },
  ] },
  { title: "Visualización y dashboards profesionales", level: "avanzado", goal: "Diseñar informes narrativos que conecten indicadores con decisiones y evidencia.", readings: [
    { title: "Visual correcto y jerarquía", desc: "Selecciona visuales según comparación, tendencia y composición.", analogy: "Cada gráfico es una herramienta: una llave inglesa no reemplaza un destornillador.", example: "Ventas por vendedor: barras; evolución: líneas; KPI principal: tarjeta", note: "Demasiados visuales compiten por atención y esconden el hallazgo.", tip: "Ordena la página desde la pregunta principal hasta el detalle.", points: ["Barras comparan categorías.", "Líneas muestran tendencias.", "Tarjetas resumen indicadores principales."] },
    { title: "Interacción y navegación", desc: "Usa bookmarks, drill-through y tooltips con intención.", analogy: "Una presentación con capítulos y notas al margen para explorar evidencia.", example: "Drill-through de región a detalle de vendedor", note: "Interacciones implícitas pueden producir filtros sorpresa; pruébalas con usuarios.", tip: "Nombra bookmarks y botones para que el recorrido sea predecible.", points: ["Bookmarks guardan estados de vista.", "Drill-through navega a detalle contextual.", "Tooltips agregan contexto sin saturar la página."] },
  ], labs: [{ title: "Medida para tarjeta regional", desc: "Prepara el total de ventas filtrado para una tarjeta KPI.", prompt: "Escribe una medida para ventas de Lima usando CALCULATE y SUM. Resultado: 1250. La tarjeta debe mostrar un valor calculado, no un literal.", solution: "CALCULATE(SUM(Ventas[Ventas]), Ventas[Ciudad] = \"Lima\")", expected: 1250, functions: ["CALCULATE", "SUM"], pattern: /Ciudad\s*=\s*"Lima"/i, hint: "Combina la medida agregada con el filtro que representa la región seleccionada." }], quiz: [
    { q: "¿Qué visual suele mostrar mejor una tendencia temporal?", options: ["Líneas", "Tarjeta", "Tabla sin orden", "Dona"], correct: 0, explain: "La línea representa continuidad y cambio en el tiempo." },
    { q: "¿Para qué sirve drill-through?", options: ["Navegar desde un resumen a un detalle filtrado por contexto", "Crear roles de seguridad", "Cambiar el origen", "Calcular una suma"], correct: 0, explain: "Drill-through abre una página detallada conservando el contexto seleccionado." },
    { q: "¿Por qué jerarquizar visuales?", options: ["Para dirigir atención desde hallazgos principales al detalle", "Para ocultar datos", "Para evitar filtros", "Para aumentar tablas"], correct: 0, explain: "Una jerarquía clara ayuda a entender qué mirar primero." },
    { q: "¿Qué devuelve la medida DAX de ventas de Lima?", options: ["1250", "4930", "1580", "2100"], correct: 0, explain: "La medida aplica el filtro de Lima a la suma de ventas." },
  ] },
  { title: "Seguridad y publicación en Service", level: "avanzado", goal: "Planificar acceso seguro, actualización y distribución gobernada de informes.", readings: [
    { title: "Roles y seguridad RLS", desc: "Restringe filas visibles según roles estáticos o dinámicos.", analogy: "Cada equipo recibe una copia del registro con solo las filas que le corresponden.", example: "Filtro de rol por región; USERPRINCIPALNAME como concepto dinámico", note: "RLS no reemplaza permisos del workspace; valida ambos controles.", tip: "Prueba cada rol con la función Ver como antes de publicar.", points: ["RLS limita filas del modelo.", "Los roles estáticos contienen reglas fijas.", "Roles dinámicos pueden depender de identidad (conceptual)."] },
    { title: "Publicar y actualizar", desc: "Organiza workspaces, credenciales y programación de refresh.", analogy: "Publicar es entregar una edición; refresh es programar la llegada de datos nuevos.", example: "Workspace de producción + credencial válida + actualización diaria", note: "Un gateway es necesario para alcanzar algunas fuentes locales desde Service.", tip: "Documenta propietario, frecuencia, gateway y responsable de incidentes.", points: ["Workspace organiza contenido colaborativo.", "Credenciales habilitan actualización.", "Gateway conecta fuentes locales con el servicio (cuando aplica)."] },
    { title: "Gobierno y distribución", desc: "Distribuye apps con permisos mínimos y ciclo de vida claro.", analogy: "Una biblioteca entrega una versión aprobada y define quién puede leer o editar.", example: "App para consumidores, workspace para autores", note: "No otorgues permisos de edición amplios cuando solo se necesita lectura.", tip: "Separa desarrollo, pruebas y producción cuando el entorno lo permita.", points: ["Apps distribuyen contenido aprobado.", "Suscripciones notifican cambios.", "Gobierno evita duplicados y versiones obsoletas."] },
  ], labs: [], quiz: [
    { q: "¿Qué controla RLS?", options: ["Qué filas puede ver un usuario", "Qué color usa una página", "El número de visuales", "La licencia del archivo local"], correct: 0, explain: "Row-Level Security restringe las filas visibles según roles." },
    { q: "¿Cuándo puede necesitarse un gateway?", options: ["Para conectar Service con una fuente local", "Para crear una medida SUM", "Para ordenar una matriz", "Para escribir un quiz"], correct: 0, explain: "El gateway puede proporcionar conectividad segura a fuentes locales." },
    { q: "¿Por qué probar roles antes de publicar?", options: ["Para confirmar que cada usuario ve las filas previstas", "Para cambiar la cardinalidad", "Para acelerar Query", "Para crear columnas"], correct: 0, explain: "Probar cada rol ayuda a detectar exposición o restricción incorrecta de datos." },
    { q: "¿Qué práctica sigue el principio de mínimo privilegio?", options: ["Dar solo permisos necesarios para la tarea", "Hacer administrador a toda la organización", "Publicar sin roles", "Compartir credenciales"], correct: 0, explain: "Los permisos deben limitarse a las acciones necesarias." },
  ] },
  { title: "Proyecto integrador BI profesional", level: "avanzado", goal: "Entregar un dashboard analítico defendible con modelo, medidas, narrativa y controles.", readings: [
    { title: "Brief y evidencia del proyecto", desc: "Define una pregunta de negocio, modelo, audiencia y criterio de éxito.", analogy: "Antes de construir una casa, acuerdas quién la usará y qué necesidades debe resolver.", example: "¿Qué ciudades impulsan ingresos y cuál es el ticket medio?", note: "No confundas correlación temporal con causa sin evidencia adicional.", tip: "Especifica grano, periodo, fuentes, métricas y limitaciones en una ficha breve.", points: ["Define decisión y audiencia.", "Valida relaciones y medidas con cálculos de control.", "Presenta conclusión y supuestos."] },
  ], labs: [{ title: "KPI compuesto para ventas", desc: "Combina agregación, filtro, iteración, división y condición en una medida.", prompt: "Escribe una medida que calcule el ticket promedio de Lima: filtra Ciudad=Lima con CALCULATE, suma Ventas, divide por las unidades calculadas con SUMX(Ventas, Ventas[Cantidad]), y con IF devuelve el cociente si es mayor que cero o 0 si no. Resultado esperado: 1250/7 = 178.5714 aproximadamente. Debe usar SUM, CALCULATE, SUMX, DIVIDE e IF.", solution: "IF(DIVIDE(CALCULATE(SUM(Ventas[Ventas]), Ventas[Ciudad] = \"Lima\"), CALCULATE(SUMX(Ventas, Ventas[Cantidad]), Ventas[Ciudad] = \"Lima\"), 0) > 0, DIVIDE(CALCULATE(SUM(Ventas[Ventas]), Ventas[Ciudad] = \"Lima\"), CALCULATE(SUMX(Ventas, Ventas[Cantidad]), Ventas[Ciudad] = \"Lima\"), 0), 0)", expected: 1250 / 7, functions: ["IF", "DIVIDE", "CALCULATE", "SUM", "SUMX"], pattern: /Ciudad\s*=\s*"Lima"/i, hint: "Arma primero numerador y denominador en Lima; después protégelos con DIVIDE y finalmente clasifica el resultado." }], quiz: [
    { q: "¿Qué devuelve el KPI compuesto del proyecto para Lima?", options: ["Aproximadamente 178.57", "1250", "7", "4930"], correct: 0, explain: "El total de Lima es 1250 y las unidades son 2+5=7; 1250/7 ≈ 178.57." },
    { q: "¿Qué combinación ayuda a que el proyecto sea reproducible?", options: ["Fuente documentada, modelo validado y supuestos", "Solo una captura del dashboard", "Filtros sin nombres", "Medidas sin descripción"], correct: 0, explain: "La reproducibilidad requiere poder rastrear fuente, transformación y reglas." },
    { q: "¿Por qué incluir RLS y probarlo en el diseño de producción?", options: ["Para proteger filas por perfil y confirmar la configuración", "Para acelerar todas las medidas", "Para crear un gráfico", "Para eliminar la tabla calendario"], correct: 0, explain: "Seguridad y pruebas forman parte de una entrega BI profesional." },
    { q: "¿Qué criterio hace más sólida la conclusión de un dashboard?", options: ["Que responda al objetivo con evidencia y límites explícitos", "Que use muchos gráficos", "Que omita periodos", "Que cambie colores según el autor"], correct: 0, explain: "Una conclusión defendible conecta resultado con evidencia y reconoce supuestos." },
  ] },
];

export const POWER_BI_MODULE_ICONS = ["📊", "🔄", "🔗", "📐", "⚡", "🧮", "🎯", "🔍", "📅", "⏳", "🧠", "🚀", "📈", "🛡️", "🏆"];

function makeReading(spec: ReadingSpec, module: ModuleSpec, moduleIndex: number, lessonIndex: number): PowerBiLesson {
  const content = `<p>${spec.desc} ${module.goal}</p><h3>Una analogía cotidiana</h3><p>${spec.analogy}</p><h3>Ejemplo</h3><pre>${spec.example}</pre><ul>${spec.points.map((point) => `<li>${point}</li>`).join("")}</ul><div class="note"><b>Atención:</b> ${spec.note}</div><div class="tip"><b>Buena práctica:</b> ${spec.tip}</div>`;
  const examples = ["SUM(Ventas[Ventas])", "AVERAGE(Ventas[Cantidad])", "MIN(Ventas[Ventas])", "MAX(Ventas[Cantidad])", "COUNT(Ventas[Cantidad])", "COUNTROWS(Ventas)", "DISTINCTCOUNT(Ventas[Ciudad])", "DIVIDE(SUM(Ventas[Ventas]), COUNTROWS(Ventas), 0)", "IF(SUM(Ventas[Ventas]) > 4000, 1, 0)", "CALCULATE(SUM(Ventas[Ventas]), Ventas[Ciudad] = \"Lima\")", "SUMX(Ventas, Ventas[Cantidad] * Ventas[Ventas])", "AVERAGEX(Ventas, Ventas[Cantidad])", "SWITCH(1, 1, 10, 0)", "AND(SUM(Ventas[Ventas]) > 0, COUNTROWS(Ventas) > 0)", "OR(SUM(Ventas[Ventas]) > 5000, COUNTROWS(Ventas) > 5)", "NOT(SUM(Ventas[Ventas]) = 0)"];
  return { id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "reading", icon: "📖", xp: 20, minutes: 10, title: spec.title, desc: spec.desc, level: module.level, objectives: ["Explicar el concepto en contexto.", "Interpretar el ejemplo y sus supuestos.", "Relacionar la técnica con una decisión de negocio."], dax: { hint: `Antes de aplicar ${spec.title.toLowerCase()}, define la pregunta y el contexto de datos.`, explain: spec.analogy, example: examples[(moduleIndex * 3 + lessonIndex) % examples.length] }, content, keyPoints: [...spec.points] };
}

function makeDaxLab(spec: LabSpec, module: ModuleSpec, moduleIndex: number, lessonIndex: number): PowerBiLesson {
  const checks: DaxCheck[] = [
    ...spec.functions.map((name) => ({ desc: `Usas la función ${name}.`, test: (code: string) => new RegExp(`\\b${name}\\s*\\(`, "i").test(code) })),
    { desc: "La referencia de tabla y columna es correcta.", test: (code: string) => /Ventas\s*\[\s*(?:Ventas|Cantidad)\s*\]/i.test(code) },
    ...(spec.pattern ? [{ desc: "El patrón o filtro solicitado está presente.", test: (code: string) => spec.pattern!.test(code) }] : []),
    { desc: `El resultado calculado es ${spec.expected.toFixed(2)}.`, test: (_code: string, result: DaxScalar) => typeof result === "number" && Math.abs(result - spec.expected) < 0.01 },
  ];
  return { id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "dax", icon: moduleIndex === 14 ? "🚀" : "📐", xp: moduleIndex === 14 ? 150 : module.level === "principiante" ? 50 : module.level === "intermedio" ? 60 : 80, minutes: moduleIndex === 14 ? 35 : module.level === "principiante" ? 16 : module.level === "intermedio" ? 19 : 22, title: spec.title, desc: spec.desc, level: module.level, objectives: ["Escribir una expresión DAX con funciones autorizadas.", "Validar referencias y filtros usados.", "Interpretar el resultado en el contexto del modelo."], dax: { hint: spec.hint, explain: "Es como preparar un informe: seleccionas primero los registros relevantes y luego aplicas el cálculo adecuado.", example: "AVERAGE(Ventas[Cantidad])" }, prompt: `<p>${spec.prompt}</p><p><strong>Modelo:</strong> tabla Ventas con Producto, Ciudad, Vendedor, Ventas y Cantidad.</p>`, starter: "", checks, solution: spec.solution };
}

function makeQuiz(questions: PowerBiQuestion[], module: ModuleSpec, moduleIndex: number, lessonIndex: number): PowerBiLesson {
  return { id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "quiz", icon: "📝", xp: moduleIndex === 14 ? 100 : 60, minutes: moduleIndex === 14 ? 15 : 10, title: moduleIndex === 14 ? "Evaluación final integradora" : `Desafío: ${module.title}`, desc: "Analiza una situación y elige la solución que mantiene el modelo correcto.", level: module.level, objectives: ["Interpretar una medida o escenario.", "Detectar un error habitual.", "Justificar una decisión técnica."], dax: { hint: "Lee las opciones y piensa qué resultado debe responder a la pregunta del negocio.", explain: "Como revisar una ruta antes de partir: el objetivo define qué decisión es la adecuada.", example: "DIVIDE(SUM(Ventas[Ventas]), COUNTROWS(Ventas), 0)" }, questions };
}

export const POWER_BI_CURRICULUM: PowerBiModule[] = specs.map((module, moduleIndex) => {
  const lessons: PowerBiLesson[] = [];
  module.readings.forEach((reading) => lessons.push(makeReading(reading, module, moduleIndex, lessons.length)));
  module.labs.forEach((lab) => lessons.push(makeDaxLab(lab, module, moduleIndex, lessons.length)));
  lessons.push(makeQuiz(module.quiz, module, moduleIndex, lessons.length));
  return { id: `m${moduleIndex + 1}`, title: module.title, goal: module.goal, level: module.level, minutes: lessons.reduce((sum, lesson) => sum + lesson.minutes, 0), lessons };
});

export function validatePowerBiCurriculum() {
  const readings = [3, 3, 3, 2, 2, 2, 2, 3, 3, 3, 3, 3, 2, 3, 1];
  const labs = [0, 0, 0, 1, 2, 2, 1, 0, 0, 0, 0, 0, 1, 0, 1];
  if (POWER_BI_CURRICULUM.length !== 15 || POWER_BI_MODULE_ICONS.length !== 15) throw new Error("Power BI requiere 15 módulos y 15 iconos.");
  POWER_BI_CURRICULUM.forEach((module, index) => {
    const level = index < 5 ? "principiante" : index < 10 ? "intermedio" : "avanzado";
    if (module.level !== level || module.lessons.filter((lesson) => lesson.type === "reading").length !== readings[index] || module.lessons.filter((lesson) => lesson.type === "dax").length !== labs[index] || module.lessons.filter((lesson) => lesson.type === "quiz").length !== 1) throw new Error(`Estructura inválida en el módulo ${module.id}.`);
    module.lessons.forEach((lesson, lessonIndex) => {
      if (lesson.id !== `m${index + 1}l${lessonIndex + 1}` || lesson.level !== module.level || lesson.objectives.length < 3 || !lesson.dax.hint || !lesson.dax.explain || !lesson.dax.example) throw new Error(`Actividad incompleta: ${lesson.id}.`);
      if (lesson.type === "dax") {
        if (!lesson.checks?.length || !lesson.solution || lesson.starter !== "") throw new Error(`Laboratorio DAX incompleto: ${lesson.id}.`);
        const result = evaluateDax(lesson.solution, POWER_BI_SAMPLE_MODEL);
        const failed = lesson.checks.filter((check) => !check.test(lesson.solution ?? "", result)).map((check) => check.desc);
        if (failed.length) throw new Error(`Solución DAX inválida en ${lesson.id}: ${failed.join("; ")} (resultado ${String(result)}).`);
      }
      if (lesson.type === "quiz" && lesson.questions?.some((question) => question.options.length !== 4 || question.correct < 0 || question.correct >= question.options.length)) throw new Error(`Quiz mal formado: ${lesson.id}.`);
    });
  });
}