import type { PythonRunResult } from "@/lib/pythonRunner";

export type PythonLevel = "principiante" | "intermedio" | "avanzado";
export type PythonLessonType = "reading" | "lab" | "quiz";
export type PythonRunContext = { output: string[]; vars: Record<string, unknown>; error: string | null };
export type PythonHelpers = { run: (code: string) => Promise<PythonRunContext> };
export type PythonCheck = { desc: string; test: (code: string, ctx: PythonRunContext, helpers: PythonHelpers) => boolean | Promise<boolean> };
export type PythonQuestion = { q: string; options: string[]; correct: number; explain: string };
export type PythonLesson = {
  id: string; type: PythonLessonType; icon: string; xp: number; minutes: number; title: string; desc: string;
  level: PythonLevel; objectives: string[]; dax: { hint: string; explain: string; example: string };
  content?: string; keyPoints?: string[]; playground?: { starter: string; hint: string };
  prompt?: string; starter?: string; checks?: PythonCheck[]; solution?: string; questions?: PythonQuestion[];
};
export type PythonModule = { id: string; title: string; minutes: number; goal: string; level: PythonLevel; lessons: PythonLesson[] };

type ReadingSpec = { title: string; desc: string; analogy: string; code: string; note: string; hint: string };
type LabSpec = {
  title: string; desc: string; prompt: string; starter: string; solution: string; expected: string;
  replaceFrom: string; replaceTo: string; alternateExpected: string; pattern: string; behavior?: string;
};
type QuizSpec = { code: string; printed: string; mistake: string; reasoning: string; answer: string; distractors: [string, string, string] };
type ModuleSpec = {
  title: string; goal: string; level: PythonLevel; analogy: string; readings: ReadingSpec[]; labs: LabSpec[]; quiz: QuizSpec;
};

const specs: ModuleSpec[] = [
  {
    title: "Fundamentos de Python", level: "principiante", goal: "Escribir un programa pequeño que guarda, convierte y presenta datos con nombres claros.", analogy: "Una receta con ingredientes etiquetados", readings: [
      { title: "Instrucciones y comentarios", desc: "Muestra resultados y documenta por qué tomas una decisión.", analogy: "Como una receta: las instrucciones se ejecutan y las notas ayudan a quien cocina.", code: 'producto = "cuaderno"\nprint(producto)\n# La etiqueta aclara el dato', note: "Un comentario no cambia el resultado; úsalo para explicar una decisión, no para repetir el código.", hint: "Distingue lo que Python ejecuta de lo que solo orienta a una persona." },
      { title: "Variables y tipos básicos", desc: "Guarda texto, números y valores lógicos en variables descriptivas.", analogy: "Una variable es una caja rotulada cuyo contenido puede cambiar.", code: 'producto = "cuaderno"\nstock = 18\nagotado = False\nprint(type(stock))', note: "El signo = asigna un valor; no significa que ambos lados sean una ecuación matemática.", hint: "Observa qué tipo de valor guarda cada nombre antes de combinarlo." },
      { title: "Conversión de datos", desc: "Convierte valores explícitamente antes de usarlos en cálculos.", analogy: "Es como expresar una distancia en la misma unidad antes de sumarla.", code: 'precio_texto = "24"\nprecio = int(precio_texto)\nprint(precio + 6)', note: "Convertir texto no numérico con int provoca ValueError; valida el origen del dato.", hint: "Sigue el tipo desde su origen hasta la operación que lo necesita." },
    ], labs: [
      { title: "Resumen de una venta", desc: "Prepara una ficha legible para un pedido de una papelería.", prompt: "Calcula el importe usando cantidad y precio unitario; imprime exactamente `Total: 48` para los datos iniciales. No escribas el total a mano.", starter: 'cantidad = 4\nprecio = 12\n# Calcula e imprime el total', solution: 'cantidad = 4\nprecio = 12\ntotal = cantidad * precio\nprint(f"Total: {total}")', expected: "Total: 48", replaceFrom: "cantidad = 4", replaceTo: "cantidad = 3", alternateExpected: "Total: 36", pattern: "total\\s*=.*cantidad.*\\*.*precio" },
    ], quiz: { code: 'unidades = 3\nprint(unidades * 5)', printed: "15", mistake: "¿Qué ocurre al sumar directamente el texto \"5\" a un entero?", reasoning: "¿Por qué conviene convertir un precio que llega como texto antes de calcular?", answer: "Se produce un TypeError porque son tipos incompatibles.", distractors: ["Python convierte siempre el texto en entero.", "El programa imprime 8.", "El texto se ignora automáticamente."] },
  },
  {
    title: "Operadores y expresiones", level: "principiante", goal: "Combinar operadores y f-strings para calcular e interpretar importes correctamente.", analogy: "Una caja registradora que aplica reglas en orden", readings: [
      { title: "Aritmética y precedencia", desc: "Calcula importes usando operadores aritméticos y paréntesis claros.", analogy: "Las operaciones siguen un orden, igual que una caja aplica primero el descuento indicado.", code: 'subtotal = 4 * 15\ndescuento = 10\nprint(subtotal - descuento)', note: "Si el orden no es obvio para quien lee, agrega paréntesis aunque Python ya conozca la precedencia.", hint: "Evalúa cada operación por pasos y observa qué cambia al agruparla." },
      { title: "Comparación y lógica", desc: "Expresa reglas de negocio con comparaciones y conectores lógicos.", analogy: "Una puerta puede requerir una credencial y además estar dentro del horario.", code: 'stock = 7\nreservado = False\ndisponible = stock > 0 and not reservado\nprint(disponible)', note: "No encadenes comparaciones usando palabras como `&&`; Python emplea `and` y `or`.", hint: "Traduce cada requisito de negocio en una condición verificable." },
    ], labs: [
      { title: "Precio con descuento", desc: "Calcula una oferta para el catálogo de una tienda.", prompt: "Aplica el porcentaje indicado y presenta el importe con la etiqueta `Pagar:`. El precio cambia en las pruebas.", starter: 'precio = 80\ndescuento = 0.25\n# Calcula el precio final y muéstralo', solution: 'precio = 80\ndescuento = 0.25\nfinal = precio * (1 - descuento)\nprint(f"Pagar: {final}")', expected: "Pagar: 60.0", replaceFrom: "precio = 80", replaceTo: "precio = 40", alternateExpected: "Pagar: 30.0", pattern: "final\\s*=.*precio.*descuento" },
    ], quiz: { code: 'print(2 + 3 * 4)', printed: "14", mistake: "¿Qué error conceptual hay en escribir `edad = 18` cuando se quería comparar?", reasoning: "¿Qué condición representa que un pedido sea urgente o supere el monto mínimo?", answer: "Usar `==` en vez de `=` para comparar.", distractors: ["Usar `and` entre las dos condiciones.", "Convertir la edad a texto.", "Poner la comparación dentro de print."] },
  },
  {
    title: "Control de flujo", level: "principiante", goal: "Clasificar datos mediante condiciones ordenadas y combinadas.", analogy: "Un cruce vial con señales evaluadas en secuencia", readings: [
      { title: "Ramas if elif else", desc: "Elige una sola respuesta entre condiciones excluyentes.", analogy: "Como una ventanilla que deriva cada trámite a una fila distinta.", code: 'puntaje = 74\nif puntaje >= 80:\n    nivel = "alto"\nelif puntaje >= 60:\n    nivel = "medio"\nelse:\n    nivel = "refuerzo"\nprint(nivel)', note: "Ordena los rangos de mayor a menor para que una condición amplia no oculte las siguientes.", hint: "Prueba mentalmente los límites y revisa cuál rama se evalúa primero." },
      { title: "Condiciones compuestas", desc: "Combina pertenencia, negación y condiciones anidadas.", analogy: "Una lista de invitados y una segunda comprobación en la entrada.", code: 'rol = "editor"\nif rol in ["editor", "admin"]:\n    acceso = "permitido"\nelse:\n    acceso = "lectura"\nprint(acceso)', note: "Usa `in` para pertenencia; una condición anidada solo conviene cuando depende de otra decisión.", hint: "Separa la regla principal de las excepciones que dependen de ella." },
      { title: "Expresión condicional", desc: "Asigna un resultado entre dos alternativas sin perder claridad.", analogy: "Un rótulo reversible que depende de una única pregunta.", code: 'saldo = 22\netiqueta = "positivo" if saldo >= 0 else "deuda"\nprint(etiqueta)', note: "La forma ternaria sirve para una decisión breve, no para esconder ramas complejas.", hint: "Comprueba si ambas alternativas caben en una sola frase clara." },
    ], labs: [
      { title: "Clasificador de notas", desc: "Asigna una categoría coherente a resultados de un taller.", prompt: "Imprime `Aprobado` cuando la nota alcanza el mínimo de 11; en otro caso, imprime `Reforzar`. Generaliza al cambiar la nota.", starter: 'nota = 14\n# Decide qué mensaje corresponde', solution: 'nota = 14\nif nota >= 11:\n    print("Aprobado")\nelse:\n    print("Reforzar")', expected: "Aprobado", replaceFrom: "nota = 14", replaceTo: "nota = 8", alternateExpected: "Reforzar", pattern: "if\\s+nota\\s*>=\\s*11" },
    ], quiz: { code: 'zona = "sur"\nprint(zona in ["norte", "sur"])', printed: "True", mistake: "¿Qué suele fallar cuando se usa `if nota = 11`?", reasoning: "Si el nivel alto se evalúa antes que el medio, ¿qué riesgo hay con rangos superpuestos?", answer: "`=` asigna; la condición necesita una comparación como `==`.", distractors: ["`if` solo acepta números enteros.", "`nota` debe ser una lista.", "La condición necesita `print`."] },
  },
  {
    title: "Bucles y control repetitivo", level: "principiante", goal: "Procesar colecciones y repetir cálculos controlando cuándo continuar o salir.", analogy: "Una cinta transportadora con una regla por artículo", readings: [
      { title: "for y secuencias", desc: "Recorre cada elemento sin depender de índices innecesarios.", analogy: "Como revisar una lista de pedidos, uno por uno.", code: 'pedidos = [12, 18, 9]\nfor monto in pedidos:\n    print(monto)', note: "Si solo necesitas cada valor, recorrer la secuencia directamente suele ser más claro que contar posiciones.", hint: "Identifica qué valor toma la variable en cada vuelta." },
      { title: "while y condición", desc: "Repite una tarea mientras una condición siga siendo verdadera.", analogy: "Como llenar un tanque mientras todavía no llega al nivel marcado.", code: 'intentos = 0\nwhile intentos < 3:\n    intentos += 1\nprint(intentos)', note: "Asegúrate de que algo cambie dentro de `while`; de lo contrario, la condición puede no terminar nunca.", hint: "Localiza qué línea hace que la condición finalmente deje de cumplirse." },
      { title: "Control y else en bucles", desc: "Usa break, continue y else para expresar el resultado de una búsqueda.", analogy: "Una inspección que termina al encontrar el artículo o al revisar todo el estante.", code: 'codigos = ["A2", "B4"]\nfor codigo in codigos:\n    if codigo == "B4":\n        print("Encontrado")\n        break\nelse:\n    print("Ausente")', note: "El `else` del bucle se ejecuta si no hubo `break`, no cuando la condición del if es falsa.", hint: "Distingue terminar la secuencia normalmente de salir con break." },
    ], labs: [
      { title: "Total de pedidos", desc: "Suma las ventas diarias de una tienda.", prompt: "Recorre las ventas y calcula el total; se espera `Total: 60`. El conjunto de ventas cambiará durante la revisión.", starter: 'ventas = [10, 20, 30]\ntotal = 0\n# Recorre ventas y muestra el total', solution: 'ventas = [10, 20, 30]\ntotal = 0\nfor venta in ventas:\n    total += venta\nprint(f"Total: {total}")', expected: "Total: 60", replaceFrom: "ventas = [10, 20, 30]", replaceTo: "ventas = [5, 15]", alternateExpected: "Total: 20", pattern: "for\\s+\\w+\\s+in\\s+ventas" },
      { title: "Buscar un producto", desc: "Detén la revisión al hallar un código en inventario.", prompt: "Busca `P-7`, imprime `Disponible` si aparece y `Agotado` si no. No dependas de la posición del producto.", starter: 'codigos = ["P-2", "P-7", "P-9"]\n# Recorre la lista y detente cuando encuentres el código', solution: 'codigos = ["P-2", "P-7", "P-9"]\nfor codigo in codigos:\n    if codigo == "P-7":\n        print("Disponible")\n        break\nelse:\n    print("Agotado")', expected: "Disponible", replaceFrom: 'codigos = ["P-2", "P-7", "P-9"]', replaceTo: 'codigos = ["P-2", "P-9"]', alternateExpected: "Agotado", pattern: "for\\s+\\w+\\s+in\\s+codigos" },
    ], quiz: { code: 'for numero in range(2):\n    print(numero)', printed: "0 y luego 1", mistake: "¿Qué provoca un `while` cuya variable de control nunca cambia?", reasoning: "¿Por qué `for ... else` resulta útil al buscar sin encontrar?", answer: "Permite distinguir que se revisó toda la secuencia sin ejecutar break.", distractors: ["Se ejecuta siempre al inicio del bucle.", "Repite únicamente la última vuelta.", "Sustituye automáticamente a break."] },
  },
  {
    title: "Funciones I: primeras herramientas", level: "principiante", goal: "Diseñar funciones pequeñas que reciben datos y devuelven resultados reutilizables.", analogy: "Una máquina etiquetada que recibe ingredientes y entrega un producto", readings: [
      { title: "Definir y llamar funciones", desc: "Agrupa pasos con nombre para resolver una tarea concreta.", analogy: "Una máquina de etiquetas: le das un texto y te devuelve una versión lista.", code: 'def etiqueta(codigo):\n    return "SKU-" + codigo\n\nprint(etiqueta("24"))', note: "Definir una función no la ejecuta; hay que llamarla explícitamente.", hint: "Sigue la diferencia entre preparar una herramienta y ponerla en marcha." },
      { title: "Parámetros y valores", desc: "Recibe valores con nombres claros y usa defaults con cuidado.", analogy: "Un formulario con campos obligatorios y opciones predeterminadas.", code: 'def precio_con_envio(precio, envio=5):\n    return precio + envio\n\nprint(precio_con_envio(20))', note: "No uses listas mutables como valor predeterminado; el mismo objeto podría compartirse entre llamadas.", hint: "Pregunta qué datos pertenecen a cada llamada y cuáles son valores por defecto." },
      { title: "return frente a print", desc: "Devuelve un valor para que otra operación lo pueda reutilizar.", analogy: "Una máquina que entrega una pieza frente a un altavoz que solo anuncia el resultado.", code: 'def subtotal(precio, cantidad):\n    return precio * cantidad\n\ntotal = subtotal(8, 3)\nprint(total)', note: "`print` muestra algo; `return` entrega un resultado al código que llamó la función.", hint: "Comprueba qué valor sale de la función y si puede guardarse en otra variable." },
    ], labs: [
      { title: "Calculadora de envío", desc: "Calcula el importe total de un pedido reutilizando una función.", prompt: "Define `total_pedido(precio, cantidad)` y devuelve el cálculo. Debe imprimir `Total: 60` con los datos iniciales y funcionar con otra cantidad.", starter: 'def total_pedido(precio, cantidad):\n    # Devuelve el importe\n    pass\n\nprint(f"Total: {total_pedido(12, 5)}")', solution: 'def total_pedido(precio, cantidad):\n    return precio * cantidad\n\nprint(f"Total: {total_pedido(12, 5)}")', expected: "Total: 60", replaceFrom: 'total_pedido(12, 5)', replaceTo: 'total_pedido(12, 2)', alternateExpected: "Total: 24", pattern: "def\\s+total_pedido\\s*\\(" },
    ], quiz: { code: 'def sumar(a, b=2):\n    return a + b\nprint(sumar(5))', printed: "7", mistake: "¿Qué sucede si una función imprime un cálculo pero no usa `return`?", reasoning: "¿Por qué devolver el subtotal permite usarlo luego en un informe?", answer: "La llamada devuelve None y no entrega el cálculo a otra operación.", distractors: ["La llamada devuelve automáticamente el texto impreso.", "La función se ejecuta dos veces.", "Python convierte print en return."] },
  },
  {
    title: "Strings y texto avanzado", level: "principiante", goal: "Limpiar, separar y reconstruir texto para normalizar datos de formularios.", analogy: "Una mesa de edición que recorta y ordena etiquetas", readings: [
      { title: "Índices y slicing", desc: "Extrae porciones de texto sin modificar la cadena original.", analogy: "Como seleccionar un tramo de una cinta por sus marcas de inicio y fin.", code: 'codigo = "INV-2048"\nprint(codigo[4:])\nprint(codigo[-2:])', note: "El límite final del slice no se incluye; cuenta desde cero y prueba índices negativos.", hint: "Observa qué posiciones entran y cuáles quedan fuera del intervalo." },
      { title: "Limpiar y reemplazar", desc: "Normaliza espacios y sustituye fragmentos conocidos.", analogy: "Como borrar espacios sobrantes de una etiqueta antes de archivarla.", code: 'nombre = "  ana lopez  "\nlimpio = nombre.strip().title()\nprint(limpio)', note: "Los strings son inmutables: los métodos devuelven una nueva cadena en vez de cambiar la original.", hint: "Guarda el resultado de cada método y revisa el valor original." },
      { title: "Separar y unir texto", desc: "Transforma líneas delimitadas en partes y vuelve a ensamblarlas.", analogy: "Como separar una dirección por comas y recomponerla en otro formato.", code: 'fila = "Lima,Centro,45"\npartes = fila.split(",")\nprint(" / ".join(partes))', note: "`join` se llama sobre el separador y espera una secuencia de strings.", hint: "Piensa primero si necesitas dividir una frase o unir sus piezas." },
    ], labs: [
      { title: "Normaliza códigos", desc: "Limpia códigos de despacho ingresados con espacios accidentales.", prompt: "Elimina espacios externos, convierte el código a mayúsculas e imprime `Código: AB-19`. Debe adaptarse a otro código.", starter: 'codigo = "  ab-19  "\n# Limpia y muestra el código', solution: 'codigo = "  ab-19  "\nlimpio = codigo.strip().upper()\nprint(f"Código: {limpio}")', expected: "Código: AB-19", replaceFrom: 'codigo = "  ab-19  "', replaceTo: 'codigo = "  xy-52  "', alternateExpected: "Código: XY-52", pattern: "strip\\(\\).*upper\\(\\)|upper\\(\\).*strip\\(\\)" },
      { title: "Reordena una fila CSV", desc: "Separa y muestra los campos de un registro compacto.", prompt: "Divide el registro por comas y presenta sus campos separados por ` | `. La segunda fila de prueba usa otros datos.", starter: 'fila = "Rosa,Arequipa,activo"\n# Separa y vuelve a unir los campos', solution: 'fila = "Rosa,Arequipa,activo"\npartes = fila.split(",")\nprint(" | ".join(partes))', expected: "Rosa | Arequipa | activo", replaceFrom: 'fila = "Rosa,Arequipa,activo"', replaceTo: 'fila = "Luis,Cusco,pausa"', alternateExpected: "Luis | Cusco | pausa", pattern: "split\\(.*,.*\\).*join\\(|join\\(.*\\).*split\\(" },
    ], quiz: { code: 'codigo = "AB-19"\nprint(codigo[-2:])', printed: "19", mistake: "¿Por qué `texto.upper()` no modifica necesariamente la variable original?", reasoning: "¿Qué operación conviene primero para normalizar un nombre con espacios exteriores?", answer: "Los strings son inmutables y el método devuelve una nueva cadena.", distractors: ["upper solo acepta listas.", "Python borra la variable tras usar un método.", "Los espacios no forman parte del texto."] },
  },
  {
    title: "Listas y tuplas", level: "principiante", goal: "Elegir y transformar secuencias mutables o inmutables para administrar registros.", analogy: "Un estante que se puede reorganizar y una ficha sellada", readings: [
      { title: "Crear y recorrer listas", desc: "Organiza elementos ordenados y modifica la colección con intención.", analogy: "Una bandeja de pedidos donde puedes agregar, retirar y reordenar tarjetas.", code: 'productos = ["té", "arroz"]\nproductos.append("café")\nprint(productos)', note: "`sort` modifica la lista; `sorted` produce una nueva lista ordenada.", hint: "Distingue las operaciones que mutan la lista de las que devuelven otra." },
      { title: "Slicing y métodos útiles", desc: "Selecciona, agrega y retira elementos según una regla verificable.", analogy: "Como tomar una bandeja parcial sin desarmar el resto del inventario.", code: 'stock = [4, 7, 2, 9]\nprint(stock[1:3])\nprint(stock.pop())', note: "`pop` devuelve y elimina un elemento; si solo quieres leerlo, indexa la lista.", hint: "Antes de llamar un método, decide si deseas conservar o cambiar la colección." },
      { title: "Tuplas y desempaquetado", desc: "Agrupa valores que representan un registro que no debe cambiar.", analogy: "Una coordenada impresa: conserva sus piezas en un orden fijo.", code: 'punto = (6, 9)\nx, y = punto\nprint(x + y)', note: "Una tupla de un solo elemento necesita coma final: `(valor,)`.", hint: "Relaciona cada posición con su nombre para evitar índices confusos." },
    ], labs: [
      { title: "Reponer inventario", desc: "Actualiza y ordena las unidades de un pequeño almacén.", prompt: "Agrega el nuevo stock a las unidades existentes, ordénalas y muestra `Stock: [2, 4, 7, 8]`.", starter: 'stock = [7, 2, 4]\nnueva_unidad = 8\n# Integra y ordena el inventario', solution: 'stock = [7, 2, 4]\nnueva_unidad = 8\nstock.append(nueva_unidad)\nstock.sort()\nprint(f"Stock: {stock}")', expected: "Stock: [2, 4, 7, 8]", replaceFrom: "nueva_unidad = 8", replaceTo: "nueva_unidad = 1", alternateExpected: "Stock: [1, 2, 4, 7]", pattern: "append\\(.*\\).*sort\\(\\)|sort\\(\\).*append\\(" },
      { title: "Desempaqueta una ubicación", desc: "Lee una coordenada de almacén sin depender de índices sueltos.", prompt: "Desempaqueta fila y columna e imprime `Casilla: F3` con la tupla inicial; también debe funcionar para otra ubicación.", starter: 'ubicacion = ("F", 3)\n# Asigna sus partes y presenta la casilla', solution: 'ubicacion = ("F", 3)\nfila, columna = ubicacion\nprint(f"Casilla: {fila}{columna}")', expected: "Casilla: F3", replaceFrom: 'ubicacion = ("F", 3)', replaceTo: 'ubicacion = ("B", 8)', alternateExpected: "Casilla: B8", pattern: "\\w+\\s*,\\s*\\w+\\s*=\\s*ubicacion" },
    ], quiz: { code: 'numeros = [3, 1]\nnumeros.append(5)\nprint(len(numeros))', printed: "3", mistake: "¿Qué error aparece al usar `pop()` en una lista vacía?", reasoning: "¿Por qué una tupla puede representar mejor una coordenada fija que una lista?", answer: "La tupla comunica que esos valores no deben cambiar.", distractors: ["Una tupla siempre ocupa más espacio.", "Las listas no aceptan números.", "Una tupla ordena sus datos automáticamente."] },
  },
  {
    title: "Diccionarios y conjuntos", level: "intermedio", goal: "Modelar registros con claves y comparar colecciones sin duplicados.", analogy: "Un archivador indexado junto a una lista de invitados únicos", readings: [
      { title: "Claves y valores", desc: "Representa atributos nombrados mediante un diccionario.", analogy: "Como una ficha donde cada dato se encuentra por el nombre de su campo.", code: 'cliente = {"nombre": "Mia", "puntos": 12}\nprint(cliente.get("puntos", 0))', note: "`get` permite definir un valor alternativo cuando la clave no existe.", hint: "Elige claves estables y verifica el valor por su nombre, no por posición." },
      { title: "Recorrer y actualizar", desc: "Lee pares clave-valor y actualiza registros sin perder campos previos.", analogy: "Como corregir un campo de una ficha sin volver a escribir el expediente completo.", code: 'perfil = {"rol": "analista"}\nperfil.update({"activo": True})\nfor clave, valor in perfil.items():\n    print(clave, valor)', note: "No cambies el tamaño del diccionario mientras recorres sus elementos.", hint: "Observa el par completo para conservar el vínculo entre cada clave y su valor." },
      { title: "Conjuntos y operaciones", desc: "Elimina duplicados y encuentra intersecciones entre grupos.", analogy: "Dos listas de asistentes transformadas en credenciales únicas.", code: 'turno_a = {"Ana", "Luis"}\nturno_b = {"Luis", "Eva"}\nprint(turno_a.intersection(turno_b))', note: "Los conjuntos no mantienen un orden para mostrar resultados; no dependas de su orden de impresión.", hint: "Selecciona unión, intersección o diferencia según la pregunta del negocio." },
    ], labs: [
      { title: "Ficha de pedido", desc: "Consulta el estado y el monto de un pedido con campos nombrados.", prompt: "Usa `get` para recuperar el monto y muestra `Monto: 35`. Cambiaremos el monto en una segunda ejecución.", starter: 'pedido = {"codigo": "A-2", "monto": 35}\n# Consulta el monto sin indexar por posición', solution: 'pedido = {"codigo": "A-2", "monto": 35}\nmonto = pedido.get("monto", 0)\nprint(f"Monto: {monto}")', expected: "Monto: 35", replaceFrom: '"monto": 35', replaceTo: '"monto": 18', alternateExpected: "Monto: 18", pattern: "get\\(\\s*[\"']monto[\"']" },
      { title: "Usuarios compartidos", desc: "Encuentra integrantes presentes en dos equipos de soporte.", prompt: "Calcula la intersección de ambos equipos e imprime el usuario compartido. Los grupos cambian durante la comprobación.", starter: 'equipo_a = {"Ada", "Leo"}\nequipo_b = {"Leo", "Sol"}\n# Encuentra sus integrantes comunes', solution: 'equipo_a = {"Ada", "Leo"}\nequipo_b = {"Leo", "Sol"}\ncomunes = equipo_a.intersection(equipo_b)\nprint(sorted(comunes))', expected: "['Leo']", replaceFrom: 'equipo_a = {"Ada", "Leo"}', replaceTo: 'equipo_a = {"Ada", "Sol"}', alternateExpected: "['Sol']", pattern: "intersection\\(|&" },
    ], quiz: { code: 'ficha = {"intentos": 2}\nprint(ficha.get("puntos", 0))', printed: "0", mistake: "¿Qué evita `get(clave, valor)` cuando falta una clave?", reasoning: "Si buscas personas presentes en ambos turnos, ¿qué operación de conjunto responde mejor?", answer: "La intersección, porque conserva solo elementos compartidos.", distractors: ["La unión, porque conserva solo coincidencias.", "La diferencia, porque suma todos los valores.", "El ordenamiento, porque quita duplicados entre listas."] },
  },
  {
    title: "Funciones avanzadas II", level: "intermedio", goal: "Crear interfaces reutilizables con argumentos variables, alcance controlado y contratos documentados.", analogy: "Un mostrador que acepta pedidos de distinto tamaño", readings: [
      { title: "Argumentos variables", desc: "Agrupa cantidades variables de valores posicionales y con nombre.", analogy: "Como una caja de herramientas que recibe piezas sueltas o un kit rotulado.", code: 'def registrar(*eventos, **datos):\n    return len(eventos) + len(datos)\n\nprint(registrar("login", usuario="Sol"))', note: "`*args` reúne argumentos posicionales; `**kwargs` reúne argumentos nombrados.", hint: "Sigue cómo cada forma de argumento llega a la función y qué colección recibe." },
      { title: "Alcance y retorno múltiple", desc: "Mantén datos locales y devuelve resultados relacionados juntos.", analogy: "Una estación de trabajo conserva herramientas locales y entrega un paquete final.", code: 'def resumir(valores):\n    minimo = min(valores)\n    maximo = max(valores)\n    return minimo, maximo\n\na, b = resumir([4, 9])\nprint(a, b)', note: "Evita modificar variables globales desde una función; pasa dependencias como argumentos.", hint: "Identifica qué nombres existen solo durante la llamada y cuáles forman su resultado." },
      { title: "Contratos y docstrings", desc: "Documenta propósito, parámetros y resultado para otras personas.", analogy: "La etiqueta de una máquina explica qué recibe y qué entrega.", code: 'def area(ancho, alto):\n    """Devuelve el área de un rectángulo."""\n    return ancho * alto\n\nprint(area.__doc__)', note: "Un docstring describe el contrato observable, no narra cada línea de implementación.", hint: "Escribe lo que necesita saber alguien que usará la función sin leer su interior." },
    ], labs: [
      { title: "Total flexible", desc: "Suma montos de una caja diaria aunque cambie el número de ventas.", prompt: "Define `totalizar(*montos)`, devuelve la suma e imprime `Caja: 42`. La prueba enviará una cantidad y valores distintos.", starter: 'def totalizar(*montos):\n    # Devuelve el acumulado\n    pass\n\nprint(f"Caja: {totalizar(10, 12, 20)}")', solution: 'def totalizar(*montos):\n    return sum(montos)\n\nprint(f"Caja: {totalizar(10, 12, 20)}")', expected: "Caja: 42", replaceFrom: 'totalizar(10, 12, 20)', replaceTo: 'totalizar(5, 5)', alternateExpected: "Caja: 10", pattern: "def\\s+totalizar\\s*\\(\\s*\\*" },
      { title: "Informe nombrado", desc: "Recibe métricas opcionales nombradas para formar un resumen legible.", prompt: "Define `resumen(**metricas)` y presenta la métrica `ventas` recibida. Una segunda prueba cambia su valor.", starter: 'def resumen(**metricas):\n    # Devuelve la métrica ventas\n    pass\n\nprint(resumen(ventas=6))', solution: 'def resumen(**metricas):\n    return metricas.get("ventas", 0)\n\nprint(resumen(ventas=6))', expected: "6", replaceFrom: "resumen(ventas=6)", replaceTo: "resumen(ventas=13)", alternateExpected: "13", pattern: "def\\s+resumen\\s*\\(\\s*\\*\\*" },
    ], quiz: { code: 'def perfil(nombre, **datos):\n    return len(datos)\nprint(perfil("Iris", sede="Lima", activo=True))', printed: "2", mistake: "¿Qué nombre local se evita modificar cuando se prefiere devolver datos?", reasoning: "¿Por qué `**kwargs` ayuda a ampliar una función con opciones nombradas?", answer: "Agrupa opciones variables por nombre sin cambiar cada llamada posicional.", distractors: ["Convierte cualquier error en None.", "Ordena los argumentos alfabéticamente.", "Hace opcionales todos los parámetros existentes."] },
  },
  {
    title: "Comprensiones de colecciones", level: "intermedio", goal: "Transformar y filtrar colecciones con comprensiones claras y legibles.", analogy: "Un tamiz que selecciona y transforma piezas al pasar", readings: [
      { title: "List comprehensions", desc: "Crea listas transformadas con una expresión compacta.", analogy: "Como una línea de montaje que convierte cada pieza en un producto etiquetado.", code: 'precios = [12, 20, 8]\ncon_igv = [precio * 1.18 for precio in precios]\nprint(con_igv)', note: "Si la comprensión necesita varias condiciones complejas, usa un bucle explícito más legible.", hint: "Lee la expresión como resultado, luego recorrido y finalmente filtro." },
      { title: "Filtros en comprensiones", desc: "Selecciona datos que cumplen una condición antes de transformarlos.", analogy: "Un colador primero retiene los elementos elegibles y luego les pone una etiqueta.", code: 'edades = [16, 21, 30]\nadultos = [edad for edad in edades if edad >= 18]\nprint(adultos)', note: "El `if` al final filtra; un `if ... else` antes del `for` elige el valor producido.", hint: "Pregunta si la condición elimina elementos o elige entre dos transformaciones." },
      { title: "Comprensiones dict y set", desc: "Genera mapas y colecciones únicas desde secuencias existentes.", analogy: "Un índice que crea una ficha por artículo y conserva códigos únicos.", code: 'nombres = ["sol", "mar"]\nlongitudes = {nombre: len(nombre) for nombre in nombres}\nprint(longitudes)', note: "No sacrifiques legibilidad con comprensiones anidadas profundas.", hint: "Define claramente qué será la clave, el valor y la colección final." },
    ], labs: [
      { title: "Filtra entregas a tiempo", desc: "Selecciona identificadores de entregas que llegaron antes del límite.", prompt: "Genera una lista con valores menores o iguales a 3 e imprime `A tiempo: [1, 2, 3]`. La lista cambia durante la revisión.", starter: 'dias = [1, 4, 2, 3]\n# Filtra las entregas dentro del plazo', solution: 'dias = [1, 4, 2, 3]\na_tiempo = [dia for dia in dias if dia <= 3]\nprint(f"A tiempo: {sorted(a_tiempo)}")', expected: "A tiempo: [1, 2, 3]", replaceFrom: "dias = [1, 4, 2, 3]", replaceTo: "dias = [5, 2, 1]", alternateExpected: "A tiempo: [1, 2]", pattern: "\\[.*for\\s+\\w+\\s+in\\s+dias.*if" },
      { title: "Índice de productos", desc: "Construye un diccionario de productos y longitudes de sus códigos.", prompt: "Crea una comprensión de diccionario que calcule longitudes y muestra la longitud del segundo código. Cambiaremos el código de prueba.", starter: 'codigos = ["pan", "café"]\n# Construye un índice codigo: longitud', solution: 'codigos = ["pan", "café"]\nlongitudes = {codigo: len(codigo) for codigo in codigos}\nprint(longitudes[codigos[1]])', expected: "4", replaceFrom: 'codigos = ["pan", "café"]', replaceTo: 'codigos = ["pan", "mango"]', alternateExpected: "5", pattern: "\\{.*:\\s*len\\(.*\\)\\s+for\\s+" },
    ], quiz: { code: 'valores = [2, 5, 8]\nprint([v * 2 for v in valores if v > 3])', printed: "[10, 16]", mistake: "¿Qué riesgo tiene anidar tres comprensiones en una sola expresión?", reasoning: "¿Qué cambia entre filtrar con `if` después de `for` y elegir con `x if ... else ...` antes?", answer: "El primero descarta elementos; el segundo transforma cada elemento en una de dos opciones.", distractors: ["Ambos eliminan todos los valores falsos.", "El primero siempre devuelve un conjunto.", "El segundo solo funciona en diccionarios."] },
  },
  {
    title: "Manejo de errores", level: "intermedio", goal: "Validar entradas y recuperar errores esperables sin ocultar fallos de programación.", analogy: "Un control de calidad con protocolos de contingencia", readings: [
      { title: "Tipos de excepciones", desc: "Diferencia entradas inválidas de errores de lógica.", analogy: "Como distinguir una dirección incompleta de un vehículo averiado.", code: 'texto = "doce"\ntry:\n    cantidad = int(texto)\nexcept ValueError:\n    cantidad = 0\nprint(cantidad)', note: "Captura excepciones específicas; `except` sin tipo puede ocultar errores que sí debías corregir.", hint: "Piensa qué operación puede fallar y qué excepción concreta representa ese problema." },
      { title: "Bloques try y finally", desc: "Organiza rutas de éxito, error y limpieza garantizada.", analogy: "Un cierre que se hace aunque el trámite salga bien o requiera revisión.", code: 'try:\n    resultado = 12 / 3\nexcept ZeroDivisionError:\n    resultado = 0\nelse:\n    print("Cálculo válido")\nfinally:\n    print("Revisión final")', note: "`else` corre cuando no hubo excepción; `finally` corre tanto en éxito como en error.", hint: "Ubica la lógica normal en try, la recuperación en except y la limpieza en finally." },
      { title: "Validar y lanzar errores", desc: "Protege contratos de funciones rechazando valores fuera de rango.", analogy: "Un torniquete que detiene entradas que no cumplen el requisito.", code: 'def dividir(total, partes):\n    if partes == 0:\n        raise ValueError("partes debe ser distinto de cero")\n    return total / partes', note: "Lanza errores con mensajes accionables y valida pronto las condiciones de entrada.", hint: "Define qué valores hacen inválida una operación antes de calcular." },
    ], labs: [
      { title: "Conversión de inventario", desc: "Convierte una cantidad recibida desde una ficha de proveedor.", prompt: "Convierte el texto numérico y captura `ValueError`; ante error muestra `Dato inválido`. En la prueba alternativa el texto es `x`.", starter: 'cantidad_texto = "12"\n# Convierte con manejo explícito de ValueError\n# Muestra la cantidad cuando es válida', solution: 'cantidad_texto = "12"\ntry:\n    cantidad = int(cantidad_texto)\nexcept ValueError:\n    print("Dato inválido")\nelse:\n    print(cantidad)', expected: "12", replaceFrom: 'cantidad_texto = "12"', replaceTo: 'cantidad_texto = "x"', alternateExpected: "Dato inválido", pattern: "try\\s*:[\\s\\S]*except\\s+ValueError" },
      { title: "División protegida", desc: "Calcula unidades por caja validando un divisor no nulo.", prompt: "Define una función que lance `ValueError` cuando las cajas sean cero y captura ese caso con el mensaje `Revisar cajas`.", starter: 'unidades = 24\ncajas = 0\n# Valida el divisor y maneja ValueError', solution: 'unidades = 24\ncajas = 0\ndef por_caja(total, cantidad):\n    if cantidad == 0:\n        raise ValueError("cantidad inválida")\n    return total / cantidad\ntry:\n    print(por_caja(unidades, cajas))\nexcept ValueError:\n    print("Revisar cajas")', expected: "Revisar cajas", replaceFrom: "cajas = 0", replaceTo: "cajas = 4", alternateExpected: "6.0", pattern: "raise\\s+ValueError" },
    ], quiz: { code: 'try:\n    print(int("x"))\nexcept ValueError:\n    print("Corregir dato")', printed: "Corregir dato", mistake: "¿Por qué no conviene capturar cualquier excepción sin especificar tipo?", reasoning: "¿Qué diferencia hay entre `else` y `finally` en un bloque try?", answer: "`else` se ejecuta solo si no hubo error; `finally` siempre.", distractors: ["`else` siempre y `finally` nunca.", "Ambos se ejecutan solo con error.", "`finally` sustituye a except."] },
  },
  {
    title: "Archivos y JSON", level: "intermedio", goal: "Persistir y recuperar registros estructurados usando archivos, JSON y CSV básico.", analogy: "Un archivador con formatos de ficha acordados", readings: [
      { title: "Archivos y context managers", desc: "Abre archivos con `with` para cerrar recursos incluso ante errores.", analogy: "Como pedir prestada una sala que se libera al terminar la reunión.", code: 'with open("nota.txt", "w") as archivo:\n    archivo.write("revisado")', note: "El modo `w` reemplaza el contenido existente; usa `a` para agregar y `r` para leer.", hint: "Decide el modo antes de abrir y deja que `with` gestione el cierre." },
      { title: "Serializar datos JSON", desc: "Convierte estructuras de Python a JSON y vuelve a leerlas.", analogy: "Como empacar una ficha en una caja estándar que otros sistemas entienden.", code: 'import json\nficha = {"id": 7, "activo": True}\ntexto = json.dumps(ficha)\nprint(json.loads(texto)["id"])', note: "JSON usa `true`, `false` y `null`; Python los representa como True, False y None.", hint: "Distingue el objeto Python del texto JSON que se guarda o transmite." },
      { title: "CSV y filas simples", desc: "Interpreta registros delimitados sin perder la estructura de sus columnas.", analogy: "Como una tabla impresa donde cada coma separa una columna.", code: 'fila = "Luz,3,activo"\nnombre, visitas, estado = fila.split(",")\nprint(nombre, visitas, estado)', note: "CSV puede contener comas escapadas; para archivos reales prefiere el módulo csv.", hint: "Cuenta columnas y confirma que cada fila conserva el mismo orden." },
    ], labs: [
      { title: "Guardar resumen JSON", desc: "Serializa una ficha de stock para guardarla y volverla a consultar.", prompt: "Usa `json.dumps` y `json.loads` para guardar y recuperar unidades; imprime `Unidades: 8`. Se cambiará el dato.", starter: 'import json\nproducto = {"nombre": "té", "unidades": 8}\n# Serializa y vuelve a leer el registro', solution: 'import json\nproducto = {"nombre": "té", "unidades": 8}\ntexto = json.dumps(producto)\nrecuperado = json.loads(texto)\nprint(f"Unidades: {recuperado[\'unidades\']}")', expected: "Unidades: 8", replaceFrom: '"unidades": 8', replaceTo: '"unidades": 14', alternateExpected: "Unidades: 14", pattern: "json\\.dumps\\(.*\\).*json\\.loads\\(" },
      { title: "Persistir una nota", desc: "Escribe y lee un archivo temporal del espacio aislado.", prompt: "Guarda el estado `listo` en `estado.txt`, vuelve a abrirlo y muestra `Estado: listo`. La prueba cambiará el estado.", starter: 'estado = "listo"\n# Guarda y lee el estado con context managers', solution: 'estado = "listo"\nwith open("estado.txt", "w") as archivo:\n    archivo.write(estado)\nwith open("estado.txt", "r") as archivo:\n    leido = archivo.read()\nprint(f"Estado: {leido}")', expected: "Estado: listo", replaceFrom: 'estado = "listo"', replaceTo: 'estado = "pausado"', alternateExpected: "Estado: pausado", pattern: "with\\s+open\\(.*as\\s+\\w+" },
    ], quiz: { code: 'import json\nprint(json.loads(json.dumps({"ok": True}))["ok"])', printed: "True", mistake: "¿Qué riesgo tiene abrir un archivo con `w` cuando se quería conservar su contenido?", reasoning: "¿Por qué se usa `with open(...)` en vez de olvidar cerrar el archivo?", answer: "El context manager garantiza el cierre del recurso al salir del bloque.", distractors: ["with convierte cualquier archivo en JSON.", "open con w agrega sin reemplazar.", "El archivo queda abierto para acelerar otras sesiones."] },
  },
  {
    title: "Programación funcional en Python", level: "intermedio", goal: "Transformar datos con funciones de orden superior y operaciones funcionales legibles.", analogy: "Una línea de preparación que transforma cada ingrediente", readings: [
      { title: "Funciones de orden superior", desc: "Pasa una función como dato para reutilizar una transformación.", analogy: "Como entregar una regla de clasificación a una máquina que procesa fichas.", code: 'def aplicar(regla, valores):\n    return [regla(valor) for valor in valores]\n\nprint(aplicar(abs, [-3, 5]))', note: "Una función de orden superior recibe o devuelve funciones; mantenla simple y explícita.", hint: "Identifica dónde se pasa la regla y dónde se aplica a cada valor." },
      { title: "map y filter", desc: "Transforma o selecciona elementos de un iterable.", analogy: "Un filtro separa pedidos; una estación posterior cambia el formato de los aprobados.", code: 'precios = [10, 18, 25]\nmayores = list(filter(lambda x: x > 12, precios))\nprint(mayores)', note: "En Python moderno, una comprensión suele ser más legible si la transformación cabe en una expresión clara.", hint: "Elige filter para selección y map para transformar cada elemento." },
      { title: "Lambda y reducción", desc: "Usa funciones breves donde una operación pequeña mejora la intención.", analogy: "Una etiqueta corta en una cinta transportadora que no necesita un manual.", code: 'from functools import reduce\nvalores = [2, 3, 4]\ntotal = reduce(lambda a, b: a + b, valores)\nprint(total)', note: "Prefiere `sum` para sumar; reserva `reduce` para acumulaciones que no tienen builtin más claro.", hint: "Antes de usar lambda, comprueba si una función con nombre sería más comprensible." },
    ], labs: [
      { title: "Filtra alertas", desc: "Selecciona temperaturas sobre el umbral de revisión.", prompt: "Filtra las temperaturas mayores a 30 e imprime la lista resultante; se probará con otras mediciones.", starter: 'temperaturas = [24, 33, 29, 38]\n# Selecciona mediciones que superan 30', solution: 'temperaturas = [24, 33, 29, 38]\nalertas = list(filter(lambda valor: valor > 30, temperaturas))\nprint(alertas)', expected: "[33, 38]", replaceFrom: "temperaturas = [24, 33, 29, 38]", replaceTo: "temperaturas = [31, 20, 40]", alternateExpected: "[31, 40]", pattern: "filter\\(" },
      { title: "Normaliza códigos", desc: "Transforma importes con una regla simple reutilizable.", prompt: "Aplica `abs` a cada ajuste de inventario y presenta la lista. Cambiaremos las entradas para comprobar la transformación.", starter: 'ajustes = [-2, 5, -7]\n# Transforma cada ajuste a su magnitud', solution: 'ajustes = [-2, 5, -7]\nmagnitudes = list(map(abs, ajustes))\nprint(magnitudes)', expected: "[2, 5, 7]", replaceFrom: "ajustes = [-2, 5, -7]", replaceTo: "ajustes = [-4, 3]", alternateExpected: "[4, 3]", pattern: "map\\(\\s*abs" },
    ], quiz: { code: 'datos = [1, 4, 6]\nprint(list(filter(lambda x: x > 3, datos)))', printed: "[4, 6]", mistake: "¿Por qué `sum(valores)` suele ser preferible a `reduce` para sumar?", reasoning: "¿Qué diferencia práctica hay entre `map` y `filter`?", answer: "map transforma cada elemento y filter conserva los que cumplen una condición.", distractors: ["map filtra y filter ordena.", "map solo opera con diccionarios.", "filter transforma todos los elementos en texto."] },
  },
  {
    title: "Módulos, paquetes y entornos", level: "intermedio", goal: "Organizar código reutilizable con imports, puntos de entrada, metadatos y entornos aislados.", analogy: "Una caja de herramientas compartida con instrucciones de uso", readings: [
      { title: "Importar de forma clara", desc: "Importa módulos y nombres explícitos para evitar colisiones.", analogy: "Como pedir una herramienta concreta en vez de vaciar todo el almacén.", code: 'import math\nradio = 3\nprint(math.pi * radio ** 2)', note: "Evita `from modulo import *`; dificulta saber de dónde viene cada nombre.", hint: "Deja visible el origen de las herramientas que usa el archivo." },
      { title: "Módulo como programa", desc: "Separa funciones reutilizables de la ejecución directa del script.", analogy: "Un manual que puedes consultar o ejecutar como una lista de pasos.", code: 'def mensaje():\n    return "listo"\n\nif __name__ == "__main__":\n    print(mensaje())', note: "El guard evita ejecutar ejemplos al importar un módulo desde otro programa.", hint: "Distingue cargar definiciones de iniciar el flujo principal." },
      { title: "Paquetes y entornos", desc: "Agrupa módulos, declara metadatos en `pyproject.toml` y aísla dependencias por proyecto.", analogy: "Cajas separadas para que las herramientas de un proyecto no se mezclen con otro.", code: 'manifest = {"name": "inventario", "version": "0.1.0"}\nprint(manifest["name"])\n# pyproject.toml declara metadatos del paquete\n# python -m venv .venv', note: "El archivo `pyproject.toml` declara nombre y versión; el entorno virtual separa dependencias. Para distribuir, documenta cómo instalar y construir el paquete.", hint: "Piensa qué archivos pertenecen al paquete y qué metadatos necesita otra persona para instalarlo." },
    ], labs: [
      { title: "Módulo de precios", desc: "Expón una función reutilizable para calcular el precio final.", prompt: "Organiza una función `con_igv` y úsala para calcular 118 desde 100 con tasa 0.18. Cambiará el precio base.", starter: 'def con_igv(base, tasa=0.18):\n    # Devuelve el precio con impuesto\n    pass\n\nprint(con_igv(100))', solution: 'def con_igv(base, tasa=0.18):\n    return base * (1 + tasa)\n\nprint(con_igv(100))', expected: "118.0", replaceFrom: "con_igv(100)", replaceTo: "con_igv(50)", alternateExpected: "59.0", pattern: "def\\s+con_igv\\s*\\(" },
    ], quiz: { code: 'import math\nprint(math.ceil(2.1))', printed: "3", mistake: "¿Qué problema evita `if __name__ == \"__main__\"`?", reasoning: "¿Por qué crear un entorno virtual distinto para cada proyecto?", answer: "Evita mezclar versiones y dependencias entre proyectos.", distractors: ["Permite importar cualquier nombre global.", "Hace que Python ejecute el archivo más rápido.", "Reemplaza la estructura de paquetes."] },
  },
  {
    title: "POO I: clases y objetos", level: "avanzado", goal: "Modelar entidades con estado e interfaces explícitas mediante clases y métodos.", analogy: "Un plano que permite fabricar registros consistentes", readings: [
      { title: "Clases e instancias", desc: "Define un plano y crea objetos con estado propio.", analogy: "Un molde define la forma; cada pieza fabricada conserva sus propios datos.", code: 'class Producto:\n    def __init__(self, nombre, precio):\n        self.nombre = nombre\n        self.precio = precio\n\nitem = Producto("taza", 18)\nprint(item.nombre)', note: "`self` refiere a la instancia actual; los atributos de instancia pertenecen a cada objeto.", hint: "Separa el plano de clase del estado guardado por cada instancia." },
      { title: "Métodos y representación", desc: "Expón operaciones y representaciones legibles de tus objetos.", analogy: "Un objeto tiene un comportamiento público y una etiqueta útil para reconocerlo.", code: 'class Lote:\n    def __init__(self, codigo):\n        self.codigo = codigo\n    def __str__(self):\n        return f"Lote {self.codigo}"\n\nprint(Lote("X4"))', note: "`__str__` es presentación para personas; `__repr__` ayuda a inspección y depuración.", hint: "Define qué información hace útil mostrar el objeto en cada contexto." },
      { title: "Encapsular invariantes", desc: "Protege reglas del dominio usando métodos que validan cambios.", analogy: "Una caja fuerte permite cambios por una cerradura controlada, no por cualquier ranura.", code: 'class Cuenta:\n    def __init__(self, saldo):\n        self.saldo = saldo\n    def depositar(self, monto):\n        if monto > 0:\n            self.saldo += monto\n        return self.saldo', note: "Ocultar detalles no significa complicar el diseño; ofrece métodos que mantienen el objeto válido.", hint: "Pregunta qué estados inválidos debe impedir el propio objeto." },
    ], labs: [
      { title: "Producto con precio", desc: "Modela artículos del catálogo y calcula su valor con cantidad.", prompt: "Implementa `Producto` con nombre, precio y método `subtotal(cantidad)`; muestra `60` y generaliza cambiando cantidad.", starter: 'class Producto:\n    def __init__(self, nombre, precio):\n        self.nombre = nombre\n        self.precio = precio\n    def subtotal(self, cantidad):\n        # Devuelve el subtotal\n        pass\n\nitem = Producto("libro", 20)\nprint(item.subtotal(3))', solution: 'class Producto:\n    def __init__(self, nombre, precio):\n        self.nombre = nombre\n        self.precio = precio\n    def subtotal(self, cantidad):\n        return self.precio * cantidad\n\nitem = Producto("libro", 20)\nprint(item.subtotal(3))', expected: "60", replaceFrom: "item.subtotal(3)", replaceTo: "item.subtotal(2)", alternateExpected: "40", pattern: "class\\s+Producto|def\\s+subtotal", behavior: "60" },
      { title: "Representación de lote", desc: "Produce una representación que permita identificar un lote en registros.", prompt: "Define `Lote.__str__` y muestra `Lote: Q8`. Cambiaremos el código del lote.", starter: 'class Lote:\n    def __init__(self, codigo):\n        self.codigo = codigo\n    # Implementa __str__\n\nlote = Lote("Q8")\nprint(lote)', solution: 'class Lote:\n    def __init__(self, codigo):\n        self.codigo = codigo\n    def __str__(self):\n        return f"Lote: {self.codigo}"\n\nlote = Lote("Q8")\nprint(lote)', expected: "Lote: Q8", replaceFrom: 'Lote("Q8")', replaceTo: 'Lote("M3")', alternateExpected: "Lote: M3", pattern: "def\\s+__str__\\s*\\(", behavior: "Lote: Q8" },
    ], quiz: { code: 'class Caja:\n    def __init__(self, unidades):\n        self.unidades = unidades\nprint(Caja(4).unidades)', printed: "4", mistake: "¿Qué ocurre si un método olvida recibir `self` como primer parámetro?", reasoning: "¿Por qué cada instancia necesita mantener sus propios atributos?", answer: "Para que el estado de un objeto no se mezcle con el de otro.", distractors: ["Para que todos los objetos compartan el mismo saldo.", "Para impedir que existan métodos.", "Para que la clase se convierta en un módulo."] },
  },
  {
    title: "POO II: herencia y polimorfismo", level: "avanzado", goal: "Extender comportamientos con herencia y definir contratos polimórficos mediante métodos especiales.", analogy: "Variantes de un mismo equipo con controles compartidos", readings: [
      { title: "Herencia con super", desc: "Extiende una clase reutilizando la inicialización común.", analogy: "Una ficha especializada conserva los datos generales y añade los propios.", code: 'class Documento:\n    def __init__(self, titulo):\n        self.titulo = titulo\nclass Informe(Documento):\n    def __init__(self, titulo, paginas):\n        super().__init__(titulo)\n        self.paginas = paginas', note: "Usa herencia para una relación real de especialización; composición puede ser mejor para piezas intercambiables.", hint: "Identifica qué comportamiento común reutiliza la subclase y qué amplía." },
      { title: "Polimorfismo en interfaces", desc: "Invoca la misma operación sobre tipos que responden de manera propia.", analogy: "Un mismo botón de envío activa el mecanismo adecuado para cada servicio.", code: 'class Correo:\n    def enviar(self):\n        return "correo"\nclass Aviso:\n    def enviar(self):\n        return "panel"\nfor canal in [Correo(), Aviso()]:\n    print(canal.enviar())', note: "Programa contra el comportamiento que necesitas, no contra una lista larga de tipos concretos.", hint: "Observa qué operación comparten los objetos aunque sus clases sean distintas." },
      { title: "Métodos especiales", desc: "Implementa igualdad, longitud y suma para respetar expectativas de Python.", analogy: "Un objeto que entiende las mismas acciones cotidianas que una colección.", code: 'class Grupo:\n    def __init__(self, miembros):\n        self.miembros = miembros\n    def __len__(self):\n        return len(self.miembros)\nprint(len(Grupo(["A", "B"])))', note: "Los métodos mágicos deben preservar contratos intuitivos; evita resultados sorprendentes para operadores comunes.", hint: "Define qué operación estándar debería significar para este objeto." },
    ], labs: [
      { title: "Tarifas polimórficas", desc: "Calcula el costo según el tipo de envío sin condicionales por tipo.", prompt: "Crea una clase base y `Express` heredada que sobrescriba `costo`; usa `super()` y muestra `Costo: 15`.", starter: 'class Envio:\n    def costo(self):\n        return 8\nclass Express(Envio):\n    # Inicializa y define el costo express\n    pass\n\nprint(f"Costo: {Express().costo()}")', solution: 'class Envio:\n    def costo(self):\n        return 8\nclass Express(Envio):\n    def __init__(self, recargo):\n        super().__init__()\n        self.recargo = recargo\n    def costo(self):\n        return 8 + self.recargo\n\nprint(f"Costo: {Express(7).costo()}")', expected: "Costo: 15", replaceFrom: "Express(7)", replaceTo: "Express(4)", alternateExpected: "Costo: 12", pattern: "class\\s+Express\\s*\\(\\s*Envio\\s*\\)|super\\(\\)", behavior: "Costo: 15" },
      { title: "Colección de registros", desc: "Haz que un objeto reporte su longitud y compare su contenido.", prompt: "Implementa `__len__` y `__eq__` en `Equipo`; la cantidad debe ser 2 y la igualdad debe comparar miembros.", starter: 'class Equipo:\n    def __init__(self, miembros):\n        self.miembros = miembros\n    # Implementa __len__ y __eq__\na = Equipo(["Luz", "Noa"])\nprint(len(a))\nprint(a == Equipo(["Luz", "Noa"]))', solution: 'class Equipo:\n    def __init__(self, miembros):\n        self.miembros = miembros\n    def __len__(self):\n        return len(self.miembros)\n    def __eq__(self, otro):\n        return self.miembros == otro.miembros\na = Equipo(["Luz", "Noa"])\nprint(len(a))\nprint(a == Equipo(["Luz", "Noa"]))', expected: "True", replaceFrom: '["Luz", "Noa"]', replaceTo: '["Luz", "Noa", "Ian"]', alternateExpected: "3", pattern: "def\\s+__len__|def\\s+__eq__", behavior: "True" },
    ], quiz: { code: 'class Base:\n    def valor(self):\n        return 2\nclass Extra(Base):\n    def valor(self):\n        return super().valor() + 3\nprint(Extra().valor())', printed: "5", mistake: "¿Qué problema puede aparecer si una subclase vuelve a escribir toda la inicialización común?", reasoning: "¿Qué permite el polimorfismo al agregar un nuevo tipo de envío?", answer: "Puede implementar el mismo contrato sin modificar el código que lo usa.", distractors: ["Obliga a cambiar cada llamada condicional existente.", "Impide que la nueva clase herede métodos.", "Convierte el envío en una función global."] },
  },
  {
    title: "Iteradores y generadores", level: "avanzado", goal: "Procesar secuencias bajo demanda mediante el protocolo iterador y generadores eficientes.", analogy: "Un grifo que entrega un registro cada vez que lo solicitas", readings: [
      { title: "Protocolo iterable", desc: "Distingue iterables de iteradores y entiende cómo avanza next.", analogy: "Una lista es el catálogo; el iterador es el marcador que avanza por él.", code: 'valores = [4, 7]\nmarcador = iter(valores)\nprint(next(marcador))\nprint(next(marcador))', note: "Un iterador se consume; no asumas que puede recorrerse de nuevo desde el inicio.", hint: "Observa qué estado conserva el iterador entre llamadas a next." },
      { title: "Crear generadores con yield", desc: "Produce valores poco a poco en vez de construir una lista completa.", analogy: "Una cocina que sirve cada plato al estar listo en vez de llenar toda la mesa.", code: 'def lotes(cantidad):\n    for numero in range(cantidad):\n        yield numero + 1\n\nprint(list(lotes(3)))', note: "`yield` pausa y conserva el estado local hasta la siguiente solicitud de valor.", hint: "Sigue qué línea reanuda la ejecución después de cada valor producido." },
      { title: "Itertools y consumo", desc: "Compone flujos de datos y procesa solo los elementos necesarios.", analogy: "Una cinta que se corta al alcanzar la cantidad requerida.", code: 'import itertools\nids = itertools.islice(range(100), 3)\nprint(list(ids))', note: "Un generador puede representar datos grandes sin almacenarlos todos; consúmelo solo cuando haga falta.", hint: "Calcula cuánto trabajo ahorras al pedir una porción del flujo." },
    ], labs: [
      { title: "Genera folios", desc: "Emite folios consecutivos para una serie de pedidos.", prompt: "Implementa `folios(inicio, cantidad)` con `yield`; debe producir `[5, 6, 7]` y adaptarse a otro inicio.", starter: 'def folios(inicio, cantidad):\n    # Produce folios con yield\n    pass\n\nprint(list(folios(5, 3)))', solution: 'def folios(inicio, cantidad):\n    for numero in range(inicio, inicio + cantidad):\n        yield numero\n\nprint(list(folios(5, 3)))', expected: "[5, 6, 7]", replaceFrom: "folios(5, 3)", replaceTo: "folios(2, 3)", alternateExpected: "[2, 3, 4]", pattern: "yield", behavior: "[5, 6, 7]" },
      { title: "Flujo de positivos", desc: "Emite únicamente saldos positivos para un reporte de conciliación.", prompt: "Crea un generador que emita valores mayores que cero; presenta `[4, 9]` desde la secuencia inicial.", starter: 'def positivos(valores):\n    # Emite solo saldos positivos\n    pass\n\nsaldos = [-2, 4, 0, 9]\nprint(list(positivos(saldos)))', solution: 'def positivos(valores):\n    for valor in valores:\n        if valor > 0:\n            yield valor\n\nsaldos = [-2, 4, 0, 9]\nprint(list(positivos(saldos)))', expected: "[4, 9]", replaceFrom: "saldos = [-2, 4, 0, 9]", replaceTo: "saldos = [3, -1, 7]", alternateExpected: "[3, 7]", pattern: "yield", behavior: "[4, 9]" },
    ], quiz: { code: 'def pasos():\n    yield "A"\n    yield "B"\nflujo = pasos()\nprint(next(flujo))', printed: "A", mistake: "¿Qué ocurre si llamas `next` después de consumir todos los valores?", reasoning: "¿Por qué un generador resulta útil al procesar millones de registros?", answer: "Produce valores bajo demanda y evita mantener toda la secuencia en memoria.", distractors: ["Guarda una copia completa automáticamente.", "Ordena los datos antes de producirlos.", "Ejecuta todos los valores en paralelo."] },
  },
  {
    title: "Decoradores y metaprogramación Python", level: "avanzado", goal: "Envolver comportamientos sin alterar funciones y exponer atributos controlados con propiedades.", analogy: "Una capa de embalaje que añade seguimiento sin cambiar el producto", readings: [
      { title: "Funciones decoradoras", desc: "Envuelve una función para añadir un comportamiento transversal.", analogy: "Como añadir una etiqueta de control alrededor de un paquete sin cambiar su contenido.", code: 'def anunciar(funcion):\n    def envoltura():\n        return "Inicio: " + funcion()\n    return envoltura\n\n@anunciar\ndef tarea():\n    return "ok"\nprint(tarea())', note: "Usa `functools.wraps` para conservar nombre y documentación de la función decorada.", hint: "Localiza la función original que entra y la nueva función que sale del decorador." },
      { title: "Property y métodos de clase", desc: "Controla el acceso a atributos y elige el tipo de método adecuado.", analogy: "Una ventana de lectura validada frente a una herramienta común del taller.", code: 'class Articulo:\n    def __init__(self, precio):\n        self._precio = precio\n    @property\n    def precio(self):\n        return self._precio\nprint(Articulo(12).precio)', note: "`@staticmethod` no recibe instancia; `@classmethod` recibe la clase como `cls`.", hint: "Decide si una operación necesita estado de instancia, de clase o ninguno." },
      { title: "Metaprogramación prudente", desc: "Inspecciona atributos y compone comportamientos con herramientas explícitas.", analogy: "Un inventario que revisa las etiquetas de una herramienta antes de utilizarla.", code: 'class Ficha:\n    def __init__(self):\n        self.estado = "abierta"\n\nficha = Ficha()\nprint(hasattr(ficha, "estado"))', note: "Prefiere decoradores y composición conocidos antes de introducir metaclases u otras abstracciones opacas.", hint: "Asegúrate de que la abstracción haga más fácil entender el contrato público." },
    ], labs: [
      { title: "Registra una operación", desc: "Añade una marca de auditoría a una función de conciliación.", prompt: "Crea un decorador `auditar` que conserva el resultado de la función y lo prefija con `OK:`; generaliza con otro código.", starter: 'def auditar(funcion):\n    # Devuelve una envoltura\n    pass\n\n@auditar\ndef estado():\n    return "C-8"\n\nprint(estado())', solution: 'from functools import wraps\ndef auditar(funcion):\n    @wraps(funcion)\n    def envoltura():\n        return "OK: " + funcion()\n    return envoltura\n\n@auditar\ndef estado():\n    return "C-8"\n\nprint(estado())', expected: "OK: C-8", replaceFrom: 'return "C-8"', replaceTo: 'return "D-2"', alternateExpected: "OK: D-2", pattern: "@auditar|def\\s+auditar", behavior: "OK: C-8" },
      { title: "Propiedad de tarifa", desc: "Expone una tarifa calculada mediante una propiedad de solo lectura.", prompt: "Implementa `@property` para calcular el total con recargo e imprime 22 desde una base 20 y recargo 2.", starter: 'class Envio:\n    def __init__(self, base, recargo):\n        self.base = base\n        self.recargo = recargo\n    # Crea la propiedad total\nenvio = Envio(20, 2)\nprint(envio.total)', solution: 'class Envio:\n    def __init__(self, base, recargo):\n        self.base = base\n        self.recargo = recargo\n    @property\n    def total(self):\n        return self.base + self.recargo\nenvio = Envio(20, 2)\nprint(envio.total)', expected: "22", replaceFrom: "Envio(20, 2)", replaceTo: "Envio(10, 2)", alternateExpected: "12", pattern: "@property", behavior: "22" },
    ], quiz: { code: 'def prefijo(funcion):\n    def nueva():\n        return "ID-" + funcion()\n    return nueva\n@prefijo\ndef codigo():\n    return "7"\nprint(codigo())', printed: "ID-7", mistake: "¿Qué información puede perderse si un decorador no usa `functools.wraps`?", reasoning: "¿Cuándo conviene `@classmethod` en vez de un método de instancia?", answer: "Cuando la operación trabaja con la clase como conjunto, no con una instancia concreta.", distractors: ["Cuando el método necesita cambiar atributos de una instancia.", "Siempre que una función tenga return.", "Solo cuando el programa usa archivos."] },
  },
  {
    title: "Concurrencia y asincronía", level: "avanzado", goal: "Coordinar tareas de entrada y salida concurrentes con corrutinas y asyncio.", analogy: "Una persona que atiende varias solicitudes mientras espera respuestas", readings: [
      { title: "Corrutinas y await", desc: "Define corrutinas y cede el control mientras una operación espera.", analogy: "Como dejar una consulta en espera y atender otra mesa mientras llega la respuesta.", code: 'import asyncio\nasync def consultar():\n    await asyncio.sleep(0)\n    return "listo"\n\nprint(await consultar())', note: "`await` solo se usa dentro de una corrutina o en un contexto que soporte top-level await.", hint: "Identifica qué operación espera y en qué punto otra tarea puede avanzar." },
      { title: "Tareas concurrentes", desc: "Programa corrutinas para que compartan el tiempo de espera de I/O.", analogy: "Dos solicitudes enviadas antes de esperar que respondan ambas.", code: 'import asyncio\nasync def dato(valor):\n    await asyncio.sleep(0)\n    return valor\n\nresultados = await asyncio.gather(dato("A"), dato("B"))\nprint(resultados)', note: "La concurrencia no acelera automáticamente trabajo intensivo de CPU; su ventaja principal es aprovechar esperas.", hint: "Compara esperar cada tarea por turno con programarlas juntas." },
      { title: "Errores y cancelación", desc: "Controla resultados y fallos de tareas concurrentes con límites claros.", analogy: "Un coordinador que recoge respuestas y registra qué encargo falló.", code: 'import asyncio\nasync def verificar(ok):\n    if not ok:\n        raise ValueError("falló")\n    return "bien"\n\ntry:\n    print(await verificar(True))\nexcept ValueError:\n    print("reintentar")', note: "Define qué hacer ante error o cancelación; no abandones tareas pendientes sin supervisión.", hint: "Separa la espera concurrente del criterio para recuperar cada error." },
    ], labs: [
      { title: "Consultas concurrentes", desc: "Coordina consultas simuladas al catálogo sin usar servicios externos.", prompt: "Define dos corrutinas y reúnelas con `asyncio.gather`; imprime `['A', 'B']`. Cambiaremos ambos códigos.", starter: 'import asyncio\nasync def consultar(codigo):\n    # Cede el control y devuelve el codigo\n    pass\n\nresultados = await asyncio.gather(consultar("A"), consultar("B"))\nprint(resultados)', solution: 'import asyncio\nasync def consultar(codigo):\n    await asyncio.sleep(0)\n    return codigo\n\nresultados = await asyncio.gather(consultar("A"), consultar("B"))\nprint(resultados)', expected: "['A', 'B']", replaceFrom: 'consultar("A"), consultar("B")', replaceTo: 'consultar("X"), consultar("Y")', alternateExpected: "['X', 'Y']", pattern: "async\\s+def|asyncio\\.gather", behavior: "['A', 'B']" },
      { title: "Recupera fallos async", desc: "Maneja una excepción de una consulta asíncrona simulada.", prompt: "Lanza `ValueError` desde la corrutina cuando recibe False y captura el error para imprimir `Reintentar`.", starter: 'async def consultar(disponible):\n    # Lanza ValueError si no está disponible\n    pass\n\ntry:\n    await consultar(False)\nexcept ValueError:\n    print("Reintentar")', solution: 'async def consultar(disponible):\n    if not disponible:\n        raise ValueError("sin respuesta")\n\ntry:\n    await consultar(False)\nexcept ValueError:\n    print("Reintentar")', expected: "Reintentar", replaceFrom: "consultar(False)", replaceTo: "consultar(True)", alternateExpected: "", pattern: "async\\s+def|await\\s+consultar", behavior: "Reintentar" },
    ], quiz: { code: 'async def valor():\n    return 5\nprint(await valor())', printed: "5", mistake: "¿Qué ocurre si llamas una corrutina sin esperarla ni programarla?", reasoning: "¿Por qué gather ayuda en tareas que esperan respuestas externas?", answer: "Permite que varias esperas avancen concurrentemente en vez de bloquearse una tras otra.", distractors: ["Convierte I/O en trabajo de CPU paralelo.", "Garantiza que las respuestas lleguen en orden temporal.", "Elimina automáticamente cualquier excepción."] },
  },
  {
    title: "Proyecto final y testing", level: "avanzado", goal: "Entregar un paquete de registros extensible, validado con pruebas y persistencia JSON.", analogy: "Un pequeño producto con piezas sustituibles y control de calidad repetible", readings: [], labs: [
      { title: "Gestor de ventas verificable", desc: "Integra objetos, herencia, generadores, decoradores, errores, JSON y unittest.", prompt: "Construye un gestor que modele `Venta` heredada de `Registro`, lea valores desde JSON, filtre ventas mediante un generador, aplique un decorador de auditoría y valide el cálculo con `unittest`. La salida debe incluir `Total: 7`, `Auditado: 7` y una prueba aprobada. No fijes resultados: se probarán otros datos.", starter: '# Integra clases, herencia, yield, un decorador, errores, JSON, unittest y empaquetado\nimport json\nimport unittest\n\n# Define las clases y el flujo verificable', solution: 'import json\nimport unittest\nfrom functools import wraps\n\nclass Registro:\n    def __init__(self, monto):\n        if monto < 0:\n            raise ValueError("monto inválido")\n        self.monto = monto\n\nclass Venta(Registro):\n    def total(self):\n        return self.monto\n\ndef auditar(funcion):\n    @wraps(funcion)\n    def envoltura(*args, **kwargs):\n        return funcion(*args, **kwargs)\n    return envoltura\n\n@auditar\ndef sumar(registros):\n    return sum([registro.total() for registro in registros])\n\ndef ventas_validas(registros):\n    for registro in registros:\n        if registro.monto > 0:\n            yield registro\n\ntexto = json.dumps({"montos": [3, 4]})\ndatos = json.loads(texto)\nregistros = [Venta(monto) for monto in datos["montos"]]\ntotal = sumar(list(ventas_validas(registros)))\nprint(f"Total: {total}")\nprint(f"Auditado: {sum([registro.total() for registro in registros])}")\nwith open("pyproject.toml", "w") as manifiesto:\n    manifiesto.write("[project]\\nname = \\\"gestor-ventas\\\"\\nversion = \\\"0.1.0\\\"\\n")\nwith open("pyproject.toml", "r") as manifiesto:\n    contenido = manifiesto.read()\nnombre_paquete = contenido.split("name = ")[1].split("\\n")[0].strip("\\\"")\nprint(f"Paquete: {nombre_paquete}")\n\nclass PruebaVentas(unittest.TestCase):\n    def test_total(self):\n        self.assertEqual(sumar(list(ventas_validas(registros))), sum(datos["montos"]))\n\nresultado = unittest.TestResult()\nPruebaVentas("test_total").run(resultado)\naprobadas = resultado.testsRun - len(resultado.failures) - len(resultado.errors)\nprint(f"Pruebas aprobadas: {aprobadas}")', expected: "Total: 7", replaceFrom: '"montos": [3, 4]', replaceTo: '"montos": [2, 5]', alternateExpected: "Total: 7", pattern: "class\\s+Venta\\s*\\(\\s*Registro\\s*\\)|yield|@auditar|json\\.(?:load|loads)|unittest|raise\\s+ValueError|pyproject", behavior: "Pruebas aprobadas: 1" },
    ], quiz: { code: 'class Base:\n    def total(self):\n        return 7\nclass Venta(Base):\n    pass\nprint(Venta().total())', printed: "7", mistake: "¿Por qué una prueba unitaria no debería depender de datos externos variables?", reasoning: "¿Cómo ayudan las pruebas cuando el generador de ventas cambia su implementación?", answer: "Comprueban el contrato y alertan cuando una modificación rompe un comportamiento esperado.", distractors: ["Hacen innecesario revisar errores en producción.", "Garantizan que el código sea siempre más rápido.", "Reemplazan la documentación del paquete."] },
  },
];

function daxFor(title: string, analogy: string, index: number) {
  return {
    hint: `Para ${title.toLowerCase()}, separa la entrada, la regla y el resultado; prueba también un caso límite.`,
    explain: `Imagínalo como ${analogy.toLowerCase()}: cada parte cumple una función y el resultado debe poder revisarse.`,
    example: `turno = "Turno ${index + 1}"\npaquetes = ${index + 2}\nprint(turno, paquetes)`,
  };
}

function escapeHtml(value: string) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function highlightPythonLine(line: string) {
  const escaped = escapeHtml(line);
  const keywords = new Set(["and", "as", "async", "await", "break", "class", "continue", "def", "elif", "else", "except", "finally", "for", "from", "if", "import", "in", "is", "lambda", "not", "or", "pass", "raise", "return", "try", "while", "with", "yield"]);
  const builtins = new Set(["abs", "bool", "dict", "filter", "float", "int", "len", "list", "map", "max", "min", "print", "range", "set", "sorted", "str", "sum", "tuple", "type"]);
  return escaped.replace(/(#.*$|"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'|\b[a-zA-Z_]\w*\b|\b\d+(?:\.\d+)?\b)/g, (token) => {
    if (token.startsWith("#")) return `<span class="cm">${token}</span>`;
    if (token.startsWith("\"") || token.startsWith("'")) return `<span class="st">${token}</span>`;
    if (keywords.has(token)) return `<span class="kw">${token}</span>`;
    if (builtins.has(token)) return `<span class="fn">${token}</span>`;
    if (/^\d/.test(token)) return `<span class="nm">${token}</span>`;
    return token;
  });
}

const quizRationales = [
  { error: "Python lanza TypeError porque no se puede sumar directamente texto e entero.", reason: "La conversión explícita permite validar y calcular con el tipo numérico correcto.", distractors: ["El intérprete agrega los dos valores como palabras.", "La conversión evita revisar de dónde vino el dato."] },
  { error: "La asignación cambia el valor; una comparación requiere `==`.", reason: "Los paréntesis hacen visible el orden y mantienen el cálculo alineado con la regla.", distractors: ["La precedencia no afecta expresiones aritméticas.", "Los operadores lógicos reemplazan todos los paréntesis."] },
  { error: "`=` asigna un valor; una condición debe comparar con `==`, `>=` u otro comparador.", reason: "Evaluar primero las categorías más específicas evita que una regla amplia capture casos ajenos.", distractors: ["El orden de las ramas no cambia qué condición se ejecuta.", "Las condiciones deben ser siempre independientes."] },
  { error: "Si la variable no cambia, la condición puede mantenerse verdadera indefinidamente.", reason: "El `else` del bucle permite comunicar que se revisó todo sin encontrar el elemento.", distractors: ["El bucle se detiene automáticamente tras tres vueltas.", "`else` se ejecuta siempre al inicio del recorrido."] },
  { error: "Sin `return`, la llamada entrega None aunque la función haya impreso el cálculo.", reason: "Un valor devuelto puede componerse, guardarse y verificarse en otros pasos.", distractors: ["`print` devuelve el contenido mostrado como número.", "Toda función devuelve su última variable automáticamente."] },
  { error: "Los métodos de string producen otra cadena; debes guardar el resultado.", reason: "Limpiar primero espacios externos evita que alteren comparaciones y etiquetas posteriores.", distractors: ["Las cadenas cambian siempre en el mismo objeto.", "`upper` elimina los caracteres de espacio."] },
  { error: "`pop()` en una lista vacía produce IndexError.", reason: "Una tupla comunica que las partes ordenadas de la coordenada son inmutables.", distractors: ["Una tupla ordena las coordenadas automáticamente.", "Las listas no pueden guardar ubicaciones."] },
  { error: "`get` ofrece un valor alternativo cuando la clave no está presente.", reason: "La intersección conserva únicamente integrantes que aparecen en los dos grupos.", distractors: ["La unión conserva solo coincidencias.", "La diferencia conserva elementos comunes."] },
  { error: "`**kwargs` agrupa opciones nombradas en un diccionario local.", reason: "Un docstring explica el contrato para que otra persona use la función sin inspeccionar su interior.", distractors: ["Los docstrings cambian el tipo de retorno.", "El scope global garantiza que una función sea reusable."] },
  { error: "Las comprensiones anidadas profundas suelen ocultar el orden y la intención.", reason: "El filtro mantiene solo los elementos válidos y luego la expresión transforma cada uno.", distractors: ["El filtro debe ejecutarse después de imprimir.", "Toda comprensión transforma en texto."] },
  { error: "Capturar todas las excepciones puede ocultar errores de programación inesperados.", reason: "`else` se ejecuta sin excepción y `finally` se ejecuta tanto si hubo error como si no.", distractors: ["`else` y `finally` se ejecutan solo cuando falla el código.", "`finally` impide que se ejecuten bloques except."] },
  { error: "El modo `w` trunca el contenido previo del archivo.", reason: "`with` asegura que el archivo se cierre al terminar el bloque incluso si ocurre un error.", distractors: ["`w` nunca cambia el archivo existente.", "Los context managers convierten los datos en JSON."] },
  { error: "`sum` expresa directamente la suma; `reduce` necesita una función acumuladora más general.", reason: "`map` transforma elementos y `filter` conserva los que cumplen la condición.", distractors: ["`map` ordena y `filter` elimina duplicados.", "Ambas funciones siempre devuelven listas."] },
  { error: "Sin el guard, el flujo principal puede ejecutarse al importar el módulo.", reason: "Un entorno virtual aísla versiones y dependencias específicas del proyecto.", distractors: ["El guard crea un paquete comprimido.", "Los entornos virtuales sustituyen al intérprete."] },
  { error: "Sin `self`, Python no puede enlazar correctamente la instancia al método.", reason: "Cada objeto conserva su estado sin sobrescribir el de las demás instancias.", distractors: ["Las instancias comparten una variable local.", "`self` convierte todos los atributos en globales."] },
  { error: "Duplicar la inicialización común hace más difícil mantener y extender las subclases.", reason: "Un cliente puede usar el contrato común y dejar que cada clase resuelva su comportamiento.", distractors: ["La subclase debe reemplazar todos los métodos heredados.", "El polimorfismo obliga a comparar tipos manualmente."] },
  { error: "Agotar el iterador produce StopIteration.", reason: "El generador crea cada valor cuando se solicita y puede ahorrar memoria.", distractors: ["Un generador carga todos los valores por adelantado.", "`next` vuelve al inicio cuando llega al final."] },
  { error: "Sin `wraps`, la función envuelta puede perder su nombre y documentación originales.", reason: "`classmethod` es apropiado cuando una operación necesita recibir y consultar la clase.", distractors: ["`classmethod` siempre modifica una instancia.", "`classmethod` evita definir parámetros."] },
  { error: "Una corrutina llamada sin await no completa su trabajo y puede generar una advertencia.", reason: "`gather` coordina varias esperas para que avancen concurrentemente.", distractors: ["`gather` hace CPU paralelo automáticamente.", "Una corrutina nunca puede producir errores."] },
  { error: "Una prueba que depende de datos externos puede fallar sin que cambie el código probado.", reason: "Las pruebas detectan regresiones al comprobar el contrato antes y después de refactorizar.", distractors: ["Las pruebas hacen innecesario validar entradas.", "Las pruebas garantizan rendimiento sin medirlo."] },
];

function makeReading(module: ModuleSpec, spec: ReadingSpec, moduleIndex: number, lessonIndex: number): PythonLesson {
  const codeLines = spec.code.split("\n").map(highlightPythonLine).join("\n");
  const content = `<p>${spec.desc} ${module.goal}</p><h3>Una analogía</h3><p>${spec.analogy}</p><h3>Prueba este ejemplo</h3><pre class="code"><code>${codeLines}</code></pre><div class="note"><b>Atención:</b> ${spec.note}</div><h3>Forma de pensar</h3><ul><li>Nombrar los datos con claridad.</li><li>Comprobar qué resultado produce cada instrucción.</li><li>Explicar por qué la solución sirve en este contexto.</li></ul>`;
  return {
    id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "reading", icon: "📖", xp: 20, minutes: 10,
    title: spec.title, desc: spec.desc, level: module.level,
    objectives: [`Explicar ${spec.title.toLowerCase()} con tus palabras.`, "Predecir el resultado antes de ejecutar el ejemplo.", "Adaptar la idea a un caso profesional distinto."],
    dax: daxFor(spec.title, spec.analogy, moduleIndex * 10 + lessonIndex), content,
    keyPoints: [spec.desc, spec.note, `La capacidad se aplica a: ${module.goal.toLowerCase()}`],
    playground: { starter: spec.code, hint: spec.hint },
  };
}

function makeLab(module: ModuleSpec, spec: LabSpec, moduleIndex: number, lessonIndex: number): PythonLesson {
  const checkSet: PythonCheck[] = [
    { desc: "El código usa la estructura solicitada.", test: (code) => new RegExp(spec.pattern, "s").test(code) },
    { desc: "La salida del caso inicial es correcta.", test: (_code, context) => context.output.includes(spec.expected) },
    { desc: "La solución generaliza con datos alternativos.", test: async (code, _context, helpers) => {
      if (!code.includes(spec.replaceFrom)) return false;
      const alternate = await helpers.run(code.replace(spec.replaceFrom, spec.replaceTo));
      return !alternate.error && (spec.alternateExpected === "" ? alternate.output.length === 0 : alternate.output.includes(spec.alternateExpected));
    } },
  ];
  if (spec.behavior) checkSet.push({ desc: "El comportamiento del objeto o patrón coincide con el contrato.", test: (_code, context) => context.output.includes(spec.behavior ?? "") });
  if (moduleIndex === 19) {
    checkSet.push({ desc: "El cálculo auditado coincide con los datos JSON.", test: (_code, context) => context.output.includes("Auditado: 7") });
    checkSet.push({ desc: "El manifiesto identifica el paquete distribuible.", test: (_code, context) => context.output.includes("Paquete: gestor-ventas") });
  }
  checkSet.push({ desc: "El programa no produce errores.", test: (_code, context) => context.error === null });
  const moduleLabXp = module.level === "principiante" ? 50 : module.level === "intermedio" ? 60 : 80;
  const moduleLabMinutes = module.level === "principiante" ? 18 : module.level === "intermedio" ? 20 : 25;
  const isFinal = moduleIndex === 19;
  return {
    id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "lab", icon: isFinal ? "🚀" : "💻",
    xp: isFinal ? 200 : moduleLabXp, minutes: isFinal ? 45 : moduleLabMinutes,
    title: spec.title, desc: spec.desc, level: module.level,
    objectives: ["Implementar una solución que calcule resultados desde sus datos.", "Validar el comportamiento con más de un caso.", "Explicar una decisión de diseño y un límite de la solución."],
    dax: daxFor(spec.title, module.analogy, moduleIndex * 10 + lessonIndex),
    prompt: `<p>${spec.prompt}</p><p><strong>Criterio:</strong> el código debe calcular el resultado, no imprimir una respuesta fija.</p>`,
    starter: spec.starter, solution: spec.solution, checks: checkSet,
  };
}

function makeQuiz(module: ModuleSpec, spec: QuizSpec, moduleIndex: number, lessonIndex: number): PythonLesson {
  const rationale = quizRationales[moduleIndex];
  return {
    id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "quiz", icon: "📝",
    xp: moduleIndex === 19 ? 100 : 60, minutes: moduleIndex === 19 ? 15 : 10,
    title: moduleIndex === 19 ? "Evaluación de integración" : `Decisiones sobre ${module.title.toLowerCase()}`,
    desc: `Comprueba tu criterio al aplicar ${module.title.toLowerCase()} en un problema real.`, level: module.level,
    objectives: ["Predecir una salida ejecutando mentalmente el código.", "Detectar un error frecuente antes de ejecutar.", "Justificar la opción que generaliza mejor."],
    dax: daxFor(module.title, module.analogy, moduleIndex * 10 + lessonIndex),
    questions: [
      { q: `¿Qué imprime este código?\n${spec.code}`, options: [spec.printed, "No imprime nada.", "Se produce un error de sintaxis.", "Imprime el nombre de la variable."], correct: 0, explain: `Sigue cada instrucción y evalúa los datos antes de elegir. El resultado es ${spec.printed}.` },
      { q: spec.mistake, options: [rationale.distractors[0], rationale.error, rationale.distractors[1], "El programa termina antes de evaluar la condición."], correct: 1, explain: rationale.error },
      { q: spec.reasoning, options: ["Porque evita toda validación.", rationale.distractors[1], rationale.reason, "Porque convierte todas las variables en texto."], correct: 2, explain: rationale.reason },
      { q: `¿Qué evidencia daría más confianza en una solución de ${module.title.toLowerCase()}?`, options: ["Probar solo el dato inicial.", "Ejecutar un caso nuevo y comprobar que conserva la regla esperada.", "Cambiar nombres hasta que parezca correcto.", "Ocultar los errores de ejecución."], correct: 1, explain: "Un caso nuevo ayuda a detectar respuestas fijadas y comprueba que la solución generaliza." },
    ],
  };
}

export const PYTHON_CURRICULUM: PythonModule[] = specs.map((spec, moduleIndex) => {
  const lessons: PythonLesson[] = [];
  spec.readings.forEach((reading, index) => lessons.push(makeReading(spec, reading, moduleIndex, lessons.length)));
  spec.labs.forEach((lab) => lessons.push(makeLab(spec, lab, moduleIndex, lessons.length)));
  lessons.push(makeQuiz(spec, spec.quiz, moduleIndex, lessons.length));
  return {
    id: `m${moduleIndex + 1}`, title: spec.title, level: spec.level, goal: spec.goal,
    minutes: lessons.reduce((total, lesson) => total + lesson.minutes, 0), lessons,
  };
});

export const MODULE_ICONS = ["🐍", "➕", "🔀", "🔁", "🧩", "🎛️", "✂️", "📋", "🗂️", "🛡️", "⚙️", "🏛️", "🧬", "⚡", "📦", "🌐", "🧪", "🚀", "🧠", "🏆"];

function validateCurriculum() {
  const readingCounts = [3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0];
  const labCounts = [1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1];
  if (PYTHON_CURRICULUM.length !== 20 || MODULE_ICONS.length !== 20) throw new Error("El currículo Python debe contener exactamente 20 módulos e iconos.");
  PYTHON_CURRICULUM.forEach((module, moduleIndex) => {
    const expectedLevel: PythonLevel = moduleIndex < 7 ? "principiante" : moduleIndex < 14 ? "intermedio" : "avanzado";
    const counts = module.lessons.reduce((total, lesson) => ({ ...total, [lesson.type]: total[lesson.type] + 1 }), { reading: 0, lab: 0, quiz: 0 });
    const moduleWordCount = module.title.trim().split(/\s+/).length;
    if (module.id !== `m${moduleIndex + 1}` || moduleWordCount < 3 || moduleWordCount > 7 || module.level !== expectedLevel || counts.reading !== readingCounts[moduleIndex] || counts.lab !== labCounts[moduleIndex] || counts.quiz !== 1) {
      throw new Error(`La estructura del módulo ${module.id} no coincide con el contrato del curso.`);
    }
    if (module.minutes !== module.lessons.reduce((sum, lesson) => sum + lesson.minutes, 0)) throw new Error(`La duración del módulo ${module.id} no coincide con sus actividades.`);
    module.lessons.forEach((lesson, lessonIndex) => {
      if (lesson.id !== `m${moduleIndex + 1}l${lessonIndex + 1}` || !lesson.title || lesson.title.trim().split(/\s+/).length > 7 || lesson.level !== module.level || lesson.objectives.length < 3 || !lesson.dax.hint || !lesson.dax.explain || !lesson.dax.example) {
        throw new Error(`La actividad ${lesson.id} tiene campos obligatorios incompletos.`);
      }
      if (lesson.type === "reading" && (!lesson.content || !lesson.keyPoints?.length || !lesson.playground)) throw new Error(`La lectura ${lesson.id} no tiene material interactivo completo.`);
      if (lesson.type === "lab") {
        if (!lesson.starter || !lesson.solution || !lesson.checks || lesson.checks.length < 4) throw new Error(`El laboratorio ${lesson.id} no tiene solución y pruebas completas.`);
        if (lesson.checks.some((check) => !check.desc || typeof check.test !== "function")) throw new Error(`El laboratorio ${lesson.id} tiene una prueba inválida.`);
        for (const check of lesson.checks) {
          if (check.desc.includes("estructura")) {
            try { new RegExp((specs[moduleIndex].labs[lessonIndex - readingCounts[moduleIndex]].pattern), "s"); }
            catch { throw new Error(`El laboratorio ${lesson.id} tiene una expresión estructural inválida.`); }
          }
        }
      }
      if (lesson.type === "quiz" && (!lesson.questions || lesson.questions.length < 3 || lesson.questions.some((question) => question.options.length !== 4 || question.correct < 0 || question.correct >= question.options.length))) {
        throw new Error(`El quiz ${lesson.id} tiene preguntas incompletas o mal formadas.`);
      }
    });
  });
}

validateCurriculum();

export function toPythonRunContext(result: PythonRunResult): PythonRunContext {
  return { output: [...result.output, ...result.stderr], vars: result.vars, error: result.error };
}