import { runSql, type SqlRunResult, type SqlResult } from "@/lib/sqlEngine";

export type SqlLevel = "principiante" | "intermedio" | "avanzado";
export type SqlLessonType = "reading" | "sql" | "quiz";
export type SqlQuestion = { q: string; options: [string, string, string, string]; correct: number; explain: string };
export type SqlCheck = { desc: string; test: (code: string, result: SqlRunResult | null) => boolean };
export type SqlLesson = {
  id: string; type: SqlLessonType; icon: string; xp: number; minutes: number; title: string; desc: string;
  level: SqlLevel; objectives: string[]; dax: { hint: string; explain: string; example: string };
  content?: string; keyPoints?: string[]; prompt?: string; starter?: string; checks?: SqlCheck[]; solution?: string; questions?: SqlQuestion[];
};
export type SqlModule = { id: string; title: string; minutes: number; goal: string; level: SqlLevel; lessons: SqlLesson[] };

type ReadingSpec = { title: string; desc: string; analogy: string; example: string; points: [string, string, string]; note: string; tip: string; hint: string };
type LabSpec = { title: string; desc: string; prompt: string; solution: string; rows: number; columns: string[]; values: Array<{ column: string; value: string | number }>; patterns: RegExp[]; hint: string; combined?: RegExp };
type ModuleSpec = { title: string; goal: string; level: SqlLevel; readings: ReadingSpec[]; labs: LabSpec[]; questions: SqlQuestion[] };

const specs: ModuleSpec[] = [
  {
    title: "Fundamentos de SQL relacional", level: "principiante", goal: "Leer un esquema relacional y consultar columnas específicas con SELECT, FROM y alias.", readings: [
      { title: "Tablas, filas y claves", desc: "Reconoce cómo se organizan registros y relaciones en una base relacional.", analogy: "Una tabla es un archivador; cada fila, una ficha; las columnas, sus campos.", example: "SELECT id, nombre FROM clientes;", points: ["Cada fila representa un registro del mismo tipo.", "Cada columna describe un atributo.", "Una PK identifica; una FK enlaza registros."], note: "No supongas que una clave foránea identifica una fila: puede repetirse muchas veces.", tip: "Define primero qué representa una fila antes de contar o relacionar registros.", hint: "Identifica qué entidad representa cada tabla y qué campo podría enlazarla con otra." },
      { title: "SELECT y FROM", desc: "Formula una consulta que indique qué campos leer y desde qué tabla.", analogy: "En un catálogo, eliges qué rótulos revisar y de qué estante salen.", example: "SELECT ciudad FROM clientes;", points: ["SELECT define las columnas de salida.", "FROM señala la fuente de registros.", "El punto y coma cierra la consulta."], note: "SELECT * es útil para explorar, pero hace impreciso el resultado de un informe.", tip: "Enumera únicamente las columnas que responden la pregunta.", hint: "Separa mentalmente la pregunta en dos partes: campos solicitados y tabla fuente." },
      { title: "Alias y resultados claros", desc: "Asigna encabezados legibles sin alterar los nombres almacenados.", analogy: "Una etiqueta de estante hace más fácil interpretar una lista al compartirla.", example: "SELECT email AS correo FROM clientes;", points: ["AS asigna un alias a una expresión de salida.", "El alias cambia el encabezado, no el esquema.", "Un nombre claro evita ambigüedad en reportes."], note: "No uses un alias para ocultar una definición de métrica poco clara.", tip: "Elige alias breves que describan el significado de la columna calculada.", hint: "Piensa qué título entendería alguien que no escribió la consulta." },
    ], labs: [
      { title: "Consulta de clientes", desc: "Prepara un listado compacto para revisar zonas y contactos.", prompt: "Consulta clientes y devuelve exactamente `nombre` y `ciudad`, en ese orden. Estructura esperada: SELECT nombre, ciudad FROM clientes. Resultado: 6 filas; primera fila Ana García, Lima.", solution: "SELECT nombre, ciudad FROM clientes;", rows: 6, columns: ["nombre", "ciudad"], values: [{ column: "nombre", value: "Ana García" }, { column: "ciudad", value: "Lima" }], patterns: [/^\s*select\b/i, /from\s+clientes/i, /nombre\s*,\s*ciudad/i], hint: "Usa dos campos explícitos y conserva su orden en el SELECT." },
    ], questions: [
      { q: "¿Qué devuelve `SELECT nombre FROM clientes LIMIT 1`?", options: ["Una columna y una fila de clientes", "Todas las columnas y seis filas", "Un conteo de clientes", "Una tabla permanente"], correct: 0, explain: "SELECT proyecta nombre y LIMIT limita la salida a una fila." },
      { q: "Una FK se repite en varias ventas. ¿Qué error hay al usarla como identificador único de venta?", options: ["Puede confundir varias ventas con una sola", "Convierte la FK en una vista", "Cambia el tipo de la columna", "Ordena automáticamente las filas"], correct: 0, explain: "La FK apunta al cliente, que puede tener más de una venta." },
      { q: "¿Cuándo conviene enumerar columnas en lugar de usar `*`?", options: ["En resultados compartidos con un propósito definido", "Solo cuando la tabla está vacía", "Para eliminar columnas de la tabla", "Nunca es necesario"], correct: 0, explain: "Un conjunto explícito de columnas es más claro y estable para informes." },
      { q: "¿Qué cláusula indica la tabla de origen?", options: ["FROM", "SELECT", "AS", "LIMIT"], correct: 0, explain: "FROM declara la tabla desde la que se leen las filas." },
    ],
  },
  {
    title: "Filtrar registros con precisión", level: "principiante", goal: "Reducir filas con comparaciones, lógica, listas, rangos, patrones y pruebas de nulos.", readings: [
      { title: "WHERE y comparaciones", desc: "Selecciona filas que cumplen una condición numérica o textual.", analogy: "Un colador retiene solo las fichas que cumplen el criterio elegido.", example: "SELECT nombre FROM clientes WHERE edad >= 30;", points: ["WHERE filtra filas antes de resumirlas.", "Los textos se comparan entre comillas simples.", "Los límites inclusivos usan >= o <=."], note: "NULL representa ausencia; una comparación normal con NULL no la detecta.", tip: "Prueba el valor justo en el límite y uno inmediatamente fuera de él.", hint: "Traduce cada criterio del enunciado en una condición independiente." },
      { title: "Combinar reglas lógicas", desc: "Expresa condiciones que requieren una o varias reglas simultáneas.", analogy: "Una entrada puede pedir dos credenciales o aceptar una de varias alternativas.", example: "SELECT id FROM clientes WHERE activo = 1 AND edad >= 25;", points: ["AND requiere que ambas condiciones sean verdaderas.", "OR acepta al menos una condición verdadera.", "NOT invierte el resultado lógico."], note: "AND se evalúa con mayor precedencia que OR; usa paréntesis para expresar intención.", tip: "Escribe la regla primero como frase y luego decide entre AND y OR.", hint: "Cuenta cuántas condiciones deben cumplirse a la vez y cuáles son alternativas." },
      { title: "Listas, rangos y patrones", desc: "Filtra pertenencia a conjuntos, intervalos inclusivos y fragmentos de texto.", analogy: "Una búsqueda puede aceptar una lista de destinos, un rango o una plantilla de etiqueta.", example: "SELECT nombre FROM clientes WHERE ciudad LIKE 'S%';", points: ["IN compara contra una lista de valores.", "BETWEEN incluye ambos extremos del rango.", "LIKE usa % para varios caracteres y _ para uno."], note: "Un comodín al inicio de LIKE también busca coincidencias que no empiezan con ese texto.", tip: "Usa IS NULL o IS NOT NULL para probar ausencia de valor.", hint: "Elige el operador que describa mejor lista, intervalo o patrón." },
    ], labs: [
      { title: "Clientes activos de Lima", desc: "Prepara una audiencia local aplicando dos condiciones.", prompt: "Devuelve `nombre`, `ciudad` y `activo` para clientes de Lima con activo igual a 1. Estructura: filtra ciudad y estado con WHERE y AND. Resultado exacto: 1 fila, Ana García en Lima.", solution: "SELECT nombre, ciudad, activo FROM clientes WHERE ciudad = 'Lima' AND activo = 1;", rows: 1, columns: ["nombre", "ciudad", "activo"], values: [{ column: "nombre", value: "Ana García" }], patterns: [/where/i, /and/i, /ciudad\s*=\s*'Lima'/i, /activo\s*=\s*1/i], hint: "Los dos criterios deben ser verdaderos para incluir al cliente." },
    ], questions: [
      { q: "¿Qué filas admite `ciudad IN ('Lima','Bogotá')`?", options: ["Las de Lima o Bogotá", "Las que pertenecen a ambas ciudades a la vez", "Solo las que tienen ciudad nula", "Todas las filas"], correct: 0, explain: "IN comprueba si el valor pertenece a cualquiera de los elementos enumerados." },
      { q: "¿Por qué `email = NULL` no comprueba correctamente los valores ausentes?", options: ["Debe usarse IS NULL", "NULL siempre es texto", "WHERE no acepta columnas de texto", "= solo funciona con fechas"], correct: 0, explain: "SQL usa IS NULL e IS NOT NULL para comprobar ausencia." },
      { q: "¿Cuándo es adecuado BETWEEN 20 AND 30?", options: ["Al filtrar un intervalo cuyos dos extremos se incluyen", "Al unir dos tablas", "Al ordenar dos columnas", "Al seleccionar un alias"], correct: 0, explain: "BETWEEN incluye 20 y 30 además de los valores intermedios." },
      { q: "¿Qué patrón encuentra nombres que empiezan con A?", options: ["LIKE 'A%'", "LIKE '%A'", "LIKE '_A_'", "= 'A%'"], correct: 0, explain: "% admite cualquier secuencia después de la A inicial." },
    ],
  },
  {
    title: "Ordenar y limitar resultados", level: "principiante", goal: "Ordenar con criterios explícitos y seleccionar un subconjunto reproducible.", readings: [
      { title: "Orden ascendente y descendente", desc: "Controla la secuencia de filas con criterios y desempates claros.", analogy: "Acomoda fichas por precio y decide cómo ordenar los empates.", example: "SELECT nombre, edad FROM clientes ORDER BY ciudad ASC, edad DESC;", points: ["ASC ordena ascendente; DESC, descendente.", "Se pueden encadenar criterios de desempate.", "Sin ORDER BY, el orden no está garantizado."], note: "Ordenar una sola columna no equivale a filtrar ni modifica los datos fuente.", tip: "Agrega una clave secundaria si los empates requieren un orden estable.", hint: "Decide primero el criterio principal y luego cómo resolver empates." },
      { title: "LIMIT y top N", desc: "Recorta un resultado ordenado para responder preguntas de prioridad.", analogy: "Primero se clasifica una lista; después se conservan los primeros puestos.", example: "SELECT nombre, precio FROM productos ORDER BY precio ASC LIMIT 2;", points: ["LIMIT restringe el número de filas devueltas.", "Combínalo con ORDER BY para formar un Top N.", "Un límite sin orden no define qué filas son las primeras."], note: "TOP y ROWNUM no forman parte de este simulador; aquí se usa LIMIT.", tip: "Ordena antes de limitar para hacer explícita la selección.", hint: "Asegura el orden deseado antes de decidir cuántas filas conservar." },
    ], labs: [
      { title: "Tres productos líderes", desc: "Encuentra los primeros productos del catálogo por precio.", prompt: "Devuelve exactamente `nombre` y `precio` de los tres productos más caros, de mayor a menor. Resultado: 3 filas; Laptop Pro con 1200 debe encabezar la lista.", solution: "SELECT nombre, precio FROM productos ORDER BY precio DESC LIMIT 3;", rows: 3, columns: ["nombre", "precio"], values: [{ column: "nombre", value: "Laptop Pro" }, { column: "precio", value: 1200 }], patterns: [/select\s+nombre\s*,\s*precio/i, /order\s+by\s+precio\s+desc/i, /limit\s+3\b/i], combined: /order\s+by[\s\S]*limit\s+3/i, hint: "Ordena precio de mayor a menor y conserva solo las primeras tres filas." },
      { title: "Clientes más jóvenes", desc: "Prioriza dos clientes con menor edad para una revisión de servicio.", prompt: "Devuelve `nombre` y `edad` de los dos clientes de menor edad, ordenados ascendentemente por edad. Resultado: 2 filas; Diego Rojas, 19, aparece primero.", solution: "SELECT nombre, edad FROM clientes ORDER BY edad ASC LIMIT 2;", rows: 2, columns: ["nombre", "edad"], values: [{ column: "nombre", value: "Diego Rojas" }, { column: "edad", value: 19 }], patterns: [/order\s+by\s+edad\s+asc/i, /limit\s+2\b/i], combined: /order\s+by[\s\S]*limit\s+2/i, hint: "Para seleccionar edades pequeñas, ordena ascendentemente antes de aplicar LIMIT." },
    ], questions: [
      { q: "¿Qué representa `ORDER BY precio DESC LIMIT 1`?", options: ["La fila con el precio mayor", "El precio promedio", "Todos los productos", "La fila más barata"], correct: 0, explain: "DESC coloca primero el valor mayor y LIMIT 1 conserva solo esa fila." },
      { q: "¿Qué falla en un Top 3 que aplica LIMIT sin ORDER BY?", options: ["No define qué registros ocupan los tres primeros lugares", "Borra los demás productos", "Crea un índice", "Agrupa los productos por precio"], correct: 0, explain: "LIMIT no establece por sí mismo una clasificación." },
      { q: "¿Para qué agregar edad como segundo criterio si ya ordenas por ciudad?", options: ["Para desempatar clientes de la misma ciudad", "Para filtrar ciudades", "Para cambiar la tabla", "Para limitar columnas"], correct: 0, explain: "El segundo criterio define la secuencia dentro de empates del primero." },
      { q: "¿Qué cláusula de este motor acota el número de filas?", options: ["LIMIT", "TOP", "ROWNUM", "FETCH FIRST"], correct: 0, explain: "La sintaxis admitida para recortar resultados es LIMIT." },
    ],
  },
  {
    title: "Funciones de agregación", level: "principiante", goal: "Resumir registros con conteos, sumas, promedios y extremos verificables.", readings: [
      { title: "COUNT y valores distintos", desc: "Distingue cantidad de filas, valores presentes y categorías únicas.", analogy: "Contar recibos no es lo mismo que contar teléfonos registrados o ciudades diferentes.", example: "SELECT COUNT(DISTINCT categoria_id) FROM productos;", points: ["COUNT(*) cuenta filas.", "COUNT(columna) ignora valores NULL.", "COUNT(DISTINCT columna) cuenta valores únicos no nulos."], note: "COUNT(columna) y COUNT(*) divergen cuando existen valores ausentes.", tip: "Verifica si la pregunta habla de registros o de valores de un campo.", hint: "Identifica cuál unidad se cuenta: filas completas o valores distintos de una columna." },
      { title: "SUM, AVG, MIN y MAX", desc: "Calcula indicadores de volumen y rango para una medida numérica.", analogy: "Un resumen de caja muestra total, promedio y los importes extremos.", example: "SELECT AVG(cantidad), MIN(cantidad), MAX(cantidad) FROM ventas;", points: ["SUM totaliza una medida numérica.", "AVG calcula la media aritmética.", "MIN y MAX devuelven los extremos."], note: "Un promedio necesita una unidad y una población bien definidas.", tip: "Asigna alias con significado de negocio a cada indicador.", hint: "Relaciona cada pregunta de negocio con la agregación que la responde." },
    ], labs: [
      { title: "Resumen de catálogo", desc: "Compara tamaño, promedio y rango de precios disponibles.", prompt: "Devuelve una sola fila con `total`, `promedio`, `minimo` y `maximo`, usando COUNT(*), AVG(precio), MIN(precio) y MAX(precio). Resultado: 6 productos, mínimo 25 y máximo 1200.", solution: "SELECT COUNT(*) AS total, AVG(precio) AS promedio, MIN(precio) AS minimo, MAX(precio) AS maximo FROM productos;", rows: 1, columns: ["total", "promedio", "minimo", "maximo"], values: [{ column: "total", value: 6 }, { column: "minimo", value: 25 }, { column: "maximo", value: 1200 }], patterns: [/count\s*\(\s*\*\s*\)/i, /avg\s*\(\s*precio\s*\)/i, /min\s*\(\s*precio\s*\)/i, /max\s*\(\s*precio\s*\)/i], hint: "Sin GROUP BY, las cuatro funciones devuelven una única fila resumen." },
      { title: "Ciudades únicas de clientes", desc: "Compara el número de clientes con la diversidad de sus ciudades.", prompt: "Devuelve `clientes` con COUNT(*) y `ciudades` con COUNT(DISTINCT ciudad). Resultado exacto: 6 clientes y 4 ciudades únicas.", solution: "SELECT COUNT(*) AS clientes, COUNT(DISTINCT ciudad) AS ciudades FROM clientes;", rows: 1, columns: ["clientes", "ciudades"], values: [{ column: "clientes", value: 6 }, { column: "ciudades", value: 4 }], patterns: [/count\s*\(\s*distinct\s+ciudad\s*\)/i], hint: "Cuenta todas las filas y luego usa DISTINCT para ignorar ciudades repetidas." },
    ], questions: [
      { q: "¿Qué cuenta COUNT(*)?", options: ["Todas las filas", "Solo las columnas", "La suma de los importes", "Únicamente valores distintos"], correct: 0, explain: "COUNT(*) cuenta cada registro del conjunto, incluso si alguna columna contiene NULL." },
      { q: "¿Qué diferencia COUNT(email) de COUNT(*) cuando hay emails NULL?", options: ["COUNT(email) ignora los NULL", "COUNT(*) ignora todos los NULL de fila", "COUNT(email) cuenta columnas", "No hay diferencia"], correct: 0, explain: "COUNT aplicado a una columna cuenta solo valores no nulos." },
      { q: "¿Qué agregación usarías para calcular el precio más alto?", options: ["MAX", "AVG", "COUNT", "LOWER"], correct: 0, explain: "MAX devuelve el valor numérico mayor del conjunto." },
      { q: "¿Para qué sirve COUNT(DISTINCT ciudad)?", options: ["Contar ciudades únicas", "Contar clientes activos", "Sumar las ventas por ciudad", "Ordenar ciudades alfabéticamente"], correct: 0, explain: "DISTINCT elimina repeticiones antes del conteo." },
    ],
  },
  {
    title: "Agrupaciones y filtros de grupo", level: "principiante", goal: "Definir la granularidad de un resumen y filtrar grupos con HAVING.", readings: [
      { title: "GROUP BY y granularidad", desc: "Construye una fila de resumen por cada valor de dimensión.", analogy: "Separar recibos en cajas por ciudad y calcular un total por caja.", example: "SELECT categoria_id, COUNT(*) FROM productos GROUP BY categoria_id;", points: ["GROUP BY crea un grupo por clave.", "Cada columna no agregada del SELECT debe aparecer en GROUP BY.", "La granularidad del resultado queda definida por esas claves."], note: "Mezclar una columna no agrupada con agregaciones produce resultados ambiguos o inválidos.", tip: "Escribe primero qué representa cada fila de salida y luego selecciona las dimensiones.", hint: "Antes de agrupar, completa la frase: una fila del resultado representa…" },
      { title: "WHERE frente a HAVING", desc: "Aplica filtros en la etapa adecuada de una consulta agregada.", analogy: "Primero separas recibos elegibles; después decides qué cajas tienen volumen suficiente.", example: "SELECT ciudad, COUNT(*) AS total FROM clientes GROUP BY ciudad HAVING COUNT(*) > 1;", points: ["WHERE filtra filas antes de formar grupos.", "HAVING filtra grupos después de agregarlos.", "El flujo pasa por FROM, WHERE, GROUP BY, HAVING, SELECT y ORDER BY."], note: "Usar HAVING para una condición por fila puede añadir complejidad innecesaria.", tip: "Filtra filas con WHERE y reserva HAVING para reglas sobre agregados.", hint: "Pregunta si el criterio se evalúa sobre un registro o sobre un resumen." },
      { title: "Diseñar resúmenes útiles", desc: "Convierte preguntas analíticas en dimensiones y métricas explícitas.", analogy: "Un informe define sus encabezados antes de calcular cada subtotal.", example: "SELECT producto_id, SUM(cantidad) AS unidades FROM ventas GROUP BY producto_id;", points: ["Las dimensiones describen cada grupo.", "Las agregaciones calculan sus métricas.", "Los alias hacen reutilizable el resultado."], note: "Un total agregado sin declarar su población puede llevar a interpretaciones erróneas.", tip: "Comprueba al menos un grupo manualmente antes de compartir el resumen.", hint: "Separa la dimensión que identifica filas de salida de la métrica que quieres calcular." },
    ], labs: [
      { title: "Unidades por producto", desc: "Detecta qué productos concentran mayor cantidad de ventas.", prompt: "Agrupa ventas por `producto_id`; devuelve `num_ventas` con COUNT(*) y `total_vendido` con SUM(cantidad). Ordena por total_vendido descendente. Resultado: 6 filas; el producto 2 suma 18 unidades y el producto 1 suma 6.", solution: "SELECT producto_id, COUNT(*) AS num_ventas, SUM(cantidad) AS total_vendido FROM ventas GROUP BY producto_id ORDER BY total_vendido DESC;", rows: 6, columns: ["producto_id", "num_ventas", "total_vendido"], values: [{ column: "producto_id", value: 2 }, { column: "total_vendido", value: 18 }], patterns: [/group\s+by\s+producto_id/i, /count\s*\(\s*\*\s*\)\s+as\s+num_ventas/i, /sum\s*\(\s*cantidad\s*\)\s+as\s+total_vendido/i], combined: /group\s+by[\s\S]*order\s+by/i, hint: "Agrupa por clave de producto antes de contar ventas y sumar las unidades." },
      { title: "Ciudades con varios clientes", desc: "Encuentra zonas con más de un cliente registrado.", prompt: "Agrupa clientes por ciudad y cuenta como `total`; conserva grupos con más de un cliente usando HAVING. Resultado: 2 filas, Lima y Santiago, ambas con total 2.", solution: "SELECT ciudad, COUNT(*) AS total FROM clientes GROUP BY ciudad HAVING COUNT(*) > 1 ORDER BY ciudad ASC;", rows: 2, columns: ["ciudad", "total"], values: [{ column: "ciudad", value: "Lima" }, { column: "total", value: 2 }], patterns: [/group\s+by\s+ciudad/i, /having\s+count\s*\(\s*\*\s*\)\s*>\s*1/i], combined: /group\s+by[\s\S]*having/i, hint: "COUNT crea el resumen por ciudad y HAVING decide qué grupos conservar." },
    ], questions: [
      { q: "¿Qué representa cada fila de `SELECT ciudad, COUNT(*) FROM clientes GROUP BY ciudad`?", options: ["Una ciudad con su cantidad de clientes", "Un cliente con todas sus ciudades", "Una columna de la tabla", "El total de ventas"], correct: 0, explain: "GROUP BY ciudad crea un grupo y COUNT lo resume en una fila." },
      { q: "¿Qué error aparece al incluir nombre en SELECT sin agregarlo ni agruparlo?", options: ["El resultado ya no tiene una fila definida por grupo", "SQL convierte nombre a número", "Se crea una clave primaria", "ORDER BY deja de funcionar"], correct: 0, explain: "Toda columna proyectada que no sea agregada debe formar parte de GROUP BY." },
      { q: "¿Cuándo corresponde HAVING en vez de WHERE?", options: ["Al filtrar grupos según COUNT o SUM", "Al elegir una columna antes de FROM", "Al renombrar una tabla", "Al ordenar registros"], correct: 0, explain: "HAVING evalúa condiciones sobre resultados agregados." },
      { q: "¿Qué etapa ocurre antes de HAVING?", options: ["GROUP BY", "ORDER BY", "LIMIT", "Alias"], correct: 0, explain: "Primero se forman los grupos; luego HAVING los filtra." },
    ],
  },
  {
    title: "INNER JOIN y relaciones", level: "intermedio", goal: "Combinar tablas por PK y FK sin crear duplicaciones accidentales.", readings: [
      { title: "INNER JOIN mediante ON", desc: "Relaciona filas coincidentes usando claves compatibles.", analogy: "Cruzar dos listas por un código común para completar una ficha.", example: "SELECT c.nombre, v.id FROM clientes c INNER JOIN ventas v ON c.id = v.cliente_id;", points: ["ON expresa la relación entre columnas.", "INNER JOIN conserva coincidencias de ambos lados.", "Una FK suele apuntar a una PK única."], note: "Una condición ON ausente o equivocada puede multiplicar filas como un producto cartesiano.", tip: "Confirma claves y conteo de filas al añadir cada unión.", hint: "Dibuja qué clave foránea apunta a qué clave primaria antes de enlazar tablas." },
      { title: "Alias y uniones múltiples", desc: "Enriquece registros de venta con sus dimensiones descriptivas.", analogy: "Un recibo se completa buscando la ficha de su cliente y del producto vendido.", example: "SELECT p.nombre, ca.nombre FROM productos p JOIN categorias ca ON p.categoria_id = ca.id;", points: ["Los alias reducen repeticiones en consultas largas.", "Cada JOIN necesita una condición ON.", "Las FK de ventas conectan cliente y producto."], note: "Una unión válida aún puede cambiar la granularidad si la clave relacionada no es única.", tip: "Parte de la tabla que representa el evento y añade dimensiones por su clave.", hint: "Piensa en cada JOIN como un paso de la venta hacia una dimensión." },
    ], labs: [
      { title: "Ventas con nombres", desc: "Entrega un detalle legible para revisar cada transacción.", prompt: "Combina ventas con clientes y productos por sus claves. Devuelve `cliente`, `producto` y `cantidad`, exactamente en ese orden. Resultado: 10 filas; la venta 1 corresponde a Ana García y Laptop Pro.", solution: "SELECT c.nombre AS cliente, p.nombre AS producto, v.cantidad FROM ventas v INNER JOIN clientes c ON v.cliente_id = c.id INNER JOIN productos p ON v.producto_id = p.id;", rows: 10, columns: ["cliente", "producto", "cantidad"], values: [{ column: "cliente", value: "Ana García" }, { column: "producto", value: "Laptop Pro" }], patterns: [/join\s+clientes/i, /join\s+productos/i, /on\s+v\.cliente_id\s*=\s*c\.id/i, /on\s+v\.producto_id\s*=\s*p\.id/i], combined: /join\s+clientes[\s\S]*join\s+productos/i, hint: "Comienza en ventas y conecta cada clave foránea con su tabla descriptiva." },
      { title: "Ventas con categorías", desc: "Añade el nombre de categoría a cada línea vendida.", prompt: "Une ventas con productos y categorías. Devuelve `categoria` y `cantidad`; resultado exacto: 10 filas. La primera venta pertenece a Computadoras; la segunda, a Accesorios.", solution: "SELECT ca.nombre AS categoria, v.cantidad FROM ventas v INNER JOIN productos p ON v.producto_id = p.id INNER JOIN categorias ca ON p.categoria_id = ca.id ORDER BY v.id ASC;", rows: 10, columns: ["categoria", "cantidad"], values: [{ column: "categoria", value: "Computadoras" }], patterns: [/join\s+productos/i, /join\s+categorias/i, /on\s+p\.categoria_id\s*=\s*ca\.id/i, /order\s+by\s+v\.id\s+asc/i], combined: /join\s+productos[\s\S]*join\s+categorias/i, hint: "Sigue la ruta ventas → productos → categorías usando cada FK." },
    ], questions: [
      { q: "¿Qué filas devuelve INNER JOIN?", options: ["Las que cumplen la condición de unión en ambos lados", "Todas las filas de la tabla izquierda", "Solo filas sin correspondencia", "Una fila por columna"], correct: 0, explain: "INNER JOIN conserva registros con una coincidencia válida según ON." },
      { q: "¿Qué puede causar un ON incorrecto entre dos tablas?", options: ["Una multiplicación inesperada de filas", "Una agrupación automática", "Que SQL cree una PK", "Que LIMIT cambie de posición"], correct: 0, explain: "Una relación equivocada puede producir combinaciones cartesianas o duplicadas." },
      { q: "¿Por qué usar alias en una consulta con varias tablas?", options: ["Para identificar el origen de cada columna con claridad", "Para reemplazar todas las claves", "Para eliminar filas repetidas", "Para omitir ON"], correct: 0, explain: "Alias cortos hacen legibles referencias como v.cliente_id y c.id." },
      { q: "Si cada fila representa una venta, ¿qué tabla suele ser buen punto de partida?", options: ["ventas", "categorias sin unión", "Una tabla de salida vacía", "clientes siempre, sin importar la pregunta"], correct: 0, explain: "La tabla de hechos define el evento y se puede enriquecer con dimensiones." },
    ],
  },
  {
    title: "LEFT y RIGHT JOIN aplicados", level: "intermedio", goal: "Conservar el lado elegido de una unión e identificar ausencias con NULL.", readings: [
      { title: "Conservar filas con LEFT JOIN", desc: "Mantiene todas las filas izquierdas aunque falte una coincidencia derecha.", analogy: "Pasar lista a todo un equipo aunque algunas personas aún no tengan compras.", example: "SELECT c.nombre, v.id FROM clientes c LEFT JOIN ventas v ON c.id = v.cliente_id;", points: ["LEFT JOIN conserva el conjunto de la izquierda.", "Columnas sin pareja del lado derecho se completan con NULL.", "IS NULL permite detectar filas sin correspondencia."], note: "Un filtro WHERE sobre columnas derechas puede descartar esas filas y cambiar el resultado esperado.", tip: "Elige como lado izquierdo la población que no quieres perder.", hint: "Decide primero qué conjunto debe permanecer completo aunque no haya relación." },
      { title: "RIGHT JOIN y población base", desc: "Conserva todas las filas del lado derecho y sus coincidencias izquierdas.", analogy: "Revisar todas las transacciones aunque falte la ficha descriptiva de alguna.", example: "SELECT v.id, p.nombre FROM productos p RIGHT JOIN ventas v ON p.id = v.producto_id;", points: ["RIGHT JOIN conserva la tabla derecha.", "Las columnas izquierdas no coincidentes resultan NULL.", "Intercambiar tablas permite expresar muchos casos con LEFT JOIN."], note: "No sustituyas NULL por cero sin una regla de negocio que lo justifique.", tip: "Nombra en el informe cuál población se conserva.", hint: "Compara mentalmente qué tabla quedaría intacta si inviertes el orden de un LEFT JOIN." },
    ], labs: [
      { title: "Conservar todas las ventas", desc: "Comprueba el número de ventas incluso al enriquecer con productos.", prompt: "Usa RIGHT JOIN para conservar ventas y mostrar `venta_id` junto al nombre `producto`. Resultado: 10 filas, ordenadas por venta_id ascendente; la primera es la venta 1 de Laptop Pro.", solution: "SELECT v.id AS venta_id, p.nombre AS producto FROM productos p RIGHT JOIN ventas v ON p.id = v.producto_id ORDER BY venta_id ASC;", rows: 10, columns: ["venta_id", "producto"], values: [{ column: "venta_id", value: 1 }, { column: "producto", value: "Laptop Pro" }], patterns: [/right\s+join\s+ventas/i, /on\s+p\.id\s*=\s*v\.producto_id/i, /order\s+by\s+venta_id\s+asc/i], combined: /right\s+join[\s\S]*order\s+by/i, hint: "Pon ventas a la derecha del RIGHT JOIN para conservar sus diez registros." },
      { title: "Clientes sin ventas", desc: "Usa una unión externa para buscar clientes sin transacciones.", prompt: "Con LEFT JOIN entre clientes y ventas, devuelve `nombre` de clientes sin venta, comprobando `v.id IS NULL`. La estructura debe preservar clientes; resultado exacto con estos datos: 0 filas y una columna nombre.", solution: "SELECT c.nombre FROM clientes c LEFT JOIN ventas v ON c.id = v.cliente_id WHERE v.id IS NULL;", rows: 0, columns: ["nombre"], values: [], patterns: [/left\s+join\s+ventas/i, /where\s+v\.id\s+is\s+null/i], combined: /left\s+join[\s\S]*is\s+null/i, hint: "Conserva clientes y busca un identificador de venta ausente en el lado derecho." },
    ], questions: [
      { q: "¿Qué devuelve `SELECT c.nombre, v.id FROM clientes c LEFT JOIN ventas v ON c.id = v.cliente_id`?", options: ["Todos los clientes con sus ventas cuando existen", "Solo las ventas sin cliente", "Solo clientes con dos ventas", "Un conteo por ciudad"], correct: 0, explain: "LEFT JOIN conserva clientes y completa con NULL las ventas no coincidentes." },
      { q: "¿Qué valor aparece en una columna derecha sin coincidencia en LEFT JOIN?", options: ["NULL", "Siempre cero", "El último valor visto", "Una cadena vacía obligatoria"], correct: 0, explain: "El motor expresa ausencia de fila coincidente mediante NULL." },
      { q: "¿Cuándo usarías WHERE v.id IS NULL tras un LEFT JOIN?", options: ["Para encontrar clientes sin venta", "Para encontrar todos los clientes con venta", "Para ordenar los productos", "Para contar columnas"], correct: 0, explain: "La condición identifica filas izquierdas que no tienen identificador de venta." },
      { q: "¿Qué conserva RIGHT JOIN en el laboratorio?", options: ["Todas las ventas del lado derecho", "Solo productos sin ventas", "Solo las filas de clientes", "Todas las columnas de todas las tablas"], correct: 0, explain: "RIGHT JOIN mantiene todas las filas de la tabla que aparece a la derecha." },
    ],
  },
  {
    title: "Texto, números y CASE WHEN", level: "intermedio", goal: "Transformar valores de salida y clasificar registros con expresiones legibles.", readings: [
      { title: "Funciones de texto", desc: "Normaliza etiquetas y deriva atributos de cadenas sin cambiar la tabla.", analogy: "Limpiar y etiquetar fichas para que un catálogo pueda leerse de forma uniforme.", example: "SELECT LOWER(ciudad), LENGTH(nombre) FROM clientes;", points: ["UPPER y LOWER cambian mayúsculas y minúsculas.", "LENGTH cuenta caracteres.", "CONCAT compone una etiqueta con varios valores."], note: "Las funciones de salida no actualizan el texto almacenado.", tip: "Conserva los campos originales si la normalización debe auditarse.", hint: "Decide si necesitas cambiar capitalización, medir texto o componer una etiqueta." },
      { title: "CASE WHEN para clasificar", desc: "Crea categorías calculadas a partir de condiciones evaluadas en orden.", analogy: "Un clasificador coloca cada paquete en la primera categoría que satisface.", example: "SELECT nombre, CASE WHEN activo = 1 THEN 'Vigente' ELSE 'Revisar' END AS estado FROM clientes;", points: ["CASE evalúa cada WHEN en orden.", "ELSE define el caso restante.", "END termina la expresión calculada."], note: "Una regla general primero puede capturar filas destinadas a un umbral más específico.", tip: "Ordena los umbrales de mayor especificidad a menor.", hint: "Escribe las condiciones de categoría en el orden en que deberían evaluarse." },
      { title: "Funciones numéricas y NULL", desc: "Redondea medidas y define alternativas explícitas para valores ausentes.", analogy: "Redondear una cuenta fija su precisión; una regla de respaldo decide qué mostrar si falta un dato.", example: "SELECT ROUND(precio / 3, 2), ABS(precio - 100) FROM productos;", points: ["ROUND(n, d) fija decimales de salida.", "ABS calcula magnitud no negativa.", "COALESCE devuelve el primer argumento no nulo."], note: "COALESCE puede esconder faltantes si se elige un reemplazo sin significado acordado.", tip: "Documenta la política usada para valores ausentes.", hint: "Piensa qué precisión comunica el negocio y qué representa un valor faltante." },
    ], labs: [
      { title: "Segmentación por edad", desc: "Prepara grupos de clientes para una comunicación diferenciada.", prompt: "Devuelve `nombre` y `categoria` usando CASE: edad >= 40 Senior, edad >= 25 Adulto y el resto Joven. Resultado exacto: 6 filas; Marco Díaz debe ser Senior y Ana García Adulto.", solution: "SELECT nombre, CASE WHEN edad >= 40 THEN 'Senior' WHEN edad >= 25 THEN 'Adulto' ELSE 'Joven' END AS categoria FROM clientes;", rows: 6, columns: ["nombre", "categoria"], values: [{ column: "nombre", value: "Marco Díaz" }, { column: "categoria", value: "Senior" }], patterns: [/case\s+when/i, /end\s+as\s+categoria/i, /from\s+clientes/i], combined: /case[\s\S]*end\s+as\s+categoria/i, hint: "Evalúa primero el umbral mayor, luego el intermedio y deja el resto para ELSE." },
      { title: "Etiquetas de producto", desc: "Presenta nombres normalizados junto con un precio redondeado.", prompt: "Devuelve `producto` con UPPER(nombre) y `precio_unitario` con ROUND(precio, 0), desde productos. Resultado: 6 filas; la primera etiqueta debe ser LAPTOP PRO y precio 1200.", solution: "SELECT UPPER(nombre) AS producto, ROUND(precio, 0) AS precio_unitario FROM productos;", rows: 6, columns: ["producto", "precio_unitario"], values: [{ column: "producto", value: "LAPTOP PRO" }, { column: "precio_unitario", value: 1200 }], patterns: [/upper\s*\(\s*nombre\s*\)/i, /round\s*\(\s*precio\s*,\s*0\s*\)/i, /as\s+precio_unitario/i], combined: /upper\s*\([\s\S]*round\s*\(/i, hint: "Aplica cada función en SELECT y asigna un alias distinto a cada resultado." },
    ], questions: [
      { q: "¿Qué devuelve LOWER('LIMA')?", options: ["lima", "LIMA", "4", "NULL"], correct: 0, explain: "LOWER convierte letras a minúsculas." },
      { q: "¿Qué error puede causar poner primero una condición CASE demasiado amplia?", options: ["Puede capturar filas antes de evaluar una categoría específica", "Cambia el contenido original", "Crea duplicados en la tabla", "Elimina todas las columnas"], correct: 0, explain: "La primera condición verdadera determina el resultado de CASE." },
      { q: "¿Cuándo usar ROUND(precio, 2)?", options: ["Cuando el reporte debe mostrar dos decimales calculados", "Para ordenar por precio", "Para reemplazar un NULL", "Para unir productos y ventas"], correct: 0, explain: "ROUND limita el resultado numérico a la precisión solicitada." },
      { q: "¿Qué función usa una alternativa explícita si su primer valor es NULL?", options: ["COALESCE", "COUNT", "UPPER", "ABS"], correct: 0, explain: "COALESCE devuelve el primer argumento que no sea NULL." },
    ],
  },
  {
    title: "Subconsultas con IN", level: "intermedio", goal: "Filtrar registros según conjuntos calculados por una subconsulta de una columna.", readings: [
      { title: "Subconsulta dentro de IN", desc: "Usa una consulta interior para producir la lista que necesita un filtro.", analogy: "Primero preparas una lista de identificadores y luego localizas sus nombres.", example: "SELECT nombre FROM clientes WHERE id IN (SELECT cliente_id FROM ventas);", points: ["IN compara un valor con un conjunto.", "La subconsulta debe devolver una sola columna.", "La consulta interior va entre paréntesis."], note: "Este laboratorio admite subconsultas únicamente en WHERE ... IN (...).", tip: "Ejecuta conceptualmente la subconsulta primero y revisa qué lista produce.", hint: "Nombra el identificador producido dentro y el campo que se compara fuera." },
      { title: "Conjuntos relacionados", desc: "Resuelve preguntas de pertenencia sin añadir columnas innecesarias al resultado.", analogy: "Una lista de acceso comprueba pertenencia sin exponer todos los datos de cada ficha.", example: "SELECT nombre FROM productos WHERE categoria_id IN (SELECT id FROM categorias WHERE id = 1);", points: ["La consulta interna puede filtrar la población comparada.", "Una columna de salida basta para una lista IN.", "El filtro exterior conserva el control de columnas finales."], note: "Subconsultas correlacionadas y subconsultas en FROM no se ejecutan en este motor.", tip: "Mantén la subconsulta enfocada en devolver el conjunto exacto que necesitas.", hint: "Comprueba que la columna interior tenga el mismo significado y tipo que la exterior." },
    ], labs: [
      { title: "Clientes con ventas", desc: "Identifica clientes que aparecen en el registro de transacciones.", prompt: "Devuelve `nombre` de clientes cuyo id aparece en la columna cliente_id de ventas usando IN y una subconsulta de una columna. Resultado exacto: 6 filas; incluye Ana García.", solution: "SELECT nombre FROM clientes WHERE id IN (SELECT cliente_id FROM ventas);", rows: 6, columns: ["nombre"], values: [{ column: "nombre", value: "Ana García" }], patterns: [/\bin\s*\(\s*select/i, /select\s+cliente_id\s+from\s+ventas/i], combined: /where[\s\S]*in\s*\([\s\S]*select/i, hint: "La subconsulta obtiene IDs comprados; la consulta externa devuelve sus nombres." },
      { title: "Productos por categoría", desc: "Valida productos relacionados con categorías registradas y prioriza su precio.", prompt: "Devuelve `nombre` y `precio` para productos cuya categoria_id aparece en `SELECT id FROM categorias`. Ordena el precio descendente. Resultado exacto: 6 filas; Laptop Pro con 1200 aparece primero.", solution: "SELECT nombre, precio FROM productos WHERE categoria_id IN (SELECT id FROM categorias) ORDER BY precio DESC;", rows: 6, columns: ["nombre", "precio"], values: [{ column: "nombre", value: "Laptop Pro" }, { column: "precio", value: 1200 }], patterns: [/categoria_id\s+in\s*\(\s*select\s+id\s+from\s+categorias/i, /order\s+by\s+precio\s+desc/i], combined: /where[\s\S]*in\s*\([\s\S]*select[\s\S]*order\s+by/i, hint: "Filtra productos por el conjunto de IDs de categoría y ordena el precio." },
    ], questions: [
      { q: "¿Qué comprueba `id IN (SELECT cliente_id FROM ventas)`?", options: ["Si id aparece entre los clientes con ventas", "El promedio de cada cliente", "Si id es una tabla", "La fecha más reciente"], correct: 0, explain: "IN evalúa pertenencia al conjunto devuelto por la consulta interior." },
      { q: "¿Qué error causa devolver dos columnas desde una subconsulta de IN?", options: ["IN espera una lista de valores de una sola columna", "SQL las suma automáticamente", "Se convierte en RIGHT JOIN", "La consulta externa deja de usar SELECT"], correct: 0, explain: "La expresión izquierda se compara con cada valor de una lista unidimensional." },
      { q: "¿Cuándo ayuda probar conceptualmente primero la subconsulta?", options: ["Al depurar qué valores se comparan", "Para añadir más columnas al resultado exterior", "Para crear una tabla física", "Para ordenar el catálogo"], correct: 0, explain: "Separar los pasos permite comprobar el conjunto antes de aplicar el filtro externo." },
      { q: "¿Qué caracteriza una subconsulta admitida en este bloque práctico?", options: ["Se ubica en IN y devuelve una columna", "Va en FROM y devuelve varias tablas", "Usa EXISTS correlacionado", "Debe crear una vista"], correct: 0, explain: "El subconjunto ejecutable de esta ruta restringe subconsultas a IN de una sola columna." },
    ],
  },
  {
    title: "Análisis combinado de ventas", level: "intermedio", goal: "Integrar JOIN, GROUP BY, agregaciones, filtros y orden para responder preguntas de negocio.", readings: [
      { title: "Cruzar dimensiones y ventas", desc: "Relaciona hechos con atributos de cliente para resumir por zona.", analogy: "Cada recibo se conecta con la ficha del cliente antes de ordenar los totales por región.", example: "SELECT c.ciudad, SUM(v.cantidad) AS unidades FROM ventas v JOIN clientes c ON v.cliente_id = c.id GROUP BY c.ciudad;", points: ["JOIN incorpora la dimensión necesaria.", "GROUP BY define el nivel del resumen.", "SUM calcula la métrica para cada grupo."], note: "Una relación de varios a varios inesperada puede inflar el valor agregado.", tip: "Compara una región de control manualmente y verifica la cardinalidad de la unión.", hint: "Determina primero la unidad de análisis y después incorpora solo sus dimensiones." },
      { title: "Ordenar resultados analíticos", desc: "Prioriza grupos según volumen y limita la lista para una decisión concreta.", analogy: "Una tabla de clasificación ordena las oportunidades antes de elegir las primeras.", example: "SELECT ciudad, COUNT(*) AS clientes FROM clientes GROUP BY ciudad ORDER BY clientes DESC LIMIT 3;", points: ["Los filtros de fila se aplican antes de agrupar.", "HAVING filtra grupos resumidos.", "ORDER BY prioriza los grupos ya calculados."], note: "No presentes un Top N sin especificar el indicador que determina su ranking.", tip: "Explica unidad, métrica y dirección del orden en los nombres de salida.", hint: "Separa los pasos de unión, agregación y orden para localizar errores." },
    ], labs: [
      { title: "Unidades vendidas por ciudad", desc: "Compara volumen de venta entre las principales zonas.", prompt: "Une ventas con clientes, agrupa por ciudad y devuelve `unidades` como SUM(cantidad). Ordena unidades descendente y limita a 3 ciudades. Resultado: Lima 17 unidades aparece primera.", solution: "SELECT c.ciudad, SUM(v.cantidad) AS unidades FROM ventas v INNER JOIN clientes c ON v.cliente_id = c.id GROUP BY c.ciudad ORDER BY unidades DESC LIMIT 3;", rows: 3, columns: ["ciudad", "unidades"], values: [{ column: "ciudad", value: "Lima" }, { column: "unidades", value: 17 }], patterns: [/join\s+clientes/i, /group\s+by\s+c\.ciudad/i, /sum\s*\(\s*v\.cantidad\s*\)/i, /order\s+by\s+unidades\s+desc/i, /limit\s+3/i], combined: /join[\s\S]*group\s+by[\s\S]*order\s+by[\s\S]*limit/i, hint: "Une para obtener ciudad, agrupa, suma cantidades y por último ordena y limita." },
      { title: "Ingresos por categoría", desc: "Calcula qué familias de productos aportan más ingreso.", prompt: "Une ventas, productos y categorías; agrupa por `categoria`; calcula ingreso como SUM(cantidad * precio), y ordena de mayor a menor. Resultado: 3 filas; Computadoras aporta 9100.", solution: "SELECT ca.nombre AS categoria, SUM(v.cantidad * p.precio) AS ingreso FROM ventas v INNER JOIN productos p ON v.producto_id = p.id INNER JOIN categorias ca ON p.categoria_id = ca.id GROUP BY ca.nombre ORDER BY ingreso DESC;", rows: 3, columns: ["categoria", "ingreso"], values: [{ column: "categoria", value: "Computadoras" }, { column: "ingreso", value: 9100 }], patterns: [/join\s+productos/i, /join\s+categorias/i, /sum\s*\(\s*v\.cantidad\s*\*\s*p\.precio\s*\)/i, /group\s+by\s+ca\.nombre/i, /order\s+by\s+ingreso\s+desc/i], combined: /join\s+productos[\s\S]*join\s+categorias[\s\S]*group\s+by/i, hint: "Sigue producto hasta categoría y calcula cada línea antes de sumar por grupo." },
    ], questions: [
      { q: "¿Qué devuelve `SELECT ciudad, SUM(v.cantidad) FROM ventas v JOIN clientes c ON v.cliente_id = c.id GROUP BY ciudad`?", options: ["Un total de unidades por ciudad", "Una fila por producto", "El precio máximo del catálogo", "Un cliente por categoría"], correct: 0, explain: "JOIN aporta ciudad y GROUP BY resume cantidad para cada zona." },
      { q: "¿Qué problema puede inflar SUM después de un JOIN?", options: ["La relación duplica filas por una clave no única", "Un alias es corto", "ORDER BY usa DESC", "Hay menos columnas seleccionadas"], correct: 0, explain: "Las filas repetidas por la unión también se suman repetidamente." },
      { q: "¿Qué patrón elige las tres ciudades de mayor volumen?", options: ["ORDER BY métrica DESC LIMIT 3", "HAVING 3", "WHERE TOP 3", "GROUP BY DESC"], correct: 0, explain: "La consulta clasifica por métrica y limita las primeras filas." },
      { q: "¿Por qué calcular cantidad * precio antes de sumar por categoría?", options: ["Cada venta puede tener cantidades distintas", "JOIN no permite SUM", "GROUP BY requiere texto", "ORDER BY multiplica valores"], correct: 0, explain: "Primero se calcula el ingreso de cada línea y luego se agregan las líneas por categoría." },
    ],
  },
  {
    title: "EXISTS y subconsultas avanzadas", level: "avanzado", goal: "Evaluar conceptualmente subconsultas correlacionadas, EXISTS y tablas derivadas.", readings: [
      { title: "EXISTS y NOT EXISTS", desc: "Interpreta pruebas de existencia y ausencia en relaciones.", analogy: "Comprobar si hay al menos una ficha dentro de cada expediente sin contar todas.", example: "SELECT c.nombre FROM clientes c WHERE EXISTS (SELECT 1 FROM ventas v WHERE v.cliente_id = c.id);", points: ["EXISTS responde si la subconsulta produce filas.", "NOT EXISTS comprueba ausencia de filas relacionadas.", "Estos operadores se estudian aquí conceptualmente."], note: "El simulador del curso no ejecuta EXISTS ni NOT EXISTS.", tip: "Explica si la pregunta busca existencia, ausencia o un conteo numérico.", hint: "Imagina qué evidencia bastaría para confirmar que existe una relación." },
      { title: "Subconsultas correlacionadas", desc: "Reconoce una consulta interior que depende de una fila exterior.", analogy: "Para cada carpeta exterior, revisas si hay una nota relacionada con esa carpeta.", example: "WHERE EXISTS (SELECT 1 FROM ventas v WHERE v.cliente_id = c.id)", points: ["La subconsulta consulta un valor de la fila externa.", "Su resultado puede variar para cada fila exterior.", "No se ejecuta en el editor curricular."], note: "Una subconsulta correlacionada no es automáticamente más rápida ni más clara.", tip: "Compara su legibilidad con una unión o agregación equivalente.", hint: "Busca qué referencia interna depende de la consulta exterior." },
      { title: "Tablas derivadas en FROM", desc: "Comprende resultados intermedios usados como fuente temporal.", analogy: "Primero elaboras un resumen en una hoja y luego lo tratas como otra tabla.", example: "FROM (SELECT ciudad, COUNT(*) AS total FROM clientes GROUP BY ciudad) resumen", points: ["Una subconsulta en FROM produce una tabla derivada.", "El alias nombra ese conjunto temporal.", "El motor del curso no admite esta sintaxis."], note: "Tablas derivadas pueden dificultar la lectura si sus columnas no están documentadas.", tip: "Nombra etapas por el resultado que producen.", hint: "Dibuja las columnas de entrada y salida de cada etapa antes de componerla." },
    ], labs: [], questions: [
      { q: "Conceptualmente, ¿qué nombres selecciona `WHERE EXISTS (ventas relacionadas)`?", options: ["Clientes con al menos una venta relacionada", "Todos los productos", "Solo filas sin cliente", "Un conteo por ciudad"], correct: 0, explain: "EXISTS conserva una fila exterior cuando su consulta relacionada produce al menos un resultado." },
      { q: "¿Qué error vuelve inútil una correlación entre ventas y clientes?", options: ["Omitir la condición que relaciona v.cliente_id con c.id", "Usar alias breves", "Elegir EXISTS para probar presencia", "Seleccionar solo nombre"], correct: 0, explain: "Sin enlazar la fila interior con la exterior, la prueba ya no responde por cada cliente." },
      { q: "¿Qué evaluarías antes de escoger una subconsulta correlacionada?", options: ["Claridad, cardinalidad y plan real del motor", "El color del resultado", "El número de espacios", "El nombre del archivo"], correct: 0, explain: "La elección debe equilibrar significado, legibilidad y desempeño medido." },
      { q: "¿Cuál de estas formas está fuera del laboratorio SQL ejecutable?", options: ["EXISTS correlacionado", "SELECT con WHERE", "INNER JOIN con ON", "COUNT(*) con GROUP BY"], correct: 0, explain: "EXISTS se enseña como concepto, pero no forma parte del subconjunto ejecutable." },
    ],
  },
  {
    title: "CTEs y funciones de ventana", level: "avanzado", goal: "Interpretar CTEs y ventanas analíticas para rankings y comparaciones por grupo.", readings: [
      { title: "CTEs con WITH", desc: "Organiza una consulta compleja en etapas con nombre.", analogy: "Un informe con cálculos intermedios rotulados antes de la conclusión final.", example: "WITH resumen AS (SELECT ciudad, COUNT(*) AS total FROM clientes GROUP BY ciudad) SELECT ciudad FROM resumen;", points: ["WITH declara una expresión tabular común.", "Una CTE puede aclarar consultas por etapas.", "El simulador de prácticas no ejecuta CTEs."], note: "Una CTE mejora organización, pero no garantiza materialización ni velocidad superior.", tip: "Nombra cada etapa por la pregunta que resuelve.", hint: "Separa mentalmente una consulta larga en resultados intermedios con nombres útiles." },
      { title: "OVER y PARTITION BY", desc: "Entiende el marco de filas donde se calcula una ventana analítica.", analogy: "Clasificar estudiantes dentro de cada aula sin retirar sus fichas individuales.", example: "RANK() OVER (PARTITION BY ciudad ORDER BY total DESC)", points: ["OVER define la ventana analítica.", "PARTITION BY reinicia el cálculo en cada grupo.", "ORDER BY define la secuencia de evaluación."], note: "Las funciones de ventana no están implementadas en el editor del curso.", tip: "Define población, partición y orden antes de elegir una función de ventana.", hint: "Identifica dónde reinicia el ranking y qué valor determina la posición." },
      { title: "Rankings y empates", desc: "Compara ROW_NUMBER, RANK y DENSE_RANK para clasificaciones.", analogy: "Una competencia asigna puestos únicos o comparte posición y decide si deja huecos.", example: "DENSE_RANK() OVER (ORDER BY ingreso DESC)", points: ["ROW_NUMBER asigna un ordinal por fila.", "RANK deja huecos después de empates.", "DENSE_RANK evita esos huecos."], note: "Un orden incompleto puede hacer que empates cambien de puesto entre ejecuciones.", tip: "Incluye un desempate estable cuando cada fila necesita posición única.", hint: "Decide si los empates comparten rango o si cada fila requiere un número propio." },
    ], labs: [], questions: [
      { q: "¿Qué puestos representa `RANK() OVER (PARTITION BY ciudad ORDER BY ingreso DESC)`?", options: ["Un ranking de ingreso que vuelve a empezar en cada ciudad", "Una suma de ingreso por todas las ciudades", "Una fila agrupada que elimina el detalle", "Un orden alfabético de nombres"], correct: 0, explain: "La ventana particiona por ciudad y ordena el ranking por ingreso descendente." },
      { q: "¿Qué fallo hace inestable un ranking cuando hay empates?", options: ["No definir un criterio de desempate si se necesita orden determinista", "Usar PARTITION BY", "Nombrar una CTE", "Elegir DENSE_RANK"], correct: 0, explain: "Un orden secundario estable define cuál fila queda primero en un empate." },
      { q: "¿Cómo se diferencian RANK y DENSE_RANK tras un empate?", options: ["RANK deja un hueco; DENSE_RANK continúa sin hueco", "DENSE_RANK elimina filas", "RANK suma los valores", "Son siempre idénticos"], correct: 0, explain: "RANK conserva la posición competitiva y deja huecos; DENSE_RANK no." },
      { q: "¿Qué ventaja ofrece una CTE bien nombrada?", options: ["Hace explícitas las etapas de razonamiento", "Garantiza menor costo siempre", "Crea una tabla permanente", "Evita SELECT"], correct: 0, explain: "Una CTE mejora estructura y comprensión, pero el plan debe medirse aparte." },
    ],
  },
  {
    title: "Optimización, índices y buenas prácticas", level: "avanzado", goal: "Diagnosticar consultas y justificar optimizaciones con planes y mediciones.", readings: [
      { title: "EXPLAIN e índices", desc: "Interpreta planes y evalúa cómo los índices apoyan búsquedas frecuentes.", analogy: "El índice de un libro evita revisar cada página para encontrar un tema.", example: "EXPLAIN SELECT id FROM clientes WHERE ciudad = 'Lima';", points: ["EXPLAIN permite inspeccionar un plan conceptual.", "Un índice puede acelerar filtros y uniones selectivos.", "Cada índice ocupa espacio y encarece escrituras."], note: "La práctica no ejecuta EXPLAIN ni crea índices.", tip: "Decide con planes reales y datos representativos, no por intuición.", hint: "Piensa qué parte de la consulta obliga al motor a revisar más registros." },
      { title: "SELECT eficiente y SARGable", desc: "Reduce trabajo evitable y conserva filtros que aprovechan índices.", analogy: "Buscar por una etiqueta exacta es más directo que abrir cada caja para leerla.", example: "SELECT id, ciudad FROM clientes WHERE ciudad = 'Lima';", points: ["Solicita solo columnas necesarias.", "Un predicado SARGable puede usar un índice adecuado.", "Aplicar funciones al campo filtrado puede impedir ese uso."], note: "La SARGabilidad depende del motor, índice, tipo y estadísticas disponibles.", tip: "Comprueba el plan después de modificar un predicado.", hint: "Identifica si filtras directamente por columna o transformas su valor primero." },
      { title: "Medir y validar cambios", desc: "Compara el plan y la duración sin cambiar la semántica del resultado.", analogy: "Un cronómetro compara el proceso antes y después de cambiar una estación.", example: "Revisar filas estimadas frente a filas reales del plan", points: ["Define una consulta de referencia.", "Cambia una sola variable por prueba.", "Comprueba exactitud y rendimiento."], note: "Una consulta más rápida no es una mejora si devuelve otro conjunto de resultados.", tip: "Registra volumen, filtros, entorno y medición.", hint: "Separa lo que esperas mejorar de cómo verificarás que no cambió el resultado." },
    ], labs: [], questions: [
      { q: "¿Qué muestra conceptualmente `EXPLAIN SELECT id FROM clientes WHERE ciudad = 'Lima'`?", options: ["El plan que propone el motor para esa búsqueda", "Las filas eliminadas", "Los permisos de usuarios", "Una tabla nueva"], correct: 0, explain: "EXPLAIN ayuda a revisar las operaciones elegidas para ejecutar la consulta." },
      { q: "¿Qué error puede impedir aprovechar un índice en una columna filtrada?", options: ["Envolver la columna en una función dentro del predicado", "Seleccionar su clave primaria", "Usar un alias en otra tabla", "Limitar filas después de ordenar"], correct: 0, explain: "Transformar la columna puede hacer que el predicado deje de ser SARGable." },
      { q: "¿Por qué evitar SELECT * en una extracción profesional?", options: ["Limita columnas innecesarias y estabiliza el resultado", "Es sintaxis prohibida en todos los motores", "Elimina filas automáticamente", "Crea un índice"], correct: 0, explain: "Seleccionar columnas explícitas controla transferencia y contrato de datos." },
      { q: "¿Cómo demostrarías que una optimización es válida?", options: ["Comparando plan, tiempo y equivalencia de resultados", "Contando caracteres SQL", "Cambiando alias", "Quitando todos los índices"], correct: 0, explain: "La evidencia debe incluir desempeño y semántica del resultado." },
    ],
  },
  {
    title: "Diseño y normalización de datos", level: "avanzado", goal: "Modelar entidades y dependencias para proteger integridad y soportar análisis.", readings: [
      { title: "Formas normales esenciales", desc: "Reconoce redundancia y anomalías al organizar atributos relacionados.", analogy: "Guardar cada dirección una vez evita corregir copias inconsistentes en muchos formularios.", example: "Separar clientes(id, nombre) de ventas(id, cliente_id, fecha)", points: ["1FN mantiene valores atómicos.", "2FN elimina dependencias parciales de claves compuestas.", "3FN reduce dependencias transitivas."], note: "La normalización organiza dependencias, pero el modelo analítico puede preparar otra estructura derivada.", tip: "Documenta claves y dependencias antes de dividir o combinar tablas.", hint: "Busca si un atributo describe toda la clave o solo parte de ella." },
      { title: "Modelo entidad-relación", desc: "Representa entidades, claves, relaciones y cardinalidades del negocio.", analogy: "Un plano muestra conexiones y proporciones antes de construir un edificio.", example: "clientes.id 1 ── N ventas.cliente_id", points: ["Una entidad representa un concepto.", "PK identifica y FK referencia.", "Cardinalidad declara cuántas filas pueden relacionarse."], note: "Una relación dibujada sin validar unicidad puede producir un modelo inconsistente.", tip: "Especifica el grano y las reglas con quienes conocen el proceso.", hint: "Traza las relaciones de las tablas de tienda usando sus claves reales." },
      { title: "OLTP y esquema estrella", desc: "Distingue el diseño transaccional del modelo dimensional para análisis.", analogy: "El archivo operativo conserva cada trámite; el tablero organiza vistas para comparar.", example: "Hechos ventas → dimensiones cliente, producto y fecha", points: ["OLTP prioriza transacciones e integridad.", "Una tabla de hechos registra eventos medibles.", "Las dimensiones aportan contexto de análisis."], note: "Desnormalizar para analítica requiere definiciones y linaje documentados.", tip: "Conserva una tabla de hechos con grano explícito y dimensiones coherentes.", hint: "Decide qué tabla representa eventos y cuáles describen perspectivas del evento." },
    ], labs: [], questions: [
      { q: "¿Qué representa `SELECT ciudad, COUNT(*) FROM clientes GROUP BY ciudad`?", options: ["Una fila por ciudad con su conteo", "Una fila por persona y cada venta", "Solo la ciudad más grande", "Una estructura de almacenamiento nueva"], correct: 0, explain: "La consulta agrupa por ciudad y devuelve un conteo para cada grupo." },
      { q: "¿Qué problema hay al guardar varios teléfonos separados por comas en una columna?", options: ["El atributo no es atómico y cuesta filtrar cada teléfono", "Se crea una dimensión automáticamente", "La clave primaria se vuelve única", "ORDER BY deja de funcionar"], correct: 0, explain: "La primera forma normal organiza valores atómicos, uno por atributo y fila." },
      { q: "¿Qué distingue un esquema estrella?", options: ["Hechos conectados a dimensiones descriptivas", "Una tabla sin relaciones", "Una función de ventana", "Un conjunto de permisos"], correct: 0, explain: "Las dimensiones entregan contexto alrededor de métricas almacenadas en hechos." },
      { q: "¿Por qué documentar el grano de una tabla de hechos?", options: ["Define qué significa cada fila y evita mezclar niveles", "Cambia el índice", "Permite quitar claves", "Reduce nombres de columnas"], correct: 0, explain: "El grano es la unidad de registro sobre la que son válidas las agregaciones." },
    ],
  },
  {
    title: "Proyecto integrador y seguridad", level: "avanzado", goal: "Construir y defender un análisis de ventas con consultas verificables y criterios seguros.", readings: [
      { title: "Transacciones y principios ACID", desc: "Comprende cómo una transacción protege cambios relacionados ante fallos.", analogy: "Un pago y su asiento deben confirmarse juntos o dejarse sin cambios.", example: "BEGIN; validar cambios; COMMIT o ROLLBACK (conceptual)", points: ["Atomicidad evita confirmar cambios parciales.", "Consistencia conserva reglas de integridad.", "Aislamiento y durabilidad protegen concurrencia y persistencia."], note: "El motor curricular es solo de lectura y no ejecuta transacciones.", tip: "Diseña el escenario de error y recuperación antes de escribir operaciones.", hint: "Piensa qué operaciones tendrían que aprobarse o revertirse como una unidad." },
      { title: "Permisos y análisis reproducible", desc: "Aplica mínimo privilegio y documenta fuentes, métricas y supuestos.", analogy: "Cada equipo recibe la llave de los espacios que necesita y no de todos.", example: "GRANT SELECT ON ventas TO analista (conceptual)", points: ["Concede solo permisos necesarios.", "RLS restringe filas por identidad o rol (conceptual).", "Un entregable explica fuente, filtros y definiciones."], note: "Nunca publiques credenciales o datos sensibles dentro del archivo SQL.", tip: "Separa acceso de lectura y escritura y deja trazabilidad del análisis.", hint: "Revisa qué usuarios necesitan lectura y qué datos pueden consultar." },
    ], labs: [
      { title: "Ingresos por ciudad y categoría", desc: "Integra uniones, filtros, clasificación y agregaciones en un informe ejecutivo.", prompt: "Combina ventas con clientes y productos. Filtra clientes activos mediante `c.id IN (SELECT id FROM clientes WHERE activo = 1)`. Agrupa por ciudad; devuelve `ciudad`, `ingreso` (SUM(cantidad * precio)) y `segmento` con CASE: ingreso >= 5000 Alto, >= 2000 Medio, resto Base. Ordena ingreso descendente. Resultado exacto: 4 filas, columnas ciudad/ingreso/segmento; Bogotá 4200 Medio, Buenos Aires 1960 Base, Lima 2525 Medio, Santiago 1595 Base; Bogotá debe aparecer primero.", solution: "SELECT c.ciudad, SUM(v.cantidad * p.precio) AS ingreso, CASE WHEN SUM(v.cantidad * p.precio) >= 5000 THEN 'Alto' WHEN SUM(v.cantidad * p.precio) >= 2000 THEN 'Medio' ELSE 'Base' END AS segmento FROM ventas v INNER JOIN clientes c ON v.cliente_id = c.id INNER JOIN productos p ON v.producto_id = p.id WHERE c.id IN (SELECT id FROM clientes WHERE activo = 1) GROUP BY c.ciudad ORDER BY ingreso DESC;", rows: 4, columns: ["ciudad", "ingreso", "segmento"], values: [{ column: "ciudad", value: "Bogotá" }, { column: "ingreso", value: 4200 }, { column: "segmento", value: "Medio" }], patterns: [/join\s+clientes/i, /join\s+productos/i, /sum\s*\(\s*v\.cantidad\s*\*\s*p\.precio\s*\)/i, /case\s+when/i, /in\s*\(\s*select/i, /group\s+by\s+c\.ciudad/i, /order\s+by\s+ingreso\s+desc/i], combined: /^(?=[\s\S]*join)(?=[\s\S]*case)(?=[\s\S]*in\s*\()(?=[\s\S]*group\s+by)(?=[\s\S]*order\s+by)/i, hint: "Valida las uniones y el filtro activo primero; después agrega por ciudad y clasifica el total." },
    ], questions: [
      { q: "¿Qué produce la consulta integradora por cada ciudad activa?", options: ["Ingreso total y segmento calculado", "Una fila de producto por cliente", "Una tabla física nueva", "Un permiso de usuario"], correct: 0, explain: "La salida combina dimensión ciudad, suma de ingresos y clasificación CASE." },
      { q: "¿Qué debería evitar un archivo SQL que se comparte en un repositorio?", options: ["Credenciales y datos personales sensibles", "Alias descriptivos", "Una nota sobre sus supuestos", "Una consulta de lectura revisada"], correct: 0, explain: "Los secretos deben administrarse fuera del código y de los repositorios." },
      { q: "¿Qué aporta atomicidad a una transacción?", options: ["Evita dejar solo una parte del conjunto confirmado", "Acelera todos los SELECT", "Ordena filas", "Crea un índice"], correct: 0, explain: "La unidad de trabajo se confirma por completo o se revierte." },
      { q: "¿Qué expresa mínimo privilegio?", options: ["Dar solo el acceso necesario a cada función", "Hacer administrador a todo el equipo", "Compartir una cuenta", "Desactivar auditoría"], correct: 0, explain: "Reducir permisos innecesarios limita exposición y errores." },
    ],
  },
];

export const SQL_MODULE_ICONS = ["📖", "🔍", "📊", "🔗", "🧩", "📝", "🔬", "📅", "⚡", "🧠", "🛡️", "🏛️", "🚀", "🎯", "🏆"];
const exampleTables = [
  { table: "clientes", column: "ciudad" },
  { table: "categorias", column: "nombre" },
  { table: "productos", column: "precio" },
  { table: "ventas", column: "cantidad" },
];

function distinctExample(moduleIndex: number, lessonIndex: number, sourceSql?: string) {
  const sequence = moduleIndex * 6 + lessonIndex + 1;
  const sourceTable = sourceSql?.match(/\bfrom\s+([a-z_]+)/i)?.[1]?.toLowerCase();
  let tableIndex = (sequence - 1) % exampleTables.length;
  if (exampleTables[tableIndex].table === sourceTable) tableIndex = (tableIndex + 1) % exampleTables.length;
  const source = exampleTables[tableIndex];
  const limit = sequence % 5 + 1;
  return `SELECT id, ${source.column} FROM ${source.table} WHERE id <= ${sequence} ORDER BY id ASC LIMIT ${limit};`;
}

function makeReading(spec: ReadingSpec, module: ModuleSpec, moduleIndex: number, lessonIndex: number): SqlLesson {
  const content = `<p>${spec.desc} ${module.goal}</p><h3>Una analogía cotidiana</h3><p>${spec.analogy}</p><h3>Consulta de ejemplo</h3><pre style="background:#0b1220;color:#e0e7ff;padding:14px 18px;border-radius:8px;overflow:auto"><code>${spec.example}</code></pre><ul>${spec.points.map((point) => `<li>${point}</li>`).join("")}</ul><div class="note"><strong>Atención:</strong> ${spec.note}</div><div class="tip"><strong>Buena práctica:</strong> ${spec.tip}</div>`;
  return {
    id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "reading", icon: "📖", xp: 20, minutes: 10,
    title: spec.title, desc: spec.desc, level: module.level,
    objectives: ["Explicar el concepto en su contexto.", "Interpretar el ejemplo y su resultado.", "Relacionar la técnica con una pregunta de negocio."],
    dax: { hint: spec.hint, explain: spec.analogy, example: distinctExample(moduleIndex, lessonIndex, spec.example) }, content, keyPoints: [...spec.points],
  };
}

function makeLab(spec: LabSpec, module: ModuleSpec, moduleIndex: number, lessonIndex: number): SqlLesson {
  const checks: SqlCheck[] = [
    { desc: "La consulta comienza con SELECT.", test: (code) => /^\s*select\b/i.test(code.trim()) },
    ...spec.patterns.map((pattern, index) => ({ desc: `La estructura SQL solicitada ${index + 1} está presente.`, test: (code: string) => pattern.test(code) })),
    { desc: "El resultado tiene las columnas y cantidad de filas esperadas.", test: (_code: string, result: SqlRunResult | null) => Boolean(result && !("error" in result) && result.rows.length === spec.rows && result.columns.length === spec.columns.length && spec.columns.every((column) => result.columns.includes(column))) },
    { desc: "Los valores de control aparecen juntos en una fila del resultado.", test: (_code: string, result: SqlRunResult | null) => Boolean(result && !("error" in result) && (spec.values.length === 0 ? result.rows.length === 0 : result.rows.some((row) => spec.values.every((expected) => String(row[expected.column]) === String(expected.value))))) },
    ...(spec.combined ? [{ desc: "Las cláusulas se combinan en el orden solicitado.", test: (code: string) => spec.combined!.test(code) }] : []),
  ];
  const finalProject = moduleIndex === 14;
  const minutes = finalProject ? 35 : module.level === "principiante" ? 16 : 20;
  return {
    id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "sql", icon: finalProject ? "🚀" : "🧪", xp: finalProject ? 150 : module.level === "principiante" ? 60 : 80,
    minutes, title: spec.title, desc: spec.desc, level: module.level,
    objectives: ["Construir una consulta para responder la pregunta de negocio.", "Verificar la estructura y los datos devueltos.", "Explicar por qué el resultado es adecuado."],
    dax: { hint: spec.hint, explain: "Descompón la consulta: define la población, añade relaciones y calcula la métrica antes de interpretar el resultado.", example: distinctExample(moduleIndex, lessonIndex, spec.solution) },
    prompt: `<p>${spec.prompt}</p><p><strong>Alcance:</strong> escribe una consulta SELECT sobre la base local de tienda_db; no se modifican datos.</p>`, starter: "", checks, solution: spec.solution,
  };
}

function makeQuiz(questions: SqlQuestion[], module: ModuleSpec, moduleIndex: number, lessonIndex: number): SqlLesson {
  const finalQuiz = moduleIndex === 14;
  const extendedQuiz = moduleIndex === 4 || moduleIndex === 9;
  return {
    id: `m${moduleIndex + 1}l${lessonIndex + 1}`, type: "quiz", icon: "📝", xp: finalQuiz ? 100 : extendedQuiz ? 80 : 60,
    minutes: finalQuiz ? 15 : extendedQuiz ? 12 : 10,
    title: finalQuiz ? "Evaluación final SQL" : `Desafío: ${module.title}`, desc: "Interpreta resultados y elige una estrategia adecuada al contexto.", level: module.level,
    objectives: ["Interpretar una consulta y sus resultados.", "Detectar un error de razonamiento frecuente.", "Justificar la cláusula adecuada al caso."],
    dax: { hint: "Sigue la consulta por etapas y determina qué población llega al resultado.", explain: "Como preparar un informe, primero reúnes los registros y luego decides qué resumen comunica la respuesta.", example: distinctExample(moduleIndex, lessonIndex) }, questions,
  };
}

export const SQL_CURRICULUM: SqlModule[] = specs.map((module, moduleIndex) => {
  const lessons: SqlLesson[] = [];
  module.readings.forEach((reading) => lessons.push(makeReading(reading, module, moduleIndex, lessons.length)));
  module.labs.forEach((lab) => lessons.push(makeLab(lab, module, moduleIndex, lessons.length)));
  lessons.push(makeQuiz(module.questions, module, moduleIndex, lessons.length));
  return { id: `m${moduleIndex + 1}`, title: module.title, minutes: lessons.reduce((sum, lesson) => sum + lesson.minutes, 0), goal: module.goal, level: module.level, lessons };
});

export function validateSqlCurriculum() {
  const readingCounts = [3, 3, 2, 2, 3, 2, 2, 3, 2, 2, 3, 3, 3, 3, 2];
  const labCounts = [1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1];
  if (SQL_CURRICULUM.length !== 15 || SQL_MODULE_ICONS.length !== 15) throw new Error("El curso SQL debe tener 15 módulos y 15 iconos.");
  SQL_CURRICULUM.forEach((module, index) => {
    const level: SqlLevel = index < 5 ? "principiante" : index < 10 ? "intermedio" : "avanzado";
    const titleWords = module.title.trim().split(/\s+/).length;
    if (module.id !== `m${index + 1}` || titleWords < 3 || titleWords > 7 || module.level !== level || module.lessons.length < 3 || module.lessons.length > 6 || module.minutes !== module.lessons.reduce((sum, item) => sum + item.minutes, 0) || module.lessons.filter((item) => item.type === "reading").length !== readingCounts[index] || module.lessons.filter((item) => item.type === "sql").length !== labCounts[index] || module.lessons.filter((item) => item.type === "quiz").length !== 1) throw new Error(`Estructura inválida en ${module.id}.`);
    module.lessons.forEach((lesson, lessonIndex) => {
      if (lesson.id !== `m${index + 1}l${lessonIndex + 1}` || lesson.level !== module.level || lesson.title.trim().split(/\s+/).length > 6 || lesson.minutes < 8 || lesson.minutes > 35 || lesson.objectives.length < 3 || !lesson.dax.hint || !lesson.dax.explain || !lesson.dax.example) throw new Error(`Actividad incompleta: ${lesson.id}.`);
      if (lesson.type === "reading" && (!lesson.content?.includes("<pre") || !lesson.content.includes("class=\"note\"") || !lesson.content.includes("class=\"tip\"") || lesson.keyPoints?.length !== 3)) throw new Error(`Lectura incompleta: ${lesson.id}.`);
      if (lesson.type === "sql") {
        const result = runSql(lesson.solution ?? "");
        const descriptions = lesson.checks?.map((check) => check.desc.toLowerCase()) ?? [];
        const needsCombinedPattern = index >= 5 && index <= 9 || index === 14;
        if (!lesson.checks || lesson.checks.length < 4 || lesson.starter !== "" || !descriptions.some((text) => text.includes("estructura")) || !descriptions.some((text) => text.includes("columnas") && text.includes("filas")) || !descriptions.some((text) => text.includes("valores de control")) || needsCombinedPattern && !descriptions.some((text) => text.includes("combinan")) || lesson.checks.some((check) => !check.test(lesson.solution ?? "", result))) throw new Error(`Laboratorio no validado: ${lesson.id}; salida ${JSON.stringify(result)}.`);
      }
      if (lesson.type === "quiz" && (!lesson.questions || lesson.questions.length !== 4 || lesson.questions.some((question) => question.options.length !== 4 || question.correct < 0 || question.correct > 3))) throw new Error(`Pregunta de quiz inválida en ${lesson.id}.`);
    });
  });
}

validateSqlCurriculum();
