const concepts: Record<string, string> = {
  "Tablas y registros": "Organizan datos en filas y columnas; cada registro representa un elemento completo.",
  "Tipos de datos": "Indican si la información es texto, número, fecha o lógica para poder procesarla correctamente.",
  "Orden y filtros": "Permiten encontrar registros y mostrar solo la información que cumple una condición.",
  "Referencias absolutas y relativas": "Definen si una referencia de celda cambia o permanece fija al copiar una fórmula.",
  "Funciones lógicas": "Evalúan condiciones y devuelven un resultado según se cumpla o no una regla.",
  "Funciones de texto y fecha": "Transforman y limpian nombres, códigos y fechas para analizarlos mejor.",
  "Campos y segmentaciones": "Permiten elegir dimensiones y filtros para explorar una tabla dinámica.",
  "Agrupación de información": "Reúne datos por categorías, periodos o rangos para encontrar patrones.",
  "Indicadores de resumen": "Medidas como suma, promedio o porcentaje que sintetizan los datos.",
  "Gráficos adecuados": "Representaciones elegidas según la comparación, tendencia o relación que se quiere comunicar.",
  "Diseño de reportes": "Organiza títulos, indicadores y gráficos para que un informe sea claro y útil.",
  "Presentación de hallazgos": "Explica los resultados importantes y la decisión que esos resultados respaldan.",
  "Validación de datos": "Reglas que controlan qué valores puede ingresar una persona en una celda.",
  "Plantillas reutilizables": "Archivos preparados para repetir un proceso sin comenzar desde cero.",
  "Introducción a macros": "Automatiza tareas repetitivas mediante instrucciones ejecutadas por Excel.",
  "Interfaz": "Espacio de trabajo donde se encuentran herramientas, paneles y opciones de Power BI.",
  "Importación de Excel y CSV": "Carga información desde hojas de cálculo o archivos separados por comas.",
  "Tipos de visualización": "Gráficos y elementos visuales que presentan datos según una pregunta.",
  "Limpieza básica": "Corrige errores, duplicados, valores vacíos y formatos inconsistentes.",
  "Relaciones entre tablas": "Conectan columnas relacionadas para analizar varias tablas juntas.",
  "Modelo estrella": "Estructura con una tabla de hechos conectada a dimensiones descriptivas.",
  "Medidas básicas": "Cálculos dinámicos que responden a filtros y crean indicadores.",
  "Filtros y segmentadores": "Controles para explorar un informe mostrando el subconjunto elegido.",
  "Publicación de un informe": "Comparte un dashboard para que otras personas puedan consultarlo.",
  Variables: "Espacios con nombre donde un programa guarda valores que pueden cambiar.",
  "Condicionales y ciclos": "Estructuras para tomar decisiones y repetir instrucciones.",
  Funciones: "Bloques reutilizables de código que reciben datos y producen un resultado.",
  "Bases del lenguaje": "Elementos iniciales de Python como sintaxis, variables, operadores y tipos de datos.",
  DataFrames: "Tablas de Pandas con filas y columnas para trabajar con datos en Python.",
  Limpieza: "Proceso de corregir formatos, duplicados y valores inconsistentes antes de analizar datos.",
  "Agrupaciones y métricas": "Cálculos por categorías para comparar cantidades, promedios o tendencias.",
  "Exportación de resultados": "Convierte el análisis en archivos o reportes utilizables.",
  SELECT: "Indica qué columnas o expresiones devuelve una consulta SQL.",
  WHERE: "Filtra registros SQL según una condición.",
  "ORDER BY y LIMIT": "Ordena resultados y limita la cantidad de filas devueltas.",
  JOIN: "Combina tablas usando columnas relacionadas.",
  "GROUP BY": "Agrupa registros para calcular resultados por categoría.",
  "Funciones de agregación": "Funciones como COUNT, SUM y AVG que resumen registros.",
  Subconsultas: "Consultas SQL dentro de otra consulta para resolver análisis por etapas.",
  "Valores nulos": "Campos sin información que deben tratarse para evitar errores.",
  "Unir consultas": "Combina tablas mediante coincidencias o apilado de filas.",
  "IA, datos y modelos": "Relaciona información de entrada, patrones aprendidos y resultados generados.",
  "Usos cotidianos": "Aplicaciones de IA en búsqueda, asistencia, clasificación y automatización.",
  "Limitaciones y sesgos": "Errores o resultados parciales provocados por datos o contexto insuficiente.",
  "Prompts claros": "Instrucciones que definen objetivo, contexto, formato y restricciones para una IA.",
  "Verificación de resultados": "Revisión de exactitud, fuentes y coherencia antes de usar una respuesta.",
  "Privacidad y ética": "Principios para proteger datos y usar IA responsablemente.",
  "Identificación del problema": "Descripción precisa de la situación que origina una investigación.",
  "Definir un problema": "Delimitación de una necesidad real y del resultado que se quiere mejorar.",
  Prototipo: "Primera versión de una solución que permite probar una idea antes de desarrollarla por completo.",
  Justificación: "Razones que explican por qué investigar un problema es importante.",
  "Preguntas de investigación": "Interrogantes que orientan la recolección y análisis de información.",
  "Objetivo general y específicos": "Resultados que la investigación busca alcanzar, del propósito a las acciones.",
  "Variables e indicadores": "Características observables y medidas usadas para estudiar un fenómeno.",
  "Fuentes académicas": "Libros, artículos y documentos especializados que respaldan una investigación.",
  Antecedentes: "Estudios anteriores relacionados con el problema investigado.",
  "Citas y referencias": "Reconocen las fuentes utilizadas y ayudan a evitar el plagio.",
  "Enfoques de investigación": "Perspectivas cualitativa, cuantitativa o mixta para estudiar un problema.",
  "Población y muestra": "Conjunto total estudiado y grupo seleccionado para representarlo.",
  Instrumentos: "Herramientas como encuestas o entrevistas para recoger datos.",
  Interpretación: "Explicación del significado de los resultados frente al problema.",
  "Informe final": "Documento que reúne problema, método, resultados y conclusiones.",
  "Navegador y servidor": "El navegador solicita recursos y el servidor entrega archivos web.",
  "HTML semántico": "Etiquetas que describen el significado y estructura del contenido web.",
  "Estructura de un documento": "Organización de metadatos, contenido y secciones de una página.",
  "Textos e imágenes": "Elementos escritos y visuales que comunican información dentro de una página web.",
  "Enlaces y formularios": "Componentes que permiten navegar y recopilar información de visitantes.",
  "Organización de carpetas": "Forma de separar archivos, componentes, estilos e imágenes para mantener el proyecto ordenado.",
  Selectores: "Reglas CSS que identifican los elementos que recibirán estilos.",
  "Colores y tipografía": "Decisiones visuales que mejoran identidad, jerarquía y legibilidad.",
  "Modelo de caja": "Contenido, relleno, borde y margen que componen un elemento CSS.",
  "Flexbox y Grid": "Sistemas CSS para distribuir elementos en filas, columnas y áreas.",
  "Adaptación a celulares": "Reorganiza la interfaz para pantallas pequeñas.",
  Accesibilidad: "Prácticas que permiten usar un sitio a personas con distintas capacidades.",
  Eventos: "Acciones del usuario o navegador que pueden activar código.",
  Validación: "Comprueba que los datos ingresados cumplen reglas esperadas.",
  Git: "Registra cambios del código y permite colaborar con versiones.",
  Hosting: "Servicio que publica una web en Internet.",
  Clasificación: "Organiza movimientos financieros según naturaleza o destino.",
  "Registro financiero": "Anotación ordenada de operaciones económicas.",
  "Presupuesto mensual": "Plan anticipado de ingresos y gastos de un mes.",
  Escenarios: "Proyecciones alternativas para prepararse ante cambios.",
  "Costos fijos y variables": "Gastos estables y gastos que cambian según la actividad.",
  "Punto de equilibrio": "Nivel de ventas donde los ingresos cubren exactamente los costos.",
  Margen: "Diferencia entre precio y costo, expresada en valor o porcentaje.",
  "Valor para el cliente": "Beneficio percibido por el que una persona está dispuesta a pagar.",
  Competencia: "Alternativas que ofrecen soluciones similares al mismo mercado.",
  "Entradas y salidas": "Movimientos de dinero que ingresan y salen del negocio.",
  Liquidez: "Capacidad de pagar obligaciones de corto plazo.",
  Proyección: "Estimación de resultados futuros con datos y supuestos.",
  Rentabilidad: "Capacidad de generar ganancias respecto a inversión o ventas.",
  Endeudamiento: "Nivel de obligaciones financieras de una persona o negocio.",
  "Automatización de reportes": "Uso de fórmulas, consultas o scripts para generar informes con menos trabajo manual.",
  "Buenas prácticas de documentación": "Registro claro de fuentes, pasos, supuestos y cambios para que el trabajo sea reproducible.",
  "KPIs comerciales": "Indicadores que permiten medir ventas, clientes, conversión y cumplimiento de objetivos.",
  "Narrativa con datos": "Forma de explicar un hallazgo conectando contexto, evidencia y una recomendación.",
  "Automatización con scripts": "Programas pequeños que ejecutan tareas repetitivas de limpieza, análisis o exportación.",
  "Control de calidad del análisis": "Revisión de datos, cálculos y resultados para detectar errores antes de comunicar conclusiones.",
  "CTE y consultas legibles": "Estructuras SQL que separan pasos complejos y hacen las consultas más fáciles de revisar.",
  "Seguridad de acceso a datos": "Reglas que limitan quién puede consultar, modificar o compartir información.",
  "Parámetros y actualización": "Configuraciones que permiten reutilizar una consulta y refrescar datos sin rehacer pasos.",
  "Control de calidad de datos": "Comprobaciones que aseguran que los datos sean completos, consistentes y correctos.",
  "Automatización de tareas": "Uso de herramientas para reducir pasos manuales y ahorrar tiempo en procesos repetitivos.",
  "IA generativa en el trabajo": "Uso de modelos que producen texto, ideas o código con revisión humana y criterios de seguridad.",
  "Alfabetización informacional": "Capacidad de buscar, evaluar y utilizar información confiable de forma crítica.",
  "Presentación de evidencia": "Comunicación de resultados acompañados de fuentes, datos y razonamiento verificable.",
  GitHub: "Plataforma para alojar código, controlar versiones y colaborar mediante repositorios.",
  "Seguridad básica": "Prácticas para proteger cuentas, formularios, dependencias y datos de una aplicación.",
  "Optimización para buscadores": "Mejoras de contenido y estructura que ayudan a que una web sea encontrada en Google.",
  "Flujo de caja proyectado": "Estimación de entradas y salidas futuras para anticipar necesidades de liquidez.",
  "Decisiones basadas en datos": "Elección de acciones usando evidencia, indicadores y objetivos medibles.",
  "Ingresos y gastos": "Registro de los recursos que entran y los pagos que salen de una actividad económica.",
  "Separar finanzas personales": "Práctica de distinguir el dinero del negocio del dinero del propietario.",
  Metas: "Resultados financieros concretos que orientan la planificación.",
  "Definir precios": "Proceso de establecer cuánto cobrar considerando costos, valor y competencia.",
  "Decisiones y crecimiento": "Evaluación de alternativas financieras para sostener y expandir el negocio.",
};

export function getTopicConcept(topic: string) {
  return concepts[topic] ?? "Concepto práctico que se aplica durante esta clase mediante ejercicios del curso.";
}
